/*
 Highcharts JS v8.2.2 (2020-11-05)

 (c) 2009-2019 Sebastian Bochan, Rafal Sebestjanski

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/dumbbell",["highcharts"],function(m){c(m);c.Highcharts=m;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function m(c,e,m,r){c.hasOwnProperty(e)||(c[e]=r.apply(null,m))}c=c?c._modules:{};m(c,"Series/AreaRangeSeries.js",[c["Core/Series/Series.js"],c["Series/Column/ColumnSeries.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],
c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,e,m,r,u,h){var w=e.prototype,p=r.prototype,t=u.prototype,v=h.defined,n=h.extend,x=h.isArray,a=h.isNumber,y=h.pick,q=c.seriesTypes.area.prototype;c.seriesType("arearange","area",{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low",
"high"],pointValKey:"low",deferTranslatePolar:!0,toYData:function(g){return[g.low,g.high]},highToXY:function(g){var a=this.chart,b=this.xAxis.postTranslate(g.rectPlotX,this.yAxis.len-g.plotHigh);g.plotHighX=b.x-a.plotLeft;g.plotHigh=b.y-a.plotTop;g.plotLowX=g.plotX},translate:function(){var g=this,a=g.yAxis,b=!!g.modifyValue;q.translate.apply(g);g.points.forEach(function(d){var c=d.high,f=d.plotY;d.isNull?d.plotY=null:(d.plotLow=f,d.plotHigh=a.translate(b?g.modifyValue(c,d):c,0,1,0,1),b&&(d.yBottom=
d.plotHigh))});this.chart.polar&&this.points.forEach(function(b){g.highToXY(b);b.tooltipPos=[(b.plotHighX+b.plotLowX)/2,(b.plotHigh+b.plotLow)/2]})},getGraphPath:function(a){var d=[],b=[],g,c=q.getGraphPath;var f=this.options;var n=this.chart.polar,l=n&&!1!==f.connectEnds,k=f.connectNulls,h=f.step;a=a||this.points;for(g=a.length;g--;){var e=a[g];var p=n?{plotX:e.rectPlotX,plotY:e.yBottom,doCurve:!1}:{plotX:e.plotX,plotY:e.plotY,doCurve:!1};e.isNull||l||k||a[g+1]&&!a[g+1].isNull||b.push(p);var m={polarPlotY:e.polarPlotY,
rectPlotX:e.rectPlotX,yBottom:e.yBottom,plotX:y(e.plotHighX,e.plotX),plotY:e.plotHigh,isNull:e.isNull};b.push(m);d.push(m);e.isNull||l||k||a[g-1]&&!a[g-1].isNull||b.push(p)}a=c.call(this,a);h&&(!0===h&&(h="left"),f.step={left:"right",center:"center",right:"left"}[h]);d=c.call(this,d);b=c.call(this,b);f.step=h;f=[].concat(a,d);!this.chart.polar&&b[0]&&"M"===b[0][0]&&(b[0]=["L",b[0][1],b[0][2]]);this.graphPath=f;this.areaPath=a.concat(b);f.isArea=!0;f.xMap=a.xMap;this.areaPath.xMap=a.xMap;return f},
drawDataLabels:function(){var a=this.points,d=a.length,b,c=[],e=this.options.dataLabels,f,h=this.chart.inverted;if(x(e)){var l=e[0]||{enabled:!1};var k=e[1]||{enabled:!1}}else l=n({},e),l.x=e.xHigh,l.y=e.yHigh,k=n({},e),k.x=e.xLow,k.y=e.yLow;if(l.enabled||this._hasPointLabels){for(b=d;b--;)if(f=a[b]){var q=l.inside?f.plotHigh<f.plotLow:f.plotHigh>f.plotLow;f.y=f.high;f._plotY=f.plotY;f.plotY=f.plotHigh;c[b]=f.dataLabel;f.dataLabel=f.dataLabelUpper;f.below=q;h?l.align||(l.align=q?"right":"left"):l.verticalAlign||
(l.verticalAlign=q?"top":"bottom")}this.options.dataLabels=l;p.drawDataLabels&&p.drawDataLabels.apply(this,arguments);for(b=d;b--;)if(f=a[b])f.dataLabelUpper=f.dataLabel,f.dataLabel=c[b],delete f.dataLabels,f.y=f.low,f.plotY=f._plotY}if(k.enabled||this._hasPointLabels){for(b=d;b--;)if(f=a[b])q=k.inside?f.plotHigh<f.plotLow:f.plotHigh>f.plotLow,f.below=!q,h?k.align||(k.align=q?"left":"right"):k.verticalAlign||(k.verticalAlign=q?"bottom":"top");this.options.dataLabels=k;p.drawDataLabels&&p.drawDataLabels.apply(this,
arguments)}if(l.enabled)for(b=d;b--;)if(f=a[b])f.dataLabels=[f.dataLabelUpper,f.dataLabel].filter(function(b){return!!b});this.options.dataLabels=e},alignDataLabel:function(){w.alignDataLabel.apply(this,arguments)},drawPoints:function(){var a=this.points.length,d;p.drawPoints.apply(this,arguments);for(d=0;d<a;){var b=this.points[d];b.origProps={plotY:b.plotY,plotX:b.plotX,isInside:b.isInside,negative:b.negative,zone:b.zone,y:b.y};b.lowerGraphic=b.graphic;b.graphic=b.upperGraphic;b.plotY=b.plotHigh;
v(b.plotHighX)&&(b.plotX=b.plotHighX);b.y=b.high;b.negative=b.high<(this.options.threshold||0);b.zone=this.zones.length&&b.getZone();this.chart.polar||(b.isInside=b.isTopInside="undefined"!==typeof b.plotY&&0<=b.plotY&&b.plotY<=this.yAxis.len&&0<=b.plotX&&b.plotX<=this.xAxis.len);d++}p.drawPoints.apply(this,arguments);for(d=0;d<a;)b=this.points[d],b.upperGraphic=b.graphic,b.graphic=b.lowerGraphic,n(b,b.origProps),delete b.origProps,d++},setStackedPoints:m.noop},{setState:function(){var a=this.state,
d=this.series,b=d.chart.polar;v(this.plotHigh)||(this.plotHigh=d.yAxis.toPixels(this.high,!0));v(this.plotLow)||(this.plotLow=this.plotY=d.yAxis.toPixels(this.low,!0));d.stateMarkerGraphic&&(d.lowerStateMarkerGraphic=d.stateMarkerGraphic,d.stateMarkerGraphic=d.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;b&&(this.plotX=this.plotHighX);t.setState.apply(this,arguments);this.state=a;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;b&&(this.plotX=this.plotLowX);
d.stateMarkerGraphic&&(d.upperStateMarkerGraphic=d.stateMarkerGraphic,d.stateMarkerGraphic=d.lowerStateMarkerGraphic,d.lowerStateMarkerGraphic=void 0);t.setState.apply(this,arguments)},haloPath:function(){var a=this.series.chart.polar,d=[];this.plotY=this.plotLow;a&&(this.plotX=this.plotLowX);this.isInside&&(d=t.haloPath.apply(this,arguments));this.plotY=this.plotHigh;a&&(this.plotX=this.plotHighX);this.isTopInside&&(d=d.concat(t.haloPath.apply(this,arguments)));return d},destroyElements:function(){["lowerGraphic",
"upperGraphic"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this);this.graphic=null;return t.destroyElements.apply(this,arguments)},isValid:function(){return a(this.low)&&a(this.high)}});""});m(c,"Series/ColumnRangeSeries.js",[c["Core/Series/Series.js"],c["Series/Column/ColumnSeries.js"],c["Core/Globals.js"],c["Core/Options.js"],c["Core/Utilities.js"]],function(c,e,m,r,u){var h=e.prototype;e=m.noop;r=r.defaultOptions;var w=u.clamp,p=u.merge,t=u.pick,v=c.seriesTypes.arearange.prototype;
c.seriesType("columnrange","arearange",p(r.plotOptions.column,r.plotOptions.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{setOptions:function(){p(!0,arguments[0],{stacking:void 0});return v.setOptions.apply(this,arguments)},translate:function(){var c=this,e=c.yAxis,a=c.xAxis,y=a.startAngleRad,q,g=c.chart,d=c.xAxis.isRadial,b=Math.max(g.chartWidth,g.chartHeight)+999,m;h.translate.apply(c);c.points.forEach(function(h){var f=h.shapeArgs,n=c.options.minPointLength;h.plotHigh=m=w(e.translate(h.high,
0,1,0,1),-b,b);h.plotLow=w(h.plotY,-b,b);var l=m;var k=t(h.rectPlotY,h.plotY)-m;Math.abs(k)<n?(n-=k,k+=n,l-=n/2):0>k&&(k*=-1,l-=k);d?(q=h.barX+y,h.shapeType="arc",h.shapeArgs=c.polarArc(l+k,l,q,q+h.pointWidth)):(f.height=k,f.y=l,h.tooltipPos=g.inverted?[e.len+e.pos-g.plotLeft-l-k/2,a.len+a.pos-g.plotTop-f.x-f.width/2,k]:[a.left-g.plotLeft+f.x+f.width/2,e.pos-g.plotTop+l+k/2,k])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:e,getSymbol:e,crispCol:function(){return h.crispCol.apply(this,
arguments)},drawPoints:function(){return h.drawPoints.apply(this,arguments)},drawTracker:function(){return h.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return h.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return h.pointAttribs.apply(this,arguments)},adjustForMissingColumns:function(){return h.adjustForMissingColumns.apply(this,arguments)},animate:function(){return h.animate.apply(this,arguments)},polarArc:function(){return h.polarArc.apply(this,arguments)},
translate3dPoints:function(){return h.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return h.translate3dShapes.apply(this,arguments)}},{setState:h.pointClass.prototype.setState});""});m(c,"Series/DumbbellSeries.js",[c["Core/Series/Series.js"],c["Series/Column/ColumnSeries.js"],c["Series/Line/LineSeries.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,e,m,r,u,h){var w=c.seriesTypes,p=e.prototype,t=m.prototype,v=h.extend,n=h.pick,
x=w.arearange.prototype;e=x.pointClass.prototype;c.seriesType("dumbbell","arearange",{trackByArea:!1,fillColor:"none",lineWidth:0,pointRange:1,connectorWidth:1,stickyTracking:!1,groupPadding:.2,crisp:!1,pointPadding:.1,lowColor:"#333333",states:{hover:{lineWidthPlus:0,connectorWidthPlus:1,halo:!1}}},{trackerGroups:["group","markerGroup","dataLabelsGroup"],drawTracker:u.TrackerMixin.drawTrackerPoint,drawGraph:u.noop,crispCol:p.crispCol,getConnectorAttribs:function(a){var c=this.chart,e=a.options,g=
this.options,d=this.xAxis,b=this.yAxis,h=n(e.connectorWidth,g.connectorWidth),m=n(e.connectorColor,g.connectorColor,e.color,a.zone?a.zone.color:void 0,a.color),f=n(g.states&&g.states.hover&&g.states.hover.connectorWidthPlus,1),p=n(e.dashStyle,g.dashStyle),l=n(a.plotLow,a.plotY),k=b.toPixels(g.threshold||0,!0);k=n(a.plotHigh,c.inverted?b.len-k:k);a.state&&(h+=f);0>l?l=0:l>=b.len&&(l=b.len);0>k?k=0:k>=b.len&&(k=b.len);if(0>a.plotX||a.plotX>d.len)h=0;a.upperGraphic&&(d={y:a.y,zone:a.zone},a.y=a.high,
a.zone=a.zone?a.getZone():void 0,m=n(e.connectorColor,g.connectorColor,e.color,a.zone?a.zone.color:void 0,a.color),v(a,d));a={d:r.prototype.crispLine([["M",a.plotX,l],["L",a.plotX,k]],h,"ceil")};c.styledMode||(a.stroke=m,a["stroke-width"]=h,p&&(a.dashstyle=p));return a},drawConnector:function(a){var c=n(this.options.animationLimit,250);c=a.connector&&this.chart.pointCount<c?"animate":"attr";a.connector||(a.connector=this.chart.renderer.path().addClass("highcharts-lollipop-stem").attr({zIndex:-1}).add(this.markerGroup));
a.connector[c](this.getConnectorAttribs(a))},getColumnMetrics:function(){var a=p.getColumnMetrics.apply(this,arguments);a.offset+=a.width/2;return a},translatePoint:x.translate,setShapeArgs:w.columnrange.prototype.translate,translate:function(){this.setShapeArgs.apply(this);this.translatePoint.apply(this,arguments);this.points.forEach(function(a){var c=a.shapeArgs,e=a.pointWidth;a.plotX=c.x;c.x=a.plotX-e/2;a.tooltipPos=null});this.columnMetrics.offset-=this.columnMetrics.width/2},seriesDrawPoints:x.drawPoints,
drawPoints:function(){var a=this.chart,c=this.points.length,e=this.lowColor=this.options.lowColor,g=0;for(this.seriesDrawPoints.apply(this,arguments);g<c;){var d=this.points[g];this.drawConnector(d);d.upperGraphic&&(d.upperGraphic.element.point=d,d.upperGraphic.addClass("highcharts-lollipop-high"));d.connector.element.point=d;if(d.lowerGraphic){var b=d.zone&&d.zone.color;b=n(d.options.lowColor,e,d.options.color,b,d.color,this.color);a.styledMode||d.lowerGraphic.attr({fill:b});d.lowerGraphic.addClass("highcharts-lollipop-low")}g++}},
markerAttribs:function(){var a=x.markerAttribs.apply(this,arguments);a.x=Math.floor(a.x);a.y=Math.floor(a.y);return a},pointAttribs:function(a,c){var e=t.pointAttribs.apply(this,arguments);"hover"===c&&delete e.fill;return e}},{destroyElements:e.destroyElements,isValid:e.isValid,pointSetState:e.setState,setState:function(){var a=this.series,c=a.chart,e=a.options.marker,g=this.options,d=n(g.lowColor,a.options.lowColor,g.color,this.zone&&this.zone.color,this.color,a.color),b="attr";this.pointSetState.apply(this,
arguments);this.state||(b="animate",this.lowerGraphic&&!c.styledMode&&(this.lowerGraphic.attr({fill:d}),this.upperGraphic&&(c={y:this.y,zone:this.zone},this.y=this.high,this.zone=this.zone?this.getZone():void 0,e=n(this.marker?this.marker.fillColor:void 0,e?e.fillColor:void 0,g.color,this.zone?this.zone.color:void 0,this.color),this.upperGraphic.attr({fill:e}),v(this,c))));this.connector[b](a.getConnectorAttribs(this))}});""});m(c,"masters/modules/dumbbell.src.js",[],function(){})});
//# sourceMappingURL=dumbbell.js.map