/*
 Highcharts JS v8.2.2 (2020-11-05)

 Highcharts funnel module

 (c) 2010-2019 Kacper Madej

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/funnel3d",["highcharts","highcharts/highcharts-3d","highcharts/modules/cylinder"],function(h){c(h);c.Highcharts=h;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function h(c,k,h,m){c.hasOwnProperty(k)||(c[k]=m.apply(null,h))}c=c?c._modules:{};h(c,"Series/Funnel3DSeries.js",[c["Core/Series/Series.js"],c["Core/Color/Color.js"],
c["Series/Column/ColumnSeries.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],c["Extensions/Math3D.js"],c["Core/Utilities.js"]],function(c,k,h,m,G,K,l){var x=k.parse,H=h.prototype,I=m.charts;k=m.Renderer.prototype;var L=K.perspective,M=l.error,E=l.extend,p=l.merge,C=l.pick,A=l.relativeLength,N=k.cuboidPath;c.seriesType("funnel3d","column",{center:["50%","50%"],width:"90%",neckWidth:"30%",height:"100%",neckHeight:"25%",reversed:!1,gradientForSides:!0,animation:!1,edgeWidth:0,colorByPoint:!0,
showInLegend:!1,dataLabels:{align:"right",crop:!1,inside:!1,overflow:"allow"}},{bindAxes:function(){G.prototype.bindAxes.apply(this,arguments);E(this.xAxis.options,{gridLineWidth:0,lineWidth:0,title:null,tickPositions:[]});E(this.yAxis.options,{gridLineWidth:0,title:null,labels:{enabled:!1}})},translate3dShapes:m.noop,translate:function(){G.prototype.translate.apply(this,arguments);var a=0,b=this.chart,d=this.options,g=d.reversed,r=d.ignoreHiddenPoint,e=b.plotWidth,c=b.plotHeight,f=0,J=d.center,B=
A(J[0],e),u=A(J[1],c),p=A(d.width,e),q,v,n=A(d.height,c),k=A(d.neckWidth,e),h=A(d.neckHeight,c),m=u-n/2+n-h;e=this.data;var y,l,w,z,x,D,t;this.getWidthAt=v=function(b){var a=u-n/2;return b>m||n===h?k:k+(p-k)*(1-(b-a)/(n-h))};this.center=[B,u,n];this.centerX=B;e.forEach(function(b){r&&!1===b.visible||(a+=b.y)});e.forEach(function(e){x=null;y=a?e.y/a:0;w=u-n/2+f*n;z=w+y*n;q=v(w);D=z-w;t={gradientForSides:C(e.options.gradientForSides,d.gradientForSides),x:B,y:w,height:D,width:q,z:1,top:{width:q}};q=
v(z);t.bottom={fraction:y,width:q};w>=m?t.isCylinder=!0:z>m&&(x=z,q=v(m),z=m,t.bottom.width=q,t.middle={fraction:D?(m-w)/D:0,width:q});g&&(t.y=w=u+n/2-(f+y)*n,t.middle&&(t.middle.fraction=1-(D?t.middle.fraction:0)),q=t.width,t.width=t.bottom.width,t.bottom.width=q);e.shapeArgs=E(e.shapeArgs,t);e.percentage=100*y;e.plotX=B;e.plotY=g?u+n/2-(f+y/2)*n:(w+(x||z))/2;l=L([{x:B,y:e.plotY,z:g?-(p-v(e.plotY))/2:-v(e.plotY)/2}],b,!0)[0];e.tooltipPos=[l.x,l.y];e.dlBoxRaw={x:B,width:v(e.plotY),y:w,bottom:t.height,
fullWidth:p};r&&!1===e.visible||(f+=y)})},alignDataLabel:function(a,b,d){var g=a.dlBoxRaw,c=this.chart.inverted,e=a.plotY>C(this.translatedThreshold,this.yAxis.len),F=C(d.inside,!!this.options.stacking),f={x:g.x,y:g.y,height:0};d.align=C(d.align,!c||F?"center":e?"right":"left");d.verticalAlign=C(d.verticalAlign,c||F?"middle":e?"top":"bottom");"top"!==d.verticalAlign&&(f.y+=g.bottom/("bottom"===d.verticalAlign?1:2));f.width=this.getWidthAt(f.y);this.options.reversed&&(f.width=g.fullWidth-f.width);
F?f.x-=f.width/2:"left"===d.align?(d.align="right",f.x-=1.5*f.width):"right"===d.align?(d.align="left",f.x+=f.width/2):f.x-=f.width/2;a.dlBox=f;H.alignDataLabel.apply(this,arguments)}},{shapeType:"funnel3d",hasNewShapeType:H.pointClass.prototype.hasNewShapeType});c=p(k.elements3d.cuboid,{parts:"top bottom frontUpper backUpper frontLower backLower rightUpper rightLower".split(" "),mainParts:["top","bottom"],sideGroups:["upperGroup","lowerGroup"],sideParts:{upperGroup:["frontUpper","backUpper","rightUpper"],
lowerGroup:["frontLower","backLower","rightLower"]},pathType:"funnel3d",opacitySetter:function(a){var b=this,d=b.parts,g=m.charts[b.renderer.chartIndex],c="group-opacity-"+a+"-"+g.index;b.parts=b.mainParts;b.singleSetterForParts("opacity",a);b.parts=d;g.renderer.filterId||(g.renderer.definition({tagName:"filter",id:c,children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncA",type:"table",tableValues:"0 "+a}]}]}),b.sideGroups.forEach(function(a){b[a].attr({filter:"url(#"+c+")"})}),b.renderer.styledMode&&
(g.renderer.definition({tagName:"style",textContent:".highcharts-"+c+" {filter:url(#"+c+")}"}),b.sideGroups.forEach(function(b){b.addClass("highcharts-"+c)})));return b},fillSetter:function(a){var b=this,d=x(a),c=d.rgba[3],r={top:x(a).brighten(.1).get(),bottom:x(a).brighten(-.2).get()};1>c?(d.rgba[3]=1,d=d.get("rgb"),b.attr({opacity:c})):d=a;d.linearGradient||d.radialGradient||!b.gradientForSides||(d={linearGradient:{x1:0,x2:1,y1:1,y2:1},stops:[[0,x(a).brighten(-.2).get()],[.5,a],[1,x(a).brighten(-.2).get()]]});
d.linearGradient?b.sideGroups.forEach(function(a){var c=b[a].gradientBox,e=d.linearGradient,g=p(d,{linearGradient:{x1:c.x+e.x1*c.width,y1:c.y+e.y1*c.height,x2:c.x+e.x2*c.width,y2:c.y+e.y2*c.height}});b.sideParts[a].forEach(function(b){r[b]=g})}):(p(!0,r,{frontUpper:d,backUpper:d,rightUpper:d,frontLower:d,backLower:d,rightLower:d}),d.radialGradient&&b.sideGroups.forEach(function(a){var d=b[a].gradientBox,c=d.x+d.width/2,e=d.y+d.height/2,g=Math.min(d.width,d.height);b.sideParts[a].forEach(function(a){b[a].setRadialReference([c,
e,g])})}));b.singleSetterForParts("fill",null,r);b.color=b.fill=a;d.linearGradient&&[b.frontLower,b.frontUpper].forEach(function(a){(a=(a=a.element)&&b.renderer.gradients[a.gradient])&&"userSpaceOnUse"!==a.attr("gradientUnits")&&a.attr({gradientUnits:"userSpaceOnUse"})});return b},adjustForGradient:function(){var a=this,b;a.sideGroups.forEach(function(d){var c={x:Number.MAX_VALUE,y:Number.MAX_VALUE},r={x:-Number.MAX_VALUE,y:-Number.MAX_VALUE};a.sideParts[d].forEach(function(d){b=a[d].getBBox(!0);
c={x:Math.min(c.x,b.x),y:Math.min(c.y,b.y)};r={x:Math.max(r.x,b.x+b.width),y:Math.max(r.y,b.y+b.height)}});a[d].gradientBox={x:c.x,width:r.x-c.x,y:c.y,height:r.y-c.y}})},zIndexSetter:function(){this.finishedOnAdd&&this.adjustForGradient();return this.renderer.Element.prototype.zIndexSetter.apply(this,arguments)},onAdd:function(){this.adjustForGradient();this.finishedOnAdd=!0}});k.elements3d.funnel3d=c;k.funnel3d=function(a){var b=this.element3d("funnel3d",a),d=this.styledMode,c={"stroke-width":1,
stroke:"none"};b.upperGroup=this.g("funnel3d-upper-group").attr({zIndex:b.frontUpper.zIndex}).add(b);[b.frontUpper,b.backUpper,b.rightUpper].forEach(function(a){d||a.attr(c);a.add(b.upperGroup)});b.lowerGroup=this.g("funnel3d-lower-group").attr({zIndex:b.frontLower.zIndex}).add(b);[b.frontLower,b.backLower,b.rightLower].forEach(function(a){d||a.attr(c);a.add(b.lowerGroup)});b.gradientForSides=a.gradientForSides;return b};k.funnel3dPath=function(a){this.getCylinderEnd||M("A required Highcharts module is missing: cylinder.js",
!0,I[this.chartIndex]);var b=I[this.chartIndex],c=a.alphaCorrection=90-Math.abs(b.options.chart.options3d.alpha%180-90),g=N.call(this,p(a,{depth:a.width,width:(a.width+a.bottom.width)/2})),r=g.isTop,e=!g.isFront,k=!!a.middle,f=this.getCylinderEnd(b,p(a,{x:a.x-a.width/2,z:a.z-a.width/2,alphaCorrection:c})),h=a.bottom.width,m=p(a,{width:h,x:a.x-h/2,z:a.z-h/2,alphaCorrection:c}),u=this.getCylinderEnd(b,m,!0),l=h,q=m,v=u,n=u;k&&(l=a.middle.width,q=p(a,{y:a.y+a.middle.fraction*a.height,width:l,x:a.x-l/
2,z:a.z-l/2}),v=this.getCylinderEnd(b,q,!1),n=this.getCylinderEnd(b,q,!1));g={top:f,bottom:u,frontUpper:this.getCylinderFront(f,v),zIndexes:{group:g.zIndexes.group,top:0!==r?0:3,bottom:1!==r?0:3,frontUpper:e?2:1,backUpper:e?1:2,rightUpper:e?2:1}};g.backUpper=this.getCylinderBack(f,v);f=1!==Math.min(l,a.width)/Math.max(l,a.width);g.rightUpper=this.getCylinderFront(this.getCylinderEnd(b,p(a,{x:a.x-a.width/2,z:a.z-a.width/2,alphaCorrection:f?-c:0}),!1),this.getCylinderEnd(b,p(q,{alphaCorrection:f?-c:
0}),!k));k&&(f=1!==Math.min(l,h)/Math.max(l,h),p(!0,g,{frontLower:this.getCylinderFront(n,u),backLower:this.getCylinderBack(n,u),rightLower:this.getCylinderFront(this.getCylinderEnd(b,p(m,{alphaCorrection:f?-c:0}),!0),this.getCylinderEnd(b,p(q,{alphaCorrection:f?-c:0}),!1)),zIndexes:{frontLower:e?2:1,backLower:e?1:2,rightLower:e?1:2}}));return g}});h(c,"masters/modules/funnel3d.src.js",[],function(){})});
//# sourceMappingURL=funnel3d.js.map