/*
 Highcharts Gantt JS v8.2.2 (2020-11-05)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(I){c(I);c.Highcharts=I;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function I(c,w,B,u){c.hasOwnProperty(w)||(c[w]=u.apply(null,B))}c=c?c._modules:{};I(c,"Gantt/Tree.js",[c["Core/Utilities.js"]],function(c){var w=c.extend,B=c.isNumber,u=c.pick,z=function(c,x){var m=c.reduce(function(d,
p){var t=u(p.parent,"");"undefined"===typeof d[t]&&(d[t]=[]);d[t].push(p);return d},{});Object.keys(m).forEach(function(d,p){var t=m[d];""!==d&&-1===x.indexOf(d)&&(t.forEach(function(d){p[""].push(d)}),delete p[d])});return m},A=function(c,x,m,d,p,t){var y=0,q=0,D=t&&t.after,e=t&&t.before;x={data:d,depth:m-1,id:c,level:m,parent:x};var g,l;"function"===typeof e&&e(x,t);e=(p[c]||[]).map(function(b){var a=A(b.id,c,m+1,b,p,t),f=b.start;b=!0===b.milestone?f:b.end;g=!B(g)||f<g?f:g;l=!B(l)||b>l?b:l;y=y+
1+a.descendants;q=Math.max(a.height+1,q);return a});d&&(d.start=u(d.start,g),d.end=u(d.end,l));w(x,{children:e,descendants:y,height:q});"function"===typeof D&&D(x,t);return x};return{getListOfParents:z,getNode:A,getTree:function(c,x){var m=c.map(function(d){return d.id});c=z(c,m);return A("",null,1,null,c,x)}}});I(c,"Core/Axis/TreeGridTick.js",[c["Core/Utilities.js"]],function(c){var w=c.addEvent,B=c.defined,u=c.isObject,z=c.isNumber,A=c.pick,E=c.wrap,x;(function(m){function d(){this.treeGrid||(this.treeGrid=
new D(this))}function p(e,g){e=e.treeGrid;var l=!e.labelIcon,b=g.renderer,a=g.xy,f=g.options,r=f.width,n=f.height,h=a.x-r/2-f.padding;a=a.y-n/2;var G=g.collapsed?90:180,H=g.show&&z(a),C=e.labelIcon;C||(e.labelIcon=C=b.path(b.symbols[f.type](f.x,f.y,r,n)).addClass("highcharts-label-icon").add(g.group));H||C.attr({y:-9999});b.styledMode||C.attr({"stroke-width":1,fill:A(g.color,"#666666")}).css({cursor:"pointer",stroke:f.lineColor,strokeWidth:f.lineWidth});C[l?"attr":"animate"]({translateX:h,translateY:a,
rotation:G})}function t(e,g,l,b,a,f,r,n,h){var G=A(this.options&&this.options.labels,f);f=this.pos;var H=this.axis,C="treegrid"===H.options.type;e=e.apply(this,[g,l,b,a,G,r,n,h]);C&&(g=G&&u(G.symbol,!0)?G.symbol:{},G=G&&z(G.indentation)?G.indentation:0,f=(f=(H=H.treeGrid.mapOfPosToGridNode)&&H[f])&&f.depth||1,e.x+=g.width+2*g.padding+(f-1)*G);return e}function y(e){var g=this,l=g.pos,b=g.axis,a=g.label,f=b.treeGrid.mapOfPosToGridNode,r=b.options,n=A(g.options&&g.options.labels,r&&r.labels),h=n&&u(n.symbol,
!0)?n.symbol:{},G=(f=f&&f[l])&&f.depth;r="treegrid"===r.type;var H=-1<b.tickPositions.indexOf(l);l=b.chart.styledMode;r&&f&&a&&a.element&&a.addClass("highcharts-treegrid-node-level-"+G);e.apply(g,Array.prototype.slice.call(arguments,1));r&&a&&a.element&&f&&f.descendants&&0<f.descendants&&(b=b.treeGrid.isCollapsed(f),p(g,{color:!l&&a.styles&&a.styles.color||"",collapsed:b,group:a.parentGroup,options:h,renderer:a.renderer,show:H,xy:a.xy}),h="highcharts-treegrid-node-"+(b?"expanded":"collapsed"),a.addClass("highcharts-treegrid-node-"+
(b?"collapsed":"expanded")).removeClass(h),l||a.css({cursor:"pointer"}),[a,g.treeGrid.labelIcon].forEach(function(f){f&&!f.attachedTreeGridEvents&&(w(f.element,"mouseover",function(){a.addClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:"underline"})}),w(f.element,"mouseout",function(){var f=B(n.style)?n.style:{};a.removeClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:f.textDecoration})}),w(f.element,"click",function(){g.treeGrid.toggleCollapse()}),
f.attachedTreeGridEvents=!0)}))}var q=!1;m.compose=function(e){q||(w(e,"init",d),E(e.prototype,"getLabelPosition",t),E(e.prototype,"renderLabel",y),e.prototype.collapse=function(e){this.treeGrid.collapse(e)},e.prototype.expand=function(e){this.treeGrid.expand(e)},e.prototype.toggleCollapse=function(e){this.treeGrid.toggleCollapse(e)},q=!0)};var D=function(){function e(e){this.tick=e}e.prototype.collapse=function(e){var l=this.tick,b=l.axis,a=b.brokenAxis;a&&b.treeGrid.mapOfPosToGridNode&&(l=b.treeGrid.collapse(b.treeGrid.mapOfPosToGridNode[l.pos]),
a.setBreaks(l,A(e,!0)))};e.prototype.expand=function(e){var l=this.tick,b=l.axis,a=b.brokenAxis;a&&b.treeGrid.mapOfPosToGridNode&&(l=b.treeGrid.expand(b.treeGrid.mapOfPosToGridNode[l.pos]),a.setBreaks(l,A(e,!0)))};e.prototype.toggleCollapse=function(e){var l=this.tick,b=l.axis,a=b.brokenAxis;a&&b.treeGrid.mapOfPosToGridNode&&(l=b.treeGrid.toggleCollapse(b.treeGrid.mapOfPosToGridNode[l.pos]),a.setBreaks(l,A(e,!0)))};return e}();m.Additions=D})(x||(x={}));return x});I(c,"Mixins/TreeSeries.js",[c["Core/Color/Color.js"],
c["Core/Utilities.js"]],function(c,w){var B=w.extend,u=w.isArray,z=w.isNumber,A=w.isObject,E=w.merge,x=w.pick;return{getColor:function(m,d){var p=d.index,t=d.mapOptionsToLevel,y=d.parentColor,q=d.parentColorIndex,D=d.series,e=d.colors,g=d.siblings,l=D.points,b=D.chart.options.chart,a;if(m){l=l[m.i];m=t[m.level]||{};if(t=l&&m.colorByPoint){var f=l.index%(e?e.length:b.colorCount);var r=e&&e[f]}if(!D.chart.styledMode){e=l&&l.options.color;b=m&&m.color;if(a=y)a=(a=m&&m.colorVariation)&&"brightness"===
a.key?c.parse(y).brighten(p/g*a.to).get():y;a=x(e,b,r,a,D.color)}var n=x(l&&l.options.colorIndex,m&&m.colorIndex,f,q,d.colorIndex)}return{color:a,colorIndex:n}},getLevelOptions:function(m){var d=null;if(A(m)){d={};var p=z(m.from)?m.from:1;var t=m.levels;var y={};var q=A(m.defaults)?m.defaults:{};u(t)&&(y=t.reduce(function(d,e){if(A(e)&&z(e.level)){var g=E({},e);var l="boolean"===typeof g.levelIsConstant?g.levelIsConstant:q.levelIsConstant;delete g.levelIsConstant;delete g.level;e=e.level+(l?0:p-1);
A(d[e])?B(d[e],g):d[e]=g}return d},{}));t=z(m.to)?m.to:1;for(m=0;m<=t;m++)d[m]=E({},q,A(y[m])?y[m]:{})}return d},setTreeValues:function t(d,p){var y=p.before,q=p.idRoot,D=p.mapIdToNode[q],e=p.points[d.i],g=e&&e.options||{},l=0,b=[];B(d,{levelDynamic:d.level-(("boolean"===typeof p.levelIsConstant?p.levelIsConstant:1)?0:D.level),name:x(e&&e.name,""),visible:q===d.id||("boolean"===typeof p.visible?p.visible:!1)});"function"===typeof y&&(d=y(d,p));d.children.forEach(function(a,f){var r=B({},p);B(r,{index:f,
siblings:d.children.length,visible:d.visible});a=t(a,r);b.push(a);a.visible&&(l+=a.val)});d.visible=0<l||d.visible;y=x(g.value,l);B(d,{children:b,childrenTotal:l,isLeaf:d.visible&&!l,val:y});return d},updateRootId:function(d){if(A(d)){var p=A(d.options)?d.options:{};p=x(d.rootNode,p.rootId,"");A(d.userOptions)&&(d.userOptions.rootId=p);d.rootNode=p}return p}}});I(c,"Core/Axis/GridAxis.js",[c["Core/Axis/Axis.js"],c["Core/Globals.js"],c["Core/Axis/Tick.js"],c["Core/Utilities.js"]],function(c,w,B,u){var z=
u.addEvent,A=u.defined,E=u.erase,x=u.find,m=u.isArray,d=u.isNumber,p=u.merge,t=u.pick,y=u.timeUnits,q=u.wrap,D=w.Chart,e=function(b){var a=b.options;a.labels||(a.labels={});a.labels.align=t(a.labels.align,"center");b.categories||(a.showLastLabel=!1);b.labelRotation=0;a.labels.rotation=0};"";c.prototype.getMaxLabelDimensions=function(b,a){var f={width:0,height:0};a.forEach(function(a){a=b[a];if(u.isObject(a,!0)){var n=u.isObject(a.label,!0)?a.label:{};a=n.getBBox?n.getBBox().height:0;n.textStr&&!d(n.textPxLength)&&
(n.textPxLength=n.getBBox().width);var h=d(n.textPxLength)?Math.round(n.textPxLength):0;n.textStr&&(h=Math.round(n.getBBox().width));f.height=Math.max(a,f.height);f.width=Math.max(h,f.width)}});return f};w.dateFormats.W=function(b){b=new this.Date(b);var a=(this.get("Day",b)+6)%7,f=new this.Date(b.valueOf());this.set("Date",f,this.get("Date",b)-a+3);a=new this.Date(this.get("FullYear",f),0,1);4!==this.get("Day",a)&&(this.set("Month",b,0),this.set("Date",b,1+(11-this.get("Day",a))%7));return(1+Math.floor((f.valueOf()-
a.valueOf())/6048E5)).toString()};w.dateFormats.E=function(b){return this.dateFormat("%a",b,!0).charAt(0)};z(D,"afterSetChartSize",function(){this.axes.forEach(function(b){(b.grid&&b.grid.columns||[]).forEach(function(a){a.setAxisSize();a.setAxisTranslation()})})});z(B,"afterGetLabelPosition",function(b){var a=this.label,f=this.axis,r=f.reversed,n=f.chart,h=f.options.grid||{},e=f.options.labels,H=e.align,C=l.Side[f.side],g=b.tickmarkOffset,q=f.tickPositions,J=this.pos-g;q=d(q[b.index+1])?q[b.index+
1]-g:f.max+g;var k=f.tickSize("tick");g=k?k[0]:0;k=k?k[1]/2:0;if(!0===h.enabled){if("top"===C){h=f.top+f.offset;var v=h-g}else"bottom"===C?(v=n.chartHeight-f.bottom+f.offset,h=v+g):(h=f.top+f.len-f.translate(r?q:J),v=f.top+f.len-f.translate(r?J:q));"right"===C?(C=n.chartWidth-f.right+f.offset,r=C+g):"left"===C?(r=f.left+f.offset,C=r-g):(C=Math.round(f.left+f.translate(r?q:J))-k,r=Math.round(f.left+f.translate(r?J:q))-k);this.slotWidth=r-C;b.pos.x="left"===H?C:"right"===H?r:C+(r-C)/2;b.pos.y=v+(h-
v)/2;n=n.renderer.fontMetrics(e.style.fontSize,a.element);a=a.getBBox().height;e.useHTML?b.pos.y+=n.b+-(a/2):(a=Math.round(a/n.h),b.pos.y+=(n.b-(n.h-n.f))/2+-((a-1)*n.h/2));b.pos.x+=f.horiz&&e.x||0}});var g=function(){function b(a){this.axis=a}b.prototype.isOuterAxis=function(){var a=this.axis,f=a.grid.columnIndex,b=a.linkedParent&&a.linkedParent.grid.columns||a.grid.columns,n=f?a.linkedParent:a,h=-1,e=0;a.chart[a.coll].forEach(function(f,b){f.side!==a.side||f.options.isInternal||(e=b,f===n&&(h=b))});
return e===h&&(d(f)?b.length===f:!0)};b.prototype.renderBorder=function(a){var f=this.axis,b=f.chart.renderer,n=f.options;a=b.path(a).addClass("highcharts-axis-line").add(f.axisBorder);b.styledMode||a.attr({stroke:n.lineColor,"stroke-width":n.lineWidth,zIndex:7});return a};return b}(),l=function(){function b(){}b.compose=function(a){c.keepProps.push("grid");q(a.prototype,"unsquish",b.wrapUnsquish);z(a,"init",b.onInit);z(a,"afterGetOffset",b.onAfterGetOffset);z(a,"afterGetTitlePosition",b.onAfterGetTitlePosition);
z(a,"afterInit",b.onAfterInit);z(a,"afterRender",b.onAfterRender);z(a,"afterSetAxisTranslation",b.onAfterSetAxisTranslation);z(a,"afterSetOptions",b.onAfterSetOptions);z(a,"afterSetOptions",b.onAfterSetOptions2);z(a,"afterSetScale",b.onAfterSetScale);z(a,"afterTickSize",b.onAfterTickSize);z(a,"trimTicks",b.onTrimTicks);z(a,"destroy",b.onDestroy)};b.onAfterGetOffset=function(){var a=this.grid;(a&&a.columns||[]).forEach(function(a){a.getOffset()})};b.onAfterGetTitlePosition=function(a){if(!0===(this.options.grid||
{}).enabled){var f=this.axisTitle,r=this.height,n=this.horiz,h=this.left,e=this.offset,l=this.opposite,C=this.options.title,g=void 0===C?{}:C;C=this.top;var q=this.width,J=this.tickSize(),k=f&&f.getBBox().width,v=g.x||0,F=g.y||0,d=t(g.margin,n?5:10);f=this.chart.renderer.fontMetrics(g.style&&g.style.fontSize,f).f;J=(n?C+r:h)+(n?1:-1)*(l?-1:1)*(J?J[0]/2:0)+(this.side===b.Side.bottom?f:0);a.titlePosition.x=n?h-k/2-d+v:J+(l?q:0)+e+v;a.titlePosition.y=n?J-(l?r:0)+(l?f:-f)/2+e+F:C-d+F}};b.onAfterInit=
function(){var a=this.chart,f=this.options.grid;f=void 0===f?{}:f;var b=this.userOptions;f.enabled&&(e(this),q(this,"labelFormatter",function(a){var f=this.axis,h=this.value,b=f.tickPositions,n=(f.isLinked?f.linkedParent:f).series[0],k=h===b[0];b=h===b[b.length-1];var v=n&&x(n.options.data,function(k){return k[f.isXAxis?"x":"y"]===h});if(v&&n.is("gantt")){var F=p(v);w.seriesTypes.gantt.prototype.setGanttPointAliases(F)}this.isFirst=k;this.isLast=b;this.point=F;return a.call(this)}));if(f.columns)for(var n=
this.grid.columns=[],h=this.grid.columnIndex=0;++h<f.columns.length;){var l=p(b,f.columns[f.columns.length-h-1],{linkedTo:0,type:"category",scrollbar:{enabled:!1}});delete l.grid.columns;l=new c(this.chart,l);l.grid.isColumn=!0;l.grid.columnIndex=h;E(a.axes,l);E(a[this.coll],l);n.push(l)}};b.onAfterRender=function(){var a,f=this.grid,e=this.options;if(!0===(e.grid||{}).enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();
if(this.grid&&this.grid.isOuterAxis()&&this.axisLine&&(e=e.lineWidth)){e=this.getLinePath(e);var n=e[0],h=e[1],l=((this.tickSize("tick")||[1])[0]-1)*(this.side===b.Side.top||this.side===b.Side.left?-1:1);"M"===n[0]&&"L"===h[0]&&(this.horiz?(n[2]+=l,h[2]+=l):(n[1]+=l,h[1]+=l));!this.horiz&&this.chart.marginRight&&(n=[n,["L",this.left,n[2]]],l=["L",this.chart.chartWidth-this.chart.marginRight,this.toPixels(this.max+this.tickmarkOffset)],h=[["M",h[1],this.toPixels(this.max+this.tickmarkOffset)],l],this.grid.upperBorder||
0===this.min%1||(this.grid.upperBorder=this.grid.renderBorder(n)),this.grid.upperBorder&&this.grid.upperBorder.animate({d:n}),this.grid.lowerBorder||0===this.max%1||(this.grid.lowerBorder=this.grid.renderBorder(h)),this.grid.lowerBorder&&this.grid.lowerBorder.animate({d:h}));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:e}):this.grid.axisLineExtra=this.grid.renderBorder(e);this.axisLine[this.showAxis?"show":"hide"](!0)}(f&&f.columns||[]).forEach(function(a){a.render()});!this.horiz&&
this.chart.hasRendered&&(this.scrollbar||(null===(a=this.linkedParent)||void 0===a?0:a.scrollbar))&&(a=this.max,f=this.tickmarkOffset,e=this.tickPositions[this.tickPositions.length-1],h=this.tickPositions[0],this.min-h>f?this.ticks[h].label.hide():this.ticks[h].label.show(),e-a>f?this.ticks[e].label.hide():this.ticks[e].label.show(),e-a<f&&0<e-a&&this.ticks[e].isLast?this.ticks[e].mark.hide():this.ticks[e-1].mark.show())}};b.onAfterSetAxisTranslation=function(){var a,f=this.tickPositions&&this.tickPositions.info,
b=this.options,n=b.grid||{},h=this.userOptions.labels||{};this.horiz?(!0===n.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),f&&b.dateTimeLabelFormats&&b.labels&&!A(h.align)&&(!1===b.dateTimeLabelFormats[f.unitName].range||1<f.count)&&(b.labels.align="left",A(h.x)||(b.labels.x=3))):"treegrid"!==this.options.type&&(null===(a=this.grid)||void 0===a?0:a.columns)&&(this.minPointOffset=this.tickInterval)};b.onAfterSetOptions=function(a){var f=this.options;a=a.userOptions;var b=f&&u.isObject(f.grid,
!0)?f.grid:{};if(!0===b.enabled){var n=p(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",
null]]},a);"xAxis"===this.coll&&(A(a.linkedTo)&&!A(a.tickPixelInterval)&&(n.tickPixelInterval=350),A(a.tickPixelInterval)||!A(a.linkedTo)||A(a.tickPositioner)||A(a.tickInterval)||(n.tickPositioner=function(a,f){var b=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(b){var h,e=n.units;for(h=0;h<e.length;h++)if(e[h][0]===b.unitName){var l=h;break}if(e[l+1]){var r=e[l+1][0];var k=(e[l+1][1]||[1])[0]}else"year"===b.unitName&&(r="year",k=10*b.count);b=y[r];this.tickInterval=
b*k;return this.getTimeTicks({unitRange:b,count:k,unitName:r},a,f,this.options.startOfWeek)}}));p(!0,this.options,n);this.horiz&&(f.minPadding=t(a.minPadding,0),f.maxPadding=t(a.maxPadding,0));d(f.grid.borderWidth)&&(f.tickWidth=f.lineWidth=b.borderWidth)}};b.onAfterSetOptions2=function(a){a=(a=a.userOptions)&&a.grid||{};var f=a.columns;a.enabled&&f&&p(!0,this.options,f[f.length-1])};b.onAfterSetScale=function(){(this.grid.columns||[]).forEach(function(a){a.setScale()})};b.onAfterTickSize=function(a){var f=
c.defaultLeftAxisOptions,b=this.horiz,n=this.maxLabelDimensions,h=this.options.grid;h=void 0===h?{}:h;h.enabled&&n&&(f=2*Math.abs(f.labels.x),b=b?h.cellHeight||f+n.height:f+n.width,m(a.tickSize)?a.tickSize[0]=b:a.tickSize=[b,0])};b.onDestroy=function(a){var f=this.grid;(f.columns||[]).forEach(function(f){f.destroy(a.keepEvents)});f.columns=void 0};b.onInit=function(a){a=a.userOptions||{};var f=a.grid||{};f.enabled&&A(f.borderColor)&&(a.tickColor=a.lineColor=f.borderColor);this.grid||(this.grid=new g(this))};
b.onTrimTicks=function(){var a=this.options,f=this.categories,b=this.tickPositions,n=b[0],h=b[b.length-1],e=this.linkedParent&&this.linkedParent.min||this.min,l=this.linkedParent&&this.linkedParent.max||this.max,g=this.tickInterval;!0!==(a.grid||{}).enabled||f||!this.horiz&&!this.isLinked||(n<e&&n+g>e&&!a.startOnTick&&(b[0]=e),h>l&&h-g<l&&!a.endOnTick&&(b[b.length-1]=l))};b.wrapUnsquish=function(a){var f=this.options.grid;return!0===(void 0===f?{}:f).enabled&&this.categories?this.tickInterval:a.apply(this,
Array.prototype.slice.call(arguments,1))};return b}();(function(b){b=b.Side||(b.Side={});b[b.top=0]="top";b[b.right=1]="right";b[b.bottom=2]="bottom";b[b.left=3]="left"})(l||(l={}));l.compose(c);return l});I(c,"Core/Axis/BrokenAxis.js",[c["Core/Axis/Axis.js"],c["Series/Line/LineSeries.js"],c["Extensions/Stacking.js"],c["Core/Utilities.js"]],function(c,w,B,u){var z=u.addEvent,A=u.find,E=u.fireEvent,x=u.isArray,m=u.isNumber,d=u.pick,p=function(){function p(p){this.hasBreaks=!1;this.axis=p}p.isInBreak=
function(p,q){var d=p.repeat||Infinity,e=p.from,g=p.to-p.from;q=q>=e?(q-e)%d:d-(e-q)%d;return p.inclusive?q<=g:q<g&&0!==q};p.lin2Val=function(d){var q=this.brokenAxis;q=q&&q.breakArray;if(!q)return d;var D;for(D=0;D<q.length;D++){var e=q[D];if(e.from>=d)break;else e.to<d?d+=e.len:p.isInBreak(e,d)&&(d+=e.len)}return d};p.val2Lin=function(d){var q=this.brokenAxis;q=q&&q.breakArray;if(!q)return d;var D=d,e;for(e=0;e<q.length;e++){var g=q[e];if(g.to<=d)D-=g.len;else if(g.from>=d)break;else if(p.isInBreak(g,
d)){D-=d-g.from;break}}return D};p.prototype.findBreakAt=function(d,p){return A(p,function(p){return p.from<d&&d<p.to})};p.prototype.isInAnyBreak=function(m,q){var D=this.axis,e=D.options.breaks,g=e&&e.length,l;if(g){for(;g--;)if(p.isInBreak(e[g],m)){var b=!0;l||(l=d(e[g].showPoints,!D.isXAxis))}var a=b&&q?b&&!l:b}return a};p.prototype.setBreaks=function(m,q){var D=this,e=D.axis,g=x(m)&&!!m.length;e.isDirty=D.hasBreaks!==g;D.hasBreaks=g;e.options.breaks=e.userOptions.breaks=m;e.forceRedraw=!0;e.series.forEach(function(e){e.isDirty=
!0});g||e.val2lin!==p.val2Lin||(delete e.val2lin,delete e.lin2val);g&&(e.userOptions.ordinal=!1,e.lin2val=p.lin2Val,e.val2lin=p.val2Lin,e.setExtremes=function(e,b,a,f,r){if(D.hasBreaks){for(var n,h=this.options.breaks;n=D.findBreakAt(e,h);)e=n.to;for(;n=D.findBreakAt(b,h);)b=n.from;b<e&&(b=e)}c.prototype.setExtremes.call(this,e,b,a,f,r)},e.setAxisTranslation=function(){c.prototype.setAxisTranslation.call(this);D.unitLength=null;if(D.hasBreaks){var l=e.options.breaks||[],b=[],a=[],f=0,r,n=e.userMin||
e.min,h=e.userMax||e.max,g=d(e.pointRangePadding,0),H;l.forEach(function(a){r=a.repeat||Infinity;p.isInBreak(a,n)&&(n+=a.to%r-n%r);p.isInBreak(a,h)&&(h-=h%r-a.from%r)});l.forEach(function(a){q=a.from;for(r=a.repeat||Infinity;q-r>n;)q-=r;for(;q<n;)q+=r;for(H=q;H<h;H+=r)b.push({value:H,move:"in"}),b.push({value:H+(a.to-a.from),move:"out",size:a.breakSize})});b.sort(function(a,f){return a.value===f.value?("in"===a.move?0:1)-("in"===f.move?0:1):a.value-f.value});var C=0;var q=n;b.forEach(function(b){C+=
"in"===b.move?1:-1;1===C&&"in"===b.move&&(q=b.value);0===C&&(a.push({from:q,to:b.value,len:b.value-q-(b.size||0)}),f+=b.value-q-(b.size||0))});e.breakArray=D.breakArray=a;D.unitLength=h-n-f+g;E(e,"afterBreaks");e.staticScale?e.transA=e.staticScale:D.unitLength&&(e.transA*=(h-e.min+g)/D.unitLength);g&&(e.minPixelPadding=e.transA*e.minPointOffset);e.min=n;e.max=h}});d(q,!0)&&e.chart.redraw()};return p}();u=function(){function t(){}t.compose=function(t,q){t.keepProps.push("brokenAxis");var D=w.prototype;
D.drawBreaks=function(e,g){var l=this,b=l.points,a,f,r,n;if(e&&e.brokenAxis&&e.brokenAxis.hasBreaks){var h=e.brokenAxis;g.forEach(function(g){a=h&&h.breakArray||[];f=e.isXAxis?e.min:d(l.options.threshold,e.min);b.forEach(function(b){n=d(b["stack"+g.toUpperCase()],b[g]);a.forEach(function(a){if(m(f)&&m(n)){r=!1;if(f<a.from&&n>a.to||f>a.from&&n<a.from)r="pointBreak";else if(f<a.from&&n>a.from&&n<a.to||f>a.from&&n>a.to&&n<a.from)r="pointInBreak";r&&E(e,r,{point:b,brk:a})}})})})}};D.gappedPath=function(){var e=
this.currentDataGrouping,g=e&&e.gapSize;e=this.options.gapSize;var l=this.points.slice(),b=l.length-1,a=this.yAxis,f;if(e&&0<b)for("value"!==this.options.gapUnit&&(e*=this.basePointRange),g&&g>e&&g>=this.basePointRange&&(e=g),f=void 0;b--;)f&&!1!==f.visible||(f=l[b+1]),g=l[b],!1!==f.visible&&!1!==g.visible&&(f.x-g.x>e&&(f=(g.x+f.x)/2,l.splice(b+1,0,{isNull:!0,x:f}),a.stacking&&this.options.stacking&&(f=a.stacking.stacks[this.stackKey][f]=new B(a,a.options.stackLabels,!1,f,this.stack),f.total=0)),
f=g);return this.getGraphPath(l)};z(t,"init",function(){this.brokenAxis||(this.brokenAxis=new p(this))});z(t,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});z(t,"afterSetTickPositions",function(){var e=this.brokenAxis;if(e&&e.hasBreaks){var g=this.tickPositions,l=this.tickPositions.info,b=[],a;for(a=0;a<g.length;a++)e.isInAnyBreak(g[a])||b.push(g[a]);this.tickPositions=b;this.tickPositions.info=l}});z(t,"afterSetOptions",function(){this.brokenAxis&&
this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});z(q,"afterGeneratePoints",function(){var e=this.options.connectNulls,g=this.points,l=this.xAxis,b=this.yAxis;if(this.isDirty)for(var a=g.length;a--;){var f=g[a],r=!(null===f.y&&!1===e)&&(l&&l.brokenAxis&&l.brokenAxis.isInAnyBreak(f.x,!0)||b&&b.brokenAxis&&b.brokenAxis.isInAnyBreak(f.y,!0));f.visible=r?!1:!1!==f.options.visible}});z(q,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,d(this.pointArrayMap,["y"]))})};
return t}();u.compose(c,w);return u});I(c,"Core/Axis/TreeGridAxis.js",[c["Core/Globals.js"],c["Core/Axis/Axis.js"],c["Core/Axis/Tick.js"],c["Gantt/Tree.js"],c["Core/Axis/TreeGridTick.js"],c["Mixins/TreeSeries.js"],c["Core/Utilities.js"]],function(c,w,B,u,z,A,E){var x=A.getLevelOptions,m=E.addEvent,d=E.find,p=E.fireEvent,t=E.isArray,y=E.isNumber,q=E.isObject,D=E.isString,e=E.merge,g=E.pick,l=E.wrap,b;(function(a){function f(a,k){var b=a.collapseStart||0;a=a.collapseEnd||0;a>=k&&(b-=.5);return{from:b,
to:a,showPoints:!1}}function b(a,k,b){var f=[],v=[],h={},e={},n=-1,l="boolean"===typeof k?k:!1;a=u.getTree(a,{after:function(a){a=e[a.pos];var k=0,b=0;a.children.forEach(function(a){b+=(a.descendants||0)+1;k=Math.max((a.height||0)+1,k)});a.descendants=b;a.height=k;a.collapsed&&v.push(a)},before:function(a){var k=q(a.data,!0)?a.data:{},b=D(k.name)?k.name:"",v=h[a.parent];v=q(v,!0)?e[v.pos]:null;var F=function(a){return a.name===b},r;l&&q(v,!0)&&(r=d(v.children,F))?(F=r.pos,r.nodes.push(a)):F=n++;e[F]||
(e[F]=r={depth:v?v.depth+1:0,name:b,id:k.id,nodes:[a],children:[],pos:F},-1!==F&&f.push(b),q(v,!0)&&v.children.push(r));D(a.id)&&(h[a.id]=a);r&&!0===k.collapsed&&(r.collapsed=!0);a.pos=F}});e=function(a,k){var b=function(a,f,v){var h=f+(-1===f?0:k-1),e=(h-f)/2,n=f+e;a.nodes.forEach(function(a){var k=a.data;q(k,!0)&&(k.y=f+(k.seriesIndex||0),delete k.seriesIndex);a.pos=n});v[n]=a;a.pos=n;a.tickmarkOffset=e+.5;a.collapseStart=h+.5;a.children.forEach(function(a){b(a,h+1,v);h=(a.collapseEnd||0)-.5});
a.collapseEnd=h+.5;return v};return b(a["-1"],-1,{})}(e,b);return{categories:f,mapOfIdToNode:h,mapOfPosToGridNode:e,collapsedNodes:v,tree:a}}function n(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(k){var f=k.options||{},h=f.labels,n=f.uniqueNames,l=0;f=f.max;if(!k.treeGrid.mapOfPosToGridNode||k.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty})){var r=k.series.reduce(function(a,k){k.visible&&((k.options.data||[]).forEach(function(f){k.options.keys&&
k.options.keys.length&&(f=k.pointClass.prototype.optionsToObject.call({series:k},f),c.seriesTypes.gantt.prototype.setGanttPointAliases(f));q(f,!0)&&(f.seriesIndex=l,a.push(f))}),!0===n&&l++);return a},[]);if(f&&r.length<f)for(var g=r.length;g<=f;g++)r.push({name:g+"\u200b"});f=b(r,n||!1,!0===n?l:1);k.categories=f.categories;k.treeGrid.mapOfPosToGridNode=f.mapOfPosToGridNode;k.hasNames=!0;k.treeGrid.tree=f.tree;k.series.forEach(function(a){var k=(a.options.data||[]).map(function(k){t(k)&&a.options.keys&&
a.options.keys.length&&r.forEach(function(a){0<=k.indexOf(a.x)&&0<=k.indexOf(a.x2)&&(k=a)});return q(k,!0)?e(k):k});a.visible&&a.setData(k,!1)});k.treeGrid.mapOptionsToLevel=x({defaults:h,from:1,levels:h&&h.levels,to:k.treeGrid.tree&&k.treeGrid.tree.height});"beforeRender"===a.type&&(k.treeGrid.collapsedNodes=f.collapsedNodes)}})}function h(a,k){var f=this.treeGrid.mapOptionsToLevel||{},b=this.ticks,h=b[k],e;if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var n=this.treeGrid.mapOfPosToGridNode[k];
(f=f[n.depth])&&(e={labels:f});h?(h.parameters.category=n.name,h.options=e,h.addLabel()):b[k]=new B(this,k,void 0,void 0,{category:n.name,tickmarkOffset:n.tickmarkOffset,options:e})}else a.apply(this,Array.prototype.slice.call(arguments,1))}function G(a){var k=this.options;k=(k=k&&k.labels)&&y(k.indentation)?k.indentation:0;var f=a.apply(this,Array.prototype.slice.call(arguments,1));if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var b=this.treeGrid.mapOfPosToGridNode[-1].height||
0;f.width+=k*(b-1)}return f}function H(a,k,f){var h=this,v="treegrid"===f.type;h.treeGrid||(h.treeGrid=new w(h));v&&(m(k,"beforeRender",n),m(k,"beforeRedraw",n),m(k,"addSeries",function(a){a.options.data&&(a=b(a.options.data,f.uniqueNames||!1,1),h.treeGrid.collapsedNodes=(h.treeGrid.collapsedNodes||[]).concat(a.collapsedNodes))}),m(h,"foundExtremes",function(){h.treeGrid.collapsedNodes&&h.treeGrid.collapsedNodes.forEach(function(a){var k=h.treeGrid.collapse(a);h.brokenAxis&&(h.brokenAxis.setBreaks(k,
!1),h.treeGrid.collapsedNodes&&(h.treeGrid.collapsedNodes=h.treeGrid.collapsedNodes.filter(function(k){return a.collapseStart!==k.collapseStart||a.collapseEnd!==k.collapseEnd})))})}),m(h,"afterBreaks",function(){var a;"yAxis"===h.coll&&!h.staticScale&&(null===(a=h.chart.options.chart)||void 0===a?0:a.height)&&(h.isDirty=!0)}),f=e({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},
f,{reversed:!0,grid:{columns:void 0}}));a.apply(h,[k,f]);v&&(h.hasNames=!0,h.options.showLastLabel=!0)}function C(a){var k=this.options;"treegrid"===k.type?(this.min=g(this.userMin,k.min,this.dataMin),this.max=g(this.userMax,k.max,this.dataMax),p(this,"foundExtremes"),this.setAxisTranslation(),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?this.treeGrid.getTickPositions():[]):a.apply(this,Array.prototype.slice.call(arguments,1))}var M=!1;a.compose=function(a){M||
(l(a.prototype,"generateTick",h),l(a.prototype,"getMaxLabelDimensions",G),l(a.prototype,"init",H),l(a.prototype,"setTickInterval",C),z.compose(B),M=!0)};var w=function(){function a(a){this.axis=a}a.prototype.setCollapsedStatus=function(a){var k=this.axis,f=k.chart;k.series.forEach(function(k){var b=k.options.data;if(a.id&&b){var h=f.get(a.id);k=b[k.data.indexOf(h)];h&&k&&(h.collapsed=a.collapsed,k.collapsed=a.collapsed)}})};a.prototype.collapse=function(a){var k=this.axis,b=k.options.breaks||[],h=
f(a,k.max);b.push(h);a.collapsed=!0;k.treeGrid.setCollapsedStatus(a);return b};a.prototype.expand=function(a){var k=this.axis,b=k.options.breaks||[],h=f(a,k.max);a.collapsed=!1;k.treeGrid.setCollapsedStatus(a);return b.reduce(function(a,k){k.to===h.to&&k.from===h.from||a.push(k);return a},[])};a.prototype.getTickPositions=function(){var a=this.axis,f=Math.floor(a.min/a.tickInterval)*a.tickInterval,b=Math.ceil(a.max/a.tickInterval)*a.tickInterval;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(k,
h){h=+h;!(h>=f&&h<=b)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(h)||k.push(h);return k},[])};a.prototype.isCollapsed=function(a){var k=this.axis,b=k.options.breaks||[],h=f(a,k.max);return b.some(function(a){return a.from===h.from&&a.to===h.to})};a.prototype.toggleCollapse=function(a){return this.isCollapsed(a)?this.expand(a):this.collapse(a)};return a}();a.Additions=w})(b||(b={}));w.prototype.utils={getNode:u.getNode};b.compose(w);return b});I(c,"Extensions/CurrentDateIndication.js",[c["Core/Axis/Axis.js"],
c["Core/Utilities.js"],c["Core/Axis/PlotLineOrBand.js"]],function(c,w,B){var u=w.addEvent,z=w.merge;w=w.wrap;var A={currentDateIndicator:!0,color:"#ccd6eb",width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:function(c,x){return this.axis.chart.time.dateFormat(x,c)},rotation:0,style:{fontSize:"10px"}}};u(c,"afterSetOptions",function(){var c=this.options,x=c.currentDateIndicator;x&&(x="object"===typeof x?z(A,x):z(A),x.value=new Date,c.plotLines||(c.plotLines=[]),c.plotLines.push(x))});u(B,"render",
function(){this.label&&this.label.attr({text:this.getLabelText(this.options.label)})});w(B.prototype,"getLabelText",function(c,x){var m=this.options;return m.currentDateIndicator&&m.label&&"function"===typeof m.label.formatter?(m.value=new Date,m.label.formatter.call(this,m.value,m.label.format)):c.call(this,x)})});I(c,"Extensions/StaticScale.js",[c["Core/Axis/Axis.js"],c["Core/Chart/Chart.js"],c["Core/Utilities.js"]],function(c,w,B){var u=B.addEvent,z=B.defined,A=B.isNumber,E=B.pick;u(c,"afterSetOptions",
function(){var c=this.chart.options&&this.chart.options.chart;!this.horiz&&A(this.options.staticScale)&&(!c.height||c.scrollablePlotArea&&c.scrollablePlotArea.minHeight)&&(this.staticScale=this.options.staticScale)});w.prototype.adjustHeight=function(){"adjustHeight"!==this.redrawTrigger&&((this.axes||[]).forEach(function(c){var m=c.chart,d=!!m.initiatedScale&&m.options.animation,p=c.options.staticScale;if(c.staticScale&&z(c.min)){var t=E(c.brokenAxis&&c.brokenAxis.unitLength,c.max+c.tickInterval-
c.min)*p;t=Math.max(t,p);p=t-m.plotHeight;1<=Math.abs(p)&&(m.plotHeight=t,m.redrawTrigger="adjustHeight",m.setSize(void 0,m.chartHeight+p,d));c.series.forEach(function(d){(d=d.sharedClipKey&&m[d.sharedClipKey])&&d.attr({height:m.plotHeight})})}}),this.initiatedScale=!0);this.redrawTrigger=null};u(w,"render",w.prototype.adjustHeight)});I(c,"Extensions/ArrowSymbols.js",[c["Core/Renderer/SVG/SVGRenderer.js"]],function(c){c.prototype.symbols.arrow=function(c,B,u,z){return[["M",c,B+z/2],["L",c+u,B],["L",
c,B+z/2],["L",c+u,B+z]]};c.prototype.symbols["arrow-half"]=function(w,B,u,z){return c.prototype.symbols.arrow(w,B,u/2,z)};c.prototype.symbols["triangle-left"]=function(c,B,u,z){return[["M",c+u,B],["L",c,B+z/2],["L",c+u,B+z],["Z"]]};c.prototype.symbols["arrow-filled"]=c.prototype.symbols["triangle-left"];c.prototype.symbols["triangle-left-half"]=function(w,B,u,z){return c.prototype.symbols["triangle-left"](w,B,u/2,z)};c.prototype.symbols["arrow-filled-half"]=c.prototype.symbols["triangle-left-half"]});
I(c,"Gantt/Connection.js",[c["Core/Globals.js"],c["Core/Options.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,w,B,u){function z(d){var p=d.shapeArgs;return p?{xMin:p.x,xMax:p.x+p.width,yMin:p.y,yMax:p.y+p.height}:(p=d.graphic&&d.graphic.getBBox())?{xMin:d.plotX-p.width/2,xMax:d.plotX+p.width/2,yMin:d.plotY-p.height/2,yMax:d.plotY+p.height/2}:null}"";var A=u.defined,E=u.error,x=u.extend,m=u.merge,d=u.objectEach,p=c.deg2rad,t=Math.max,y=Math.min;x(w.defaultOptions,{connectors:{type:"straight",
lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});w=function(){function c(d,e,g){this.toPoint=this.pathfinder=this.graphics=this.fromPoint=this.chart=void 0;this.init(d,e,g)}c.prototype.init=function(d,e,g){this.fromPoint=d;this.toPoint=e;this.options=g;this.chart=d.series.chart;this.pathfinder=this.chart.pathfinder};c.prototype.renderPath=function(d,e,g){var l=this.chart,b=l.styledMode,a=
l.pathfinder,f=!l.options.chart.forExport&&!1!==g,r=this.graphics&&this.graphics.path;a.group||(a.group=l.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(l.seriesGroup));a.group.translate(l.plotLeft,l.plotTop);r&&r.renderer||(r=l.renderer.path().add(a.group),b||r.attr({opacity:0}));r.attr(e);d={d:d};b||(d.opacity=1);r[f?"animate":"attr"](d,g);this.graphics=this.graphics||{};this.graphics.path=r};c.prototype.addMarker=function(d,e,g){var l=this.fromPoint.series.chart,b=l.pathfinder;
l=l.renderer;var a="start"===d?this.fromPoint:this.toPoint,f=a.getPathfinderAnchorPoint(e);if(e.enabled&&((g="start"===d?g[1]:g[g.length-2])&&"M"===g[0]||"L"===g[0])){g={x:g[1],y:g[2]};g=a.getRadiansToVector(g,f);f=a.getMarkerVector(g,e.radius,f);g=-g/p;if(e.width&&e.height){var r=e.width;var n=e.height}else r=n=2*e.radius;this.graphics=this.graphics||{};f={x:f.x-r/2,y:f.y-n/2,width:r,height:n,rotation:g,rotationOriginX:f.x,rotationOriginY:f.y};this.graphics[d]?this.graphics[d].animate(f):(this.graphics[d]=
l.symbol(e.symbol).addClass("highcharts-point-connecting-path-"+d+"-marker").attr(f).add(b.group),l.styledMode||this.graphics[d].attr({fill:e.color||this.fromPoint.color,stroke:e.lineColor,"stroke-width":e.lineWidth,opacity:0}).animate({opacity:1},a.series.options.animation))}};c.prototype.getPath=function(d){var e=this.pathfinder,g=this.chart,l=e.algorithms[d.type],b=e.chartObstacles;if("function"!==typeof l)return E('"'+d.type+'" is not a Pathfinder algorithm.'),{path:[],obstacles:[]};l.requiresObstacles&&
!b&&(b=e.chartObstacles=e.getChartObstacles(d),g.options.connectors.algorithmMargin=d.algorithmMargin,e.chartObstacleMetrics=e.getObstacleMetrics(b));return l(this.fromPoint.getPathfinderAnchorPoint(d.startMarker),this.toPoint.getPathfinderAnchorPoint(d.endMarker),m({chartObstacles:b,lineObstacles:e.lineObstacles||[],obstacleMetrics:e.chartObstacleMetrics,hardBounds:{xMin:0,xMax:g.plotWidth,yMin:0,yMax:g.plotHeight},obstacleOptions:{margin:d.algorithmMargin},startDirectionX:e.getAlgorithmStartDirection(d.startMarker)},
d))};c.prototype.render=function(){var d=this.fromPoint,e=d.series,g=e.chart,l=g.pathfinder,b=m(g.options.connectors,e.options.connectors,d.options.connectors,this.options),a={};g.styledMode||(a.stroke=b.lineColor||d.color,a["stroke-width"]=b.lineWidth,b.dashStyle&&(a.dashstyle=b.dashStyle));a["class"]="highcharts-point-connecting-path highcharts-color-"+d.colorIndex;b=m(a,b);A(b.marker.radius)||(b.marker.radius=y(t(Math.ceil((b.algorithmMargin||8)/2)-1,1),5));d=this.getPath(b);g=d.path;d.obstacles&&
(l.lineObstacles=l.lineObstacles||[],l.lineObstacles=l.lineObstacles.concat(d.obstacles));this.renderPath(g,a,e.options.animation);this.addMarker("start",m(b.marker,b.startMarker),g);this.addMarker("end",m(b.marker,b.endMarker),g)};c.prototype.destroy=function(){this.graphics&&(d(this.graphics,function(d){d.destroy()}),delete this.graphics)};return c}();c.Connection=w;x(B.prototype,{getPathfinderAnchorPoint:function(d){var p=z(this);switch(d.align){case "right":var e="xMax";break;case "left":e="xMin"}switch(d.verticalAlign){case "top":var g=
"yMin";break;case "bottom":g="yMax"}return{x:e?p[e]:(p.xMin+p.xMax)/2,y:g?p[g]:(p.yMin+p.yMax)/2}},getRadiansToVector:function(d,p){var e;A(p)||(e=z(this))&&(p={x:(e.xMin+e.xMax)/2,y:(e.yMin+e.yMax)/2});return Math.atan2(p.y-d.y,d.x-p.x)},getMarkerVector:function(d,p,e){var g=2*Math.PI,l=z(this),b=l.xMax-l.xMin,a=l.yMax-l.yMin,f=Math.atan2(a,b),r=!1;b/=2;var n=a/2,h=l.xMin+b;l=l.yMin+n;for(var c=h,H=l,C=1,m=1;d<-Math.PI;)d+=g;for(;d>Math.PI;)d-=g;g=Math.tan(d);d>-f&&d<=f?(m=-1,r=!0):d>f&&d<=Math.PI-
f?m=-1:d>Math.PI-f||d<=-(Math.PI-f)?(C=-1,r=!0):C=-1;r?(c+=C*b,H+=m*b*g):(c+=a/(2*g)*C,H+=m*n);e.x!==h&&(c=e.x);e.y!==l&&(H=e.y);return{x:c+p*Math.cos(d),y:H-p*Math.sin(d)}}});return w});I(c,"Gantt/PathfinderAlgorithms.js",[c["Core/Utilities.js"]],function(c){function w(d,c,m){m=m||0;var p=d.length-1;c-=1e-7;for(var t,e;m<=p;)if(t=p+m>>1,e=c-d[t].xMin,0<e)m=t+1;else if(0>e)p=t-1;else return t;return 0<m?m-1:0}function B(d,c){for(var p=w(d,c.x+1)+1;p--;){var m;if(m=d[p].xMax>=c.x)m=d[p],m=c.x<=m.xMax&&
c.x>=m.xMin&&c.y<=m.yMax&&c.y>=m.yMin;if(m)return p}return-1}function u(d){var p=[];if(d.length){p.push(["M",d[0].start.x,d[0].start.y]);for(var c=0;c<d.length;++c)p.push(["L",d[c].end.x,d[c].end.y])}return p}function z(d,c){d.yMin=m(d.yMin,c.yMin);d.yMax=x(d.yMax,c.yMax);d.xMin=m(d.xMin,c.xMin);d.xMax=x(d.xMax,c.xMax)}var A=c.extend,E=c.pick,x=Math.min,m=Math.max,d=Math.abs;c=A(function(c,m,y){function p(a,f,b,e,d){a={x:a.x,y:a.y};a[f]=b[e||f]+(d||0);return a}function t(a,f,b){var h=d(f[b]-a[b+"Min"])>
d(f[b]-a[b+"Max"]);return p(f,b,a,b+(h?"Max":"Min"),h?1:-1)}var e=[],g=E(y.startDirectionX,d(m.x-c.x)>d(m.y-c.y))?"x":"y",l=y.chartObstacles,b=B(l,c);y=B(l,m);if(-1<y){var a=l[y];y=t(a,m,g);a={start:y,end:m};var f=y}else f=m;-1<b&&(l=l[b],y=t(l,c,g),e.push({start:c,end:y}),y[g]>=c[g]===y[g]>=f[g]&&(g="y"===g?"x":"y",m=c[g]<m[g],e.push({start:y,end:p(y,g,l,g+(m?"Max":"Min"),m?1:-1)}),g="y"===g?"x":"y"));c=e.length?e[e.length-1].end:c;y=p(c,g,f);e.push({start:c,end:y});g=p(y,"y"===g?"x":"y",f);e.push({start:y,
end:g});e.push(a);return{path:u(e),obstacles:e}},{requiresObstacles:!0});return{fastAvoid:A(function(c,t,y){function p(a,k,f){var b,h=a.x<k.x?1:-1;if(a.x<k.x){var e=a;var n=k}else e=k,n=a;if(a.y<k.y){var d=a;var v=k}else d=k,v=a;for(b=0>h?x(w(C,n.x),C.length-1):0;C[b]&&(0<h&&C[b].xMin<=n.x||0>h&&C[b].xMax>=e.x);){if(C[b].xMin<=n.x&&C[b].xMax>=e.x&&C[b].yMin<=v.y&&C[b].yMax>=d.y)return f?{y:a.y,x:a.x<k.x?C[b].xMin-1:C[b].xMax+1,obstacle:C[b]}:{x:a.x,y:a.y<k.y?C[b].yMin-1:C[b].yMax+1,obstacle:C[b]};
b+=h}return k}function D(a,k,b,f,h){var e=h.soft,n=h.hard,v=f?"x":"y",c={x:k.x,y:k.y},l={x:k.x,y:k.y};h=a[v+"Max"]>=e[v+"Max"];e=a[v+"Min"]<=e[v+"Min"];var r=a[v+"Max"]>=n[v+"Max"];n=a[v+"Min"]<=n[v+"Min"];var g=d(a[v+"Min"]-k[v]),F=d(a[v+"Max"]-k[v]);b=10>d(g-F)?k[v]<b[v]:F<g;l[v]=a[v+"Min"];c[v]=a[v+"Max"];a=p(k,l,f)[v]!==l[v];k=p(k,c,f)[v]!==c[v];b=a?k?b:!0:k?!1:b;b=e?h?b:!0:h?!1:b;return n?r?b:!0:r?!1:b}function e(a,k,b){if(a.x===k.x&&a.y===k.y)return[];var d=b?"x":"y",v=y.obstacleOptions.margin;
var c={soft:{xMin:n,xMax:h,yMin:G,yMax:H},hard:y.hardBounds};var l=B(C,a);if(-1<l){l=C[l];c=D(l,a,k,b,c);z(l,y.hardBounds);var r=b?{y:a.y,x:l[c?"xMax":"xMin"]+(c?1:-1)}:{x:a.x,y:l[c?"yMax":"yMin"]+(c?1:-1)};var g=B(C,r);-1<g&&(g=C[g],z(g,y.hardBounds),r[d]=c?m(l[d+"Max"]-v+1,(g[d+"Min"]+l[d+"Max"])/2):x(l[d+"Min"]+v-1,(g[d+"Max"]+l[d+"Min"])/2),a.x===r.x&&a.y===r.y?(f&&(r[d]=c?m(l[d+"Max"],g[d+"Max"])+1:x(l[d+"Min"],g[d+"Min"])-1),f=!f):f=!1);a=[{start:a,end:r}]}else d=p(a,{x:b?k.x:a.x,y:b?a.y:k.y},
b),a=[{start:a,end:{x:d.x,y:d.y}}],d[b?"x":"y"]!==k[b?"x":"y"]&&(c=D(d.obstacle,d,k,!b,c),z(d.obstacle,y.hardBounds),c={x:b?d.x:d.obstacle[c?"xMax":"xMin"]+(c?1:-1),y:b?d.obstacle[c?"yMax":"yMin"]+(c?1:-1):d.y},b=!b,a=a.concat(e({x:d.x,y:d.y},c,b)));return a=a.concat(e(a[a.length-1].end,k,!b))}function g(a,k,b){var f=x(a.xMax-k.x,k.x-a.xMin)<x(a.yMax-k.y,k.y-a.yMin);b=D(a,k,b,f,{soft:y.hardBounds,hard:y.hardBounds});return f?{y:k.y,x:a[b?"xMax":"xMin"]+(b?1:-1)}:{x:k.x,y:a[b?"yMax":"yMin"]+(b?1:-1)}}
var l=E(y.startDirectionX,d(t.x-c.x)>d(t.y-c.y)),b=l?"x":"y",a=[],f=!1,r=y.obstacleMetrics,n=x(c.x,t.x)-r.maxWidth-10,h=m(c.x,t.x)+r.maxWidth+10,G=x(c.y,t.y)-r.maxHeight-10,H=m(c.y,t.y)+r.maxHeight+10,C=y.chartObstacles;var M=w(C,n);r=w(C,h);C=C.slice(M,r+1);if(-1<(r=B(C,t))){var K=g(C[r],t,c);a.push({end:t,start:K});t=K}for(;-1<(r=B(C,t));)M=0>t[b]-c[b],K={x:t.x,y:t.y},K[b]=C[r][M?b+"Max":b+"Min"]+(M?1:-1),a.push({end:t,start:K}),t=K;c=e(c,t,l);c=c.concat(a.reverse());return{path:u(c),obstacles:c}},
{requiresObstacles:!0}),straight:function(d,c){return{path:[["M",d.x,d.y],["L",c.x,c.y]],obstacles:[{start:d,end:c}]}},simpleConnect:c}});I(c,"Gantt/Pathfinder.js",[c["Gantt/Connection.js"],c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Options.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"],c["Gantt/PathfinderAlgorithms.js"]],function(c,w,B,u,z,A,E){function x(a){var b=a.shapeArgs;return b?{xMin:b.x,xMax:b.x+b.width,yMin:b.y,yMax:b.y+b.height}:(b=a.graphic&&a.graphic.getBBox())?{xMin:a.plotX-
b.width/2,xMax:a.plotX+b.width/2,yMin:a.plotY-b.height/2,yMax:a.plotY+b.height/2}:null}function m(a){for(var f=a.length,d=0,h,c,g=[],p=function(a,f,h){h=e(h,10);var k=a.yMax+h>f.yMin-h&&a.yMin-h<f.yMax+h,d=a.xMax+h>f.xMin-h&&a.xMin-h<f.xMax+h,n=k?a.xMin>f.xMax?a.xMin-f.xMax:f.xMin-a.xMax:Infinity,c=d?a.yMin>f.yMax?a.yMin-f.yMax:f.yMin-a.yMax:Infinity;return d&&k?h?p(a,f,Math.floor(h/2)):Infinity:b(n,c)};d<f;++d)for(h=d+1;h<f;++h)c=p(a[d],a[h]),80>c&&g.push(c);g.push(80);return l(Math.floor(g.sort(function(a,
b){return a-b})[Math.floor(g.length/10)]/2-1),1)}function d(a){if(a.options.pathfinder||a.series.reduce(function(a,b){b.options&&D(!0,b.options.connectors=b.options.connectors||{},b.options.pathfinder);return a||b.options&&b.options.pathfinder},!1))D(!0,a.options.connectors=a.options.connectors||{},a.options.pathfinder),y('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}"";var p=A.addEvent,t=A.defined,y=A.error,q=A.extend,D=A.merge,e=A.pick,
g=A.splat,l=Math.max,b=Math.min;q(u.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});var a=function(){function a(a){this.lineObstacles=this.group=this.connections=this.chartObstacleMetrics=this.chartObstacles=this.chart=void 0;this.init(a)}a.prototype.init=function(a){this.chart=a;this.connections=[];p(a,"redraw",function(){this.pathfinder.update()})};
a.prototype.update=function(a){var b=this.chart,f=this,d=f.connections;f.connections=[];b.series.forEach(function(a){a.visible&&!a.options.isInternal&&a.points.forEach(function(a){var k=a.options;k&&k.dependency&&(k.connect=k.dependency);var h;k=a.options&&a.options.connect&&g(a.options.connect);a.visible&&!1!==a.isInside&&k&&k.forEach(function(k){h=b.get("string"===typeof k?k:k.to);h instanceof z&&h.series.visible&&h.visible&&!1!==h.isInside&&f.connections.push(new c(a,h,"string"===typeof k?{}:k))})})});
for(var e=0,l,r,p=d.length,m=f.connections.length;e<p;++e){r=!1;for(l=0;l<m;++l)if(d[e].fromPoint===f.connections[l].fromPoint&&d[e].toPoint===f.connections[l].toPoint){f.connections[l].graphics=d[e].graphics;r=!0;break}r||d[e].destroy()}delete this.chartObstacles;delete this.lineObstacles;f.renderConnections(a)};a.prototype.renderConnections=function(a){a?this.chart.series.forEach(function(a){var b=function(){var b=a.chart.pathfinder;(b&&b.connections||[]).forEach(function(b){b.fromPoint&&b.fromPoint.series===
a&&b.render()});a.pathfinderRemoveRenderEvent&&(a.pathfinderRemoveRenderEvent(),delete a.pathfinderRemoveRenderEvent)};!1===a.options.animation?b():a.pathfinderRemoveRenderEvent=p(a,"afterAnimate",b)}):this.connections.forEach(function(a){a.render()})};a.prototype.getChartObstacles=function(a){for(var b=[],f=this.chart.series,d=e(a.algorithmMargin,0),c,l=0,g=f.length;l<g;++l)if(f[l].visible&&!f[l].options.isInternal)for(var r=0,p=f[l].points.length,k;r<p;++r)k=f[l].points[r],k.visible&&(k=x(k))&&
b.push({xMin:k.xMin-d,xMax:k.xMax+d,yMin:k.yMin-d,yMax:k.yMax+d});b=b.sort(function(a,b){return a.xMin-b.xMin});t(a.algorithmMargin)||(c=a.algorithmMargin=m(b),b.forEach(function(a){a.xMin-=c;a.xMax+=c;a.yMin-=c;a.yMax+=c}));return b};a.prototype.getObstacleMetrics=function(a){for(var b=0,f=0,d,e,c=a.length;c--;)d=a[c].xMax-a[c].xMin,e=a[c].yMax-a[c].yMin,b<d&&(b=d),f<e&&(f=e);return{maxHeight:f,maxWidth:b}};a.prototype.getAlgorithmStartDirection=function(a){var b="top"!==a.verticalAlign&&"bottom"!==
a.verticalAlign;return"left"!==a.align&&"right"!==a.align?b?void 0:!1:b?!0:void 0};return a}();a.prototype.algorithms=E;B.Pathfinder=a;q(z.prototype,{getPathfinderAnchorPoint:function(a){var b=x(this);switch(a.align){case "right":var f="xMax";break;case "left":f="xMin"}switch(a.verticalAlign){case "top":var h="yMin";break;case "bottom":h="yMax"}return{x:f?b[f]:(b.xMin+b.xMax)/2,y:h?b[h]:(b.yMin+b.yMax)/2}},getRadiansToVector:function(a,b){var f;t(b)||(f=x(this))&&(b={x:(f.xMin+f.xMax)/2,y:(f.yMin+
f.yMax)/2});return Math.atan2(b.y-a.y,a.x-b.x)},getMarkerVector:function(a,b,d){var f=2*Math.PI,e=x(this),c=e.xMax-e.xMin,l=e.yMax-e.yMin,n=Math.atan2(l,c),g=!1;c/=2;var p=l/2,k=e.xMin+c;e=e.yMin+p;for(var v=k,m=e,r=1,q=1;a<-Math.PI;)a+=f;for(;a>Math.PI;)a-=f;f=Math.tan(a);a>-n&&a<=n?(q=-1,g=!0):a>n&&a<=Math.PI-n?q=-1:a>Math.PI-n||a<=-(Math.PI-n)?(r=-1,g=!0):r=-1;g?(v+=r*c,m+=q*c*f):(v+=l/(2*f)*r,m+=q*p);d.x!==k&&(v=d.x);d.y!==e&&(m=d.y);return{x:v+b*Math.cos(a),y:m-b*Math.sin(a)}}});w.prototype.callbacks.push(function(b){!1!==
b.options.connectors.enabled&&(d(b),this.pathfinder=new a(this),this.pathfinder.update(!0))});return a});I(c,"Series/XRangeSeries.js",[c["Core/Axis/Axis.js"],c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Color/Color.js"],c["Series/Column/ColumnSeries.js"],c["Series/Line/LineSeries.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,w,B,u,z,A,E,x){var m=u.parse,d=z.prototype;u=x.addEvent;var p=x.clamp,t=x.correctFloat,y=x.defined,q=x.find,D=x.isNumber,e=x.isObject,g=x.merge,
l=x.pick,b=w.seriesTypes;w.seriesType("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;e(a)&&(a=a.amount);if(D(a)&&0<a)return t(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,
animate:b.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:B.noop,buildKDTree:B.noop,init:function(){b.column.prototype.init.apply(this,arguments);this.options.stacking=void 0},getColumnMetrics:function(){function a(){b.series.forEach(function(a){var b=a.xAxis;a.xAxis=a.yAxis;a.yAxis=b})}var b=this.chart;a();var e=d.getColumnMetrics.call(this);a();return e},cropData:function(a,b,d,e){b=A.prototype.cropData.call(this,this.x2Data,b,d,e);b.xData=a.slice(b.start,b.end);return b},
findPointIndex:function(a){var b=this.cropped,d=this.cropStart,e=this.points,h=a.id;if(h)var c=(c=q(e,function(a){return a.id===h}))?c.index:void 0;"undefined"===typeof c&&(c=(c=q(e,function(b){return b.x===a.x&&b.x2===a.x2&&!b.touched}))?c.index:void 0);b&&D(c)&&D(d)&&c>=d&&(c-=d);return c},translatePoint:function(a){var b=this.xAxis,d=this.yAxis,c=this.columnMetrics,h=this.options,m=h.minPointLength||0,H=a.plotX,C=l(a.x2,a.x+(a.len||0)),q=b.translate(C,0,0,0,1);C=Math.abs(q-H);var t=this.chart.inverted,
J=l(h.borderWidth,1)%2/2,k=c.offset,v=Math.round(c.width);m&&(m-=C,0>m&&(m=0),H-=m/2,q+=m/2);H=Math.max(H,-10);q=p(q,-10,b.len+10);y(a.options.pointWidth)&&(k-=(Math.ceil(a.options.pointWidth)-v)/2,v=Math.ceil(a.options.pointWidth));h.pointPlacement&&D(a.plotY)&&d.categories&&(a.plotY=d.translate(a.y,0,1,0,1,h.pointPlacement));a.shapeArgs={x:Math.floor(Math.min(H,q))+J,y:Math.floor(a.plotY+k)+J,width:Math.round(Math.abs(q-H)),height:v,r:this.options.borderRadius};h=a.shapeArgs.x;m=h+a.shapeArgs.width;
0>h||m>b.len?(h=p(h,0,b.len),m=p(m,0,b.len),q=m-h,a.dlBox=g(a.shapeArgs,{x:h,width:m-h,centerX:q?q/2:null})):a.dlBox=null;h=a.tooltipPos;m=t?1:0;q=t?0:1;c=this.columnMetrics?this.columnMetrics.offset:-c.width/2;h[m]=p(h[m]+C/2*(b.reversed?-1:1)*(t?-1:1),0,b.len-1);h[q]=p(h[q]+(t?-1:1)*c,0,d.len-1);if(c=a.partialFill)e(c)&&(c=c.amount),D(c)||(c=0),d=a.shapeArgs,a.partShapeArgs={x:d.x,y:d.y,width:d.width,height:d.height,r:this.options.borderRadius},H=Math.max(Math.round(C*c+a.plotX-H),0),a.clipRectArgs=
{x:b.reversed?d.x+C-H:d.x,y:d.y,width:H,height:d.height}},translate:function(){d.translate.apply(this,arguments);this.points.forEach(function(a){this.translatePoint(a)},this)},drawPoint:function(a,b){var f=this.options,d=this.chart.renderer,h=a.graphic,c=a.shapeType,p=a.shapeArgs,C=a.partShapeArgs,q=a.clipRectArgs,t=a.partialFill,J=f.stacking&&!f.borderRadius,k=a.state,v=f.states[k||"normal"]||{},F="undefined"===typeof k?"attr":b;k=this.pointAttribs(a,k);v=l(this.chart.options.chart.animation,v.animation);
if(a.isNull||!1===a.visible)h&&(a.graphic=h.destroy());else{if(h)h.rect[b](p);else a.graphic=h=d.g("point").addClass(a.getClassName()).add(a.group||this.group),h.rect=d[c](g(p)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(h);C&&(h.partRect?(h.partRect[b](g(C)),h.partialClipRect[b](g(q))):(h.partialClipRect=d.clipRect(q.x,q.y,q.width,q.height),h.partRect=d[c](C).addClass("highcharts-partfill-overlay").add(h).clip(h.partialClipRect)));this.chart.styledMode||(h.rect[b](k,
v).shadow(f.shadow,null,J),C&&(e(t)||(t={}),e(f.partialFill)&&(t=g(f.partialFill,t)),a=t.fill||m(k.fill).brighten(-.3).get()||m(a.color||this.color).brighten(-.3).get(),k.fill=a,h.partRect[F](k,v).shadow(f.shadow,null,J)))}},drawPoints:function(){var a=this,b=a.getAnimationVerb();a.points.forEach(function(f){a.drawPoint(f,b)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var a=this.series;if(a.options.colorByPoint&&
!this.options.color){var b=a.options.colors||a.chart.options.colors;var d=this.y%(b?b.length:a.chart.options.chart.colorCount);b=b&&b[d];a.chart.styledMode||(this.color=b);this.options.colorIndex||(this.colorIndex=d)}else this.color||(this.color=a.color)},init:function(){E.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){E.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},getLabelConfig:function(){var a=E.prototype.getLabelConfig.call(this),
b=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=b&&b[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});u(c,"afterGetSeriesExtremes",function(){var a=this.series,b;if(this.isXAxis){var d=l(this.dataMax,-Number.MAX_VALUE);a.forEach(function(a){a.x2Data&&a.x2Data.forEach(function(a){a>d&&(d=a,b=!0)})});b&&(this.dataMax=d)}});""});I(c,"Series/GanttSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],
c["Series/Line/LineSeries.js"],c["Core/Utilities.js"]],function(c,w,B,u){var z=u.isNumber,A=u.merge,E=u.pick,x=u.splat,m=c.seriesTypes.xrange;c.seriesType("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},tooltip:{headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',pointFormat:null,pointFormatter:function(){var d=this.series,c=d.chart.tooltip,m=d.xAxis,y=d.tooltipOptions.dateTimeLabelFormats,q=m.options.startOfWeek,u=d.tooltipOptions,e=u.xDateFormat,g=this.options.milestone,
l="<b>"+(this.name||this.yCategory)+"</b>";if(u.pointFormat)return this.tooltipFormatter(u.pointFormat);e||(e=x(c.getDateFormat(m.closestPointRange,this.start,q,y))[0]);c=d.chart.time.dateFormat(e,this.start);d=d.chart.time.dateFormat(e,this.end);l+="<br/>";return g?l+(c+"<br/>"):l+("Start: "+c+"<br/>End: ")+(d+"<br/>")}},connectors:{type:"simpleConnect",animation:{reversed:!0},startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",align:"left"},endMarker:{enabled:!1,align:"right"}}},
{pointArrayMap:["start","end","y"],keyboardMoveVertical:!1,translatePoint:function(d){m.prototype.translatePoint.call(this,d);if(d.options.milestone){var c=d.shapeArgs;var t=c.height;d.shapeArgs={x:c.x-t/2,y:c.y,width:t,height:t}}},drawPoint:function(d,c){var p=this.options,y=this.chart.renderer,q=d.shapeArgs,u=d.plotY,e=d.graphic,g=d.selected&&"select",l=p.stacking&&!p.borderRadius;if(d.options.milestone)if(z(u)&&null!==d.y&&!1!==d.visible){q=y.symbols.diamond(q.x,q.y,q.width,q.height);if(e)e[c]({d:q});
else d.graphic=y.path(q).addClass(d.getClassName(),!0).add(d.group||this.group);this.chart.styledMode||d.graphic.attr(this.pointAttribs(d,g)).shadow(p.shadow,null,l)}else e&&(d.graphic=e.destroy());else m.prototype.drawPoint.call(this,d,c)},setData:B.prototype.setData,setGanttPointAliases:function(d){function c(c,m){"undefined"!==typeof m&&(d[c]=m)}c("x",E(d.start,d.x));c("x2",E(d.end,d.x2));c("partialFill",E(d.completed,d.partialFill))}},A(m.prototype.pointClass.prototype,{applyOptions:function(d,
c){d=m.prototype.pointClass.prototype.applyOptions.call(this,d,c);w.seriesTypes.gantt.prototype.setGanttPointAliases(d);return d},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===typeof this.end||"number"===typeof this.x2||this.milestone)}}));""});I(c,"Core/Chart/GanttChart.js",[c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,w,B){var u=B.getOptions,z=B.isArray,A=B.merge,E=B.splat;w.ganttChart=function(x,m,d){var p="string"===
typeof x||x.nodeName,t=m.series,y=u(),q,w=m;m=arguments[p?1:0];z(m.xAxis)||(m.xAxis=[m.xAxis||{},{}]);m.xAxis=m.xAxis.map(function(d,c){1===c&&(q=0);return A(y.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:q},d,{type:"datetime"})});m.yAxis=E(m.yAxis||{}).map(function(d){return A(y.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:d.categories?d.type:"treegrid"},d)});m.series=null;m=A(!0,{chart:{type:"gantt"},title:{text:null},legend:{enabled:!1},navigator:{series:{type:"gantt"},yAxis:{type:"category"}}},
m,{isGantt:!0});m.series=w.series=t;return p?new c(x,m,d):new c(m,m)}});I(c,"Core/Axis/ScrollbarAxis.js",[c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,w){var B=w.addEvent,u=w.defined,z=w.pick;return function(){function w(){}w.compose=function(w,x){B(w,"afterInit",function(){var m=this;m.options&&m.options.scrollbar&&m.options.scrollbar.enabled&&(m.options.scrollbar.vertical=!m.horiz,m.options.startOnTick=m.options.endOnTick=!1,m.scrollbar=new x(m.chart.renderer,m.options.scrollbar,m.chart),
B(m.scrollbar,"changed",function(d){var p=z(m.options&&m.options.min,m.min),t=z(m.options&&m.options.max,m.max),y=u(m.dataMin)?Math.min(p,m.min,m.dataMin):p,q=(u(m.dataMax)?Math.max(t,m.max,m.dataMax):t)-y;u(p)&&u(t)&&(m.horiz&&!m.reversed||!m.horiz&&m.reversed?(p=y+q*this.to,y+=q*this.from):(p=y+q*(1-this.from),y+=q*(1-this.to)),z(this.options.liveRedraw,c.svg&&!c.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===d.DOMType||!u(d.DOMType)?m.setExtremes(y,p,!0,"mousemove"!==d.DOMType,d):this.setRange(this.from,
this.to))}))});B(w,"afterRender",function(){var c=Math.min(z(this.options.min,this.min),this.min,z(this.dataMin,this.min)),d=Math.max(z(this.options.max,this.max),this.max,z(this.dataMax,this.max)),p=this.scrollbar,t=this.axisTitleMargin+(this.titleOffset||0),y=this.chart.scrollbarsOffsets,q=this.options.margin||0;p&&(this.horiz?(this.opposite||(y[1]+=t),p.position(this.left,this.top+this.height+2+y[1]-(this.opposite?q:0),this.width,this.height),this.opposite||(y[1]+=q),t=1):(this.opposite&&(y[0]+=
t),p.position(this.left+this.width+2+y[0]-(this.opposite?0:q),this.top,this.width,this.height),this.opposite&&(y[0]+=q),t=0),y[t]+=p.size+p.options.margin,isNaN(c)||isNaN(d)||!u(this.min)||!u(this.max)||this.min===this.max?p.setRange(0,1):(y=(this.min-c)/(d-c),c=(this.max-c)/(d-c),this.horiz&&!this.reversed||!this.horiz&&this.reversed?p.setRange(y,c):p.setRange(1-c,1-y)))});B(w,"afterGetOffset",function(){var c=this.horiz?2:1,d=this.scrollbar;d&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[c]+=
d.size+d.options.margin)})};return w}()});I(c,"Core/Scrollbar.js",[c["Core/Axis/Axis.js"],c["Core/Globals.js"],c["Core/Axis/ScrollbarAxis.js"],c["Core/Utilities.js"],c["Core/Options.js"]],function(c,w,B,u,z){var A=u.addEvent,E=u.correctFloat,x=u.defined,m=u.destroyObjectProperties,d=u.fireEvent,p=u.merge,t=u.pick,y=u.removeEvent;u=z.defaultOptions;var q=w.hasTouch,D=w.isTouchDevice,e=w.swapXY=function(d,c){c&&d.forEach(function(b){for(var a=b.length,d,c=0;c<a;c+=2)d=b[c+1],"number"===typeof d&&(b[c+
1]=b[c+2],b[c+2]=d)});return d};z=function(){function c(c,b,a){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=a;this.options=b;this.renderer=a.renderer;this.init(c,b,a)}c.prototype.addEvents=function(){var c=
this.options.inverted?[1,0]:[0,1],b=this.scrollbarButtons,a=this.scrollbarGroup.element,d=this.track.element,e=this.mouseDownHandler.bind(this),n=this.mouseMoveHandler.bind(this),h=this.mouseUpHandler.bind(this);c=[[b[c[0]].element,"click",this.buttonToMinClick.bind(this)],[b[c[1]].element,"click",this.buttonToMaxClick.bind(this)],[d,"click",this.trackClick.bind(this)],[a,"mousedown",e],[a.ownerDocument,"mousemove",n],[a.ownerDocument,"mouseup",h]];q&&c.push([a,"touchstart",e],[a.ownerDocument,"touchmove",
n],[a.ownerDocument,"touchend",h]);c.forEach(function(a){A.apply(null,a)});this._events=c};c.prototype.buttonToMaxClick=function(c){var b=(this.to-this.from)*t(this.options.step,.2);this.updatePosition(this.from+b,this.to+b);d(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:c})};c.prototype.buttonToMinClick=function(c){var b=E(this.to-this.from)*t(this.options.step,.2);this.updatePosition(E(this.from-b),E(this.to-b));d(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",
DOMEvent:c})};c.prototype.cursorToScrollbarPosition=function(c){var b=this.options;b=b.minWidth>this.calculatedWidth?b.minWidth:0;return{chartX:(c.chartX-this.x-this.xOffset)/(this.barWidth-b),chartY:(c.chartY-this.y-this.yOffset)/(this.barWidth-b)}};c.prototype.destroy=function(){var c=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(b){this[b]&&this[b].destroy&&(this[b]=this[b].destroy())},this);c&&this===c.scrollbar&&(c.scrollbar=
null,m(c.scrollbarButtons))};c.prototype.drawScrollbarButton=function(c){var b=this.renderer,a=this.scrollbarButtons,d=this.options,l=this.size;var n=b.g().add(this.group);a.push(n);n=b.rect().addClass("highcharts-scrollbar-button").add(n);this.chart.styledMode||n.attr({stroke:d.buttonBorderColor,"stroke-width":d.buttonBorderWidth,fill:d.buttonBackgroundColor});n.attr(n.crisp({x:-.5,y:-.5,width:l+1,height:l+1,r:d.buttonBorderRadius},n.strokeWidth()));n=b.path(e([["M",l/2+(c?-1:1),l/2-3],["L",l/2+
(c?-1:1),l/2+3],["L",l/2+(c?2:-2),l/2]],d.vertical)).addClass("highcharts-scrollbar-arrow").add(a[c]);this.chart.styledMode||n.attr({fill:d.buttonArrowColor})};c.prototype.init=function(d,b,a){this.scrollbarButtons=[];this.renderer=d;this.userOptions=b;this.options=p(c.defaultOptions,b);this.chart=a;this.size=t(this.options.size,this.options.height);b.enabled&&(this.render(),this.addEvents())};c.prototype.mouseDownHandler=function(c){c=this.chart.pointer.normalize(c);c=this.cursorToScrollbarPosition(c);
this.chartX=c.chartX;this.chartY=c.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};c.prototype.mouseMoveHandler=function(c){var b=this.chart.pointer.normalize(c),a=this.options.vertical?"chartY":"chartX",f=this.initPositions||[];!this.grabbedCenter||c.touches&&0===c.touches[0][a]||(b=this.cursorToScrollbarPosition(b)[a],a=this[a],a=b-a,this.hasDragged=!0,this.updatePosition(f[0]+a,f[1]+a),this.hasDragged&&d(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:c.type,
DOMEvent:c}))};c.prototype.mouseUpHandler=function(c){this.hasDragged&&d(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:c.type,DOMEvent:c});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};c.prototype.position=function(c,b,a,d){var f=this.options.vertical,e=0,h=this.rendered?"animate":"attr";this.x=c;this.y=b+this.trackBorderWidth;this.width=a;this.xOffset=this.height=d;this.yOffset=e;f?(this.width=this.yOffset=a=e=this.size,this.xOffset=b=0,this.barWidth=d-
2*a,this.x=c+=this.options.margin):(this.height=this.xOffset=d=b=this.size,this.barWidth=a-2*d,this.y+=this.options.margin);this.group[h]({translateX:c,translateY:this.y});this.track[h]({width:a,height:d});this.scrollbarButtons[1][h]({translateX:f?0:a-b,translateY:f?d-e:0})};c.prototype.removeEvents=function(){this._events.forEach(function(c){y.apply(null,c)});this._events.length=0};c.prototype.render=function(){var c=this.renderer,b=this.options,a=this.size,d=this.chart.styledMode,g;this.group=g=
c.g("scrollbar").attr({zIndex:b.zIndex,translateY:-99999}).add();this.track=c.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:b.trackBorderRadius||0,height:a,width:a}).add(g);d||this.track.attr({fill:b.trackBackgroundColor,stroke:b.trackBorderColor,"stroke-width":b.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=c.g().add(g);this.scrollbar=c.rect().addClass("highcharts-scrollbar-thumb").attr({height:a,
width:a,r:b.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=c.path(e([["M",-3,a/4],["L",-3,2*a/3],["M",0,a/4],["L",0,2*a/3],["M",3,a/4],["L",3,2*a/3]],b.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);d||(this.scrollbar.attr({fill:b.barBackgroundColor,stroke:b.barBorderColor,"stroke-width":b.barBorderWidth}),this.scrollbarRifles.attr({stroke:b.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%
2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};c.prototype.setRange=function(c,b){var a=this.options,d=a.vertical,e=a.minWidth,n=this.barWidth,h,g=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(x(n)){c=Math.max(c,0);var l=Math.ceil(n*c);this.calculatedWidth=h=E(n*Math.min(b,1)-l);h<e&&(l=(n-e+h)*c,h=e);e=Math.floor(l+this.xOffset+this.yOffset);n=h/2-.5;this.from=c;this.to=b;d?(this.scrollbarGroup[g]({translateY:e}),
this.scrollbar[g]({height:h}),this.scrollbarRifles[g]({translateY:n}),this.scrollbarTop=e,this.scrollbarLeft=0):(this.scrollbarGroup[g]({translateX:e}),this.scrollbar[g]({width:h}),this.scrollbarRifles[g]({translateX:n}),this.scrollbarLeft=e,this.scrollbarTop=0);12>=h?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===a.showFull&&(0>=c&&1<=b?this.group.hide():this.group.show());this.rendered=!0}};c.prototype.trackClick=function(c){var b=this.chart.pointer.normalize(c),a=this.to-this.from,
e=this.y+this.scrollbarTop,g=this.x+this.scrollbarLeft;this.options.vertical&&b.chartY>e||!this.options.vertical&&b.chartX>g?this.updatePosition(this.from+a,this.to+a):this.updatePosition(this.from-a,this.to-a);d(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:c})};c.prototype.update=function(c){this.destroy();this.init(this.chart.renderer,p(!0,this.options,c),this.chart)};c.prototype.updatePosition=function(c,b){1<b&&(c=E(1-E(b-c)),b=1);0>c&&(b=E(b-c),c=0);this.from=c;this.to=
b};c.defaultOptions={height:D?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};return c}();w.Scrollbar||(u.scrollbar=p(!0,z.defaultOptions,u.scrollbar),w.Scrollbar=z,B.compose(c,
z));return w.Scrollbar});I(c,"Extensions/RangeSelector.js",[c["Core/Axis/Axis.js"],c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Options.js"],c["Core/Renderer/SVG/SVGElement.js"],c["Core/Utilities.js"]],function(c,w,B,u,z,A){var E=u.defaultOptions,x=A.addEvent,m=A.createElement,d=A.css,p=A.defined,t=A.destroyObjectProperties,y=A.discardElement,q=A.extend,D=A.fireEvent,e=A.isNumber,g=A.merge,l=A.objectEach,b=A.pick,a=A.pInt,f=A.splat;q(E,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,
height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});E.lang=g(E.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});var r=function(){function n(a){this.buttons=void 0;this.buttonOptions=n.prototype.defaultButtons;this.options=void 0;this.chart=a;this.init(a)}n.prototype.clickButton=function(a,d){var h=this.chart,g=this.buttonOptions[a],n=h.xAxis[0],l=h.scroller&&
h.scroller.getUnionExtremes()||n||{},m=l.dataMin,k=l.dataMax,v=n&&Math.round(Math.min(n.max,b(k,n.max))),F=g.type;l=g._range;var q,t=g.dataGrouping;if(null!==m&&null!==k){h.fixedRange=l;t&&(this.forcedDataGrouping=!0,c.prototype.setDataGrouping.call(n||{chart:this.chart},t,!1),this.frozenStates=g.preserveDataGrouping);if("month"===F||"year"===F)if(n){F={range:g,max:v,chart:h,dataMin:m,dataMax:k};var r=n.minFromRange.call(F);e(F.newMax)&&(v=F.newMax)}else l=g;else if(l)r=Math.max(v-l,m),v=Math.min(r+
l,k);else if("ytd"===F)if(n)"undefined"===typeof k&&(m=Number.MAX_VALUE,k=Number.MIN_VALUE,h.series.forEach(function(a){a=a.xData;m=Math.min(a[0],m);k=Math.max(a[a.length-1],k)}),d=!1),v=this.getYTDExtremes(k,m,h.time.useUTC),r=q=v.min,v=v.max;else{this.deferredYTDClick=a;return}else"all"===F&&n&&(r=m,v=k);p(r)&&(r+=g._offsetMin);p(v)&&(v+=g._offsetMax);this.setSelected(a);if(n)n.setExtremes(r,v,b(d,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:g});else{var G=f(h.options.xAxis)[0];var Q=
G.range;G.range=l;var u=G.min;G.min=q;x(h,"load",function(){G.range=Q;G.min=u})}}};n.prototype.setSelected=function(a){this.selected=this.options.selected=a};n.prototype.init=function(a){var b=this,c=a.options.rangeSelector,d=c.buttons||b.defaultButtons.slice(),e=c.selected,f=function(){var a=b.minInput,c=b.maxInput;a&&a.blur&&D(a,"blur");c&&c.blur&&D(c,"blur")};b.chart=a;b.options=c;b.buttons=[];b.buttonOptions=d;this.unMouseDown=x(a.container,"mousedown",f);this.unResize=x(a,"resize",f);d.forEach(b.computeButtonRange);
"undefined"!==typeof e&&d[e]&&this.clickButton(e,!1);x(a,"load",function(){a.xAxis&&a.xAxis[0]&&x(a.xAxis[0],"setExtremes",function(c){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==c.trigger&&"updatedData"!==c.trigger&&b.forcedDataGrouping&&!b.frozenStates&&this.setDataGrouping(!1,!1)})})};n.prototype.updateButtonStates=function(){var a=this,b=this.chart,c=b.xAxis[0],d=Math.round(c.max-c.min),f=!c.hasVisibleSeries,g=b.scroller&&b.scroller.getUnionExtremes()||c,n=g.dataMin,k=g.dataMax;
b=a.getYTDExtremes(k,n,b.time.useUTC);var v=b.min,l=b.max,m=a.selected,p=e(m),q=a.options.allButtonsEnabled,t=a.buttons;a.buttonOptions.forEach(function(b,e){var h=b._range,g=b.type,F=b.count||1,C=t[e],r=0,H=b._offsetMax-b._offsetMin;b=e===m;var u=h>k-n,T=h<c.minRange,Q=!1,y=!1;h=h===d;("month"===g||"year"===g)&&d+36E5>=864E5*{month:28,year:365}[g]*F-H&&d-36E5<=864E5*{month:31,year:366}[g]*F+H?h=!0:"ytd"===g?(h=l-v+H===d,Q=!b):"all"===g&&(h=c.max-c.min>=k-n,y=!b&&p&&h);g=!q&&(u||T||y||f);F=b&&h||
h&&!p&&!Q||b&&a.frozenStates;g?r=3:F&&(p=!0,r=2);C.state!==r&&(C.setState(r),0===r&&m===e&&a.setSelected(null))})};n.prototype.computeButtonRange=function(a){var c=a.type,d=a.count||1,e={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(e[c])a._range=e[c]*d;else if("month"===c||"year"===c)a._range=864E5*{month:30,year:365}[c]*d;a._offsetMin=b(a.offsetMin,0);a._offsetMax=b(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin};n.prototype.setInputValue=function(a,b){var c=this.chart.options.rangeSelector,
d=this.chart.time,e=this[a+"Input"];p(b)&&(e.previousValue=e.HCTime,e.HCTime=b);e.value=d.dateFormat(c.inputEditDateFormat||"%Y-%m-%d",e.HCTime);this[a+"DateBox"].attr({text:d.dateFormat(c.inputDateFormat||"%b %e, %Y",e.HCTime)})};n.prototype.showInput=function(a){var b=this.inputGroup,c=this[a+"DateBox"];d(this[a+"Input"],{left:b.translateX+c.x+"px",top:b.translateY+"px",width:c.width-2+"px",height:c.height-2+"px",border:"2px solid silver"})};n.prototype.hideInput=function(a){d(this[a+"Input"],{border:0,
width:"1px",height:"1px"});this.setInputValue(a)};n.prototype.defaultInputDateParser=function(a,b){var c=new Date;return B.isSafari?Date.parse(a.split(" ").join("T")):b?Date.parse(a+"Z"):Date.parse(a)-6E4*c.getTimezoneOffset()};n.prototype.drawInput=function(b){function c(){var b=F.value,c=h.xAxis[0];var k=h.scroller&&h.scroller.xAxis?h.scroller.xAxis:c;var d=k.dataMin,g=k.dataMax;k=(p.inputDateParser||u)(b,h.time.useUTC);k!==F.previousValue&&(F.previousValue=k,e(k)||(k=b.split("-"),k=Date.UTC(a(k[0]),
a(k[1])-1,a(k[2]))),e(k)&&(h.time.useUTC||(k+=6E4*(new Date).getTimezoneOffset()),v?k>f.maxInput.HCTime?k=void 0:k<d&&(k=d):k<f.minInput.HCTime?k=void 0:k>g&&(k=g),"undefined"!==typeof k&&c.setExtremes(v?k:c.min,v?c.max:k,void 0,void 0,{trigger:"rangeSelectorInput"})))}var f=this,h=f.chart,n=h.renderer.style||{},l=h.renderer,p=h.options.rangeSelector,k=f.div,v="min"===b,F,r,t=this.inputGroup,u=this.defaultInputDateParser;this[b+"Label"]=r=l.label(E.lang[v?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(t);
t.offset+=r.width+5;this[b+"DateBox"]=l=l.label("",t.offset).addClass("highcharts-range-input").attr({padding:2,width:p.inputBoxWidth||90,height:p.inputBoxHeight||17,"text-align":"center"}).on("click",function(){f.showInput(b);f[b+"Input"].focus()});h.styledMode||l.attr({stroke:p.inputBoxBorderColor||"#cccccc","stroke-width":1});l.add(t);t.offset+=l.width+(v?10:0);this[b+"Input"]=F=m("input",{name:b,className:"highcharts-range-selector",type:"text"},{top:h.plotTop+"px"},k);h.styledMode||(r.css(g(n,
p.labelStyle)),l.css(g({color:"#333333"},n,p.inputStyle)),d(F,q({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:n.fontSize,fontFamily:n.fontFamily,top:"-9999em"},p.inputStyle)));F.onfocus=function(){f.showInput(b)};F.onblur=function(){F===B.doc.activeElement&&c();f.hideInput(b);F.blur()};F.onchange=c;F.onkeypress=function(a){13===a.keyCode&&c()}};n.prototype.getPosition=function(){var a=this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-
a.axisOffset[0]:0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}};n.prototype.getYTDExtremes=function(a,b,c){var d=this.chart.time,e=new d.Date(a),f=d.get("FullYear",e);c=c?d.Date.UTC(f,0,1):+new d.Date(f,0,1);b=Math.max(b||0,c);e=e.getTime();return{max:Math.min(a||e,e),min:b}};n.prototype.render=function(a,c){var d=this,e=d.chart,f=e.renderer,h=e.container,g=e.options,k=g.exporting&&!1!==g.exporting.enabled&&g.navigation&&g.navigation.buttonOptions,v=E.lang,n=d.div,l=g.rangeSelector,
p=b(g.chart.style&&g.chart.style.zIndex,0)+1;g=l.floating;var q=d.buttons;n=d.inputGroup;var t=l.buttonTheme,r=l.buttonPosition,u=l.inputPosition,y=l.inputEnabled,w=t&&t.states,x=e.plotLeft,z=d.buttonGroup,B,A=d.options.verticalAlign,D=e.legend,G=D&&D.options,I=r.y,O=u.y,P=e.hasLoaded,R=P?"animate":"attr",N=0,L=0;if(!1!==l.enabled){d.rendered||(d.group=B=f.g("range-selector-group").attr({zIndex:7}).add(),d.buttonGroup=z=f.g("range-selector-buttons").add(B),d.zoomText=f.text(v.rangeSelectorZoom,0,
15).add(z),e.styledMode||(d.zoomText.css(l.labelStyle),t["stroke-width"]=b(t["stroke-width"],0)),d.buttonOptions.forEach(function(a,b){q[b]=f.button(a.text,0,0,function(c){var k=a.events&&a.events.click,e;k&&(e=k.call(a,c));!1!==e&&d.clickButton(b);d.isActive=!0},t,w&&w.hover,w&&w.select,w&&w.disabled).attr({"text-align":"center"}).add(z)}),!1!==y&&(d.div=n=m("div",null,{position:"relative",height:0,zIndex:p}),h.parentNode.insertBefore(n,h),d.inputGroup=n=f.g("input-group").add(B),n.offset=0,d.drawInput("min"),
d.drawInput("max")));d.zoomText[R]({x:b(x+r.x,x)});var S=b(x+r.x,x)+d.zoomText.getBBox().width+5;d.buttonOptions.forEach(function(a,c){q[c][R]({x:S});S+=q[c].width+b(l.buttonSpacing,5)});x=e.plotLeft-e.spacing[3];d.updateButtonStates();k&&this.titleCollision(e)&&"top"===A&&"right"===r.align&&r.y+z.getBBox().height-12<(k.y||0)+k.height&&(N=-40);h=r.x-e.spacing[3];"right"===r.align?h+=N-x:"center"===r.align&&(h-=x/2);z.align({y:r.y,width:z.getBBox().width,align:r.align,x:h},!0,e.spacingBox);d.group.placed=
P;d.buttonGroup.placed=P;!1!==y&&(N=k&&this.titleCollision(e)&&"top"===A&&"right"===u.align&&u.y-n.getBBox().height-12<(k.y||0)+k.height+e.spacing[0]?-40:0,"left"===u.align?h=x:"right"===u.align&&(h=-Math.max(e.axisOffset[1],-N)),n.align({y:u.y,width:n.getBBox().width,align:u.align,x:u.x+h-2},!0,e.spacingBox),k=n.alignAttr.translateX+n.alignOptions.x-N+n.getBBox().x+2,h=n.alignOptions.width,v=z.alignAttr.translateX+z.getBBox().x,x=z.getBBox().width+20,(u.align===r.align||v+x>k&&k+h>v&&I<O+n.getBBox().height)&&
n.attr({translateX:n.alignAttr.translateX+(e.axisOffset[1]>=-N?0:-N),translateY:n.alignAttr.translateY+z.getBBox().height+10}),d.setInputValue("min",a),d.setInputValue("max",c),d.inputGroup.placed=P);d.group.align({verticalAlign:A},!0,e.spacingBox);a=d.group.getBBox().height+20;c=d.group.alignAttr.translateY;"bottom"===A&&(D=G&&"bottom"===G.verticalAlign&&G.enabled&&!G.floating?D.legendHeight+b(G.margin,10):0,a=a+D-20,L=c-a-(g?0:l.y)-(e.titleOffset?e.titleOffset[2]:0)-10);if("top"===A)g&&(L=0),e.titleOffset&&
e.titleOffset[0]&&(L=e.titleOffset[0]),L+=e.margin[0]-e.spacing[0]||0;else if("middle"===A)if(O===I)L=0>O?c+void 0:c;else if(O||I)L=0>O||0>I?L-Math.min(O,I):c-a+NaN;d.group.translate(l.x,l.y+Math.floor(L));!1!==y&&(d.minInput.style.marginTop=d.group.translateY+"px",d.maxInput.style.marginTop=d.group.translateY+"px");d.rendered=!0}};n.prototype.getHeight=function(){var a=this.options,b=this.group,c=a.y,d=a.buttonPosition.y,e=a.inputPosition.y;if(a.height)return a.height;a=b?b.getBBox(!0).height+13+
c:0;b=Math.min(e,d);if(0>e&&0>d||0<e&&0<d)a+=Math.abs(b);return a};n.prototype.titleCollision=function(a){return!(a.options.title.text||a.options.subtitle.text)};n.prototype.update=function(a){var b=this.chart;g(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()};n.prototype.destroy=function(){var a=this,b=a.minInput,c=a.maxInput;a.unMouseDown();a.unResize();t(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);c&&(c.onfocus=c.onblur=c.onchange=null);l(a,function(b,
c){b&&"chart"!==c&&(b instanceof z?b.destroy():b instanceof window.HTMLElement&&y(b));b!==n.prototype[c]&&(a[c]=null)},this)};return n}();r.prototype.defaultButtons=[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}];c.prototype.minFromRange=function(){var a=this.range,c=a.type,d=this.max,f=this.chart.time,g=function(a,b){var d="year"===c?"FullYear":"Month",k=new f.Date(a),
e=f.get(d,k);f.set(d,k,e+b);e===f.get(d,k)&&f.set("Date",k,0);return k.getTime()-a};if(e(a)){var l=d-a;var m=a}else l=d+g(d,-a.count),this.chart&&(this.chart.fixedRange=d-l);var p=b(this.dataMin,Number.MIN_VALUE);e(l)||(l=p);l<=p&&(l=p,"undefined"===typeof m&&(m=g(l,a.count)),this.newMax=Math.min(l+m,this.dataMax));e(d)||(l=void 0);return l};B.RangeSelector||(x(w,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new r(this))}),x(w,"beforeRender",function(){var a=
this.axes,b=this.rangeSelector;b&&(e(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),x(w,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var c=this.extraBottomMargin,d=this.extraTopMargin;b&&b.enabled&&!p(a)&&(this.options.rangeSelector.enabled=
!0,this.rangeSelector=new r(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==d)&&(this.isDirtyBox=!0)}),x(w,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=
!0))}),x(w,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),w.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();f=a.legend;n=null===d||void 0===d?void 0:d.options.verticalAlign;e(c.min)&&d.render(c.min,c.max);d&&f.display&&"top"===n&&n===f.options.verticalAlign&&(l=g(a.spacingBox),l.y="vertical"===f.options.layout?a.plotTop:l.y+d.getHeight(),f.group.placed=!1,f.align(l))}
var c,d=a.rangeSelector,f,l,n;if(d){var m=x(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)});var k=x(a,"redraw",b);b()}x(a,"destroy",function(){d&&(k(),m())})}),B.RangeSelector=r);return B.RangeSelector});I(c,"Core/Axis/NavigatorAxis.js",[c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,w){var B=c.isTouchDevice,u=w.addEvent,z=w.correctFloat,A=w.defined,E=w.isNumber,x=w.pick,m=function(){function c(c){this.axis=c}c.prototype.destroy=function(){this.axis=void 0};c.prototype.toFixedRange=
function(c,d,m,q){var p=this.axis,e=p.chart;e=e&&e.fixedRange;var g=(p.pointRange||0)/2;c=x(m,p.translate(c,!0,!p.horiz));d=x(q,p.translate(d,!0,!p.horiz));p=e&&(d-c)/e;A(m)||(c=z(c+g));A(q)||(d=z(d-g));.7<p&&1.3>p&&(q?c=d-e:d=c+e);E(c)&&E(d)||(c=d=void 0);return{min:c,max:d}};return c}();return function(){function c(){}c.compose=function(c){c.keepProps.push("navigatorAxis");u(c,"init",function(){this.navigatorAxis||(this.navigatorAxis=new m(this))});u(c,"zoom",function(c){var d=this.chart.options,
m=d.navigator,p=this.navigatorAxis,e=d.chart.pinchType,g=d.rangeSelector;d=d.chart.zoomType;this.isXAxis&&(m&&m.enabled||g&&g.enabled)&&("y"===d?c.zoomed=!1:(!B&&"xy"===d||B&&"xy"===e)&&this.options.range&&(m=p.previousZoom,A(c.newMin)?p.previousZoom=[this.min,this.max]:m&&(c.newMin=m[0],c.newMax=m[1],p.previousZoom=void 0)));"undefined"!==typeof c.zoomed&&c.preventDefault()})};c.AdditionsClass=m;return c}()});I(c,"Core/Navigator.js",[c["Core/Axis/Axis.js"],c["Core/Series/Series.js"],c["Core/Chart/Chart.js"],
c["Core/Color/Color.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],c["Core/Axis/NavigatorAxis.js"],c["Core/Options.js"],c["Core/Scrollbar.js"],c["Core/Utilities.js"]],function(c,w,B,u,z,A,E,x,m,d){u=u.parse;var p=z.hasTouch,t=z.isTouchDevice,y=x.defaultOptions,q=d.addEvent,D=d.clamp,e=d.correctFloat,g=d.defined,l=d.destroyObjectProperties,b=d.erase,a=d.extend,f=d.find,r=d.isArray,n=d.isNumber,h=d.merge,G=d.pick,H=d.removeEvent,C=d.splat,I=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-
1]=arguments[c];b=[].filter.call(b,n);if(b.length)return Math[a].apply(0,b)};w="undefined"===typeof w.seriesTypes.areaspline?"line":"areaspline";a(y,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:u("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:w,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",
enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",
gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});z.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,e){a=(e&&e.width||0)/2;b=Math.round(a/3)+.5;e=e&&e.height||0;return[["M",-a-1,.5],["L",a,.5],["L",a,e+.5],["L",-a-1,e+.5],["L",-a-
1,.5],["M",-b,4],["L",-b,e-3],["M",b-1,4],["L",b-1,e-3]]};var K=function(){function d(a){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(a)}d.prototype.drawHandle=function(a,b,c,d){var k=this.navigatorOptions.handles.height;
this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-k)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-k/2-1)})};d.prototype.drawOutline=function(a,b,c,d){var k=this.navigatorOptions.maskInside,e=this.outline.strokeWidth(),f=e/2,h=e%2/2;e=this.outlineHeight;var g=this.scrollbarHeight||0,l=this.size,v=this.left-g,m=this.top;c?(v-=f,c=m+b+h,b=m+a+h,h=[["M",v+e,m-g-h],["L",v+e,c],["L",v,c],
["L",v,b],["L",v+e,b],["L",v+e,m+l+g]],k&&h.push(["M",v+e,c-f],["L",v+e,b+f])):(a+=v+g-h,b+=v+g-h,m+=f,h=[["M",v,m],["L",a,m],["L",a,m+e],["L",b,m+e],["L",b,m],["L",v+l+2*g,m]],k&&h.push(["M",a-f,m],["L",b+f,m]));this.outline[d]({d:h})};d.prototype.drawMasks=function(a,b,c,d){var k=this.left,e=this.top,f=this.height;if(c){var h=[k,k,k];var g=[e,e+a,e+b];var l=[f,f,f];var m=[a,b-a,this.size-b]}else h=[k,k+a,k+b],g=[e,e,e],l=[a,b-a,this.size-b],m=[f,f,f];this.shades.forEach(function(a,b){a[d]({x:h[b],
y:g[b],width:l[b],height:m[b]})})};d.prototype.renderElements=function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,e=d.renderer,f,h={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=f=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,k){a.shades[k]=e.rect().addClass("highcharts-navigator-mask"+(1===k?"-inside":"-outside")).add(f);d.styledMode||a.shades[k].attr({fill:c?b.maskFill:"rgba(0,0,0,0)"}).css(1===k&&h)});a.outline=e.path().addClass("highcharts-navigator-outline").add(f);
d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(c){b.handles.inverted=d.inverted;a.handles[c]=e.symbol(b.handles.symbols[c],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);a.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(f);if(!d.styledMode){var k=b.handles;a.handles[c].attr({fill:k.backgroundColor,stroke:k.borderColor,"stroke-width":k.lineWidth}).css(h)}})};
d.prototype.update=function(a){(this.series||[]).forEach(function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();h(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)};d.prototype.render=function(a,b,c,d){var k=this.chart,f=this.scrollbarHeight,h,l=this.xAxis,m=l.pointRange||0;var v=l.navigatorAxis.fake?k.xAxis[0]:l;var p=this.navigatorEnabled,q,r=this.rendered;var t=k.inverted;var F=k.xAxis[0].minRange,u=k.xAxis[0].options.maxRange;if(!this.hasDragged||g(c)){a=
e(a-m/2);b=e(b+m/2);if(!n(a)||!n(b))if(r)c=0,d=G(l.width,v.width);else return;this.left=G(l.left,k.plotLeft+f+(t?k.plotWidth:0));this.size=q=h=G(l.len,(t?k.plotHeight:k.plotWidth)-2*f);k=t?f:h+2*f;c=G(c,l.toPixels(a,!0));d=G(d,l.toPixels(b,!0));n(c)&&Infinity!==Math.abs(c)||(c=0,d=k);a=l.toValue(c,!0);b=l.toValue(d,!0);var w=Math.abs(e(b-a));w<F?this.grabbedLeft?c=l.toPixels(b-F-m,!0):this.grabbedRight&&(d=l.toPixels(a+F+m,!0)):g(u)&&e(w-m)>u&&(this.grabbedLeft?c=l.toPixels(b-u-m,!0):this.grabbedRight&&
(d=l.toPixels(a+u+m,!0)));this.zoomedMax=D(Math.max(c,d),0,q);this.zoomedMin=D(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(c,d),0,q);this.range=this.zoomedMax-this.zoomedMin;q=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);p&&(this.navigatorGroup.attr({visibility:"visible"}),r=r&&!this.hasDragged?"animate":"attr",this.drawMasks(c,q,t,r),this.drawOutline(c,q,t,r),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,t,r),this.drawHandle(q,1,t,r)));this.scrollbar&&(t?(t=this.top-
f,v=this.left-f+(p||!v.opposite?0:(v.titleOffset||0)+v.axisTitleMargin),f=h+2*f):(t=this.top+(p?this.height:-f),v=this.left-f),this.scrollbar.position(v,t,k,f),this.scrollbar.setRange(this.zoomedMin/(h||1),this.zoomedMax/(h||1)));this.rendered=!0}};d.prototype.addMouseEvents=function(){var a=this,b=a.chart,c=b.container,d=[],e,f;a.mouseMoveHandler=e=function(b){a.onMouseMove(b)};a.mouseUpHandler=f=function(b){a.onMouseUp(b)};d=a.getPartsEvents("mousedown");d.push(q(b.renderTo,"mousemove",e),q(c.ownerDocument,
"mouseup",f));p&&(d.push(q(b.renderTo,"touchmove",e),q(c.ownerDocument,"touchend",f)),d.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=d;a.series&&a.series[0]&&d.push(q(a.series[0].xAxis,"foundExtremes",function(){b.navigator.modifyNavigatorAxisExtremes()}))};d.prototype.getPartsEvents=function(a){var b=this,c=[];["shades","handles"].forEach(function(d){b[d].forEach(function(e,k){c.push(q(e.element,a,function(a){b[d+"Mousedown"](a,k)}))})});return c};d.prototype.shadesMousedown=function(a,
b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,e=this.zoomedMin,k=this.left,f=this.size,h=this.range,l=a.chartX;c.inverted&&(l=a.chartY,k=this.top);if(1===b)this.grabbedCenter=l,this.fixedWidth=h,this.dragOffset=l-e;else{a=l-k-h/2;if(0===b)a=Math.max(0,a);else if(2===b&&a+h>=f)if(a=f-h,this.reversedExtremes){a-=h;var m=this.getUnionExtremes().dataMin}else var n=this.getUnionExtremes().dataMax;a!==e&&(this.fixedWidth=h,b=d.navigatorAxis.toFixedRange(a,a+h,m,n),g(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,
b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}};d.prototype.handlesMousedown=function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=null};d.prototype.onMouseMove=function(a){var b=this,c=b.chart,d=b.left,e=b.navigatorSize,f=b.range,k=b.dragOffset,
h=c.inverted;a.touches&&0===a.touches[0].pageX||(a=c.pointer.normalize(a),c=a.chartX,h&&(d=b.top,c=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,c-d,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,c-d)):b.grabbedCenter&&(b.hasDragged=!0,c<k?c=k:c>e+k-f&&(c=e+k-f),b.render(0,0,c-k,c-k+f)),b.hasDragged&&b.scrollbar&&G(b.scrollbar.options.liveRedraw,z.svg&&!t&&!this.chart.isBoosting)&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))};d.prototype.onMouseUp=
function(a){var b=this.chart,c=this.xAxis,d=this.scrollbar,e=a.DOMEvent||a,f=b.inverted,k=this.rendered&&!this.hasDragged?"animate":"attr";if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===a.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var h=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var l=this.fixedExtreme;this.zoomedMax===this.size&&(l=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(h=this.reversedExtremes?d.dataMax:d.dataMin);
c=c.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,h,l);g(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:e})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&n(this.zoomedMin)&&n(this.zoomedMax)&&(b=Math.round(this.zoomedMin),
a=Math.round(this.zoomedMax),this.shades&&this.drawMasks(b,a,f,k),this.outline&&this.drawOutline(b,a,f,k),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(b,0,f,k),this.drawHandle(a,1,f,k)))};d.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};d.prototype.removeBaseSeriesEvents=function(){var a=this.baseSeries||[];this.navigatorEnabled&&
a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){H(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&H(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};d.prototype.init=function(a){var b=a.options,d=b.navigator,e=d.enabled,f=b.scrollbar,k=f.enabled;b=e?d.height:0;var l=k?f.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=b;this.scrollbarHeight=l;this.scrollbarEnabled=k;this.navigatorEnabled=e;this.navigatorOptions=
d;this.scrollbarOptions=f;this.outlineHeight=b+l;this.opposite=G(d.opposite,!(e||!a.inverted));var g=this;e=g.baseSeries;f=a.xAxis.length;k=a.yAxis.length;var n=e&&e[0]&&e[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;g.navigatorEnabled?(g.xAxis=new c(a,h({breaks:n.options.breaks,ordinal:n.options.ordinal},d.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:f,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},
a.inverted?{offsets:[l,0,-l,0],width:b}:{offsets:[0,-l,0,l],height:b})),g.yAxis=new c(a,h(d.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:k,isInternal:!0,reversed:G(d.yAxis&&d.yAxis.reversed,a.yAxis[0]&&a.yAxis[0].reversed,!1),zoomEnabled:!1},a.inverted?{width:b}:{height:b})),e||d.series.data?g.updateNavigatorSeries(!1):0===a.series.length&&(g.unbindRedraw=q(a,"beforeRedraw",function(){0<a.series.length&&!g.series&&(g.setBaseSeries(),g.unbindRedraw())})),g.reversedExtremes=a.inverted&&
!g.xAxis.reversed||!a.inverted&&g.xAxis.reversed,g.renderElements(),g.addMouseEvents()):(g.xAxis={chart:a,navigatorAxis:{fake:!0},translate:function(b,c){var d=a.xAxis[0],e=d.getExtremes(),f=d.len-2*l,k=I("min",d.options.min,e.dataMin);d=I("max",d.options.max,e.dataMax)-k;return c?b*d/f+k:f*(b-k)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)}},g.xAxis.navigatorAxis.axis=g.xAxis,g.xAxis.navigatorAxis.toFixedRange=E.AdditionsClass.prototype.toFixedRange.bind(g.xAxis.navigatorAxis));
a.options.scrollbar.enabled&&(a.scrollbar=g.scrollbar=new m(a.renderer,h(a.options.scrollbar,{margin:g.navigatorEnabled?0:10,vertical:a.inverted}),a),q(g.scrollbar,"changed",function(b){var c=g.size,d=c*this.to;c*=this.from;g.hasDragged=g.scrollbar.hasDragged;g.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&setTimeout(function(){g.onMouseUp(b)})}));g.addBaseSeriesEvents();g.addChartEvents()};d.prototype.getUnionExtremes=function(a){var b=this.chart.xAxis[0],
c=this.xAxis,d=c.options,e=b.options,f;a&&null===b.dataMin||(f={dataMin:G(d&&d.min,I("min",e.min,b.dataMin,c.dataMin,c.min)),dataMax:G(d&&d.max,I("max",e.max,b.dataMax,c.dataMax,c.max))});return f};d.prototype.setBaseSeries=function(a,b){var c=this.chart,d=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||(c.series.length?f(c.series,function(a){return!a.options.isInternal}).index:0);(c.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==
a||!1===b.options.showInNavigator)||d.push(b)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,b)};d.prototype.updateNavigatorSeries=function(b,c){var d=this,e=d.chart,f=d.baseSeries,k,g,l=d.navigatorOptions.series,m,n={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},p=d.series=(d.series||[]).filter(function(a){var b=a.baseSeries;
return 0>f.indexOf(b)?(b&&(H(b,"updatedData",d.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});f&&f.length&&f.forEach(function(b){var q=b.navigatorSeries,v=a({color:b.color,visible:b.visible},r(l)?y.navigator.series:l);q&&!1===d.navigatorOptions.adaptToUpdatedData||(n.name="Navigator "+f.length,k=b.options||{},m=k.navigatorOptions||{},g=h(k,n,v,m),g.pointRange=G(v.pointRange,m.pointRange,y.plotOptions[g.type||"line"].pointRange),v=m.data||v.data,d.hasNavigatorData=d.hasNavigatorData||
!!v,g.data=v||k.data&&k.data.slice(0),q&&q.options?q.update(g,c):(b.navigatorSeries=e.initSeries(g),b.navigatorSeries.baseSeries=b,p.push(b.navigatorSeries)))});if(l.data&&(!f||!f.length)||r(l))d.hasNavigatorData=!1,l=C(l),l.forEach(function(a,b){n.name="Navigator "+(p.length+1);g=h(y.navigator.series,{color:e.series[b]&&!e.series[b].options.isInternal&&e.series[b].color||e.options.colors[b]||e.options.colors[0]},n,a);g.data=a.data;g.data&&(d.hasNavigatorData=!0,p.push(e.initSeries(g)))});b&&this.addBaseSeriesEvents()};
d.prototype.addBaseSeriesEvents=function(){var a=this,c=a.baseSeries||[];c[0]&&c[0].xAxis&&q(c[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);c.forEach(function(c){q(c,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});q(c,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&c.xAxis&&q(c,"updatedData",this.updatedDataHandler);q(c,"remove",function(){this.navigatorSeries&&(b(a.series,this.navigatorSeries),
g(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};d.prototype.getBaseSeriesMin=function(a){return this.baseSeries.reduce(function(a,b){return Math.min(a,b.xData?b.xData[0]:a)},a)};d.prototype.modifyNavigatorAxisExtremes=function(){var a=this.xAxis,b;"undefined"!==typeof a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))};d.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,
b=this.getExtremes(),c=b.dataMin,d=b.dataMax;b=b.max-b.min;var e=a.stickToMin,f=a.stickToMax,h=G(this.options.overscroll,0),g=a.series&&a.series[0],l=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(e){var m=c;var p=m+b}f&&(p=d+h,e||(m=Math.max(c,p-b,a.getBaseSeriesMin(g&&g.xData?g.xData[0]:-Number.MAX_VALUE))));l&&(e||f)&&n(m)&&(this.min=this.userMin=m,this.max=this.userMax=p)}a.stickToMin=a.stickToMax=null};d.prototype.updatedDataHandler=function(){var a=
this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=n(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))};d.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(q(this.chart,"redraw",
function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||this.xAxis[0]);b&&a.render(b.min,b.max)}),q(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";this.inverted&&(b=a.opposite?"marginRight":"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))};d.prototype.destroy=function(){this.removeEvents();this.xAxis&&(b(this.chart.xAxis,this.xAxis),b(this.chart.axes,
this.xAxis));this.yAxis&&(b(this.chart.yAxis,this.yAxis),b(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){l(a)},this)};return d}();z.Navigator||(z.Navigator=K,E.compose(c),q(B,"beforeShowResetZoom",function(){var a=
this.options,b=a.navigator,c=a.rangeSelector;if((b&&b.enabled||c&&c.enabled)&&(!t&&"x"===a.chart.zoomType||t&&"x"===a.chart.pinchType))return!1}),q(B,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new K(this)}),q(B,"afterSetChartSize",function(){var a=this.legend,b=this.navigator;if(b){var c=a&&a.options;var d=b.xAxis;var e=b.yAxis;var f=b.scrollbarHeight;this.inverted?(b.left=b.opposite?this.chartWidth-f-b.height:this.spacing[3]+
f,b.top=this.plotTop+f):(b.left=this.plotLeft+f,b.top=b.navigatorOptions.top||this.chartHeight-b.height-f-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&"proximate"!==c.layout&&c.enabled&&!c.floating?a.legendHeight+G(c.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));d&&e&&(this.inverted?d.options.left=e.options.left=b.left:d.options.top=e.options.top=b.top,d.setAxisSize(),e.setAxisSize())}}),q(B,"update",function(a){var b=
a.options.navigator||{},c=a.options.scrollbar||{};this.navigator||this.scroller||!b.enabled&&!c.enabled||(h(!0,this.options.navigator,b),h(!0,this.options.scrollbar,c),delete a.options.navigator,delete a.options.scrollbar)}),q(B,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new K(this),G(a.redraw,!0)&&this.redraw(a.animation))}),q(B,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,
!1)}),q(A,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),B.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}));z.Navigator=K;return z.Navigator});I(c,"masters/modules/gantt.src.js",[],function(){})});
//# sourceMappingURL=gantt.js.map