/*
 Highmaps JS v8.2.2 (2020-11-05)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(r){a(r);a.Highcharts=r;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function r(a,h,p,q){a.hasOwnProperty(h)||(a[h]=q.apply(null,p))}a=a?a._modules:{};r(a,"Core/Axis/MapAxis.js",[a["Core/Axis/Axis.js"],a["Core/Utilities.js"]],function(a,h){var p=h.addEvent,q=h.pick,m=function(){return function(a){this.axis=
a}}();h=function(){function a(){}a.compose=function(a){a.keepProps.push("mapAxis");p(a,"init",function(){this.mapAxis||(this.mapAxis=new m(this))});p(a,"getSeriesExtremes",function(){if(this.mapAxis){var a=[];this.isXAxis&&(this.series.forEach(function(c,m){c.useMapGeometry&&(a[m]=c.xData,c.xData=[])}),this.mapAxis.seriesXData=a)}});p(a,"afterGetSeriesExtremes",function(){if(this.mapAxis){var a=this.mapAxis.seriesXData||[],c;if(this.isXAxis){var m=q(this.dataMin,Number.MAX_VALUE);var f=q(this.dataMax,
-Number.MAX_VALUE);this.series.forEach(function(e,z){e.useMapGeometry&&(m=Math.min(m,q(e.minX,m)),f=Math.max(f,q(e.maxX,f)),e.xData=a[z],c=!0)});c&&(this.dataMin=m,this.dataMax=f);this.mapAxis.seriesXData=void 0}}});p(a,"afterSetAxisTranslation",function(){if(this.mapAxis){var a=this.chart,c=a.plotWidth/a.plotHeight;a=a.xAxis[0];var m;"yAxis"===this.coll&&"undefined"!==typeof a.transA&&this.series.forEach(function(a){a.preserveAspectRatio&&(m=!0)});if(m&&(this.transA=a.transA=Math.min(this.transA,
a.transA),c/=(a.max-a.min)/(this.max-this.min),c=1>c?this:a,a=(c.max-c.min)*c.transA,c.mapAxis.pixelPadding=c.len-a,c.minPixelPadding=c.mapAxis.pixelPadding/2,a=c.mapAxis.fixTo)){a=a[1]-c.toValue(a[0],!0);a*=c.transA;if(Math.abs(a)>c.minPixelPadding||c.min===c.dataMin&&c.max===c.dataMax)a=0;c.minPixelPadding-=a}}});p(a,"render",function(){this.mapAxis&&(this.mapAxis.fixTo=void 0)})};return a}();h.compose(a);return h});r(a,"Mixins/ColorSeries.js",[],function(){return{colorPointMixin:{setVisible:function(a){var h=
this,p=a?"show":"hide";h.visible=h.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(h[a])h[a][p]()});this.series.buildKDTree()}},colorSeriesMixin:{optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var a=this,h=this.options.nullColor,p=this.colorAxis,q=this.colorKey;(this.data.length?this.data:this.points).forEach(function(m){var c=m.getNestedProperty(q);(c=m.options.color||(m.isNull||null===m.value?h:p&&"undefined"!==typeof c?p.toColor(c,m):m.color||a.color))&&m.color!==
c&&(m.color=c,"point"===a.options.legendType&&m.legendItem&&a.chart.legend.colorizeItem(m,m.visible))})}}}});r(a,"Core/Axis/ColorAxis.js",[a["Core/Axis/Axis.js"],a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Mixins/ColorSeries.js"],a["Core/Animation/Fx.js"],a["Core/Globals.js"],a["Core/Legend.js"],a["Mixins/LegendSymbol.js"],a["Series/Line/LineSeries.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,h,p,q,m,c,w,G,u,t,f){var e=this&&this.__extends||function(){var b=function(g,
k){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(g,k){g.__proto__=k}||function(g,k){for(var b in k)k.hasOwnProperty(b)&&(g[b]=k[b])};return b(g,k)};return function(g,k){function d(){this.constructor=g}b(g,k);g.prototype=null===k?Object.create(k):(d.prototype=k.prototype,new d)}}(),z=p.parse;p=q.colorPointMixin;q=q.colorSeriesMixin;var A=c.noop,B=f.addEvent,D=f.erase,y=f.extend,l=f.isNumber,b=f.merge,d=f.pick,n=f.splat;"";y(u.prototype,q);y(t.prototype,p);h.prototype.collectionsWithUpdate.push("colorAxis");
h.prototype.collectionsWithInit.colorAxis=[h.prototype.addColorAxis];var x=function(a){function g(g,b){var k=a.call(this,g,b)||this;k.beforePadding=!1;k.chart=void 0;k.coll="colorAxis";k.dataClasses=void 0;k.legendItem=void 0;k.legendItems=void 0;k.name="";k.options=void 0;k.stops=void 0;k.visible=!0;k.init(g,b);return k}e(g,a);g.buildOptions=function(k,g,d){k=k.options.legend||{};var a=d.layout?"vertical"!==d.layout:"vertical"!==k.layout;return b(g,{side:a?2:1,reversed:!a},d,{opposite:!a,showEmpty:!1,
title:null,visible:k.enabled&&(d?!1!==d.visible:!0)})};g.prototype.init=function(k,b){var d=g.buildOptions(k,g.defaultOptions,b);this.coll="colorAxis";a.prototype.init.call(this,k,d);b.dataClasses&&this.initDataClasses(b);this.initStops();this.horiz=!d.opposite;this.zoomEnabled=!1};g.prototype.initDataClasses=function(k){var g=this.chart,d,a=0,n=g.options.chart.colorCount,e=this.options,l=k.dataClasses.length;this.dataClasses=d=[];this.legendItems=[];k.dataClasses.forEach(function(k,C){k=b(k);d.push(k);
if(g.styledMode||!k.color)"category"===e.dataClassColor?(g.styledMode||(C=g.options.colors,n=C.length,k.color=C[a]),k.colorIndex=a,a++,a===n&&(a=0)):k.color=z(e.minColor).tweenTo(z(e.maxColor),2>l?.5:C/(l-1))})};g.prototype.hasData=function(){return!!(this.tickPositions||[]).length};g.prototype.setTickPositions=function(){if(!this.dataClasses)return a.prototype.setTickPositions.call(this)};g.prototype.initStops=function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];
this.stops.forEach(function(k){k.color=z(k[1])})};g.prototype.setOptions=function(k){a.prototype.setOptions.call(this,k);this.options.crosshair=this.options.marker};g.prototype.setAxisSize=function(){var k=this.legendSymbol,b=this.chart,d=b.options.legend||{},a,n;k?(this.left=d=k.attr("x"),this.top=a=k.attr("y"),this.width=n=k.attr("width"),this.height=k=k.attr("height"),this.right=b.chartWidth-d-n,this.bottom=b.chartHeight-a-k,this.len=this.horiz?n:k,this.pos=this.horiz?d:a):this.len=(this.horiz?
d.symbolWidth:d.symbolHeight)||g.defaultLegendLength};g.prototype.normalizedValue=function(k){this.logarithmic&&(k=this.logarithmic.log2lin(k));return 1-(this.max-k)/(this.max-this.min||1)};g.prototype.toColor=function(k,g){var b=this.dataClasses,d=this.stops,a;if(b)for(a=b.length;a--;){var n=b[a];var e=n.from;d=n.to;if(("undefined"===typeof e||k>=e)&&("undefined"===typeof d||k<=d)){var C=n.color;g&&(g.dataClass=a,g.colorIndex=n.colorIndex);break}}else{k=this.normalizedValue(k);for(a=d.length;a--&&
!(k>d[a][0]););e=d[a]||d[a+1];d=d[a+1]||e;k=1-(d[0]-k)/(d[0]-e[0]||1);C=e.color.tweenTo(d.color,k)}return C};g.prototype.getOffset=function(){var k=this.legendGroup,g=this.chart.axisOffset[this.side];k&&(this.axisParent=k,a.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=g)};g.prototype.setLegendColor=function(){var g=this.reversed,b=g?1:0;g=g?0:1;b=this.horiz?[b,0,g,0]:[0,g,0,b];this.legendColor={linearGradient:{x1:b[0],
y1:b[1],x2:b[2],y2:b[3]},stops:this.stops}};g.prototype.drawLegendSymbol=function(b,a){var k=b.padding,n=b.options,e=this.horiz,l=d(n.symbolWidth,e?g.defaultLegendLength:12),C=d(n.symbolHeight,e?12:g.defaultLegendLength),c=d(n.labelPadding,e?16:30);n=d(n.itemDistance,10);this.setLegendColor();a.legendSymbol=this.chart.renderer.rect(0,b.baseline-11,l,C).attr({zIndex:1}).add(a.legendGroup);this.legendItemWidth=l+k+(e?n:c);this.legendItemHeight=C+k+(e?c:0)};g.prototype.setState=function(g){this.series.forEach(function(b){b.setState(g)})};
g.prototype.setVisible=function(){};g.prototype.getSeriesExtremes=function(){var g=this.series,b=g.length,a;this.dataMin=Infinity;for(this.dataMax=-Infinity;b--;){var n=g[b];var e=n.colorKey=d(n.options.colorKey,n.colorKey,n.pointValKey,n.zoneAxis,"y");var l=n.pointArrayMap;var c=n[e+"Min"]&&n[e+"Max"];if(n[e+"Data"])var f=n[e+"Data"];else if(l){f=[];l=l.indexOf(e);var v=n.yData;if(0<=l&&v)for(a=0;a<v.length;a++)f.push(d(v[a][l],v[a]))}else f=n.yData;c?(n.minColorValue=n[e+"Min"],n.maxColorValue=
n[e+"Max"]):(f=u.prototype.getExtremes.call(n,f),n.minColorValue=f.dataMin,n.maxColorValue=f.dataMax);"undefined"!==typeof n.minColorValue&&(this.dataMin=Math.min(this.dataMin,n.minColorValue),this.dataMax=Math.max(this.dataMax,n.maxColorValue));c||u.prototype.applyExtremes.call(n)}};g.prototype.drawCrosshair=function(g,b){var k=b&&b.plotX,d=b&&b.plotY,n=this.pos,e=this.len;if(b){var l=this.toPixels(b.getNestedProperty(b.series.colorKey));l<n?l=n-2:l>n+e&&(l=n+e+2);b.plotX=l;b.plotY=this.len-l;a.prototype.drawCrosshair.call(this,
g,b);b.plotX=k;b.plotY=d;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,!this.chart.styledMode&&this.crosshair&&this.cross.attr({fill:this.crosshair.color}))}};g.prototype.getPlotLinePath=function(b){var g=this.left,k=b.translatedValue,d=this.top;return l(k)?this.horiz?[["M",k-4,d-6],["L",k+4,d-6],["L",k,d],["Z"]]:[["M",g,k],["L",g-6,k+6],["L",g-6,k-6],["Z"]]:a.prototype.getPlotLinePath.call(this,
b)};g.prototype.update=function(k,d){var n=this.chart,e=n.legend,l=g.buildOptions(n,{},k);this.series.forEach(function(b){b.isDirtyData=!0});(k.dataClasses&&e.allItems||this.dataClasses)&&this.destroyItems();n.options[this.coll]=b(this.userOptions,l);a.prototype.update.call(this,l,d);this.legendItem&&(this.setLegendColor(),e.colorizeItem(this,!0))};g.prototype.destroyItems=function(){var b=this.chart;this.legendItem?b.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(g){b.legend.destroyItem(g)});
b.isDirtyLegend=!0};g.prototype.remove=function(b){this.destroyItems();a.prototype.remove.call(this,b)};g.prototype.getDataClassLegendSymbols=function(){var b=this,g=b.chart,d=b.legendItems,a=g.options.legend,n=a.valueDecimals,e=a.valueSuffix||"",l;d.length||b.dataClasses.forEach(function(k,a){var c=!0,f=k.from,v=k.to,m=g.numberFormatter;l="";"undefined"===typeof f?l="< ":"undefined"===typeof v&&(l="> ");"undefined"!==typeof f&&(l+=m(f,n)+e);"undefined"!==typeof f&&"undefined"!==typeof v&&(l+=" - ");
"undefined"!==typeof v&&(l+=m(v,n)+e);d.push(y({chart:g,name:l,options:{},drawLegendSymbol:G.drawRectangle,visible:!0,setState:A,isDataClass:!0,setVisible:function(){c=b.visible=!c;b.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===a&&b.setVisible(c)})});g.legend.colorizeItem(this,c)}},k))});return d};g.defaultLegendLength=200;g.defaultOptions={lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},
width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0};g.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return g}(a);Array.prototype.push.apply(a.keepProps,x.keepProps);c.ColorAxis=x;["fill","stroke"].forEach(function(b){m.prototype[b+"Setter"]=function(){this.elem.attr(b,z(this.start).tweenTo(z(this.end),this.pos),null,!0)}});B(h,"afterGetAxes",function(){var b=this,g=b.options;
this.colorAxis=[];g.colorAxis&&(g.colorAxis=n(g.colorAxis),g.colorAxis.forEach(function(g,d){g.index=d;new x(b,g)}))});B(u,"bindAxes",function(){var b=this.axisTypes;b?-1===b.indexOf("colorAxis")&&b.push("colorAxis"):this.axisTypes=["colorAxis"]});B(w,"afterGetAllItems",function(b){var g=[],k,d;(this.chart.colorAxis||[]).forEach(function(d){(k=d.options)&&k.showInLegend&&(k.dataClasses&&k.visible?g=g.concat(d.getDataClassLegendSymbols()):k.visible&&g.push(d),d.series.forEach(function(g){if(!g.options.showInLegend||
k.dataClasses)"point"===g.options.legendType?g.points.forEach(function(g){D(b.allItems,g)}):D(b.allItems,g)}))});for(d=g.length;d--;)b.allItems.unshift(g[d])});B(w,"afterColorizeItem",function(b){b.visible&&b.item.legendColor&&b.item.legendSymbol.attr({fill:b.item.legendColor})});B(w,"afterUpdate",function(){var b=this.chart.colorAxis;b&&b.forEach(function(b,k,d){b.update({},d)})});B(u,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()});
return x});r(a,"Mixins/ColorMapSeries.js",[a["Core/Globals.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,h,p){var q=p.defined;return{colorMapPointMixin:{dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(a){h.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group",
"markerGroup","dataLabelsGroup"],getSymbol:a.noop,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:a.seriesTypes.column.prototype.pointAttribs,colorAttribs:function(a){var c={};q(a.color)&&(c[this.colorProp||"fill"]=a.color);return c}}}});r(a,"Maps/MapNavigation.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,h,p){function q(a){a&&(a.preventDefault&&a.preventDefault(),a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)}function m(a){this.init(a)}
var c=h.doc,w=p.addEvent,E=p.extend,u=p.merge,t=p.objectEach,f=p.pick;m.prototype.init=function(a){this.chart=a;a.mapNavButtons=[]};m.prototype.update=function(a){var e=this.chart,c=e.options.mapNavigation,m,h,y,l,b,d=function(b){this.handler.call(e,b);q(b)},n=e.mapNavButtons;a&&(c=e.options.mapNavigation=u(e.options.mapNavigation,a));for(;n.length;)n.pop().destroy();f(c.enableButtons,c.enabled)&&!e.renderer.forExport&&t(c.buttons,function(a,f){m=u(c.buttonOptions,a);e.styledMode||(h=m.theme,h.style=
u(m.theme.style,m.style),l=(y=h.states)&&y.hover,b=y&&y.select);a=e.renderer.button(m.text,0,0,d,h,l,b,0,"zoomIn"===f?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[f]).attr({width:m.width,height:m.height,title:e.options.lang[f],padding:m.padding,zIndex:5}).add();a.handler=m.onclick;w(a.element,"dblclick",q);n.push(a);var g=m,k=w(e,"load",function(){a.align(E(g,{width:a.width,height:2*a.height}),null,g.alignTo);k()})});this.updateEvents(c)};
m.prototype.updateEvents=function(a){var e=this.chart;f(a.enableDoubleClickZoom,a.enabled)||a.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||w(e.container,"dblclick",function(a){e.pointer.onContainerDblClick(a)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());f(a.enableMouseWheelZoom,a.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||w(e.container,"undefined"===typeof c.onmousewheel?"DOMMouseScroll":"mousewheel",function(a){e.pointer.onContainerMouseWheel(a);
q(a);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};E(a.prototype,{fitToBox:function(a,c){[["x","width"],["y","height"]].forEach(function(e){var f=e[0];e=e[1];a[f]+a[e]>c[f]+c[e]&&(a[e]>c[e]?(a[e]=c[e],a[f]=c[f]):a[f]=c[f]+c[e]-a[e]);a[e]>c[e]&&(a[e]=c[e]);a[f]<c[f]&&(a[f]=c[f])});return a},mapZoom:function(a,c,m,h,t){var e=this.xAxis[0],l=e.max-e.min,b=f(c,e.min+l/2),d=l*a;l=this.yAxis[0];var n=l.max-l.min,x=f(m,l.min+n/2);n*=a;b=this.fitToBox({x:b-d*(h?(h-e.pos)/
e.len:.5),y:x-n*(t?(t-l.pos)/l.len:.5),width:d,height:n},{x:e.dataMin,y:l.dataMin,width:e.dataMax-e.dataMin,height:l.dataMax-l.dataMin});d=b.x<=e.dataMin&&b.width>=e.dataMax-e.dataMin&&b.y<=l.dataMin&&b.height>=l.dataMax-l.dataMin;h&&e.mapAxis&&(e.mapAxis.fixTo=[h-e.pos,c]);t&&l.mapAxis&&(l.mapAxis.fixTo=[t-l.pos,m]);"undefined"===typeof a||d?(e.setExtremes(void 0,void 0,!1),l.setExtremes(void 0,void 0,!1)):(e.setExtremes(b.x,b.x+b.width,!1),l.setExtremes(b.y,b.y+b.height,!1));this.redraw()}});w(a,
"beforeRender",function(){this.mapNavigation=new m(this);this.mapNavigation.update()});h.MapNavigation=m});r(a,"Maps/MapPointer.js",[a["Core/Pointer.js"],a["Core/Utilities.js"]],function(a,h){var p=h.extend,q=h.pick;h=h.wrap;p(a.prototype,{onContainerDblClick:function(a){var c=this.chart;a=this.normalize(a);c.options.mapNavigation.enableDoubleClickZoomTo?c.pointer.inClass(a.target,"highcharts-tracker")&&c.hoverPoint&&c.hoverPoint.zoomTo():c.isInsidePlot(a.chartX-c.plotLeft,a.chartY-c.plotTop)&&c.mapZoom(.5,
c.xAxis[0].toValue(a.chartX),c.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)},onContainerMouseWheel:function(a){var c=this.chart;a=this.normalize(a);var m=a.detail||-(a.wheelDelta/120);c.isInsidePlot(a.chartX-c.plotLeft,a.chartY-c.plotTop)&&c.mapZoom(Math.pow(c.options.mapNavigation.mouseWheelSensitivity,m),c.xAxis[0].toValue(a.chartX),c.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)}});h(a.prototype,"zoomOption",function(a){var c=this.chart.options.mapNavigation;q(c.enableTouchZoom,c.enabled)&&(this.chart.options.chart.pinchType=
"xy");a.apply(this,[].slice.call(arguments,1))});h(a.prototype,"pinchTranslate",function(a,c,h,p,q,t,f){a.call(this,c,h,p,q,t,f);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=p.scaleX>p.scaleY,this.pinchTranslateDirection(!a,c,h,p,q,t,f,a?p.scaleX:p.scaleY))})});r(a,"Maps/Map.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Options.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,h,p,q,m){function c(a,c,f,m,h,p,l,b){return[["M",a+h,c],["L",a+f-p,c],
["C",a+f-p/2,c,a+f,c+p/2,a+f,c+p],["L",a+f,c+m-l],["C",a+f,c+m-l/2,a+f-l/2,c+m,a+f-l,c+m],["L",a+b,c+m],["C",a+b/2,c+m,a,c+m-b/2,a,c+m-b],["L",a,c+h],["C",a,c+h/2,a+h/2,c,a+h,c],["Z"]]}p=p.defaultOptions;var w=m.extend,E=m.getOptions,u=m.merge,t=m.pick;m=h.Renderer;var f=h.VMLRenderer;w(p.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});p.mapNavigation={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,
"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};p=h.splitPath=function(a){"string"===typeof a&&(a=a.replace(/([A-Za-z])/g," $1 ").replace(/^\s*/,"").replace(/\s*$/,""),a=a.split(/[ ,;]+/).map(function(a){return/[A-za-z]/.test(a)?a:parseFloat(a)}));return q.prototype.pathToSegments(a)};h.maps={};q.prototype.symbols.topbutton=function(a,f,m,h,p){p=p&&p.r||0;return c(a-
1,f-1,m,h,p,p,0,0)};q.prototype.symbols.bottombutton=function(a,f,m,h,p){p=p&&p.r||0;return c(a-1,f-1,m,h,0,0,p,p)};m===f&&["topbutton","bottombutton"].forEach(function(a){f.prototype.symbols[a]=q.prototype.symbols[a]});return{mapChart:h.Map=h.mapChart=function(c,f,m){var e="string"===typeof c||c.nodeName,p=arguments[e?1:0],h=p,l={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,startOnTick:!1},b=E().credits;var d=p.series;p.series=null;p=u({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:t(b.mapText,
' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:t(b.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:l,yAxis:u(l,{reversed:!0})},p,{chart:{inverted:!1,alignTicks:!1}});p.series=h.series=d;return e?new a(c,p,m):new a(p,f)},maps:h.maps,splitPath:p}});r(a,"Series/MapSeries.js",[a["Core/Series/Series.js"],a["Mixins/ColorMapSeries.js"],a["Core/Globals.js"],a["Mixins/LegendSymbol.js"],a["Series/Line/LineSeries.js"],a["Maps/Map.js"],a["Core/Series/Point.js"],
a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,h,p,q,m,c,w,r,u){var t=a.seriesTypes,f=h.colorMapPointMixin,e=p.noop,z=c.maps,A=c.splitPath,B=u.extend,E=u.fireEvent,y=u.getNestedProperty,l=u.isArray,b=u.isNumber,d=u.merge,n=u.objectEach,x=u.pick,v=u.splat;a.seriesType("map","scatter",{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,
pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,allAreas:!0,borderColor:"#cccccc",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:"#cccccc"},inactive:{opacity:1}}},d(h.colorMapSeriesMixin,{type:"map",getExtremesFromAll:!0,useMapGeometry:!0,forceDL:!0,searchPoint:e,directTouch:!0,preserveAspectRatio:!0,pointArrayMap:["value"],setOptions:function(a){a=m.prototype.setOptions.call(this,a);var b=a.joinBy;null===b&&(b="_i");b=this.joinBy=
v(b);b[1]||(b[1]=b[0]);return a},getBox:function(a){var b=Number.MAX_VALUE,g=-b,d=b,n=-b,c=b,f=b,l=this.xAxis,e=this.yAxis,p;(a||[]).forEach(function(a){if(a.path){"string"===typeof a.path?a.path=A(a.path):"M"===a.path[0]&&(a.path=r.prototype.pathToSegments(a.path));var k=a.path||[],l=-b,e=b,m=-b,h=b,v=a.properties;a._foundBox||(k.forEach(function(a){var b=a[a.length-2];a=a[a.length-1];"number"===typeof b&&"number"===typeof a&&(e=Math.min(e,b),l=Math.max(l,b),h=Math.min(h,a),m=Math.max(m,a))}),a._midX=
e+(l-e)*x(a.middleX,v&&v["hc-middle-x"],.5),a._midY=h+(m-h)*x(a.middleY,v&&v["hc-middle-y"],.5),a._maxX=l,a._minX=e,a._maxY=m,a._minY=h,a.labelrank=x(a.labelrank,(l-e)*(m-h)),a._foundBox=!0);g=Math.max(g,a._maxX);d=Math.min(d,a._minX);n=Math.max(n,a._maxY);c=Math.min(c,a._minY);f=Math.min(a._maxX-a._minX,a._maxY-a._minY,f);p=!0}});p&&(this.minY=Math.min(c,x(this.minY,b)),this.maxY=Math.max(n,x(this.maxY,-b)),this.minX=Math.min(d,x(this.minX,b)),this.maxX=Math.max(g,x(this.maxX,-b)),l&&"undefined"===
typeof l.options.minRange&&(l.minRange=Math.min(5*f,(this.maxX-this.minX)/5,l.minRange||b)),e&&"undefined"===typeof e.options.minRange&&(e.minRange=Math.min(5*f,(this.maxY-this.minY)/5,e.minRange||b)))},hasData:function(){return!!this.processedXData.length},getExtremes:function(){var a=m.prototype.getExtremes.call(this,this.valueData),d=a.dataMin;a=a.dataMax;this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);b(d)&&(this.valueMin=d);b(a)&&(this.valueMax=a);return{dataMin:this.minY,
dataMax:this.maxY}},translatePath:function(a){var b=this.xAxis,g=this.yAxis,d=b.min,n=b.transA,c=b.minPixelPadding,f=g.min,l=g.transA,e=g.minPixelPadding,m=[];a&&a.forEach(function(a){"M"===a[0]?m.push(["M",(a[1]-(d||0))*n+c,(a[2]-(f||0))*l+e]):"L"===a[0]?m.push(["L",(a[1]-(d||0))*n+c,(a[2]-(f||0))*l+e]):"C"===a[0]?m.push(["C",(a[1]-(d||0))*n+c,(a[2]-(f||0))*l+e,(a[3]-(d||0))*n+c,(a[4]-(f||0))*l+e,(a[5]-(d||0))*n+c,(a[6]-(f||0))*l+e]):"Q"===a[0]?m.push(["Q",(a[1]-(d||0))*n+c,(a[2]-(f||0))*l+e,(a[3]-
(d||0))*n+c,(a[4]-(f||0))*l+e]):"Z"===a[0]&&m.push(["Z"])});return m},setData:function(a,k,c,f){var g=this.options,e=this.chart.options.chart,h=e&&e.map,v=g.mapData,x=this.joinBy,C=g.keys||this.pointArrayMap,t=[],F={},q=this.chart.mapTransforms;!v&&h&&(v="string"===typeof h?z[h]:h);a&&a.forEach(function(d,k){var n=0;if(b(d))a[k]={value:d};else if(l(d)){a[k]={};!g.keys&&d.length>C.length&&"string"===typeof d[0]&&(a[k]["hc-key"]=d[0],++n);for(var c=0;c<C.length;++c,++n)C[c]&&"undefined"!==typeof d[n]&&
(0<C[c].indexOf(".")?w.prototype.setNestedProperty(a[k],d[n],C[c]):a[k][C[c]]=d[n])}x&&"_i"===x[0]&&(a[k]._i=k)});this.getBox(a);(this.chart.mapTransforms=q=e&&e.mapTransforms||v&&v["hc-transform"]||q)&&n(q,function(a){a.rotation&&(a.cosAngle=Math.cos(a.rotation),a.sinAngle=Math.sin(a.rotation))});if(v){"FeatureCollection"===v.type&&(this.mapTitle=v.title,v=p.geojson(v,this.type,this));this.mapData=v;this.mapMap={};for(q=0;q<v.length;q++)e=v[q],h=e.properties,e._i=q,x[0]&&h&&h[x[0]]&&(e[x[0]]=h[x[0]]),
F[e[x[0]]]=e;this.mapMap=F;if(a&&x[1]){var u=x[1];a.forEach(function(a){a=y(u,a);F[a]&&t.push(F[a])})}if(g.allAreas){this.getBox(v);a=a||[];if(x[1]){var A=x[1];a.forEach(function(a){t.push(y(A,a))})}t="|"+t.map(function(a){return a&&a[x[0]]}).join("|")+"|";v.forEach(function(b){x[0]&&-1!==t.indexOf("|"+b[x[0]]+"|")||(a.push(d(b,{value:null})),f=!1)})}else this.getBox(t)}m.prototype.setData.call(this,a,k,c,f)},drawGraph:e,drawDataLabels:e,doFullTranslate:function(){return this.isDirtyData||this.chart.isResizing||
this.chart.renderer.isVML||!this.baseTrans},translate:function(){var a=this,d=a.xAxis,n=a.yAxis,c=a.doFullTranslate();a.generatePoints();a.data.forEach(function(g){b(g._midX)&&b(g._midY)&&(g.plotX=d.toPixels(g._midX,!0),g.plotY=n.toPixels(g._midY,!0));c&&(g.shapeType="path",g.shapeArgs={d:a.translatePath(g.path)})});E(a,"afterTranslate")},pointAttribs:function(a,b){b=a.series.chart.styledMode?this.colorAttribs(a):t.column.prototype.pointAttribs.call(this,a,b);b["stroke-width"]=x(a.options[this.pointAttrToOptions&&
this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return b},drawPoints:function(){var a=this,b=a.xAxis,d=a.yAxis,n=a.group,c=a.chart,e=c.renderer,f=this.baseTrans;a.transformGroup||(a.transformGroup=e.g().attr({scaleX:1,scaleY:1}).add(n),a.transformGroup.survive=!0);if(a.doFullTranslate())c.hasRendered&&!c.styledMode&&a.points.forEach(function(b){b.shapeArgs&&(b.shapeArgs.fill=a.pointAttribs(b,b.state).fill)}),a.group=a.transformGroup,t.column.prototype.drawPoints.apply(a),a.group=
n,a.points.forEach(function(b){if(b.graphic){var d="";b.name&&(d+="highcharts-name-"+b.name.replace(/ /g,"-").toLowerCase());b.properties&&b.properties["hc-key"]&&(d+=" highcharts-key-"+b.properties["hc-key"].toLowerCase());d&&b.graphic.addClass(d);c.styledMode&&b.graphic.css(a.pointAttribs(b,b.selected&&"select"||void 0))}}),this.baseTrans={originX:b.min-b.minPixelPadding/b.transA,originY:d.min-d.minPixelPadding/d.transA+(d.reversed?0:d.len/d.transA),transAX:b.transA,transAY:d.transA},this.transformGroup.animate({translateX:0,
translateY:0,scaleX:1,scaleY:1});else{var l=b.transA/f.transAX;var m=d.transA/f.transAY;var h=b.toPixels(f.originX,!0);var v=d.toPixels(f.originY,!0);.99<l&&1.01>l&&.99<m&&1.01>m&&(m=l=1,h=Math.round(h),v=Math.round(v));var p=this.transformGroup;if(c.renderer.globalAnimation){var y=p.attr("translateX");var q=p.attr("translateY");var z=p.attr("scaleX");var w=p.attr("scaleY");p.attr({animator:0}).animate({animator:1},{step:function(a,b){p.attr({translateX:y+(h-y)*b.pos,translateY:q+(v-q)*b.pos,scaleX:z+
(l-z)*b.pos,scaleY:w+(m-w)*b.pos})}})}else p.attr({translateX:h,translateY:v,scaleX:l,scaleY:m})}c.styledMode||n.element.setAttribute("stroke-width",x(a.options[a.pointAttrToOptions&&a.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(l||1));this.drawMapDataLabels()},drawMapDataLabels:function(){m.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)},render:function(){var a=this,b=m.prototype.render;a.chart.renderer.isVML&&3E3<a.data.length?
setTimeout(function(){b.call(a)}):b.call(a)},animate:function(a){var b=this.options.animation,d=this.group,g=this.xAxis,n=this.yAxis,c=g.pos,f=n.pos;this.chart.renderer.isSVG&&(!0===b&&(b={duration:1E3}),a?d.attr({translateX:c+g.len/2,translateY:f+n.len/2,scaleX:.001,scaleY:.001}):d.animate({translateX:c,translateY:f,scaleX:1,scaleY:1},b))},animateDrilldown:function(a){var b=this.chart.plotBox,d=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],g=d.bBox,n=this.chart.options.drilldown.animation;
a||(a=Math.min(g.width/b.width,g.height/b.height),d.shapeArgs={scaleX:a,scaleY:a,translateX:g.x,translateY:g.y},this.points.forEach(function(a){a.graphic&&a.graphic.attr(d.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},n)}))},drawLegendSymbol:q.drawRectangle,animateDrillupFrom:function(a){t.column.prototype.animateDrillupFrom.call(this,a)},animateDrillupTo:function(a){t.column.prototype.animateDrillupTo.call(this,a)}}),B({applyOptions:function(a,b){var d=this.series;a=w.prototype.applyOptions.call(this,
a,b);b=d.joinBy;d.mapData&&d.mapMap&&(b=w.prototype.getNestedProperty.call(a,b[1]),(b="undefined"!==typeof b&&d.mapMap[b])?(d.xyFromShape&&(a.x=b._midX,a.y=b._midY),B(a,b)):a.value=a.value||null);return a},onMouseOver:function(a){u.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)w.prototype.onMouseOver.call(this,a);else this.series.onMouseOut(a)},zoomTo:function(){var a=this.series;a.xAxis.setExtremes(this._minX,this._maxX,!1);a.yAxis.setExtremes(this._minY,
this._maxY,!1);a.chart.redraw()}},f));""});r(a,"Series/MapLineSeries.js",[a["Core/Series/Series.js"]],function(a){var h=a.seriesTypes;a.seriesType("mapline","map",{lineWidth:1,fillColor:"none"},{type:"mapline",colorProp:"stroke",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(a,q){a=h.map.prototype.pointAttribs.call(this,a,q);a.fill=this.options.fillColor;return a},drawLegendSymbol:h.line.prototype.drawLegendSymbol});""});r(a,"Series/MapPointSeries.js",[a["Core/Series/Series.js"],
a["Series/Line/LineSeries.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,h,p,q){var m=q.merge;a.seriesType("mappoint","scatter",{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:"#000000"}}},{type:"mappoint",forceDL:!0,drawDataLabels:function(){h.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)}},{applyOptions:function(a,h){a="undefined"!==typeof a.lat&&"undefined"!==
typeof a.lon?m(a,this.series.chart.fromLatLonToPoint(a)):a;return p.prototype.applyOptions.call(this,a,h)}});""});r(a,"Series/Bubble/BubbleLegend.js",[a["Core/Chart/Chart.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],a["Core/Legend.js"],a["Series/Line/LineSeries.js"],a["Core/Utilities.js"]],function(a,h,p,q,m,c){var w=h.parse,r=p.noop;h=c.addEvent;var u=c.arrayMax,t=c.arrayMin,f=c.isNumber,e=c.merge,z=c.objectEach,A=c.pick,B=c.setOptions,D=c.stableSort,y=c.wrap;"";B({legend:{bubbleLegend:{borderColor:void 0,
borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});B=function(){function a(a,d){this.options=this.symbols=this.visible=
this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=r;this.init(a,d)}a.prototype.init=function(a,d){this.options=a;this.visible=!0;this.chart=d.chart;this.legend=d};a.prototype.addToLegend=function(a){a.splice(this.options.legendIndex,0,this)};a.prototype.drawLegendSymbol=function(a){var b=this.chart,n=this.options,c=A(a.options.itemDistance,20),e=n.ranges;
var g=n.connectorDistance;this.fontMetrics=b.renderer.fontMetrics(n.labels.style.fontSize.toString()+"px");e&&e.length&&f(e[0].value)?(D(e,function(a,b){return b.value-a.value}),this.ranges=e,this.setOptions(),this.render(),b=this.getMaxLabelSize(),e=this.ranges[0].radius,a=2*e,g=g-e+b.width,g=0<g?g:0,this.maxLabel=b,this.movementX="left"===n.labels.align?g:0,this.legendItemWidth=a+g+c,this.legendItemHeight=a+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var a=
this.ranges,d=this.options,n=this.chart.series[d.seriesIndex],c=this.legend.baseline,f={"z-index":d.zIndex,"stroke-width":d.borderWidth},g={"z-index":d.zIndex,"stroke-width":d.connectorWidth},k=this.getLabelStyles(),l=n.options.marker.fillOpacity,m=this.chart.styledMode;a.forEach(function(b,h){m||(f.stroke=A(b.borderColor,d.borderColor,n.color),f.fill=A(b.color,d.color,1!==l?w(n.color).setOpacity(l).get("rgba"):n.color),g.stroke=A(b.connectorColor,d.connectorColor,n.color));a[h].radius=this.getRangeRadius(b.value);
a[h]=e(a[h],{center:a[0].radius-a[h].radius+c});m||e(!0,a[h],{bubbleStyle:e(!1,f),connectorStyle:e(!1,g),labelStyle:k})},this)};a.prototype.getLabelStyles=function(){var a=this.options,d={},n="left"===a.labels.align,c=this.legend.options.rtl;z(a.labels.style,function(a,b){"color"!==b&&"fontSize"!==b&&"z-index"!==b&&(d[b]=a)});return e(!1,d,{"font-size":a.labels.style.fontSize,fill:A(a.labels.style.color,"#000000"),"z-index":a.zIndex,align:c||n?"right":"left"})};a.prototype.getRangeRadius=function(a){var b=
this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,b.ranges[b.ranges.length-1].value,b.ranges[0].value,b.minSize,b.maxSize,a)};a.prototype.render=function(){var a=this.chart.renderer,d=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(a){a.value>=d&&this.renderRange(a)},
this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};a.prototype.renderRange=function(a){var b=this.options,n=b.labels,c=this.chart.renderer,e=this.symbols,g=e.labels,k=a.center,f=Math.abs(a.radius),l=b.connectorDistance||0,h=n.align,m=n.style.fontSize;l=this.legend.options.rtl||"left"===h?-l:l;n=b.connectorWidth;var p=this.ranges[0].radius||0,t=k-f-b.borderWidth/2+n/2;m=m/2-(this.fontMetrics.h-m)/2;var y=c.styledMode;"center"===h&&(l=0,
b.connectorDistance=0,a.labelStyle.align="center");h=t+b.labels.y;var q=p+l+b.labels.x;e.bubbleItems.push(c.circle(p,k+((t%1?1:.5)-(n%2?0:.5)),f).attr(y?{}:a.bubbleStyle).addClass((y?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(b.className||"")).add(this.legendSymbol));e.connectors.push(c.path(c.crispLine([["M",p,t],["L",p+l,t]],b.connectorWidth)).attr(y?{}:a.connectorStyle).addClass((y?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+
(b.connectorClassName||"")).add(this.legendSymbol));a=c.text(this.formatLabel(a),q,h+m).attr(y?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+(b.labels.className||"")).add(this.legendSymbol);g.push(a);a.placed=!0;a.alignAttr={x:q,y:h+m}};a.prototype.getMaxLabelSize=function(){var a,d;this.symbols.labels.forEach(function(b){d=b.getBBox(!0);a=a?d.width>a.width?d:a:d});return a||{}};a.prototype.formatLabel=function(a){var b=this.options,n=b.labels.formatter;b=b.labels.format;var e=this.chart.numberFormatter;
return b?c.format(b,a):n?n.call(a):e(a.value,1)};a.prototype.hideOverlappingLabels=function(){var a=this.chart,d=this.symbols;!this.options.labels.allowOverlap&&d&&(a.hideOverlappingLabels(d.labels),d.labels.forEach(function(a,b){a.newOpacity?a.newOpacity!==a.oldOpacity&&d.connectors[b].show():d.connectors[b].hide()}))};a.prototype.getRanges=function(){var a=this.legend.bubbleLegend,d=a.options.ranges,n,c=Number.MAX_VALUE,l=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&
(n=a.zData.filter(f),n.length&&(c=A(a.options.zMin,Math.min(c,Math.max(t(n),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),l=A(a.options.zMax,Math.max(l,u(n)))))});var g=c===l?[{value:l}]:[{value:c},{value:(c+l)/2},{value:l,autoRanges:!0}];d.length&&d[0].radius&&g.reverse();g.forEach(function(a,b){d&&d[b]&&(g[b]=e(!1,d[b],a))});return g};a.prototype.predictBubbleSizes=function(){var a=this.chart,d=this.fontMetrics,n=a.legend.options,c="horizontal"===n.layout,e=c?a.legend.lastLineHeight:
0,g=a.plotSizeX,f=a.plotSizeY,l=a.series[this.options.seriesIndex];a=Math.ceil(l.minPxSize);var h=Math.ceil(l.maxPxSize);l=l.options.maxSize;var m=Math.min(f,g);if(n.floating||!/%$/.test(l))d=h;else if(l=parseFloat(l),d=(m+e-d.h/2)*l/100/(l/100+1),c&&f-d>=g||!c&&g-d>=f)d=h;return[a,Math.ceil(d)]};a.prototype.updateRanges=function(a,d){var b=this.legend.options.bubbleLegend;b.minSize=a;b.maxSize=d;b.ranges=this.getRanges()};a.prototype.correctSizes=function(){var a=this.legend,d=this.chart.series[this.options.seriesIndex];
1<Math.abs(Math.ceil(d.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,d.maxPxSize),a.render())};return a}();h(q,"afterGetAllItems",function(a){var b=this.bubbleLegend,d=this.options,c=d.bubbleLegend,e=this.chart.getVisibleBubbleSeriesIndex();b&&b.ranges&&b.ranges.length&&(c.ranges.length&&(c.autoRanges=!!c.ranges[0].autoRanges),this.destroyItem(b));0<=e&&d.enabled&&c.enabled&&(c.seriesIndex=e,this.bubbleLegend=new p.BubbleLegend(c,this),this.bubbleLegend.addToLegend(a.allItems))});
a.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=this.series,b=0;b<a.length;){if(a[b]&&a[b].isBubble&&a[b].visible&&a[b].zData.length)return b;b++}return-1};q.prototype.getLinesHeights=function(){var a=this.allItems,b=[],d=a.length,c,e=0;for(c=0;c<d;c++)if(a[c].legendItemHeight&&(a[c].itemHeight=a[c].legendItemHeight),a[c]===a[d-1]||a[c+1]&&a[c]._legendItemPos[1]!==a[c+1]._legendItemPos[1]){b.push({height:0});var f=b[b.length-1];for(e;e<=c;e++)a[e].itemHeight>f.height&&(f.height=a[e].itemHeight);
f.step=c}return b};q.prototype.retranslateItems=function(a){var b,d,c,e=this.options.rtl,f=0;this.allItems.forEach(function(g,n){b=g.legendGroup.translateX;d=g._legendItemPos[1];if((c=g.movementX)||e&&g.ranges)c=e?b-g.options.maxSize/2:b+c,g.legendGroup.attr({translateX:c});n>a[f].step&&f++;g.legendGroup.attr({translateY:Math.round(d+a[f].height/2)});g._legendItemPos[1]=d+a[f].height/2})};h(m,"legendItemClick",function(){var a=this.chart,b=this.visible,d=this.chart.legend;d&&d.bubbleLegend&&(this.visible=
!b,this.ignoreSeries=b,a=0<=a.getVisibleBubbleSeriesIndex(),d.bubbleLegend.visible!==a&&(d.update({bubbleLegend:{enabled:a}}),d.bubbleLegend.visible=a),this.visible=b)});y(a.prototype,"drawChartBox",function(a,b,d){var c=this.legend,e=0<=this.getVisibleBubbleSeriesIndex();if(c&&c.options.enabled&&c.bubbleLegend&&c.options.bubbleLegend.autoRanges&&e){var f=c.bubbleLegend.options;e=c.bubbleLegend.predictBubbleSizes();c.bubbleLegend.updateRanges(e[0],e[1]);f.placed||(c.group.placed=!1,c.allItems.forEach(function(a){a.legendGroup.translateY=
null}));c.render();this.getMargins();this.axes.forEach(function(a){a.visible&&a.render();f.placed||(a.setScale(),a.updateNames(),z(a.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))});f.placed=!0;this.getMargins();a.call(this,b,d);c.bubbleLegend.correctSizes();c.retranslateItems(c.getLinesHeights())}else a.call(this,b,d),c&&c.options.enabled&&c.bubbleLegend&&(c.render(),c.retranslateItems(c.getLinesHeights()))});p.BubbleLegend=B;return p.BubbleLegend});r(a,"Series/Bubble/BubbleSeries.js",[a["Core/Axis/Axis.js"],
a["Core/Series/Series.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],a["Series/Line/LineSeries.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,h,p,q,m,c,w){var r=h.seriesTypes,u=p.parse;p=q.noop;var t=w.arrayMax,f=w.arrayMin,e=w.clamp,z=w.extend,A=w.isNumber,B=w.pick,D=w.pInt;"";h.seriesType("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,
states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(a,c){var b=this.options.marker.fillOpacity;a=m.prototype.pointAttribs.call(this,
a,c);1!==b&&(a.fill=u(a.fill).setOpacity(b).get("rgba"));return a},getRadii:function(a,c,b){var d=this.zData,e=this.yData,f=b.minPxSize,l=b.maxPxSize,g=[];var k=0;for(b=d.length;k<b;k++){var h=d[k];g.push(this.getRadius(a,c,f,l,h,e[k]))}this.radii=g},getRadius:function(a,c,b,d,e,f){var n=this.options,g="width"!==n.sizeBy,k=n.zThreshold,l=c-a,h=.5;if(null===f||null===e)return null;if(A(e)){n.sizeByAbsoluteValue&&(e=Math.abs(e-k),l=Math.max(c-k,Math.abs(a-k)),a=0);if(e<a)return b/2-1;0<l&&(h=(e-a)/
l)}g&&0<=h&&(h=Math.sqrt(h));return Math.ceil(b+h*(d-b))/2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&this.points.forEach(function(a){var b=a.graphic;b&&b.width&&(this.hasRendered||b.attr({x:a.plotX,y:a.plotY,width:1,height:1}),b.animate(this.markerAttribs(a),this.options.animation))},this)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,c=this.data,b=this.radii;r.scatter.prototype.translate.call(this);for(a=c.length;a--;){var d=c[a];
var e=b?b[a]:0;A(e)&&e>=this.minPxSize/2?(d.marker=z(d.marker,{radius:e,width:2*e,height:2*e}),d.dlBox={x:d.plotX-e,y:d.plotY-e,width:2*e,height:2*e}):d.shapeArgs=d.plotY=d.dlBox=void 0}},alignDataLabel:r.column.prototype.alignDataLabel,buildKDTree:p,applyZones:p},{haloPath:function(a){return c.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});a.prototype.beforePadding=function(){var a=this,c=this.len,b=this.chart,d=0,n=c,h=this.isXAxis,m=h?"xData":"yData",
g=this.min,k={},p=Math.min(b.plotWidth,b.plotHeight),q=Number.MAX_VALUE,z=-Number.MAX_VALUE,w=this.max-g,u=c/w,r=[];this.series.forEach(function(c){var d=c.options;!c.bubblePadding||!c.visible&&b.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,r.push(c),h&&(["minSize","maxSize"].forEach(function(a){var b=d[a],c=/%$/.test(b);b=D(b);k[a]=c?p*b/100:b}),c.minPxSize=k.minSize,c.maxPxSize=Math.max(k.maxSize,k.minSize),c=c.zData.filter(A),c.length&&(q=B(d.zMin,e(f(c),!1===d.displayNegative?d.zThreshold:
-Number.MAX_VALUE,q)),z=B(d.zMax,Math.max(z,t(c))))))});r.forEach(function(b){var c=b[m],e=c.length;h&&b.getRadii(q,z,b);if(0<w)for(;e--;)if(A(c[e])&&a.dataMin<=c[e]&&c[e]<=a.max){var f=b.radii?b.radii[e]:0;d=Math.min((c[e]-g)*u-f,d);n=Math.max((c[e]-g)*u+f,n)}});r.length&&0<w&&!this.logarithmic&&(n-=c,u*=(c+Math.max(0,d)-Math.min(n,c))/c,[["min","userMin",d],["max","userMax",n]].forEach(function(b){"undefined"===typeof B(a.options[b[0]],a[b[1]])&&(a[b[0]]+=b[2]/u)}))};""});r(a,"Series/MapBubbleSeries.js",
[a["Core/Series/Series.js"],a["Core/Series/Point.js"],a["Core/Utilities.js"]],function(a,h,p){var q=p.merge,m=a.seriesTypes;m.bubble&&a.seriesType("mapbubble","bubble",{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}},{xyFromShape:!0,type:"mapbubble",pointArrayMap:["z"],getMapData:m.map.prototype.getMapData,getBox:m.map.prototype.getBox,setData:m.map.prototype.setData,setOptions:m.map.prototype.setOptions},{applyOptions:function(a,p){return a&&"undefined"!==typeof a.lat&&"undefined"!==
typeof a.lon?h.prototype.applyOptions.call(this,q(a,this.series.chart.fromLatLonToPoint(a)),p):m.map.prototype.pointClass.prototype.applyOptions.call(this,a,p)},isValid:function(){return"number"===typeof this.z},ttBelow:!1});""});r(a,"Series/HeatmapSeries.js",[a["Core/Series/Series.js"],a["Mixins/ColorMapSeries.js"],a["Core/Globals.js"],a["Core/Series/Point.js"],a["Mixins/LegendSymbol.js"],a["Series/Line/LineSeries.js"],a["Core/Renderer/SVG/SVGRenderer.js"],a["Core/Utilities.js"]],function(a,h,p,
q,m,c,w,r){var u=a.seriesTypes,t=h.colorMapPointMixin;h=h.colorMapSeriesMixin;var f=p.noop,e=r.clamp,z=r.extend,A=r.fireEvent,B=r.isNumber,D=r.merge,y=r.pick,l=w.prototype.symbols;"";a.seriesType("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,
tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}},D(h,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){c.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=y(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;z(l,{ellipse:l.circle,rect:l.square})},getSymbol:c.prototype.getSymbol,setClip:function(a){var b=this.chart;c.prototype.setClip.apply(this,arguments);
(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&this.sharedClipKey?b[this.sharedClipKey]:b.clipRect)},translate:function(){var a=this.options,c=a.marker&&a.marker.symbol||"",e=l[c]?c:"rect";a=this.options;var f=-1!==["circle","square"].indexOf(e);this.generatePoints();this.points.forEach(function(a){var b=a.getCellAttributes(),d={x:Math.min(b.x1,b.x2),y:Math.min(b.y1,b.y2),width:Math.max(Math.abs(b.x2-b.x1),0),height:Math.max(Math.abs(b.y2-b.y1),0)};var n=a.hasImage=0===(a.marker&&
a.marker.symbol||c||"").indexOf("url");if(f){var h=Math.abs(d.width-d.height);d.x=Math.min(b.x1,b.x2)+(d.width<d.height?0:h/2);d.y=Math.min(b.y1,b.y2)+(d.width<d.height?h/2:0);d.width=d.height=Math.min(d.width,d.height)}h={plotX:(b.x1+b.x2)/2,plotY:(b.y1+b.y2)/2,clientX:(b.x1+b.x2)/2,shapeType:"path",shapeArgs:D(!0,d,{d:l[e](d.x,d.y,d.width,d.height)})};n&&(a.marker={width:d.width,height:d.height});z(a,h)});A(this,"afterTranslate")},pointAttribs:function(a,d){var b=c.prototype.pointAttribs.call(this,
a,d),e=this.options||{},f=this.chart.options.plotOptions||{},g=f.series||{},k=f.heatmap||{};f=e.borderColor||k.borderColor||g.borderColor;g=e.borderWidth||k.borderWidth||g.borderWidth||b["stroke-width"];b.stroke=a&&a.marker&&a.marker.lineColor||e.marker&&e.marker.lineColor||f||this.color;b["stroke-width"]=g;d&&(a=D(e.states[d],e.marker&&e.marker.states[d],a.options.states&&a.options.states[d]||{}),d=a.brightness,b.fill=a.color||p.color(b.fill).brighten(d||0).get(),b.stroke=a.lineColor);return b},
markerAttribs:function(a,c){var b=a.marker||{},d=this.options.marker||{},e=a.shapeArgs||{},f={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(c){var k=d.states[c]||{};var h=b.states&&b.states[c]||{};[["width","x"],["height","y"]].forEach(function(a){f[a[0]]=(h[a[0]]||k[a[0]]||e[a[0]])+(h[a[0]+"Plus"]||k[a[0]+"Plus"]||0);f[a[1]]=e[a[1]]+(e[a[0]]-f[a[0]])/2})}return c?f:e},drawPoints:function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)c.prototype.drawPoints.call(this),this.points.forEach(function(b){b.graphic&&
b.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(b))})},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,d){return c.prototype.getValidPoints.call(this,a,d,!0)},getBox:f,drawLegendSymbol:m.drawRectangle,alignDataLabel:u.column.prototype.alignDataLabel,getExtremes:function(){var a=c.prototype.getExtremes.call(this,this.valueData),d=a.dataMin;a=a.dataMax;B(d)&&(this.valueMin=d);B(a)&&(this.valueMax=a);return c.prototype.getExtremes.call(this)}}),D(t,{applyOptions:function(a,
c){a=q.prototype.applyOptions.call(this,a,c);a.formatPrefix=a.isNull||null===a.value?"null":"point";return a},isValid:function(){return Infinity!==this.value&&-Infinity!==this.value},haloPath:function(a){if(!a)return[];var b=this.shapeArgs;return["M",b.x-a,b.y-a,"L",b.x-a,b.y+b.height+a,b.x+b.width+a,b.y+b.height+a,b.x+b.width+a,b.y-a,"Z"]},getCellAttributes:function(){var a=this.series,c=a.options,f=(c.colsize||1)/2,h=(c.rowsize||1)/2,l=a.xAxis,g=a.yAxis,k=this.options.marker||a.options.marker;a=
a.pointPlacementToXValue();var m=y(this.pointPadding,c.pointPadding,0),p={x1:e(Math.round(l.len-(l.translate(this.x-f,!1,!0,!1,!0,-a)||0)),-l.len,2*l.len),x2:e(Math.round(l.len-(l.translate(this.x+f,!1,!0,!1,!0,-a)||0)),-l.len,2*l.len),y1:e(Math.round(g.translate(this.y-h,!1,!0,!1,!0)||0),-g.len,2*g.len),y2:e(Math.round(g.translate(this.y+h,!1,!0,!1,!0)||0),-g.len,2*g.len)};[["width","x"],["height","y"]].forEach(function(a){var b=a[0];a=a[1];var c=a+"1",d=a+"2",e=Math.abs(p[c]-p[d]),f=k&&k.lineWidth||
0,g=Math.abs(p[c]+p[d])/2;k[b]&&k[b]<e&&(p[c]=g-k[b]/2-f/2,p[d]=g+k[b]/2+f/2);m&&("y"===a&&(c=d,d=a+"1"),p[c]+=m,p[d]-=m)});return p}}));""});r(a,"Extensions/GeoJSON.js",[a["Core/Chart/Chart.js"],a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,h,p){function q(a,c){var e,f=!1,h=a.x,m=a.y;a=0;for(e=c.length-1;a<c.length;e=a++){var p=c[a][1]>m;var t=c[e][1]>m;p!==t&&h<(c[e][0]-c[a][0])*(m-c[a][1])/(c[e][1]-c[a][1])+c[a][0]&&(f=!f)}return f}var m=h.win,c=p.error,r=p.extend,E=p.format,u=p.merge;
p=p.wrap;"";a.prototype.transformFromLatLon=function(a,f){var e,h=(null===(e=this.userOptions.chart)||void 0===e?void 0:e.proj4)||m.proj4;if(!h)return c(21,!1,this),{x:0,y:null};a=h(f.crs,[a.lon,a.lat]);e=f.cosAngle||f.rotation&&Math.cos(f.rotation);h=f.sinAngle||f.rotation&&Math.sin(f.rotation);a=f.rotation?[a[0]*e+a[1]*h,-a[0]*h+a[1]*e]:a;return{x:((a[0]-(f.xoffset||0))*(f.scale||1)+(f.xpan||0))*(f.jsonres||1)+(f.jsonmarginX||0),y:(((f.yoffset||0)-a[1])*(f.scale||1)+(f.ypan||0))*(f.jsonres||1)-
(f.jsonmarginY||0)}};a.prototype.transformToLatLon=function(a,f){if("undefined"===typeof m.proj4)c(21,!1,this);else{a={x:((a.x-(f.jsonmarginX||0))/(f.jsonres||1)-(f.xpan||0))/(f.scale||1)+(f.xoffset||0),y:((-a.y-(f.jsonmarginY||0))/(f.jsonres||1)+(f.ypan||0))/(f.scale||1)+(f.yoffset||0)};var e=f.cosAngle||f.rotation&&Math.cos(f.rotation),h=f.sinAngle||f.rotation&&Math.sin(f.rotation);f=m.proj4(f.crs,"WGS84",f.rotation?{x:a.x*e+a.y*-h,y:a.x*h+a.y*e}:a);return{lat:f.y,lon:f.x}}};a.prototype.fromPointToLatLon=
function(a){var f=this.mapTransforms,e;if(f){for(e in f)if(Object.hasOwnProperty.call(f,e)&&f[e].hitZone&&q({x:a.x,y:-a.y},f[e].hitZone.coordinates[0]))return this.transformToLatLon(a,f[e]);return this.transformToLatLon(a,f["default"])}c(22,!1,this)};a.prototype.fromLatLonToPoint=function(a){var f=this.mapTransforms,e;if(!f)return c(22,!1,this),{x:0,y:null};for(e in f)if(Object.hasOwnProperty.call(f,e)&&f[e].hitZone){var h=this.transformFromLatLon(a,f[e]);if(q({x:h.x,y:-h.y},f[e].hitZone.coordinates[0]))return h}return this.transformFromLatLon(a,
f["default"])};h.geojson=function(a,c,e){var f=[],h=[],m=function(a){a.forEach(function(a,c){0===c?h.push(["M",a[0],-a[1]]):h.push(["L",a[0],-a[1]])})};c=c||"map";a.features.forEach(function(a){var e=a.geometry,l=e.type;e=e.coordinates;a=a.properties;var b;h=[];"map"===c||"mapbubble"===c?("Polygon"===l?(e.forEach(m),h.push(["Z"])):"MultiPolygon"===l&&(e.forEach(function(a){a.forEach(m)}),h.push(["Z"])),h.length&&(b={path:h})):"mapline"===c?("LineString"===l?m(e):"MultiLineString"===l&&e.forEach(m),
h.length&&(b={path:h})):"mappoint"===c&&"Point"===l&&(b={x:e[0],y:-e[1]});b&&f.push(r(b,{name:a.name||a.NAME,properties:a}))});e&&a.copyrightShort&&(e.chart.mapCredits=E(e.chart.options.credits.mapText,{geojson:a}),e.chart.mapCreditsFull=E(e.chart.options.credits.mapTextFull,{geojson:a}));return f};p(a.prototype,"addCredits",function(a,c){c=u(!0,this.options.credits,c);this.mapCredits&&(c.href=null);a.call(this,c);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});
r(a,"masters/modules/map.src.js",[],function(){})});
//# sourceMappingURL=map.js.map