/*
 Highcharts JS v8.2.2 (2020-11-05)

 Old IE (v6, v7, v8) module for Highcharts v6+.

 (c) 2010-2019 Highsoft AS
 Author: Torstein Honsi

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/oldie",["highcharts"],function(y){b(y);b.Highcharts=y;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function y(b,D,r,t){b.hasOwnProperty(D)||(b[D]=t.apply(null,r))}b=b?b._modules:{};y(b,"Extensions/Math3D.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,D){function w(b,m,g){m=0<g&&g<Number.POSITIVE_INFINITY?
g/(b.z+m.z+g):1;return{x:b.x*m,y:b.y*m}}function t(b,m,n,k){var l=m.options.chart.options3d,C=g(k,n?m.inverted:!1),u={x:m.plotWidth/2,y:m.plotHeight/2,z:l.depth/2,vd:g(l.depth,1)*g(l.viewDistance,0)},t=m.scale3d||1;k=S*l.beta*(C?-1:1);l=S*l.alpha*(C?-1:1);var r=Math.cos(l),B=Math.cos(-k),D=Math.sin(l),G=Math.sin(-k);n||(u.x+=m.plotLeft,u.y+=m.plotTop);return b.map(function(b){var m=(C?b.y:b.x)-u.x;var g=(C?b.x:b.y)-u.y;b=(b.z||0)-u.z;m={x:B*m-G*b,y:-D*G*m+r*g-B*D*b,z:r*G*m+D*g+r*B*b};g=w(m,u,u.vd);
g.x=g.x*t+u.x;g.y=g.y*t+u.y;g.z=m.z*t+u.z;return{x:C?g.y:g.x,y:C?g.x:g.y,z:g.z}})}function n(b,m){var k=m.options.chart.options3d,n=m.plotWidth/2;m=m.plotHeight/2;k=g(k.depth,1)*g(k.viewDistance,0)+k.depth;return Math.sqrt(Math.pow(n-g(b.plotX,b.x),2)+Math.pow(m-g(b.plotY,b.y),2)+Math.pow(k-g(b.plotZ,b.z),2))}function k(b){var g=0,k;for(k=0;k<b.length;k++){var n=(k+1)%b.length;g+=b[k].x*b[n].y-b[n].x*b[k].y}return g/2}function l(b,g,n){return k(t(b,g,n))}var g=D.pick,S=b.deg2rad;b.perspective3D=w;
b.perspective=t;b.pointCameraDistance=n;b.shapeArea=k;b.shapeArea3d=l;return{perspective:t,perspective3D:w,pointCameraDistance:n,shapeArea:k,shapeArea3D:l}});y(b,"Core/Renderer/SVG/SVGRenderer3D.js",[b["Core/Animation/AnimationUtilities.js"],b["Core/Color/Color.js"],b["Core/Globals.js"],b["Extensions/Math3D.js"],b["Core/Renderer/SVG/SVGElement.js"],b["Core/Renderer/SVG/SVGRenderer.js"],b["Core/Utilities.js"]],function(b,D,r,t,n,k,l){function g(f,b,c,e,z,a,d,h){var p=[],q=a-z;return a>z&&a-z>Math.PI/
2+.0001?(p=p.concat(g(f,b,c,e,z,z+Math.PI/2,d,h)),p=p.concat(g(f,b,c,e,z+Math.PI/2,a,d,h))):a<z&&z-a>Math.PI/2+.0001?(p=p.concat(g(f,b,c,e,z,z-Math.PI/2,d,h)),p=p.concat(g(f,b,c,e,z-Math.PI/2,a,d,h))):[["C",f+c*Math.cos(z)-c*P*q*Math.sin(z)+d,b+e*Math.sin(z)+e*P*q*Math.cos(z)+h,f+c*Math.cos(a)+c*P*q*Math.sin(a)+d,b+e*Math.sin(a)-e*P*q*Math.cos(a)+h,f+c*Math.cos(a)+d,b+e*Math.sin(a)+h]]}var w=b.animObject,C=D.parse,m=t.perspective,u=t.shapeArea,B=l.defined,y=l.extend,J=l.merge,N=l.objectEach,F=l.pick,
L=Math.cos,I=Math.PI,H=Math.sin,G=r.charts,Q=r.deg2rad;var P=4*(Math.sqrt(2)-1)/3/(I/2);k.prototype.toLinePath=function(f,b){var c=[];f.forEach(function(e){c.push(["L",e.x,e.y])});f.length&&(c[0][0]="M",b&&c.push(["Z"]));return c};k.prototype.toLineSegments=function(b){var f=[],c=!0;b.forEach(function(e){f.push(c?["M",e.x,e.y]:["L",e.x,e.y]);c=!c});return f};k.prototype.face3d=function(b){var f=this,c=this.createElement("path");c.vertexes=[];c.insidePlotArea=!1;c.enabled=!0;c.attr=function(c){if("object"===
typeof c&&(B(c.enabled)||B(c.vertexes)||B(c.insidePlotArea))){this.enabled=F(c.enabled,this.enabled);this.vertexes=F(c.vertexes,this.vertexes);this.insidePlotArea=F(c.insidePlotArea,this.insidePlotArea);delete c.enabled;delete c.vertexes;delete c.insidePlotArea;var e=m(this.vertexes,G[f.chartIndex],this.insidePlotArea),a=f.toLinePath(e,!0);e=u(e);e=this.enabled&&0<e?"visible":"hidden";c.d=a;c.visibility=e}return n.prototype.attr.apply(this,arguments)};c.animate=function(c){if("object"===typeof c&&
(B(c.enabled)||B(c.vertexes)||B(c.insidePlotArea))){this.enabled=F(c.enabled,this.enabled);this.vertexes=F(c.vertexes,this.vertexes);this.insidePlotArea=F(c.insidePlotArea,this.insidePlotArea);delete c.enabled;delete c.vertexes;delete c.insidePlotArea;var e=m(this.vertexes,G[f.chartIndex],this.insidePlotArea),a=f.toLinePath(e,!0);e=u(e);e=this.enabled&&0<e?"visible":"hidden";c.d=a;this.attr("visibility",e)}return n.prototype.animate.apply(this,arguments)};return c.attr(b)};k.prototype.polyhedron=
function(b){var f=this,c=this.g(),e=c.destroy;this.styledMode||c.attr({"stroke-linejoin":"round"});c.faces=[];c.destroy=function(){for(var b=0;b<c.faces.length;b++)c.faces[b].destroy();return e.call(this)};c.attr=function(e,a,d,h){if("object"===typeof e&&B(e.faces)){for(;c.faces.length>e.faces.length;)c.faces.pop().destroy();for(;c.faces.length<e.faces.length;)c.faces.push(f.face3d().add(c));for(var p=0;p<e.faces.length;p++)f.styledMode&&delete e.faces[p].fill,c.faces[p].attr(e.faces[p],null,d,h);
delete e.faces}return n.prototype.attr.apply(this,arguments)};c.animate=function(e,a,d){if(e&&e.faces){for(;c.faces.length>e.faces.length;)c.faces.pop().destroy();for(;c.faces.length<e.faces.length;)c.faces.push(f.face3d().add(c));for(var h=0;h<e.faces.length;h++)c.faces[h].animate(e.faces[h],a,d);delete e.faces}return n.prototype.animate.apply(this,arguments)};return c.attr(b)};b={initArgs:function(b){var f=this,c=f.renderer,e=c[f.pathType+"Path"](b),g=e.zIndexes;f.parts.forEach(function(a){f[a]=
c.path(e[a]).attr({"class":"highcharts-3d-"+a,zIndex:g[a]||0}).add(f)});f.attr({"stroke-linejoin":"round",zIndex:g.group});f.originalDestroy=f.destroy;f.destroy=f.destroyParts;f.forcedSides=e.forcedSides},singleSetterForParts:function(f,b,c,e,g,a){var d={};e=[null,null,e||"attr",g,a];var h=c&&c.zIndexes;c?(h&&h.group&&this.attr({zIndex:h.group}),N(c,function(a,e){d[e]={};d[e][f]=a;h&&(d[e].zIndex=c.zIndexes[e]||0)}),e[1]=d):(d[f]=b,e[0]=d);return this.processParts.apply(this,e)},processParts:function(f,
b,c,e,g){var a=this;a.parts.forEach(function(d){b&&(f=F(b[d],!1));if(!1!==f)a[d][c](f,e,g)});return a},destroyParts:function(){this.processParts(null,null,"destroy");return this.originalDestroy()}};var R=J(b,{parts:["front","top","side"],pathType:"cuboid",attr:function(b,g,c,e){if("string"===typeof b&&"undefined"!==typeof g){var f=b;b={};b[f]=g}return b.shapeArgs||B(b.x)?this.singleSetterForParts("d",null,this.renderer[this.pathType+"Path"](b.shapeArgs||b)):n.prototype.attr.call(this,b,void 0,c,e)},
animate:function(b,g,c){if(B(b.x)&&B(b.y)){b=this.renderer[this.pathType+"Path"](b);var e=b.forcedSides;this.singleSetterForParts("d",null,b,"animate",g,c);this.attr({zIndex:b.zIndexes.group});e!==this.forcedSides&&(this.forcedSides=e,R.fillSetter.call(this,this.fill))}else n.prototype.animate.call(this,b,g,c);return this},fillSetter:function(b){this.forcedSides=this.forcedSides||[];this.singleSetterForParts("fill",null,{front:b,top:C(b).brighten(0<=this.forcedSides.indexOf("top")?0:.1).get(),side:C(b).brighten(0<=
this.forcedSides.indexOf("side")?0:-.1).get()});this.color=this.fill=b;return this}});k.prototype.elements3d={base:b,cuboid:R};k.prototype.element3d=function(b,g){var c=this.g();y(c,this.elements3d[b]);c.initArgs(g);return c};k.prototype.cuboid=function(b){return this.element3d("cuboid",b)};k.prototype.cuboidPath=function(b){function g(a){return 0===d&&1<a&&6>a?{x:A[a].x,y:A[a].y+10,z:A[a].z}:A[0].x===A[7].x&&4<=a?{x:A[a].x+10,y:A[a].y,z:A[a].z}:0===p&&2>a||5<a?{x:A[a].x,y:A[a].y,z:A[a].z+10}:A[a]}
function c(a){return A[a]}var e=b.x,f=b.y,a=b.z||0,d=b.height,h=b.width,p=b.depth,q=G[this.chartIndex],x=q.options.chart.options3d.alpha,k=0,A=[{x:e,y:f,z:a},{x:e+h,y:f,z:a},{x:e+h,y:f+d,z:a},{x:e,y:f+d,z:a},{x:e,y:f+d,z:a+p},{x:e+h,y:f+d,z:a+p},{x:e+h,y:f,z:a+p},{x:e,y:f,z:a+p}],n=[];A=m(A,q,b.insidePlotArea);var v=function(a,d,h){var b=[[],-1],e=a.map(c),p=d.map(c);a=a.map(g);d=d.map(g);0>u(e)?b=[e,0]:0>u(p)?b=[p,1]:h&&(n.push(h),b=0>u(a)?[e,0]:0>u(d)?[p,1]:[e,0]);return b};var M=v([3,2,1,0],[7,
6,5,4],"front");b=M[0];var l=M[1];M=v([1,6,7,0],[4,5,2,3],"top");h=M[0];var E=M[1];M=v([1,2,5,6],[0,7,4,3],"side");v=M[0];M=M[1];1===M?k+=1E6*(q.plotWidth-e):M||(k+=1E6*e);k+=10*(!E||0<=x&&180>=x||360>x&&357.5<x?q.plotHeight-f:10+f);1===l?k+=100*a:l||(k+=100*(1E3-a));return{front:this.toLinePath(b,!0),top:this.toLinePath(h,!0),side:this.toLinePath(v,!0),zIndexes:{group:Math.round(k)},forcedSides:n,isFront:l,isTop:E}};k.prototype.arc3d=function(b){function g(a){var d=!1,h={},c;a=J(a);for(c in a)-1!==
f.indexOf(c)&&(h[c]=a[c],delete a[c],d=!0);return d?[h,a]:!1}var c=this.g(),e=c.renderer,f="x y r innerR start end depth".split(" ");b=J(b);b.alpha=(b.alpha||0)*Q;b.beta=(b.beta||0)*Q;c.top=e.path();c.side1=e.path();c.side2=e.path();c.inn=e.path();c.out=e.path();c.onAdd=function(){var a=c.parentGroup,d=c.attr("class");c.top.add(c);["out","inn","side1","side2"].forEach(function(h){c[h].attr({"class":d+" highcharts-3d-side"}).add(a)})};["addClass","removeClass"].forEach(function(a){c[a]=function(){var d=
arguments;["top","out","inn","side1","side2"].forEach(function(h){c[h][a].apply(c[h],d)})}});c.setPaths=function(a){var d=c.renderer.arc3dPath(a),h=100*d.zTop;c.attribs=a;c.top.attr({d:d.top,zIndex:d.zTop});c.inn.attr({d:d.inn,zIndex:d.zInn});c.out.attr({d:d.out,zIndex:d.zOut});c.side1.attr({d:d.side1,zIndex:d.zSide1});c.side2.attr({d:d.side2,zIndex:d.zSide2});c.zIndex=h;c.attr({zIndex:h});a.center&&(c.top.setRadialReference(a.center),delete a.center)};c.setPaths(b);c.fillSetter=function(a){var d=
C(a).brighten(-.1).get();this.fill=a;this.side1.attr({fill:d});this.side2.attr({fill:d});this.inn.attr({fill:d});this.out.attr({fill:d});this.top.attr({fill:a});return this};["opacity","translateX","translateY","visibility"].forEach(function(a){c[a+"Setter"]=function(a,h){c[h]=a;["out","inn","side1","side2","top"].forEach(function(d){c[d].attr(h,a)})}});c.attr=function(a){var d;if("object"===typeof a&&(d=g(a))){var h=d[0];arguments[0]=d[1];y(c.attribs,h);c.setPaths(c.attribs)}return n.prototype.attr.apply(c,
arguments)};c.animate=function(a,d,h){var b=this.attribs,e="data-"+Math.random().toString(26).substring(2,9);delete a.center;delete a.z;delete a.alpha;delete a.beta;var f=w(F(d,this.renderer.globalAnimation));if(f.duration){d=g(a);c[e]=0;a[e]=1;c[e+"Setter"]=r.noop;if(d){var k=d[0];f.step=function(a,d){function h(a){return b[a]+(F(k[a],b[a])-b[a])*d.pos}d.prop===e&&d.elem.setPaths(J(b,{x:h("x"),y:h("y"),r:h("r"),innerR:h("innerR"),start:h("start"),end:h("end"),depth:h("depth")}))}}d=f}return n.prototype.animate.call(this,
a,d,h)};c.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();return n.prototype.destroy.call(this)};c.hide=function(){this.top.hide();this.out.hide();this.inn.hide();this.side1.hide();this.side2.hide()};c.show=function(a){this.top.show(a);this.out.show(a);this.inn.show(a);this.side1.show(a);this.side2.show(a)};return c};k.prototype.arc3dPath=function(b){function k(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var c=b.x,e=b.y,
f=b.start,a=b.end-.00001,d=b.r,h=b.innerR||0,p=b.depth||0,q=b.alpha,x=b.beta,n=Math.cos(f),A=Math.sin(f);b=Math.cos(a);var m=Math.sin(a),v=d*Math.cos(x);d*=Math.cos(q);var l=h*Math.cos(x),K=h*Math.cos(q);h=p*Math.sin(x);var E=p*Math.sin(q);p=[["M",c+v*n,e+d*A]];p=p.concat(g(c,e,v,d,f,a,0,0));p.push(["L",c+l*b,e+K*m]);p=p.concat(g(c,e,l,K,a,f,0,0));p.push(["Z"]);var w=0<x?Math.PI/2:0;x=0<q?0:Math.PI/2;w=f>-w?f:a>-w?-w:f;var t=a<I-x?a:f<I-x?I-x:a,r=2*I-x;q=[["M",c+v*L(w),e+d*H(w)]];q=q.concat(g(c,e,
v,d,w,t,0,0));a>r&&f<r?(q.push(["L",c+v*L(t)+h,e+d*H(t)+E]),q=q.concat(g(c,e,v,d,t,r,h,E)),q.push(["L",c+v*L(r),e+d*H(r)]),q=q.concat(g(c,e,v,d,r,a,0,0)),q.push(["L",c+v*L(a)+h,e+d*H(a)+E]),q=q.concat(g(c,e,v,d,a,r,h,E)),q.push(["L",c+v*L(r),e+d*H(r)]),q=q.concat(g(c,e,v,d,r,t,0,0))):a>I-x&&f<I-x&&(q.push(["L",c+v*Math.cos(t)+h,e+d*Math.sin(t)+E]),q=q.concat(g(c,e,v,d,t,a,h,E)),q.push(["L",c+v*Math.cos(a),e+d*Math.sin(a)]),q=q.concat(g(c,e,v,d,a,t,0,0)));q.push(["L",c+v*Math.cos(t)+h,e+d*Math.sin(t)+
E]);q=q.concat(g(c,e,v,d,t,w,h,E));q.push(["Z"]);x=[["M",c+l*n,e+K*A]];x=x.concat(g(c,e,l,K,f,a,0,0));x.push(["L",c+l*Math.cos(a)+h,e+K*Math.sin(a)+E]);x=x.concat(g(c,e,l,K,a,f,h,E));x.push(["Z"]);n=[["M",c+v*n,e+d*A],["L",c+v*n+h,e+d*A+E],["L",c+l*n+h,e+K*A+E],["L",c+l*n,e+K*A],["Z"]];c=[["M",c+v*b,e+d*m],["L",c+v*b+h,e+d*m+E],["L",c+l*b+h,e+K*m+E],["L",c+l*b,e+K*m],["Z"]];m=Math.atan2(E,-h);e=Math.abs(a+m);b=Math.abs(f+m);f=Math.abs((f+a)/2+m);e=k(e);b=k(b);f=k(f);f*=1E5;a=1E5*b;e*=1E5;return{top:p,
zTop:1E5*Math.PI+1,out:q,zOut:Math.max(f,a,e),inn:x,zInn:Math.max(f,a,e),side1:n,zSide1:.99*e,side2:c,zSide2:.99*a}};return k});y(b,"Extensions/Oldie/VMLAxis3D.js",[b["Core/Utilities.js"]],function(b){var w=b.addEvent,r=function(){return function(b){this.axis=b}}();return function(){function b(){}b.compose=function(n){n.keepProps.push("vml");w(n,"init",b.onInit);w(n,"render",b.onRender)};b.onInit=function(){this.vml||(this.vml=new r(this))};b.onRender=function(){var b=this.vml;b.sideFrame&&(b.sideFrame.css({zIndex:0}),
b.sideFrame.front.attr({fill:b.sideFrame.color}));b.bottomFrame&&(b.bottomFrame.css({zIndex:1}),b.bottomFrame.front.attr({fill:b.bottomFrame.color}));b.backFrame&&(b.backFrame.css({zIndex:0}),b.backFrame.front.attr({fill:b.backFrame.color}))};return b}()});y(b,"Extensions/Oldie/VMLRenderer3D.js",[b["Core/Axis/Axis.js"],b["Core/Utilities.js"],b["Extensions/Oldie/VMLAxis3D.js"]],function(b,D,r){var w=D.setOptions;return function(){function n(){}n.compose=function(k,l){var g=l.prototype;k=k.prototype;
w({animate:!1});k.face3d=g.face3d;k.polyhedron=g.polyhedron;k.elements3d=g.elements3d;k.element3d=g.element3d;k.cuboid=g.cuboid;k.cuboidPath=g.cuboidPath;k.toLinePath=g.toLinePath;k.toLineSegments=g.toLineSegments;k.arc3d=function(b){b=g.arc3d.call(this,b);b.css({zIndex:b.zIndex});return b};k.arc3dPath=g.arc3dPath;r.compose(b)};return n}()});y(b,"Extensions/Oldie/Oldie.js",[b["Core/Chart/Chart.js"],b["Core/Color/Color.js"],b["Core/Globals.js"],b["Core/Pointer.js"],b["Core/Renderer/SVG/SVGElement.js"],
b["Core/Renderer/SVG/SVGRenderer3D.js"],b["Core/Utilities.js"],b["Extensions/Oldie/VMLRenderer3D.js"]],function(b,D,r,t,n,k,l,g){var w=D.parse,C=r.deg2rad,m=r.doc,u=r.noop,B=r.svg,y=r.win,J=l.addEvent,N=l.createElement,F=l.css,L=l.defined,I=l.discardElement,H=l.erase,G=l.extend;D=l.extendClass;var Q=l.getOptions,P=l.isArray,R=l.isNumber,f=l.isObject,T=l.offset,c=l.pick,e=l.pInt,z=l.uniqueKey;Q().global.VMLRadialGradientURL="http://code.highcharts.com/8.2.2/gfx/vml-radial-gradient.png";m&&!m.defaultView&&
(r.getStyle=l.getStyle=function(a,d){var b={width:"clientWidth",height:"clientHeight"}[d];if(a.style[d])return e(a.style[d]);"opacity"===d&&(d="filter");if(b)return a.style.zoom=1,Math.max(a[b]-2*l.getStyle(a,"padding"),0);a=a.currentStyle[d.replace(/\-(\w)/g,function(a,d){return d.toUpperCase()})];"filter"===d&&(a=a.replace(/alpha\(opacity=([0-9]+)\)/,function(a,d){return d/100}));return""===a?1:e(a)});B||(J(n,"afterInit",function(){"text"===this.element.nodeName&&this.css({position:"absolute"})}),
t.prototype.normalize=function(a,d){a=a||y.event;a.target||(a.target=a.srcElement);d||(this.chartPosition=d=T(this.chart.container));return G(a,{chartX:Math.round(Math.max(a.x,a.clientX-d.left)),chartY:Math.round(a.y)})},b.prototype.ieSanitizeSVG=function(a){return a=a.replace(/<IMG /g,"<image ").replace(/<(\/?)TITLE>/g,"<$1title>").replace(/height=([^" ]+)/g,'height="$1"').replace(/width=([^" ]+)/g,'width="$1"').replace(/hc-svg-href="([^"]+)">/g,'xlink:href="$1"/>').replace(/ id=([^" >]+)/g,' id="$1"').replace(/class=([^" >]+)/g,
'class="$1"').replace(/ transform /g," ").replace(/:(path|rect)/g,"$1").replace(/style="([^"]+)"/g,function(a){return a.toLowerCase()})},b.prototype.isReadyToRender=function(){var a=this;return B||y!=y.top||"complete"===m.readyState?!0:(m.attachEvent("onreadystatechange",function(){m.detachEvent("onreadystatechange",a.firstRender);"complete"===m.readyState&&a.firstRender()}),!1)},m.createElementNS||(m.createElementNS=function(a,d){return m.createElement(d)}),r.addEventListenerPolyfill=function(a,
d){function b(a){a.target=a.srcElement||y;d.call(c,a)}var c=this;c.attachEvent&&(c.hcEventsIE||(c.hcEventsIE={}),d.hcKey||(d.hcKey=z()),c.hcEventsIE[d.hcKey]=b,c.attachEvent("on"+a,b))},r.removeEventListenerPolyfill=function(a,d){this.detachEvent&&(d=this.hcEventsIE[d.hcKey],this.detachEvent("on"+a,d))},b={docMode8:m&&8===m.documentMode,init:function(a,d){var b=["<",d,' filled="f" stroked="f"'],c=["position: ","absolute",";"],e="div"===d;("shape"===d||e)&&c.push("left:0;top:0;width:1px;height:1px;");
c.push("visibility: ",e?"hidden":"visible");b.push(' style="',c.join(""),'"/>');d&&(b=e||"span"===d||"img"===d?b.join(""):a.prepVML(b),this.element=N(b));this.renderer=a},add:function(a){var d=this.renderer,b=this.element,c=d.box,e=a&&a.inverted;c=a?a.element||a:c;a&&(this.parentGroup=a);e&&d.invertChild(b,c);c.appendChild(b);this.added=!0;this.alignOnAdd&&!this.deferUpdateTransform&&this.updateTransform();if(this.onAdd)this.onAdd();this.className&&this.attr("class",this.className);return this},updateTransform:n.prototype.htmlUpdateTransform,
setSpanRotation:function(){var a=this.rotation,d=Math.cos(a*C),b=Math.sin(a*C);F(this.element,{filter:a?["progid:DXImageTransform.Microsoft.Matrix(M11=",d,", M12=",-b,", M21=",b,", M22=",d,", sizingMethod='auto expand')"].join(""):"none"})},getSpanCorrection:function(a,d,b,e,f){var h=e?Math.cos(e*C):1,p=e?Math.sin(e*C):0,g=c(this.elemHeight,this.element.offsetHeight);this.xCorr=0>h&&-a;this.yCorr=0>p&&-g;var q=0>h*p;this.xCorr+=p*d*(q?1-b:b);this.yCorr-=h*d*(e?q?b:1-b:1);f&&"left"!==f&&(this.xCorr-=
a*b*(0>h?-1:1),e&&(this.yCorr-=g*b*(0>p?-1:1)),F(this.element,{textAlign:f}))},pathToVML:function(a){for(var d=a.length,b=[];d--;)R(a[d])?b[d]=Math.round(10*a[d])-5:"Z"===a[d]?b[d]="x":(b[d]=a[d],!a.isArc||"wa"!==a[d]&&"at"!==a[d]||(b[d+5]===b[d+7]&&(b[d+7]+=a[d+7]>a[d+5]?1:-1),b[d+6]===b[d+8]&&(b[d+8]+=a[d+8]>a[d+6]?1:-1)));return b.join(" ")||"x"},clip:function(a){var b=this;if(a){var c=a.members;H(c,b);c.push(b);b.destroyClip=function(){H(c,b)};a=a.getCSS(b)}else b.destroyClip&&b.destroyClip(),
a={clip:b.docMode8?"inherit":"rect(auto)"};return b.css(a)},css:n.prototype.htmlCss,safeRemoveChild:function(a){a.parentNode&&I(a)},destroy:function(){this.destroyClip&&this.destroyClip();return n.prototype.destroy.apply(this)},on:function(a,b){this.element["on"+a]=function(){var a=y.event;a.target=a.srcElement;b(a)};return this},cutOffPath:function(a,b){a=a.split(/[ ,]/);var d=a.length;if(9===d||11===d)a[d-4]=a[d-2]=e(a[d-2])-10*b;return a.join(" ")},shadow:function(a,b,h){var d=[],f,g=this.element,
k=this.renderer,m=g.style,l=g.path;l&&"string"!==typeof l.value&&(l="x");var n=l;if(a){var r=c(a.width,3);var K=(a.opacity||.15)/r;for(f=1;3>=f;f++){var t=2*r+1-2*f;h&&(n=this.cutOffPath(l.value,t+.5));var w=['<shape isShadow="true" strokeweight="',t,'" filled="false" path="',n,'" coordsize="10 10" style="',g.style.cssText,'" />'];var u=N(k.prepVML(w),null,{left:e(m.left)+c(a.offsetX,1),top:e(m.top)+c(a.offsetY,1)});h&&(u.cutOff=t+1);w=['<stroke color="',a.color||"#000000",'" opacity="',K*f,'"/>'];
N(k.prepVML(w),null,null,u);b?b.element.appendChild(u):g.parentNode.insertBefore(u,g);d.push(u)}this.shadows=d}return this},updateShadows:u,setAttr:function(a,b){this.docMode8?this.element[a]=b:this.element.setAttribute(a,b)},getAttr:function(a){return this.docMode8?this.element[a]:this.element.getAttribute(a)},classSetter:function(a){(this.added?this.element:this).className=a},dashstyleSetter:function(a,b,c){(c.getElementsByTagName("stroke")[0]||N(this.renderer.prepVML(["<stroke/>"]),null,null,c))[b]=
a||"solid";this[b]=a},dSetter:function(a,b,c){var d=this.shadows;a=a||[];this.d=a.join&&a.join(" ");c.path=a=this.pathToVML(a);if(d)for(c=d.length;c--;)d[c].path=d[c].cutOff?this.cutOffPath(a,d[c].cutOff):a;this.setAttr(b,a)},fillSetter:function(a,b,c){var d=c.nodeName;"SPAN"===d?c.style.color=a:"IMG"!==d&&(c.filled="none"!==a,this.setAttr("fillcolor",this.renderer.color(a,c,b,this)))},"fill-opacitySetter":function(a,b,c){N(this.renderer.prepVML(["<",b.split("-")[0],' opacity="',a,'"/>']),null,null,
c)},opacitySetter:u,rotationSetter:function(a,b,c){c=c.style;this[b]=c[b]=a;c.left=-Math.round(Math.sin(a*C)+1)+"px";c.top=Math.round(Math.cos(a*C))+"px"},strokeSetter:function(a,b,c){this.setAttr("strokecolor",this.renderer.color(a,c,b,this))},"stroke-widthSetter":function(a,b,c){c.stroked=!!a;this[b]=a;R(a)&&(a+="px");this.setAttr("strokeweight",a)},titleSetter:function(a,b){this.setAttr(b,a)},visibilitySetter:function(a,b,c){"inherit"===a&&(a="visible");this.shadows&&this.shadows.forEach(function(d){d.style[b]=
a});"DIV"===c.nodeName&&(a="hidden"===a?"-999em":0,this.docMode8||(c.style[b]=a?"visible":"hidden"),b="top");c.style[b]=a},xSetter:function(a,b,c){this[b]=a;"x"===b?b="left":"y"===b&&(b="top");this.updateClipping?(this[b]=a,this.updateClipping()):c.style[b]=a},zIndexSetter:function(a,b,c){c.style[b]=a},fillGetter:function(){return this.getAttr("fillcolor")||""},strokeGetter:function(){return this.getAttr("strokecolor")||""},classGetter:function(){return this.getAttr("className")||""}},b["stroke-opacitySetter"]=
b["fill-opacitySetter"],r.VMLElement=b=D(n,b),b.prototype.ySetter=b.prototype.widthSetter=b.prototype.heightSetter=b.prototype.xSetter,t={Element:b,isIE8:-1<y.navigator.userAgent.indexOf("MSIE 8.0"),init:function(a,b,c){this.crispPolyLine=k.prototype.crispPolyLine;this.alignedObjects=[];var d=this.createElement("div").css({position:"relative"});var e=d.element;a.appendChild(d.element);this.isVML=!0;this.box=e;this.boxWrapper=d;this.gradients={};this.cache={};this.cacheKeys=[];this.imgCount=0;this.setSize(b,
c,!1);if(!m.namespaces.hcv){m.namespaces.add("hcv","urn:schemas-microsoft-com:vml");try{m.createStyleSheet().cssText="hcv\\:fill, hcv\\:path, hcv\\:shape, hcv\\:stroke{ behavior:url(#default#VML); display: inline-block; } "}catch(x){m.styleSheets[0].cssText+="hcv\\:fill, hcv\\:path, hcv\\:shape, hcv\\:stroke{ behavior:url(#default#VML); display: inline-block; } "}}},isHidden:function(){return!this.box.offsetWidth},clipRect:function(a,b,c,e){var d=this.createElement(),h=f(a);return G(d,{members:[],
count:0,left:(h?a.x:a)+1,top:(h?a.y:b)+1,width:(h?a.width:c)-1,height:(h?a.height:e)-1,getCSS:function(a){var b=a.element,c=b.nodeName,d=a.inverted,e=this.top-("shape"===c?b.offsetTop:0),h=this.left;b=h+this.width;var f=e+this.height;e={clip:"rect("+Math.round(d?h:e)+"px,"+Math.round(d?f:b)+"px,"+Math.round(d?b:f)+"px,"+Math.round(d?e:h)+"px)"};!d&&a.docMode8&&"DIV"===c&&G(e,{width:b+"px",height:f+"px"});return e},updateClipping:function(){d.members.forEach(function(a){a.element&&a.css(d.getCSS(a))})}})},
color:function(a,b,c,e){var d=this,h=/^rgba/,f,g,k="none";a&&a.linearGradient?g="gradient":a&&a.radialGradient&&(g="pattern");if(g){var p,m,l=a.linearGradient||a.radialGradient,n,r,t,u,y="";a=a.stops;var B=[],C=function(){f=['<fill colors="'+B.join(",")+'" opacity="',r,'" o:opacity2="',n,'" type="',g,'" ',y,'focus="100%" method="any" />'];N(d.prepVML(f),null,null,b)};var z=a[0];var D=a[a.length-1];0<z[0]&&a.unshift([0,z[1]]);1>D[0]&&a.push([1,D[1]]);a.forEach(function(a,b){h.test(a[1])?(J=w(a[1]),
p=J.get("rgb"),m=J.get("a")):(p=a[1],m=1);B.push(100*a[0]+"% "+p);b?(r=m,t=p):(n=m,u=p)});if("fill"===c)if("gradient"===g)c=l.x1||l[0]||0,a=l.y1||l[1]||0,z=l.x2||l[2]||0,l=l.y2||l[3]||0,y='angle="'+(90-180*Math.atan((l-a)/(z-c))/Math.PI)+'"',C();else{k=l.r;var F=2*k,G=2*k,I=l.cx,L=l.cy,H=b.radialReference,O;k=function(){H&&(O=e.getBBox(),I+=(H[0]-O.x)/O.width-.5,L+=(H[1]-O.y)/O.height-.5,F*=H[2]/O.width,G*=H[2]/O.height);y='src="'+Q().global.VMLRadialGradientURL+'" size="'+F+","+G+'" origin="0.5,0.5" position="'+
I+","+L+'" color2="'+u+'" ';C()};e.added?k():e.onAdd=k;k=t}else k=p}else if(h.test(a)&&"IMG"!==b.tagName){var J=w(a);e[c+"-opacitySetter"](J.get("a"),c,b);k=J.get("rgb")}else k=b.getElementsByTagName(c),k.length&&(k[0].opacity=1,k[0].type="solid"),k=a;return k},prepVML:function(a){var b=this.isIE8;a=a.join("");b?(a=a.replace("/>",' xmlns="urn:schemas-microsoft-com:vml" />'),a=-1===a.indexOf('style="')?a.replace("/>",' style="display:inline-block;behavior:url(#default#VML);" />'):a.replace('style="',
'style="display:inline-block;behavior:url(#default#VML);')):a=a.replace("<","<hcv:");return a},text:k.prototype.html,path:function(a){var b={coordsize:"10 10"};P(a)?b.d=a:f(a)&&G(b,a);return this.createElement("shape").attr(b)},circle:function(a,b,c){var d=this.symbol("circle");f(a)&&(c=a.r,b=a.y,a=a.x);d.isCircle=!0;d.r=c;return d.attr({x:a,y:b})},g:function(a){var b;a&&(b={className:"highcharts-"+a,"class":"highcharts-"+a});return this.createElement("div").attr(b)},image:function(a,b,c,e,f){var d=
this.createElement("img").attr({src:a});1<arguments.length&&d.attr({x:b,y:c,width:e,height:f});return d},createElement:function(a){return"rect"===a?this.symbol(a):k.prototype.createElement.call(this,a)},invertChild:function(a,b){var c=this;b=b.style;var d="IMG"===a.tagName&&a.style;F(a,{flip:"x",left:e(b.width)-(d?e(d.top):1),top:e(b.height)-(d?e(d.left):1),rotation:-90});[].forEach.call(a.childNodes,function(b){c.invertChild(b,a)})},symbols:{arc:function(a,b,c,e,f){var d=f.start,h=f.end,g=f.r||c||
e;c=f.innerR;e=Math.cos(d);var k=Math.sin(d),l=Math.cos(h),m=Math.sin(h);if(0===h-d)return["x"];d=["wa",a-g,b-g,a+g,b+g,a+g*e,b+g*k,a+g*l,b+g*m];f.open&&!c&&d.push("e","M",a,b);d.push("at",a-c,b-c,a+c,b+c,a+c*l,b+c*m,a+c*e,b+c*k,"x","e");d.isArc=!0;return d},circle:function(a,b,c,e,f){f&&L(f.r)&&(c=e=2*f.r);f&&f.isCircle&&(a-=c/2,b-=e/2);return["wa",a,b,a+c,b+e,a+c,b+e/2,a+c,b+e/2,"e"]},rect:function(a,b,c,e,f){return k.prototype.symbols[L(f)&&f.r?"callout":"square"].call(0,a,b,c,e,f)}}},r.VMLRenderer=
b=function(){this.init.apply(this,arguments)},G(b.prototype,k.prototype),G(b.prototype,t),r.Renderer=b,g.compose(b,k));k.prototype.getSpanWidth=function(a,b){var c=a.getBBox(!0).width;!B&&this.forExport&&(c=this.measureSpanWidth(b.firstChild.data,a.styles));return c};k.prototype.measureSpanWidth=function(a,b){var c=m.createElement("span");a=m.createTextNode(a);c.appendChild(a);F(c,b);this.box.appendChild(c);b=c.offsetWidth;I(c);return b}});y(b,"masters/modules/oldie.src.js",[],function(){})});
//# sourceMappingURL=oldie.js.map