/*
 Highcharts JS v8.2.2 (2020-11-05)

 Sankey diagram module

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/sankey",["highcharts"],function(f){d(f);d.Highcharts=f;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function f(d,k,m,t){d.hasOwnProperty(k)||(d[k]=t.apply(null,m))}d=d?d._modules:{};f(d,"Mixins/Nodes.js",[d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Core/Series/Point.js"],d["Core/Utilities.js"]],function(d,
k,m,t){var y=t.defined,h=t.extend,f=t.find,r=t.pick;return d.NodesMixin={createNode:function(c){function b(a,b){return f(a,function(a){return a.id===b})}var a=b(this.nodes,c),d=this.pointClass;if(!a){var x=this.options.nodes&&b(this.options.nodes,c);a=(new d).init(this,h({className:"highcharts-node",isNode:!0,id:c,y:1},x));a.linksTo=[];a.linksFrom=[];a.formatPrefix="node";a.name=a.name||a.options.id||"";a.mass=r(a.options.mass,a.options.marker&&a.options.marker.radius,this.options.marker&&this.options.marker.radius,
4);a.getSum=function(){var b=0,c=0;a.linksTo.forEach(function(a){b+=a.weight});a.linksFrom.forEach(function(a){c+=a.weight});return Math.max(b,c)};a.offset=function(b,c){for(var d=0,w=0;w<a[c].length;w++){if(a[c][w]===b)return d;d+=a[c][w].weight}};a.hasShape=function(){var b=0;a.linksTo.forEach(function(a){a.outgoing&&b++});return!a.linksTo.length||b!==a.linksTo.length};this.nodes.push(a)}return a},generatePoints:function(){var c=this.chart,b={};k.prototype.generatePoints.call(this);this.nodes||
(this.nodes=[]);this.colorCounter=0;this.nodes.forEach(function(a){a.linksFrom.length=0;a.linksTo.length=0;a.level=a.options.level});this.points.forEach(function(a){y(a.from)&&(b[a.from]||(b[a.from]=this.createNode(a.from)),b[a.from].linksFrom.push(a),a.fromNode=b[a.from],c.styledMode?a.colorIndex=r(a.options.colorIndex,b[a.from].colorIndex):a.color=a.options.color||b[a.from].color);y(a.to)&&(b[a.to]||(b[a.to]=this.createNode(a.to)),b[a.to].linksTo.push(a),a.toNode=b[a.to]);a.name=a.name||a.id},this);
this.nodeLookup=b},setData:function(){this.nodes&&(this.nodes.forEach(function(c){c.destroy()}),this.nodes.length=0);k.prototype.setData.apply(this,arguments)},destroy:function(){this.data=[].concat(this.points||[],this.nodes);return k.prototype.destroy.apply(this,arguments)},setNodeState:function(c){var b=arguments,a=this.isNode?this.linksTo.concat(this.linksFrom):[this.fromNode,this.toNode];"select"!==c&&a.forEach(function(a){a&&a.series&&(m.prototype.setState.apply(a,b),a.isNode||(a.fromNode.graphic&&
m.prototype.setState.apply(a.fromNode,b),a.toNode&&a.toNode.graphic&&m.prototype.setState.apply(a.toNode,b)))});m.prototype.setState.apply(this,b)}}});f(d,"Mixins/TreeSeries.js",[d["Core/Color/Color.js"],d["Core/Utilities.js"]],function(d,k){var m=k.extend,t=k.isArray,f=k.isNumber,h=k.isObject,z=k.merge,r=k.pick;return{getColor:function(c,b){var a=b.index,h=b.mapOptionsToLevel,x=b.parentColor,k=b.parentColorIndex,v=b.series,n=b.colors,m=b.siblings,e=v.points,l=v.chart.options.chart,p;if(c){e=e[c.i];
c=h[c.level]||{};if(h=e&&c.colorByPoint){var E=e.index%(n?n.length:l.colorCount);var A=n&&n[E]}if(!v.chart.styledMode){n=e&&e.options.color;l=c&&c.color;if(p=x)p=(p=c&&c.colorVariation)&&"brightness"===p.key?d.parse(x).brighten(a/m*p.to).get():x;p=r(n,l,A,p,v.color)}var M=r(e&&e.options.colorIndex,c&&c.colorIndex,E,k,b.colorIndex)}return{color:p,colorIndex:M}},getLevelOptions:function(c){var b=null;if(h(c)){b={};var a=f(c.from)?c.from:1;var d=c.levels;var k={};var r=h(c.defaults)?c.defaults:{};t(d)&&
(k=d.reduce(function(b,c){if(h(c)&&f(c.level)){var d=z({},c);var e="boolean"===typeof d.levelIsConstant?d.levelIsConstant:r.levelIsConstant;delete d.levelIsConstant;delete d.level;c=c.level+(e?0:a-1);h(b[c])?m(b[c],d):b[c]=d}return b},{}));d=f(c.to)?c.to:1;for(c=0;c<=d;c++)b[c]=z({},r,h(k[c])?k[c]:{})}return b},setTreeValues:function w(b,a){var d=a.before,k=a.idRoot,h=a.mapIdToNode[k],n=a.points[b.i],f=n&&n.options||{},e=0,l=[];m(b,{levelDynamic:b.level-(("boolean"===typeof a.levelIsConstant?a.levelIsConstant:
1)?0:h.level),name:r(n&&n.name,""),visible:k===b.id||("boolean"===typeof a.visible?a.visible:!1)});"function"===typeof d&&(b=d(b,a));b.children.forEach(function(p,d){var A=m({},a);m(A,{index:d,siblings:b.children.length,visible:b.visible});p=w(p,A);l.push(p);p.visible&&(e+=p.val)});b.visible=0<e||b.visible;d=r(f.value,e);m(b,{children:l,childrenTotal:e,isLeaf:b.visible&&!e,val:d});return b},updateRootId:function(b){if(h(b)){var a=h(b.options)?b.options:{};a=r(b.rootNode,a.rootId,"");h(b.userOptions)&&
(b.userOptions.rootId=a);b.rootNode=a}return a}}});f(d,"Series/SankeySeries.js",[d["Core/Series/Series.js"],d["Core/Color/Color.js"],d["Series/Column/ColumnSeries.js"],d["Core/Globals.js"],d["Series/Line/LineSeries.js"],d["Mixins/Nodes.js"],d["Core/Series/Point.js"],d["Mixins/TreeSeries.js"],d["Core/Utilities.js"]],function(d,k,m,f,y,h,z,r,c){var b=r.getLevelOptions,a=c.defined,t=c.find,x=c.isObject,K=c.merge,v=c.pick,n=c.relativeLength,L=c.stableSort;"";d.seriesType("sankey","column",{borderWidth:0,
colorByPoint:!0,curveFactor:.33,dataLabels:{enabled:!0,backgroundColor:"none",crop:!1,nodeFormat:void 0,nodeFormatter:function(){return this.point.name},format:void 0,formatter:function(){},inside:!0},inactiveOtherPoints:!0,linkOpacity:.5,minLinkWidth:0,nodeWidth:20,nodePadding:10,showInLegend:!1,states:{hover:{linkOpacity:1},inactive:{linkOpacity:.1,opacity:.1,animation:{duration:50}}},tooltip:{followPointer:!0,headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',pointFormat:"{point.fromNode.name} \u2192 {point.toNode.name}: <b>{point.weight}</b><br/>",
nodeFormat:"{point.name}: <b>{point.sum}</b><br/>"}},{isCartesian:!1,invertable:!0,forceDL:!0,orderNodes:!0,pointArrayMap:["from","to"],createNode:h.createNode,searchPoint:f.noop,setData:h.setData,destroy:h.destroy,getNodePadding:function(){var a=this.options.nodePadding||0;if(this.nodeColumns){var b=this.nodeColumns.reduce(function(a,e){return Math.max(a,e.length)},0);b*a>this.chart.plotSizeY&&(a=this.chart.plotSizeY/b)}return a},createNodeColumn:function(){var a=this,b=this.chart,d=[];d.sum=function(){return this.reduce(function(a,
e){return a+e.getSum()},0)};d.offset=function(e,b){for(var c=0,l,p=a.nodePadding,A=0;A<d.length;A++){l=d[A].getSum();var E=Math.max(l*b,a.options.minLinkWidth);l=l?E+p:0;if(d[A]===e)return{relativeTop:c+n(e.options.offset||0,l)};c+=l}};d.top=function(e){var d=a.nodePadding,c=this.reduce(function(b,c){0<b&&(b+=d);c=Math.max(c.getSum()*e,a.options.minLinkWidth);return b+c},0);return(b.plotSizeY-c)/2};return d},createNodeColumns:function(){var e=[];this.nodes.forEach(function(b){var d=-1,c;if(!a(b.options.column))if(0===
b.linksTo.length)b.column=0;else{for(c=0;c<b.linksTo.length;c++){var l=b.linksTo[0];if(l.fromNode.column>d){var p=l.fromNode;d=p.column}}b.column=d+1;p&&"hanging"===p.options.layout&&(b.hangsFrom=p,c=-1,t(p.linksFrom,function(a,e){(a=a.toNode===b)&&(c=e);return a}),b.column+=c)}e[b.column]||(e[b.column]=this.createNodeColumn());e[b.column].push(b)},this);for(var b=0;b<e.length;b++)"undefined"===typeof e[b]&&(e[b]=this.createNodeColumn());return e},hasData:function(){return!!this.processedXData.length},
pointAttribs:function(a,b){var e=this,d=e.mapOptionsToLevel[(a.isNode?a.level:a.fromNode.level)||0]||{},c=a.options,l=d.states&&d.states[b]||{};b=["colorByPoint","borderColor","borderWidth","linkOpacity"].reduce(function(a,b){a[b]=v(l[b],c[b],d[b],e.options[b]);return a},{});var g=v(l.color,c.color,b.colorByPoint?a.color:d.color);return a.isNode?{fill:g,stroke:b.borderColor,"stroke-width":b.borderWidth}:{fill:k.parse(g).setOpacity(b.linkOpacity).get()}},generatePoints:function(){function a(b,e){"undefined"===
typeof b.level&&(b.level=e,b.linksFrom.forEach(function(b){b.toNode&&a(b.toNode,e+1)}))}h.generatePoints.apply(this,arguments);this.orderNodes&&(this.nodes.filter(function(a){return 0===a.linksTo.length}).forEach(function(b){a(b,0)}),L(this.nodes,function(a,b){return a.level-b.level}))},translateNode:function(a,b){var d=this.translationFactor,c=this.chart,e=this.options,l=a.getSum(),g=Math.max(Math.round(l*d),this.options.minLinkWidth),q=Math.round(e.borderWidth)%2/2,u=b.offset(a,d);b=Math.floor(v(u.absoluteTop,
b.top(d)+u.relativeTop))+q;q=Math.floor(this.colDistance*a.column+e.borderWidth/2)+q;q=c.inverted?c.plotSizeX-q:q;d=Math.round(this.nodeWidth);(a.sum=l)?(a.shapeType="rect",a.nodeX=q,a.nodeY=b,a.shapeArgs=c.inverted?{x:q-d,y:c.plotSizeY-b-g,width:a.options.height||e.height||d,height:a.options.width||e.width||g}:{x:q,y:b,width:a.options.width||e.width||d,height:a.options.height||e.height||g},a.shapeArgs.display=a.hasShape()?"":"none",e=this.mapOptionsToLevel[a.level],l=a.options,l=x(l)?l.dataLabels:
{},e=x(e)?e.dataLabels:{},e=K({style:{}},e,l),a.dlOptions=e,a.plotY=1,a.tooltipPos=c.inverted?[c.plotSizeY-a.shapeArgs.y-a.shapeArgs.height/2,c.plotSizeX-a.shapeArgs.x-a.shapeArgs.width/2]:[a.shapeArgs.x+a.shapeArgs.width/2,a.shapeArgs.y+a.shapeArgs.height/2]):a.dlOptions={enabled:!1}},translateLink:function(a){var b=function(b,c){var d;c=b.offset(a,c)*k;return Math.min(b.nodeY+c,b.nodeY+(null===(d=b.shapeArgs)||void 0===d?void 0:d.height)-g)},d=a.fromNode,c=a.toNode,e=this.chart,k=this.translationFactor,
g=Math.max(a.weight*k,this.options.minLinkWidth),q=(e.inverted?-this.colDistance:this.colDistance)*this.options.curveFactor,u=b(d,"linksFrom");b=b(c,"linksTo");var h=d.nodeX,f=this.nodeWidth;c=c.column*this.colDistance;var m=a.outgoing,n=c>h+f;e.inverted&&(u=e.plotSizeY-u,b=(e.plotSizeY||0)-b,c=e.plotSizeX-c,f=-f,g=-g,n=h>c);a.shapeType="path";a.linkBase=[u,u+g,b,b+g];if(n&&"number"===typeof b)a.shapeArgs={d:[["M",h+f,u],["C",h+f+q,u,c-q,b,c,b],["L",c+(m?f:0),b+g/2],["L",c,b+g],["C",c-q,b+g,h+f+q,
u+g,h+f,u+g],["Z"]]};else if("number"===typeof b){q=c-20-g;m=c-20;n=c;var r=h+f,t=r+20,v=t+g,x=u,w=u+g,z=w+20,C=z+(e.plotHeight-u-g),B=C+20,y=B+g,F=b,D=F+g,G=D+20,H=B+.7*g,I=n-.7*g,J=r+.7*g;a.shapeArgs={d:[["M",r,x],["C",J,x,v,w-.7*g,v,z],["L",v,C],["C",v,H,J,y,r,y],["L",n,y],["C",I,y,q,H,q,C],["L",q,G],["C",q,D-.7*g,I,F,n,F],["L",n,D],["C",m,D,m,D,m,G],["L",m,C],["C",m,B,m,B,n,B],["L",r,B],["C",t,B,t,B,t,C],["L",t,z],["C",t,w,t,w,r,w],["Z"]]}}a.dlBox={x:h+(c-h+f)/2,y:u+(b-u)/2,height:g,width:0};
a.tooltipPos=e.inverted?[e.plotSizeY-a.dlBox.y-g/2,e.plotSizeX-a.dlBox.x]:[a.dlBox.x,a.dlBox.y+g/2];a.y=a.plotY=1;a.color||(a.color=d.color)},translate:function(){var a=this,c=function(b){for(var c=b.slice(),e=a.options.minLinkWidth||0,g,k=0,l,q=h.plotSizeY-f.borderWidth-(b.length-1)*d.nodePadding;b.length;){k=q/b.sum();g=!1;for(l=b.length;l--;)b[l].getSum()*k<e&&(b.splice(l,1),q-=e,g=!0);if(!g)break}b.length=0;c.forEach(function(a){return b.push(a)});return k};this.processedXData||this.processData();
this.generatePoints();this.nodeColumns=this.createNodeColumns();this.nodeWidth=n(this.options.nodeWidth,this.chart.plotSizeX);var d=this,h=this.chart,f=this.options,k=this.nodeWidth,g=this.nodeColumns;this.nodePadding=this.getNodePadding();this.translationFactor=g.reduce(function(a,b){return Math.min(a,c(b))},Infinity);this.colDistance=(h.plotSizeX-k-f.borderWidth)/Math.max(1,g.length-1);d.mapOptionsToLevel=b({from:1,levels:f.levels,to:g.length-1,defaults:{borderColor:f.borderColor,borderRadius:f.borderRadius,
borderWidth:f.borderWidth,color:d.color,colorByPoint:f.colorByPoint,levelIsConstant:!0,linkColor:f.linkColor,linkLineWidth:f.linkLineWidth,linkOpacity:f.linkOpacity,states:f.states}});g.forEach(function(a){a.forEach(function(b){d.translateNode(b,a)})},this);this.nodes.forEach(function(a){a.linksFrom.forEach(function(a){(a.weight||a.isNull)&&a.to&&(d.translateLink(a),a.allowShadow=!1)})})},render:function(){var a=this.points;this.points=this.points.concat(this.nodes||[]);m.prototype.render.call(this);
this.points=a},animate:y.prototype.animate},{applyOptions:function(b,c){z.prototype.applyOptions.call(this,b,c);a(this.options.level)&&(this.options.column=this.column=this.options.level);return this},setState:h.setNodeState,getClassName:function(){return(this.isNode?"highcharts-node ":"highcharts-link ")+z.prototype.getClassName.call(this)},isValid:function(){return this.isNode||"number"===typeof this.weight}});""});f(d,"masters/modules/sankey.src.js",[],function(){})});
//# sourceMappingURL=sankey.js.map