/*
 Highstock JS v8.2.2 (2020-11-05)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(H){c(H);c.Highcharts=H;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function H(c,C,E,B){c.hasOwnProperty(C)||(c[C]=B.apply(null,E))}c=c?c._modules:{};H(c,"Core/Axis/NavigatorAxis.js",[c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,C){var E=c.isTouchDevice,B=C.addEvent,v=C.correctFloat,
A=C.defined,y=C.isNumber,k=C.pick,b=function(){function b(b){this.axis=b}b.prototype.destroy=function(){this.axis=void 0};b.prototype.toFixedRange=function(b,r,u,p){var c=this.axis,f=c.chart;f=f&&f.fixedRange;var w=(c.pointRange||0)/2;b=k(u,c.translate(b,!0,!c.horiz));r=k(p,c.translate(r,!0,!c.horiz));c=f&&(r-b)/f;A(u)||(b=v(b+w));A(p)||(r=v(r-w));.7<c&&1.3>c&&(p?b=r-f:r=b+f);y(b)&&y(r)||(b=r=void 0);return{min:b,max:r}};return b}();return function(){function r(){}r.compose=function(r){r.keepProps.push("navigatorAxis");
B(r,"init",function(){this.navigatorAxis||(this.navigatorAxis=new b(this))});B(r,"zoom",function(b){var r=this.chart.options,p=r.navigator,c=this.navigatorAxis,f=r.chart.pinchType,w=r.rangeSelector;r=r.chart.zoomType;this.isXAxis&&(p&&p.enabled||w&&w.enabled)&&("y"===r?b.zoomed=!1:(!E&&"xy"===r||E&&"xy"===f)&&this.options.range&&(p=c.previousZoom,A(b.newMin)?c.previousZoom=[this.min,this.max]:p&&(b.newMin=p[0],b.newMax=p[1],c.previousZoom=void 0)));"undefined"!==typeof b.zoomed&&b.preventDefault()})};
r.AdditionsClass=b;return r}()});H(c,"Core/Axis/ScrollbarAxis.js",[c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,C){var E=C.addEvent,B=C.defined,v=C.pick;return function(){function A(){}A.compose=function(y,k){E(y,"afterInit",function(){var b=this;b.options&&b.options.scrollbar&&b.options.scrollbar.enabled&&(b.options.scrollbar.vertical=!b.horiz,b.options.startOnTick=b.options.endOnTick=!1,b.scrollbar=new k(b.chart.renderer,b.options.scrollbar,b.chart),E(b.scrollbar,"changed",function(r){var k=
v(b.options&&b.options.min,b.min),y=v(b.options&&b.options.max,b.max),u=B(b.dataMin)?Math.min(k,b.min,b.dataMin):k,p=(B(b.dataMax)?Math.max(y,b.max,b.dataMax):y)-u;B(k)&&B(y)&&(b.horiz&&!b.reversed||!b.horiz&&b.reversed?(k=u+p*this.to,u+=p*this.from):(k=u+p*(1-this.from),u+=p*(1-this.to)),v(this.options.liveRedraw,c.svg&&!c.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===r.DOMType||!B(r.DOMType)?b.setExtremes(u,k,!0,"mousemove"!==r.DOMType,r):this.setRange(this.from,this.to))}))});E(y,"afterRender",
function(){var b=Math.min(v(this.options.min,this.min),this.min,v(this.dataMin,this.min)),r=Math.max(v(this.options.max,this.max),this.max,v(this.dataMax,this.max)),c=this.scrollbar,k=this.axisTitleMargin+(this.titleOffset||0),u=this.chart.scrollbarsOffsets,p=this.options.margin||0;c&&(this.horiz?(this.opposite||(u[1]+=k),c.position(this.left,this.top+this.height+2+u[1]-(this.opposite?p:0),this.width,this.height),this.opposite||(u[1]+=p),k=1):(this.opposite&&(u[0]+=k),c.position(this.left+this.width+
2+u[0]-(this.opposite?0:p),this.top,this.width,this.height),this.opposite&&(u[0]+=p),k=0),u[k]+=c.size+c.options.margin,isNaN(b)||isNaN(r)||!B(this.min)||!B(this.max)||this.min===this.max?c.setRange(0,1):(u=(this.min-b)/(r-b),b=(this.max-b)/(r-b),this.horiz&&!this.reversed||!this.horiz&&this.reversed?c.setRange(u,b):c.setRange(1-b,1-u)))});E(y,"afterGetOffset",function(){var b=this.horiz?2:1,c=this.scrollbar;c&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[b]+=c.size+c.options.margin)})};
return A}()});H(c,"Core/Scrollbar.js",[c["Core/Axis/Axis.js"],c["Core/Globals.js"],c["Core/Axis/ScrollbarAxis.js"],c["Core/Utilities.js"],c["Core/Options.js"]],function(c,C,E,B,v){var A=B.addEvent,y=B.correctFloat,k=B.defined,b=B.destroyObjectProperties,r=B.fireEvent,I=B.merge,J=B.pick,u=B.removeEvent;B=v.defaultOptions;var p=C.hasTouch,L=C.isTouchDevice,f=C.swapXY=function(f,g){g&&f.forEach(function(d){for(var l=d.length,g,f=0;f<l;f+=2)g=d[f+1],"number"===typeof g&&(d[f+1]=d[f+2],d[f+2]=g)});return f};
v=function(){function w(g,d,l){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=l;this.options=d;this.renderer=l.renderer;this.init(g,d,l)}w.prototype.addEvents=function(){var g=this.options.inverted?[1,0]:[0,
1],d=this.scrollbarButtons,l=this.scrollbarGroup.element,f=this.track.element,b=this.mouseDownHandler.bind(this),n=this.mouseMoveHandler.bind(this),e=this.mouseUpHandler.bind(this);g=[[d[g[0]].element,"click",this.buttonToMinClick.bind(this)],[d[g[1]].element,"click",this.buttonToMaxClick.bind(this)],[f,"click",this.trackClick.bind(this)],[l,"mousedown",b],[l.ownerDocument,"mousemove",n],[l.ownerDocument,"mouseup",e]];p&&g.push([l,"touchstart",b],[l.ownerDocument,"touchmove",n],[l.ownerDocument,"touchend",
e]);g.forEach(function(q){A.apply(null,q)});this._events=g};w.prototype.buttonToMaxClick=function(g){var d=(this.to-this.from)*J(this.options.step,.2);this.updatePosition(this.from+d,this.to+d);r(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:g})};w.prototype.buttonToMinClick=function(g){var d=y(this.to-this.from)*J(this.options.step,.2);this.updatePosition(y(this.from-d),y(this.to-d));r(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:g})};w.prototype.cursorToScrollbarPosition=
function(g){var d=this.options;d=d.minWidth>this.calculatedWidth?d.minWidth:0;return{chartX:(g.chartX-this.x-this.xOffset)/(this.barWidth-d),chartY:(g.chartY-this.y-this.yOffset)/(this.barWidth-d)}};w.prototype.destroy=function(){var g=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(d){this[d]&&this[d].destroy&&(this[d]=this[d].destroy())},this);g&&this===g.scrollbar&&(g.scrollbar=null,b(g.scrollbarButtons))};w.prototype.drawScrollbarButton=
function(g){var d=this.renderer,l=this.scrollbarButtons,b=this.options,w=this.size;var n=d.g().add(this.group);l.push(n);n=d.rect().addClass("highcharts-scrollbar-button").add(n);this.chart.styledMode||n.attr({stroke:b.buttonBorderColor,"stroke-width":b.buttonBorderWidth,fill:b.buttonBackgroundColor});n.attr(n.crisp({x:-.5,y:-.5,width:w+1,height:w+1,r:b.buttonBorderRadius},n.strokeWidth()));n=d.path(f([["M",w/2+(g?-1:1),w/2-3],["L",w/2+(g?-1:1),w/2+3],["L",w/2+(g?2:-2),w/2]],b.vertical)).addClass("highcharts-scrollbar-arrow").add(l[g]);
this.chart.styledMode||n.attr({fill:b.buttonArrowColor})};w.prototype.init=function(g,d,l){this.scrollbarButtons=[];this.renderer=g;this.userOptions=d;this.options=I(w.defaultOptions,d);this.chart=l;this.size=J(this.options.size,this.options.height);d.enabled&&(this.render(),this.addEvents())};w.prototype.mouseDownHandler=function(g){g=this.chart.pointer.normalize(g);g=this.cursorToScrollbarPosition(g);this.chartX=g.chartX;this.chartY=g.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=
!0};w.prototype.mouseMoveHandler=function(g){var d=this.chart.pointer.normalize(g),l=this.options.vertical?"chartY":"chartX",f=this.initPositions||[];!this.grabbedCenter||g.touches&&0===g.touches[0][l]||(d=this.cursorToScrollbarPosition(d)[l],l=this[l],l=d-l,this.hasDragged=!0,this.updatePosition(f[0]+l,f[1]+l),this.hasDragged&&r(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:g.type,DOMEvent:g}))};w.prototype.mouseUpHandler=function(g){this.hasDragged&&r(this,"changed",{from:this.from,
to:this.to,trigger:"scrollbar",DOMType:g.type,DOMEvent:g});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};w.prototype.position=function(g,d,l,f){var b=this.options.vertical,n=0,e=this.rendered?"animate":"attr";this.x=g;this.y=d+this.trackBorderWidth;this.width=l;this.xOffset=this.height=f;this.yOffset=n;b?(this.width=this.yOffset=l=n=this.size,this.xOffset=d=0,this.barWidth=f-2*l,this.x=g+=this.options.margin):(this.height=this.xOffset=f=d=this.size,this.barWidth=l-2*f,this.y+=this.options.margin);
this.group[e]({translateX:g,translateY:this.y});this.track[e]({width:l,height:f});this.scrollbarButtons[1][e]({translateX:b?0:l-d,translateY:b?f-n:0})};w.prototype.removeEvents=function(){this._events.forEach(function(f){u.apply(null,f)});this._events.length=0};w.prototype.render=function(){var g=this.renderer,d=this.options,l=this.size,b=this.chart.styledMode,w;this.group=w=g.g("scrollbar").attr({zIndex:d.zIndex,translateY:-99999}).add();this.track=g.rect().addClass("highcharts-scrollbar-track").attr({x:0,
r:d.trackBorderRadius||0,height:l,width:l}).add(w);b||this.track.attr({fill:d.trackBackgroundColor,stroke:d.trackBorderColor,"stroke-width":d.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=g.g().add(w);this.scrollbar=g.rect().addClass("highcharts-scrollbar-thumb").attr({height:l,width:l,r:d.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=g.path(f([["M",-3,l/4],["L",-3,2*l/3],["M",0,l/4],["L",
0,2*l/3],["M",3,l/4],["L",3,2*l/3]],d.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);b||(this.scrollbar.attr({fill:d.barBackgroundColor,stroke:d.barBorderColor,"stroke-width":d.barBorderWidth}),this.scrollbarRifles.attr({stroke:d.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};w.prototype.setRange=
function(f,d){var l=this.options,g=l.vertical,b=l.minWidth,n=this.barWidth,e,q=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(k(n)){f=Math.max(f,0);var a=Math.ceil(n*f);this.calculatedWidth=e=y(n*Math.min(d,1)-a);e<b&&(a=(n-b+e)*f,e=b);b=Math.floor(a+this.xOffset+this.yOffset);n=e/2-.5;this.from=f;this.to=d;g?(this.scrollbarGroup[q]({translateY:b}),this.scrollbar[q]({height:e}),this.scrollbarRifles[q]({translateY:n}),this.scrollbarTop=b,
this.scrollbarLeft=0):(this.scrollbarGroup[q]({translateX:b}),this.scrollbar[q]({width:e}),this.scrollbarRifles[q]({translateX:n}),this.scrollbarLeft=b,this.scrollbarTop=0);12>=e?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===l.showFull&&(0>=f&&1<=d?this.group.hide():this.group.show());this.rendered=!0}};w.prototype.trackClick=function(f){var d=this.chart.pointer.normalize(f),l=this.to-this.from,g=this.y+this.scrollbarTop,b=this.x+this.scrollbarLeft;this.options.vertical&&d.chartY>
g||!this.options.vertical&&d.chartX>b?this.updatePosition(this.from+l,this.to+l):this.updatePosition(this.from-l,this.to-l);r(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:f})};w.prototype.update=function(f){this.destroy();this.init(this.chart.renderer,I(!0,this.options,f),this.chart)};w.prototype.updatePosition=function(f,d){1<d&&(f=y(1-y(d-f)),d=1);0>f&&(d=y(d-f),f=0);this.from=f;this.to=d};w.defaultOptions={height:L?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,
margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};return w}();C.Scrollbar||(B.scrollbar=I(!0,v.defaultOptions,B.scrollbar),C.Scrollbar=v,E.compose(c,v));return C.Scrollbar});H(c,"Core/Navigator.js",[c["Core/Axis/Axis.js"],c["Core/Series/Series.js"],
c["Core/Chart/Chart.js"],c["Core/Color/Color.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],c["Core/Axis/NavigatorAxis.js"],c["Core/Options.js"],c["Core/Scrollbar.js"],c["Core/Utilities.js"]],function(c,C,E,B,v,A,y,k,b,r){B=B.parse;var I=v.hasTouch,J=v.isTouchDevice,u=k.defaultOptions,p=r.addEvent,L=r.clamp,f=r.correctFloat,w=r.defined,g=r.destroyObjectProperties,d=r.erase,l=r.extend,F=r.find,K=r.isArray,n=r.isNumber,e=r.merge,q=r.pick,a=r.removeEvent,z=r.splat,h=function(a){for(var m=[],
D=1;D<arguments.length;D++)m[D-1]=arguments[D];m=[].filter.call(m,n);if(m.length)return Math[a].apply(0,m)};C="undefined"===typeof C.seriesTypes.areaspline?"line":"areaspline";l(u,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:B("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:C,fillOpacity:.05,lineWidth:1,compare:null,
dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",
tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});v.Renderer.prototype.symbols["navigator-handle"]=function(a,m,D,h,q){a=(q&&q.width||0)/2;m=Math.round(a/3)+.5;q=q&&q.height||0;return[["M",-a-1,.5],
["L",a,.5],["L",a,q+.5],["L",-a-1,q+.5],["L",-a-1,.5],["M",-m,4],["L",-m,q-3],["M",m-1,4],["L",m-1,q-3]]};var x=function(){function t(m){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(m)}t.prototype.drawHandle=function(m,
D,a,q){var h=this.navigatorOptions.handles.height;this.handles[D][q](a?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(m,10)+.5-h)}:{translateX:Math.round(this.left+parseInt(m,10)),translateY:Math.round(this.top+this.height/2-h/2-1)})};t.prototype.drawOutline=function(m,D,a,q){var h=this.navigatorOptions.maskInside,e=this.outline.strokeWidth(),t=e/2,G=e%2/2;e=this.outlineHeight;var x=this.scrollbarHeight||0,f=this.size,d=this.left-x,z=this.top;a?(d-=t,a=z+D+
G,D=z+m+G,G=[["M",d+e,z-x-G],["L",d+e,a],["L",d,a],["L",d,D],["L",d+e,D],["L",d+e,z+f+x]],h&&G.push(["M",d+e,a-t],["L",d+e,D+t])):(m+=d+x-G,D+=d+x-G,z+=t,G=[["M",d,z],["L",m,z],["L",m,z+e],["L",D,z+e],["L",D,z],["L",d+f+2*x,z]],h&&G.push(["M",m-t,z],["L",D+t,z]));this.outline[q]({d:G})};t.prototype.drawMasks=function(m,D,a,q){var h=this.left,e=this.top,t=this.height;if(a){var G=[h,h,h];var d=[e,e+m,e+D];var x=[t,t,t];var z=[m,D-m,this.size-D]}else G=[h,h+m,h+D],d=[e,e,e],x=[m,D-m,this.size-D],z=[t,
t,t];this.shades.forEach(function(m,D){m[q]({x:G[D],y:d[D],width:x[D],height:z[D]})})};t.prototype.renderElements=function(){var m=this,D=m.navigatorOptions,a=D.maskInside,q=m.chart,h=q.renderer,e,t={cursor:q.inverted?"ns-resize":"ew-resize"};m.navigatorGroup=e=h.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!a,a,!a].forEach(function(a,d){m.shades[d]=h.rect().addClass("highcharts-navigator-mask"+(1===d?"-inside":"-outside")).add(e);q.styledMode||m.shades[d].attr({fill:a?D.maskFill:"rgba(0,0,0,0)"}).css(1===
d&&t)});m.outline=h.path().addClass("highcharts-navigator-outline").add(e);q.styledMode||m.outline.attr({"stroke-width":D.outlineWidth,stroke:D.outlineColor});D.handles.enabled&&[0,1].forEach(function(a){D.handles.inverted=q.inverted;m.handles[a]=h.symbol(D.handles.symbols[a],-D.handles.width/2-1,0,D.handles.width,D.handles.height,D.handles);m.handles[a].attr({zIndex:7-a}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][a]).add(e);if(!q.styledMode){var d=D.handles;
m.handles[a].attr({fill:d.backgroundColor,stroke:d.borderColor,"stroke-width":d.lineWidth}).css(t)}})};t.prototype.update=function(m){(this.series||[]).forEach(function(m){m.baseSeries&&delete m.baseSeries.navigatorSeries});this.destroy();e(!0,this.chart.options.navigator,this.options,m);this.init(this.chart)};t.prototype.render=function(m,D,a,h){var e=this.chart,t=this.scrollbarHeight,d,x=this.xAxis,z=x.pointRange||0;var G=x.navigatorAxis.fake?e.xAxis[0]:x;var l=this.navigatorEnabled,b,g=this.rendered;
var M=e.inverted;var c=e.xAxis[0].minRange,F=e.xAxis[0].options.maxRange;if(!this.hasDragged||w(a)){m=f(m-z/2);D=f(D+z/2);if(!n(m)||!n(D))if(g)a=0,h=q(x.width,G.width);else return;this.left=q(x.left,e.plotLeft+t+(M?e.plotWidth:0));this.size=b=d=q(x.len,(M?e.plotHeight:e.plotWidth)-2*t);e=M?t:d+2*t;a=q(a,x.toPixels(m,!0));h=q(h,x.toPixels(D,!0));n(a)&&Infinity!==Math.abs(a)||(a=0,h=e);m=x.toValue(a,!0);D=x.toValue(h,!0);var k=Math.abs(f(D-m));k<c?this.grabbedLeft?a=x.toPixels(D-c-z,!0):this.grabbedRight&&
(h=x.toPixels(m+c+z,!0)):w(F)&&f(k-z)>F&&(this.grabbedLeft?a=x.toPixels(D-F-z,!0):this.grabbedRight&&(h=x.toPixels(m+F+z,!0)));this.zoomedMax=L(Math.max(a,h),0,b);this.zoomedMin=L(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(a,h),0,b);this.range=this.zoomedMax-this.zoomedMin;b=Math.round(this.zoomedMax);a=Math.round(this.zoomedMin);l&&(this.navigatorGroup.attr({visibility:"visible"}),g=g&&!this.hasDragged?"animate":"attr",this.drawMasks(a,b,M,g),this.drawOutline(a,b,M,g),this.navigatorOptions.handles.enabled&&
(this.drawHandle(a,0,M,g),this.drawHandle(b,1,M,g)));this.scrollbar&&(M?(M=this.top-t,G=this.left-t+(l||!G.opposite?0:(G.titleOffset||0)+G.axisTitleMargin),t=d+2*t):(M=this.top+(l?this.height:-t),G=this.left-t),this.scrollbar.position(G,M,e,t),this.scrollbar.setRange(this.zoomedMin/(d||1),this.zoomedMax/(d||1)));this.rendered=!0}};t.prototype.addMouseEvents=function(){var m=this,D=m.chart,a=D.container,h=[],q,e;m.mouseMoveHandler=q=function(a){m.onMouseMove(a)};m.mouseUpHandler=e=function(a){m.onMouseUp(a)};
h=m.getPartsEvents("mousedown");h.push(p(D.renderTo,"mousemove",q),p(a.ownerDocument,"mouseup",e));I&&(h.push(p(D.renderTo,"touchmove",q),p(a.ownerDocument,"touchend",e)),h.concat(m.getPartsEvents("touchstart")));m.eventsToUnbind=h;m.series&&m.series[0]&&h.push(p(m.series[0].xAxis,"foundExtremes",function(){D.navigator.modifyNavigatorAxisExtremes()}))};t.prototype.getPartsEvents=function(m){var a=this,h=[];["shades","handles"].forEach(function(D){a[D].forEach(function(q,e){h.push(p(q.element,m,function(m){a[D+
"Mousedown"](m,e)}))})});return h};t.prototype.shadesMousedown=function(m,a){m=this.chart.pointer.normalize(m);var D=this.chart,h=this.xAxis,q=this.zoomedMin,e=this.left,t=this.size,d=this.range,x=m.chartX;D.inverted&&(x=m.chartY,e=this.top);if(1===a)this.grabbedCenter=x,this.fixedWidth=d,this.dragOffset=x-q;else{m=x-e-d/2;if(0===a)m=Math.max(0,m);else if(2===a&&m+d>=t)if(m=t-d,this.reversedExtremes){m-=d;var z=this.getUnionExtremes().dataMin}else var f=this.getUnionExtremes().dataMax;m!==q&&(this.fixedWidth=
d,a=h.navigatorAxis.toFixedRange(m,m+d,z,f),w(a.min)&&D.xAxis[0].setExtremes(Math.min(a.min,a.max),Math.max(a.min,a.max),!0,null,{trigger:"navigator"}))}};t.prototype.handlesMousedown=function(m,a){this.chart.pointer.normalize(m);m=this.chart;var D=m.xAxis[0],h=this.reversedExtremes;0===a?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=h?D.min:D.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=h?D.max:D.min);m.fixedRange=null};t.prototype.onMouseMove=
function(m){var a=this,h=a.chart,e=a.left,t=a.navigatorSize,d=a.range,x=a.dragOffset,z=h.inverted;m.touches&&0===m.touches[0].pageX||(m=h.pointer.normalize(m),h=m.chartX,z&&(e=a.top,h=m.chartY),a.grabbedLeft?(a.hasDragged=!0,a.render(0,0,h-e,a.otherHandlePos)):a.grabbedRight?(a.hasDragged=!0,a.render(0,0,a.otherHandlePos,h-e)):a.grabbedCenter&&(a.hasDragged=!0,h<x?h=x:h>t+x-d&&(h=t+x-d),a.render(0,0,h-x,h-x+d)),a.hasDragged&&a.scrollbar&&q(a.scrollbar.options.liveRedraw,v.svg&&!J&&!this.chart.isBoosting)&&
(m.DOMType=m.type,setTimeout(function(){a.onMouseUp(m)},0)))};t.prototype.onMouseUp=function(a){var m=this.chart,h=this.xAxis,e=this.scrollbar,q=a.DOMEvent||a,t=m.inverted,d=this.rendered&&!this.hasDragged?"animate":"attr";if(this.hasDragged&&(!e||!e.hasDragged)||"scrollbar"===a.trigger){e=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var x=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var z=this.fixedExtreme;this.zoomedMax===this.size&&(z=this.reversedExtremes?
e.dataMin:e.dataMax);0===this.zoomedMin&&(x=this.reversedExtremes?e.dataMax:e.dataMin);h=h.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,x,z);w(h.min)&&m.xAxis[0].setExtremes(Math.min(h.min,h.max),Math.max(h.min,h.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:q})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=
null);this.navigatorEnabled&&n(this.zoomedMin)&&n(this.zoomedMax)&&(m=Math.round(this.zoomedMin),a=Math.round(this.zoomedMax),this.shades&&this.drawMasks(m,a,t,d),this.outline&&this.drawOutline(m,a,t,d),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(m,0,t,d),this.drawHandle(a,1,t,d)))};t.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};
t.prototype.removeBaseSeriesEvents=function(){var m=this.baseSeries||[];this.navigatorEnabled&&m[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&m.forEach(function(m){a(m,"updatedData",this.updatedDataHandler)},this),m[0].xAxis&&a(m[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};t.prototype.init=function(a){var m=a.options,t=m.navigator,d=t.enabled,x=m.scrollbar,z=x.enabled;m=d?t.height:0;var f=z?x.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=
m;this.scrollbarHeight=f;this.scrollbarEnabled=z;this.navigatorEnabled=d;this.navigatorOptions=t;this.scrollbarOptions=x;this.outlineHeight=m+f;this.opposite=q(t.opposite,!(d||!a.inverted));var l=this;d=l.baseSeries;x=a.xAxis.length;z=a.yAxis.length;var n=d&&d[0]&&d[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;l.navigatorEnabled?(l.xAxis=new c(a,e({breaks:n.options.breaks,ordinal:n.options.ordinal},t.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:x,isInternal:!0,
offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[f,0,-f,0],width:m}:{offsets:[0,-f,0,f],height:m})),l.yAxis=new c(a,e(t.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:z,isInternal:!0,reversed:q(t.yAxis&&t.yAxis.reversed,a.yAxis[0]&&a.yAxis[0].reversed,!1),zoomEnabled:!1},a.inverted?{width:m}:{height:m})),d||t.series.data?l.updateNavigatorSeries(!1):0===a.series.length&&(l.unbindRedraw=p(a,"beforeRedraw",function(){0<
a.series.length&&!l.series&&(l.setBaseSeries(),l.unbindRedraw())})),l.reversedExtremes=a.inverted&&!l.xAxis.reversed||!a.inverted&&l.xAxis.reversed,l.renderElements(),l.addMouseEvents()):(l.xAxis={chart:a,navigatorAxis:{fake:!0},translate:function(m,e){var t=a.xAxis[0],q=t.getExtremes(),d=t.len-2*f,x=h("min",t.options.min,q.dataMin);t=h("max",t.options.max,q.dataMax)-x;return e?m*t/d+x:d*(m-x)/t},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)}},l.xAxis.navigatorAxis.axis=
l.xAxis,l.xAxis.navigatorAxis.toFixedRange=y.AdditionsClass.prototype.toFixedRange.bind(l.xAxis.navigatorAxis));a.options.scrollbar.enabled&&(a.scrollbar=l.scrollbar=new b(a.renderer,e(a.options.scrollbar,{margin:l.navigatorEnabled?0:10,vertical:a.inverted}),a),p(l.scrollbar,"changed",function(m){var h=l.size,e=h*this.to;h*=this.from;l.hasDragged=l.scrollbar.hasDragged;l.render(0,0,h,e);(a.options.scrollbar.liveRedraw||"mousemove"!==m.DOMType&&"touchmove"!==m.DOMType)&&setTimeout(function(){l.onMouseUp(m)})}));
l.addBaseSeriesEvents();l.addChartEvents()};t.prototype.getUnionExtremes=function(a){var m=this.chart.xAxis[0],e=this.xAxis,t=e.options,d=m.options,x;a&&null===m.dataMin||(x={dataMin:q(t&&t.min,h("min",d.min,m.dataMin,e.dataMin,e.min)),dataMax:q(t&&t.max,h("max",d.max,m.dataMax,e.dataMax,e.max))});return x};t.prototype.setBaseSeries=function(a,h){var m=this.chart,e=this.baseSeries=[];a=a||m.options&&m.options.navigator.baseSeries||(m.series.length?F(m.series,function(a){return!a.options.isInternal}).index:
0);(m.series||[]).forEach(function(m,h){m.options.isInternal||!m.options.showInNavigator&&(h!==a&&m.options.id!==a||!1===m.options.showInNavigator)||e.push(m)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,h)};t.prototype.updateNavigatorSeries=function(m,h){var t=this,d=t.chart,x=t.baseSeries,D,f,n=t.navigatorOptions.series,b,g={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,
isInternal:!0,states:{inactive:{opacity:1}}},w=t.series=(t.series||[]).filter(function(m){var h=m.baseSeries;return 0>x.indexOf(h)?(h&&(a(h,"updatedData",t.updatedDataHandler),delete h.navigatorSeries),m.chart&&m.destroy(),!1):!0});x&&x.length&&x.forEach(function(a){var m=a.navigatorSeries,z=l({color:a.color,visible:a.visible},K(n)?u.navigator.series:n);m&&!1===t.navigatorOptions.adaptToUpdatedData||(g.name="Navigator "+x.length,D=a.options||{},b=D.navigatorOptions||{},f=e(D,g,z,b),f.pointRange=q(z.pointRange,
b.pointRange,u.plotOptions[f.type||"line"].pointRange),z=b.data||z.data,t.hasNavigatorData=t.hasNavigatorData||!!z,f.data=z||D.data&&D.data.slice(0),m&&m.options?m.update(f,h):(a.navigatorSeries=d.initSeries(f),a.navigatorSeries.baseSeries=a,w.push(a.navigatorSeries)))});if(n.data&&(!x||!x.length)||K(n))t.hasNavigatorData=!1,n=z(n),n.forEach(function(a,m){g.name="Navigator "+(w.length+1);f=e(u.navigator.series,{color:d.series[m]&&!d.series[m].options.isInternal&&d.series[m].color||d.options.colors[m]||
d.options.colors[0]},g,a);f.data=a.data;f.data&&(t.hasNavigatorData=!0,w.push(d.initSeries(f)))});m&&this.addBaseSeriesEvents()};t.prototype.addBaseSeriesEvents=function(){var a=this,h=a.baseSeries||[];h[0]&&h[0].xAxis&&p(h[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);h.forEach(function(m){p(m,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});p(m,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&
m.xAxis&&p(m,"updatedData",this.updatedDataHandler);p(m,"remove",function(){this.navigatorSeries&&(d(a.series,this.navigatorSeries),w(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};t.prototype.getBaseSeriesMin=function(a){return this.baseSeries.reduce(function(a,m){return Math.min(a,m.xData?m.xData[0]:a)},a)};t.prototype.modifyNavigatorAxisExtremes=function(){var a=this.xAxis,h;"undefined"!==typeof a.getExtremes&&(!(h=this.getUnionExtremes(!0))||
h.dataMin===a.min&&h.dataMax===a.max||(a.min=h.dataMin,a.max=h.dataMax))};t.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,h=this.getExtremes(),t=h.dataMin,e=h.dataMax;h=h.max-h.min;var d=a.stickToMin,x=a.stickToMax,z=q(this.options.overscroll,0),f=a.series&&a.series[0],l=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(d){var b=t;var g=b+h}x&&(g=e+z,d||(b=Math.max(t,g-h,a.getBaseSeriesMin(f&&f.xData?f.xData[0]:-Number.MAX_VALUE))));
l&&(d||x)&&n(b)&&(this.min=this.userMin=b,this.max=this.userMax=g)}a.stickToMin=a.stickToMax=null};t.prototype.updatedDataHandler=function(){var a=this.chart.navigator,h=this.navigatorSeries,t=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=n(this.xAxis.min)&&this.xAxis.min<=t&&(!this.chart.fixedRange||!a.stickToMax);h&&!a.hasNavigatorData&&(h.options.pointStart=this.xData[0],h.setData(this.options.data,
!1,null,!1))};t.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(p(this.chart,"redraw",function(){var a=this.navigator,h=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||this.xAxis[0]);h&&a.render(h.min,h.max)}),p(this.chart,"getMargins",function(){var a=this.navigator,h=a.opposite?"plotTop":"marginBottom";this.inverted&&(h=a.opposite?"marginRight":"plotLeft");this[h]=(this[h]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:
0)+a.navigatorOptions.margin}))};t.prototype.destroy=function(){this.removeEvents();this.xAxis&&(d(this.chart.xAxis,this.xAxis),d(this.chart.axes,this.xAxis));this.yAxis&&(d(this.chart.yAxis,this.yAxis),d(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},
this);[this.handles].forEach(function(a){g(a)},this)};return t}();v.Navigator||(v.Navigator=x,y.compose(c),p(E,"beforeShowResetZoom",function(){var a=this.options,h=a.navigator,e=a.rangeSelector;if((h&&h.enabled||e&&e.enabled)&&(!J&&"x"===a.chart.zoomType||J&&"x"===a.chart.pinchType))return!1}),p(E,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new x(this)}),p(E,"afterSetChartSize",function(){var a=this.legend,h=this.navigator;
if(h){var e=a&&a.options;var d=h.xAxis;var x=h.yAxis;var z=h.scrollbarHeight;this.inverted?(h.left=h.opposite?this.chartWidth-z-h.height:this.spacing[3]+z,h.top=this.plotTop+z):(h.left=this.plotLeft+z,h.top=h.navigatorOptions.top||this.chartHeight-h.height-z-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(e&&"bottom"===e.verticalAlign&&"proximate"!==e.layout&&e.enabled&&!e.floating?a.legendHeight+q(e.margin,10):0)-(this.titleOffset?this.titleOffset[2]:
0));d&&x&&(this.inverted?d.options.left=x.options.left=h.left:d.options.top=x.options.top=h.top,d.setAxisSize(),x.setAxisSize())}}),p(E,"update",function(a){var h=a.options.navigator||{},d=a.options.scrollbar||{};this.navigator||this.scroller||!h.enabled&&!d.enabled||(e(!0,this.options.navigator,h),e(!0,this.options.scrollbar,d),delete a.options.navigator,delete a.options.scrollbar)}),p(E,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||
(this.scroller=this.navigator=new x(this),q(a.redraw,!0)&&this.redraw(a.animation))}),p(E,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),p(A,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),E.prototype.callbacks.push(function(a){var h=a.navigator;h&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),h.render(a.min,a.max))}));v.Navigator=x;return v.Navigator});H(c,"Core/Axis/OrdinalAxis.js",[c["Core/Axis/Axis.js"],
c["Core/Globals.js"],c["Series/Line/LineSeries.js"],c["Core/Utilities.js"],c["Core/Chart/Chart.js"]],function(c,C,E,B,v){var A=B.addEvent,y=B.css,k=B.defined,b=B.error,r=B.pick,I=B.timeUnits,J;(function(c){var p=function(){function b(f){this.index={};this.axis=f}b.prototype.beforeSetTickPositions=function(){var f=this.axis,b=f.ordinal,g=[],d,l=!1,c=f.getExtremes(),k=c.min,n=c.max,e,q=f.isXAxis&&!!f.options.breaks;c=f.options.ordinal;var a=Number.MAX_VALUE,z=f.chart.options.chart.ignoreHiddenSeries,
h;if(c||q){f.series.forEach(function(e,t){d=[];if(!(z&&!1===e.visible||!1===e.takeOrdinalPosition&&!q)&&(g=g.concat(e.processedXData),x=g.length,g.sort(function(a,h){return a-h}),a=Math.min(a,r(e.closestPointRange,a)),x)){for(t=0;t<x-1;)g[t]!==g[t+1]&&d.push(g[t+1]),t++;d[0]!==g[0]&&d.unshift(g[0]);g=d}e.isSeriesBoosting&&(h=!0)});h&&(g.length=0);var x=g.length;if(2<x){var t=g[1]-g[0];for(e=x-1;e--&&!l;)g[e+1]-g[e]!==t&&(l=!0);!f.options.keepOrdinalPadding&&(g[0]-k>t||n-g[g.length-1]>t)&&(l=!0)}else f.options.overscroll&&
(2===x?a=g[1]-g[0]:1===x?(a=f.options.overscroll,g=[g[0],g[0]+a]):a=b.overscrollPointsRange);l?(f.options.overscroll&&(b.overscrollPointsRange=a,g=g.concat(b.getOverscrollPositions())),b.positions=g,t=f.ordinal2lin(Math.max(k,g[0]),!0),e=Math.max(f.ordinal2lin(Math.min(n,g[g.length-1]),!0),1),b.slope=n=(n-k)/(e-t),b.offset=k-t*n):(b.overscrollPointsRange=r(f.closestPointRange,b.overscrollPointsRange),b.positions=f.ordinal.slope=b.offset=void 0)}f.isOrdinal=c&&l;b.groupIntervalFactor=null};b.prototype.getExtendedPositions=
function(){var f=this,b=f.axis,g=b.constructor.prototype,d=b.chart,l=b.series[0].currentDataGrouping,c=f.index,k=l?l.count+l.unitName:"raw",n=b.options.overscroll,e=b.getExtremes(),q;c||(c=f.index={});if(!c[k]){var a={series:[],chart:d,getExtremes:function(){return{min:e.dataMin,max:e.dataMax+n}},options:{ordinal:!0},ordinal:{},ordinal2lin:g.ordinal2lin,val2lin:g.val2lin};a.ordinal.axis=a;b.series.forEach(function(e){q={xAxis:a,xData:e.xData.slice(),chart:d,destroyGroupedData:C.noop,getProcessedData:E.prototype.getProcessedData};
q.xData=q.xData.concat(f.getOverscrollPositions());q.options={dataGrouping:l?{enabled:!0,forced:!0,approximation:"open",units:[[l.unitName,[l.count]]]}:{enabled:!1}};e.processData.apply(q);a.series.push(q)});b.ordinal.beforeSetTickPositions.apply({axis:a});c[k]=a.ordinal.positions}return c[k]};b.prototype.getGroupIntervalFactor=function(f,b,g){g=g.processedXData;var d=g.length,l=[];var c=this.groupIntervalFactor;if(!c){for(c=0;c<d-1;c++)l[c]=g[c+1]-g[c];l.sort(function(d,f){return d-f});l=l[Math.floor(d/
2)];f=Math.max(f,g[0]);b=Math.min(b,g[d-1]);this.groupIntervalFactor=c=d*l/(b-f)}return c};b.prototype.getOverscrollPositions=function(){var f=this.axis,b=f.options.overscroll,g=this.overscrollPointsRange,d=[],l=f.dataMax;if(k(g))for(d.push(l);l<=f.dataMax+b;)l+=g,d.push(l);return d};b.prototype.postProcessTickInterval=function(f){var b=this.axis,g=this.slope;return g?b.options.breaks?b.closestPointRange||f:f/(g/b.closestPointRange):f};return b}();c.Composition=p;c.compose=function(p,f,r){p.keepProps.push("ordinal");
var g=p.prototype;p.prototype.getTimeTicks=function(d,f,g,c,n,e,q){void 0===n&&(n=[]);void 0===e&&(e=0);var a=0,z,h,x={},t=[],m=-Number.MAX_VALUE,l=this.options.tickPixelInterval,G=this.chart.time,p=[];if(!this.options.ordinal&&!this.options.breaks||!n||3>n.length||"undefined"===typeof f)return G.getTimeTicks.apply(G,arguments);var r=n.length;for(z=0;z<r;z++){var w=z&&n[z-1]>g;n[z]<f&&(a=z);if(z===r-1||n[z+1]-n[z]>5*e||w){if(n[z]>m){for(h=G.getTimeTicks(d,n[a],n[z],c);h.length&&h[0]<=m;)h.shift();
h.length&&(m=h[h.length-1]);p.push(t.length);t=t.concat(h)}a=z+1}if(w)break}if(h){h=h.info;if(q&&h.unitRange<=I.hour){z=t.length-1;for(a=1;a<z;a++)if(G.dateFormat("%d",t[a])!==G.dateFormat("%d",t[a-1])){x[t[a]]="day";var F=!0}F&&(x[t[0]]="day");h.higherRanks=x}h.segmentStarts=p;t.info=h}else b(12,!1,this.chart);if(q&&k(l)){a=p=t.length;F=[];var u;for(G=[];a--;)z=this.translate(t[a]),u&&(G[a]=u-z),F[a]=u=z;G.sort();G=G[Math.floor(G.length/2)];G<.6*l&&(G=null);a=t[p-1]>g?p-1:p;for(u=void 0;a--;)z=F[a],
p=Math.abs(u-z),u&&p<.8*l&&(null===G||p<.8*G)?(x[t[a]]&&!x[t[a+1]]?(p=a+1,u=z):p=a,t.splice(p,1)):u=z}return t};g.lin2val=function(d,f){var b=this.ordinal,l=b.positions;if(l){var n=b.slope,e=b.offset;b=l.length-1;if(f)if(0>d)d=l[0];else if(d>b)d=l[b];else{b=Math.floor(d);var q=d-b}else for(;b--;)if(f=n*b+e,d>=f){n=n*(b+1)+e;q=(d-f)/(n-f);break}return"undefined"!==typeof q&&"undefined"!==typeof l[b]?l[b]+(q?q*(l[b+1]-l[b]):0):d}return d};g.val2lin=function(d,f){var b=this.ordinal,l=b.positions;if(l){var n=
l.length,e;for(e=n;e--;)if(l[e]===d){var q=e;break}for(e=n-1;e--;)if(d>l[e]||0===e){d=(d-l[e])/(l[e+1]-l[e]);q=e+d;break}f=f?q:b.slope*(q||0)+b.offset}else f=d;return f};g.ordinal2lin=g.val2lin;A(p,"afterInit",function(){this.ordinal||(this.ordinal=new c.Composition(this))});A(p,"foundExtremes",function(){this.isXAxis&&k(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=
this.options.overscroll,!this.isInternal&&k(this.userMin)&&(this.min+=this.options.overscroll))});A(p,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&!this.chart.navigator.adaptToUpdatedData)});A(p,"initialAxisTranslation",function(){this.ordinal&&(this.ordinal.beforeSetTickPositions(),this.tickInterval=this.ordinal.postProcessTickInterval(this.tickInterval))});A(f,"pan",function(d){var f=this.xAxis[0],b=f.options.overscroll,g=d.originalEvent.chartX,
n=this.options.chart&&this.options.chart.panning,e=!1;if(n&&"y"!==n.type&&f.options.ordinal&&f.series.length){var q=this.mouseDownX,a=f.getExtremes(),z=a.dataMax,h=a.min,x=a.max,t=this.hoverPoints,m=f.closestPointRange||f.ordinal&&f.ordinal.overscrollPointsRange;q=(q-g)/(f.translationSlope*(f.ordinal.slope||m));var D={ordinal:{positions:f.ordinal.getExtendedPositions()}};m=f.lin2val;var c=f.val2lin;if(!D.ordinal.positions)e=!0;else if(1<Math.abs(q)){t&&t.forEach(function(a){a.setState()});if(0>q){t=
D;var p=f.ordinal.positions?f:D}else t=f.ordinal.positions?f:D,p=D;D=p.ordinal.positions;z>D[D.length-1]&&D.push(z);this.fixedRange=x-h;q=f.navigatorAxis.toFixedRange(null,null,m.apply(t,[c.apply(t,[h,!0])+q,!0]),m.apply(p,[c.apply(p,[x,!0])+q,!0]));q.min>=Math.min(a.dataMin,h)&&q.max<=Math.max(z,x)+b&&f.setExtremes(q.min,q.max,!0,!1,{trigger:"pan"});this.mouseDownX=g;y(this.container,{cursor:"move"})}}else e=!0;e||n&&/y/.test(n.type)?b&&(f.max=f.dataMax+b):d.preventDefault()});A(r,"updatedData",
function(){var d=this.xAxis;d&&d.options.ordinal&&delete d.ordinal.index})}})(J||(J={}));J.compose(c,v,E);return J});H(c,"Core/Axis/BrokenAxis.js",[c["Core/Axis/Axis.js"],c["Series/Line/LineSeries.js"],c["Extensions/Stacking.js"],c["Core/Utilities.js"]],function(c,C,E,B){var v=B.addEvent,A=B.find,y=B.fireEvent,k=B.isArray,b=B.isNumber,r=B.pick,I=function(){function b(b){this.hasBreaks=!1;this.axis=b}b.isInBreak=function(b,c){var p=b.repeat||Infinity,f=b.from,k=b.to-b.from;c=c>=f?(c-f)%p:p-(f-c)%p;
return b.inclusive?c<=k:c<k&&0!==c};b.lin2Val=function(c){var p=this.brokenAxis;p=p&&p.breakArray;if(!p)return c;var k;for(k=0;k<p.length;k++){var f=p[k];if(f.from>=c)break;else f.to<c?c+=f.len:b.isInBreak(f,c)&&(c+=f.len)}return c};b.val2Lin=function(c){var p=this.brokenAxis;p=p&&p.breakArray;if(!p)return c;var k=c,f;for(f=0;f<p.length;f++){var r=p[f];if(r.to<=c)k-=r.len;else if(r.from>=c)break;else if(b.isInBreak(r,c)){k-=c-r.from;break}}return k};b.prototype.findBreakAt=function(b,c){return A(c,
function(c){return c.from<b&&b<c.to})};b.prototype.isInAnyBreak=function(c,k){var p=this.axis,f=p.options.breaks,w=f&&f.length,g;if(w){for(;w--;)if(b.isInBreak(f[w],c)){var d=!0;g||(g=r(f[w].showPoints,!p.isXAxis))}var l=d&&k?d&&!g:d}return l};b.prototype.setBreaks=function(u,p){var A=this,f=A.axis,w=k(u)&&!!u.length;f.isDirty=A.hasBreaks!==w;A.hasBreaks=w;f.options.breaks=f.userOptions.breaks=u;f.forceRedraw=!0;f.series.forEach(function(b){b.isDirty=!0});w||f.val2lin!==b.val2Lin||(delete f.val2lin,
delete f.lin2val);w&&(f.userOptions.ordinal=!1,f.lin2val=b.lin2Val,f.val2lin=b.val2Lin,f.setExtremes=function(b,d,f,k,p){if(A.hasBreaks){for(var l,e=this.options.breaks;l=A.findBreakAt(b,e);)b=l.to;for(;l=A.findBreakAt(d,e);)d=l.from;d<b&&(d=b)}c.prototype.setExtremes.call(this,b,d,f,k,p)},f.setAxisTranslation=function(){c.prototype.setAxisTranslation.call(this);A.unitLength=null;if(A.hasBreaks){var g=f.options.breaks||[],d=[],l=[],k=0,p,n=f.userMin||f.min,e=f.userMax||f.max,q=r(f.pointRangePadding,
0),a;g.forEach(function(a){p=a.repeat||Infinity;b.isInBreak(a,n)&&(n+=a.to%p-n%p);b.isInBreak(a,e)&&(e-=e%p-a.from%p)});g.forEach(function(b){h=b.from;for(p=b.repeat||Infinity;h-p>n;)h-=p;for(;h<n;)h+=p;for(a=h;a<e;a+=p)d.push({value:a,move:"in"}),d.push({value:a+(b.to-b.from),move:"out",size:b.breakSize})});d.sort(function(a,h){return a.value===h.value?("in"===a.move?0:1)-("in"===h.move?0:1):a.value-h.value});var z=0;var h=n;d.forEach(function(a){z+="in"===a.move?1:-1;1===z&&"in"===a.move&&(h=a.value);
0===z&&(l.push({from:h,to:a.value,len:a.value-h-(a.size||0)}),k+=a.value-h-(a.size||0))});f.breakArray=A.breakArray=l;A.unitLength=e-n-k+q;y(f,"afterBreaks");f.staticScale?f.transA=f.staticScale:A.unitLength&&(f.transA*=(e-f.min+q)/A.unitLength);q&&(f.minPixelPadding=f.transA*f.minPointOffset);f.min=n;f.max=e}});r(p,!0)&&f.chart.redraw()};return b}();B=function(){function c(){}c.compose=function(c,p){c.keepProps.push("brokenAxis");var k=C.prototype;k.drawBreaks=function(f,c){var g=this,d=g.points,
l,k,p,n;if(f&&f.brokenAxis&&f.brokenAxis.hasBreaks){var e=f.brokenAxis;c.forEach(function(q){l=e&&e.breakArray||[];k=f.isXAxis?f.min:r(g.options.threshold,f.min);d.forEach(function(a){n=r(a["stack"+q.toUpperCase()],a[q]);l.forEach(function(e){if(b(k)&&b(n)){p=!1;if(k<e.from&&n>e.to||k>e.from&&n<e.from)p="pointBreak";else if(k<e.from&&n>e.from&&n<e.to||k>e.from&&n>e.to&&n<e.from)p="pointInBreak";p&&y(f,p,{point:a,brk:e})}})})})}};k.gappedPath=function(){var b=this.currentDataGrouping,c=b&&b.gapSize;
b=this.options.gapSize;var g=this.points.slice(),d=g.length-1,l=this.yAxis,k;if(b&&0<d)for("value"!==this.options.gapUnit&&(b*=this.basePointRange),c&&c>b&&c>=this.basePointRange&&(b=c),k=void 0;d--;)k&&!1!==k.visible||(k=g[d+1]),c=g[d],!1!==k.visible&&!1!==c.visible&&(k.x-c.x>b&&(k=(c.x+k.x)/2,g.splice(d+1,0,{isNull:!0,x:k}),l.stacking&&this.options.stacking&&(k=l.stacking.stacks[this.stackKey][k]=new E(l,l.options.stackLabels,!1,k,this.stack),k.total=0)),k=c);return this.getGraphPath(g)};v(c,"init",
function(){this.brokenAxis||(this.brokenAxis=new I(this))});v(c,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});v(c,"afterSetTickPositions",function(){var b=this.brokenAxis;if(b&&b.hasBreaks){var c=this.tickPositions,g=this.tickPositions.info,d=[],l;for(l=0;l<c.length;l++)b.isInAnyBreak(c[l])||d.push(c[l]);this.tickPositions=d;this.tickPositions.info=g}});v(c,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=
!1)});v(p,"afterGeneratePoints",function(){var b=this.options.connectNulls,c=this.points,g=this.xAxis,d=this.yAxis;if(this.isDirty)for(var l=c.length;l--;){var k=c[l],p=!(null===k.y&&!1===b)&&(g&&g.brokenAxis&&g.brokenAxis.isInAnyBreak(k.x,!0)||d&&d.brokenAxis&&d.brokenAxis.isInAnyBreak(k.y,!0));k.visible=p?!1:!1!==k.options.visible}});v(p,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,r(this.pointArrayMap,["y"]))})};return c}();B.compose(c,C);return B});H(c,
"masters/modules/broken-axis.src.js",[],function(){});H(c,"Extensions/DataGrouping.js",[c["Core/Axis/Axis.js"],c["Core/Axis/DateTimeAxis.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],c["Core/Options.js"],c["Core/Series/Point.js"],c["Core/Tooltip.js"],c["Core/Utilities.js"]],function(c,C,E,B,v,A,y,k){var b=B.prototype,r=k.addEvent,I=k.arrayMax,J=k.arrayMin,u=k.correctFloat,p=k.defined,L=k.error,f=k.extend,w=k.format,g=k.isNumber,d=k.merge,l=k.pick;"";var F=E.approximations={sum:function(a){var h=
a.length;if(!h&&a.hasNulls)var e=null;else if(h)for(e=0;h--;)e+=a[h];return e},average:function(a){var h=a.length;a=F.sum(a);g(a)&&h&&(a=u(a/h));return a},averages:function(){var a=[];[].forEach.call(arguments,function(h){a.push(F.average(h))});return"undefined"===typeof a[0]?void 0:a},open:function(a){return a.length?a[0]:a.hasNulls?null:void 0},high:function(a){return a.length?I(a):a.hasNulls?null:void 0},low:function(a){return a.length?J(a):a.hasNulls?null:void 0},close:function(a){return a.length?
a[a.length-1]:a.hasNulls?null:void 0},ohlc:function(a,e,b,d){a=F.open(a);e=F.high(e);b=F.low(b);d=F.close(d);if(g(a)||g(e)||g(b)||g(d))return[a,e,b,d]},range:function(a,e){a=F.low(a);e=F.high(e);if(g(a)||g(e))return[a,e];if(null===a&&null===e)return null}};k=function(a,e,b,q){var h=this,t=h.data,f=h.options&&h.options.data,m=[],z=[],x=[],c=a.length,l=!!e,n=[],k=h.pointArrayMap,r=k&&k.length,w=["x"].concat(k||["y"]),A=0,y=0,u;q="function"===typeof q?q:F[q]?F[q]:F[h.getDGApproximation&&h.getDGApproximation()||
"average"];r?k.forEach(function(){n.push([])}):n.push([]);var B=r||1;for(u=0;u<=c&&!(a[u]>=b[0]);u++);for(u;u<=c;u++){for(;"undefined"!==typeof b[A+1]&&a[u]>=b[A+1]||u===c;){var v=b[A];h.dataGroupInfo={start:h.cropStart+y,length:n[0].length};var C=q.apply(h,n);h.pointClass&&!p(h.dataGroupInfo.options)&&(h.dataGroupInfo.options=d(h.pointClass.prototype.optionsToObject.call({series:h},h.options.data[h.cropStart+y])),w.forEach(function(a){delete h.dataGroupInfo.options[a]}));"undefined"!==typeof C&&
(m.push(v),z.push(C),x.push(h.dataGroupInfo));y=u;for(v=0;v<B;v++)n[v].length=0,n[v].hasNulls=!1;A+=1;if(u===c)break}if(u===c)break;if(k)for(v=h.cropStart+u,C=t&&t[v]||h.pointClass.prototype.applyOptions.apply({series:h},[f[v]]),v=0;v<r;v++){var E=C[k[v]];g(E)?n[v].push(E):null===E&&(n[v].hasNulls=!0)}else v=l?e[u]:null,g(v)?n[0].push(v):null===v&&(n[0].hasNulls=!0)}return{groupedXData:m,groupedYData:z,groupMap:x}};var K={approximations:F,groupData:k},n=b.processData,e=b.generatePoints,q={groupPixelWidth:2,
dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},a={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},
columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},z=E.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];b.getDGApproximation=function(){return this.is("arearange")?"range":this.is("ohlc")?"ohlc":this.is("column")?"sum":"average"};b.groupData=k;b.processData=function(){var a=this.chart,e=this.options.dataGrouping,
d=!1!==this.allowDG&&e&&l(e.enabled,a.options.isStock),q=this.visible||!a.options.chart.ignoreHiddenSeries,f,c=this.currentDataGrouping,g=!1;this.forceCrop=d;this.groupPixelWidth=null;this.hasProcessed=!0;d&&!this.requireSorting&&(this.requireSorting=g=!0);d=!1===n.apply(this,arguments)||!d;g&&(this.requireSorting=!1);if(!d){this.destroyGroupedData();d=e.groupAll?this.xData:this.processedXData;var k=e.groupAll?this.yData:this.processedYData,r=a.plotSizeX;a=this.xAxis;var w=a.options.ordinal,A=this.groupPixelWidth=
a.getGroupPixelWidth&&a.getGroupPixelWidth();if(A){this.isDirty=f=!0;this.points=null;g=a.getExtremes();var u=g.min;g=g.max;w=w&&a.ordinal&&a.ordinal.getGroupIntervalFactor(u,g,this)||1;A=A*(g-u)/r*w;r=a.getTimeTicks(C.AdditionsClass.prototype.normalizeTimeTickInterval(A,e.units||z),Math.min(u,d[0]),Math.max(g,d[d.length-1]),a.options.startOfWeek,d,this.closestPointRange);k=b.groupData.apply(this,[d,k,r,e.approximation]);d=k.groupedXData;w=k.groupedYData;var v=0;if(e.smoothed&&d.length){var y=d.length-
1;for(d[y]=Math.min(d[y],g);y--&&0<y;)d[y]+=A/2;d[0]=Math.max(d[0],u)}for(y=1;y<r.length;y++)r.info.segmentStarts&&-1!==r.info.segmentStarts.indexOf(y)||(v=Math.max(r[y]-r[y-1],v));u=r.info;u.gapSize=v;this.closestPointRange=r.info.totalRange;this.groupMap=k.groupMap;if(p(d[0])&&d[0]<a.min&&q){if(!p(a.options.min)&&a.min<=a.dataMin||a.min===a.dataMin)a.min=Math.min(d[0],a.min);a.dataMin=Math.min(d[0],a.dataMin)}e.groupAll&&(e=this.cropData(d,w,a.min,a.max,1),d=e.xData,w=e.yData);this.processedXData=
d;this.processedYData=w}else this.groupMap=null;this.hasGroupedData=f;this.currentDataGrouping=u;this.preventGraphAnimation=(c&&c.totalRange)!==(u&&u.totalRange)}};b.destroyGroupedData=function(){this.groupedData&&(this.groupedData.forEach(function(a,e){a&&(this.groupedData[e]=a.destroy?a.destroy():null)},this),this.groupedData.length=0)};b.generatePoints=function(){e.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};r(A,"update",function(){if(this.dataGroup)return L(24,
!1,this.series.chart),!1});r(y,"headerFormatter",function(a){var e=this.chart,h=e.time,d=a.labelConfig,b=d.series,c=b.tooltipOptions,z=b.options.dataGrouping,l=c.xDateFormat,n=b.xAxis,k=c[(a.isFooter?"footer":"header")+"Format"];if(n&&"datetime"===n.options.type&&z&&g(d.key)){var p=b.currentDataGrouping;z=z.dateTimeLabelFormats||q.dateTimeLabelFormats;if(p)if(c=z[p.unitName],1===p.count)l=c[0];else{l=c[1];var r=c[2]}else!l&&z&&(l=this.getXDateFormat(d,c,n));l=h.dateFormat(l,d.key);r&&(l+=h.dateFormat(r,
d.key+p.totalRange-1));b.chart.styledMode&&(k=this.styledModeFormat(k));a.text=w(k,{point:f(d.point,{key:l}),series:b},e);a.preventDefault()}});r(B,"destroy",b.destroyGroupedData);r(B,"afterSetOptions",function(e){e=e.options;var h=this.type,b=this.chart.options.plotOptions,f=v.defaultOptions.plotOptions[h].dataGrouping,c=this.useCommonDataGrouping&&q;if(a[h]||c)f||(f=d(q,a[h])),e.dataGrouping=d(c,f,b.series&&b.series.dataGrouping,b[h].dataGrouping,this.userOptions.dataGrouping)});r(c,"afterSetScale",
function(){this.series.forEach(function(a){a.hasProcessed=!1})});c.prototype.getGroupPixelWidth=function(){var a=this.series,e=a.length,d,b=0,f=!1,c;for(d=e;d--;)(c=a[d].options.dataGrouping)&&(b=Math.max(b,l(c.groupPixelWidth,q.groupPixelWidth)));for(d=e;d--;)(c=a[d].options.dataGrouping)&&a[d].hasProcessed&&(e=(a[d].processedXData||a[d].data).length,a[d].groupPixelWidth||e>this.chart.plotSizeX/b||e&&c.forced)&&(f=!0);return f?b:0};c.prototype.setDataGrouping=function(a,e){var d;e=l(e,!0);a||(a=
{forced:!1,units:null});if(this instanceof c)for(d=this.series.length;d--;)this.series[d].update({dataGrouping:a},!1);else this.chart.options.series.forEach(function(e){e.dataGrouping=a},!1);this.ordinal&&(this.ordinal.slope=void 0);e&&this.chart.redraw()};E.dataGrouping=K;"";return K});H(c,"Series/OHLCSeries.js",[c["Core/Series/Series.js"],c["Series/Column/ColumnSeries.js"],c["Core/Series/Point.js"]],function(c,C,E){var B=C.prototype;c.seriesType("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},
threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(c){return[c.open,c.high,c.low,c.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},init:function(){B.init.apply(this,arguments);this.options.stacking=void 0},pointAttribs:function(c,A){A=B.pointAttribs.call(this,c,A);var y=this.options;delete A.fill;!c.options.color&&y.upColor&&c.open<c.close&&(A.stroke=y.upColor);return A},
translate:function(){var c=this,A=c.yAxis,y=!!c.modifyValue,k=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];B.translate.apply(c);c.points.forEach(function(b){[b.open,b.high,b.low,b.close,b.low].forEach(function(r,v){null!==r&&(y&&(r=c.modifyValue(r)),b[k[v]]=A.toPixels(r,!0))});b.tooltipPos[1]=b.plotHigh+A.pos-c.chart.plotTop})},drawPoints:function(){var c=this,A=c.chart,y=function(c,b,r){var k=c[0];c=c[1];"number"===typeof k[2]&&(k[2]=Math.max(r+b,k[2]));"number"===typeof c[2]&&(c[2]=Math.min(r-
b,c[2]))};c.points.forEach(function(k){var b=k.graphic,r=!b;if("undefined"!==typeof k.plotY){b||(k.graphic=b=A.renderer.path().add(c.group));A.styledMode||b.attr(c.pointAttribs(k,k.selected&&"select"));var v=b.strokeWidth();var B=v%2/2;var u=Math.round(k.plotX)-B;var p=Math.round(k.shapeArgs.width/2);var C=[["M",u,Math.round(k.yBottom)],["L",u,Math.round(k.plotHigh)]];if(null!==k.open){var f=Math.round(k.plotOpen)+B;C.push(["M",u,f],["L",u-p,f]);y(C,v/2,f)}null!==k.close&&(f=Math.round(k.plotClose)+
B,C.push(["M",u,f],["L",u+p,f]),y(C,v/2,f));b[r?"attr":"animate"]({d:C}).addClass(k.getClassName(),!0)}})},animate:null},{getClassName:function(){return E.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}});""});H(c,"Series/CandlestickSeries.js",[c["Core/Series/Series.js"],c["Series/Column/ColumnSeries.js"],c["Core/Options.js"],c["Core/Utilities.js"]],function(c,C,E,B){var v=C.prototype;C=E.defaultOptions;B=B.merge;c.seriesType("candlestick",
"ohlc",B(C.plotOptions.column,{states:{hover:{lineWidth:2}},tooltip:C.plotOptions.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(c,y){var k=v.pointAttribs.call(this,c,y),b=this.options,r=c.open<c.close,A=b.lineColor||this.color;k["stroke-width"]=b.lineWidth;k.fill=c.options.color||(r?b.upColor||this.color:this.color);k.stroke=c.options.lineColor||(r?b.upLineColor||A:A);y&&(c=b.states[y],k.fill=c.color||k.fill,k.stroke=c.lineColor||
k.stroke,k["stroke-width"]=c.lineWidth||k["stroke-width"]);return k},drawPoints:function(){var c=this,y=c.chart,k=c.yAxis.reversed;c.points.forEach(function(b){var r=b.graphic,A=!r;if("undefined"!==typeof b.plotY){r||(b.graphic=r=y.renderer.path().add(c.group));c.chart.styledMode||r.attr(c.pointAttribs(b,b.selected&&"select")).shadow(c.options.shadow);var v=r.strokeWidth()%2/2;var u=Math.round(b.plotX)-v;var p=b.plotOpen;var B=b.plotClose;var f=Math.min(p,B);p=Math.max(p,B);var w=Math.round(b.shapeArgs.width/
2);B=k?p!==b.yBottom:Math.round(f)!==Math.round(b.plotHigh);var g=k?Math.round(f)!==Math.round(b.plotHigh):p!==b.yBottom;f=Math.round(f)+v;p=Math.round(p)+v;v=[];v.push(["M",u-w,p],["L",u-w,f],["L",u+w,f],["L",u+w,p],["Z"],["M",u,f],["L",u,B?Math.round(k?b.yBottom:b.plotHigh):f],["M",u,p],["L",u,g?Math.round(k?b.plotHigh:b.yBottom):p]);r[A?"attr":"animate"]({d:v}).addClass(b.getClassName(),!0)}})}});""});H(c,"Mixins/OnSeries.js",[c["Series/Column/ColumnSeries.js"],c["Series/Line/LineSeries.js"],c["Core/Utilities.js"]],
function(c,C,E){var B=c.prototype,v=C.prototype,A=E.defined,y=E.stableSort;return{getPlotBox:function(){return v.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){B.translate.apply(this);var c=this,b=c.options,r=c.chart,v=c.points,C=v.length-1,u,p=b.onSeries;p=p&&r.get(p);b=b.onKey||"y";var E=p&&p.options.step,f=p&&p.points,w=f&&f.length,g=r.inverted,d=c.xAxis,l=c.yAxis,F=0,K;if(p&&p.visible&&w){F=(p.pointXOffset||0)+(p.barW||0)/2;r=p.currentDataGrouping;
var n=f[w-1].x+(r?r.totalRange:0);y(v,function(a,e){return a.x-e.x});for(b="plot"+b[0].toUpperCase()+b.substr(1);w--&&v[C];){var e=f[w];r=v[C];r.y=e.y;if(e.x<=r.x&&"undefined"!==typeof e[b]){if(r.x<=n&&(r.plotY=e[b],e.x<r.x&&!E&&(K=f[w+1])&&"undefined"!==typeof K[b])){var q=(r.x-e.x)/(K.x-e.x);r.plotY+=q*(K[b]-e[b]);r.y+=q*(K.y-e.y)}C--;w++;if(0>C)break}}}v.forEach(function(a,e){a.plotX+=F;if("undefined"===typeof a.plotY||g)0<=a.plotX&&a.plotX<=d.len?g?(a.plotY=d.translate(a.x,0,1,0,1),a.plotX=A(a.y)?
l.translate(a.y,0,0,0,1):0):a.plotY=(d.opposite?0:c.yAxis.len)+d.offset:a.shapeArgs={};if((u=v[e-1])&&u.plotX===a.plotX){"undefined"===typeof u.stackIndex&&(u.stackIndex=0);var b=u.stackIndex+1}a.stackIndex=b});this.onSeries=p}}});H(c,"Series/FlagsSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],c["Mixins/OnSeries.js"],c["Core/Renderer/SVG/SVGElement.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Utilities.js"]],function(c,C,E,B,v,A,y){function k(d){g[d+
"pin"]=function(b,c,f,n,e){var q=e&&e.anchorX;e=e&&e.anchorY;"circle"===d&&n>f&&(b-=Math.round((n-f)/2),f=n);var a=g[d](b,c,f,n);if(q&&e){var z=q;"circle"===d?z=b+f/2:(b=a[0],f=a[1],"M"===b[0]&&"L"===f[0]&&(z=(b[1]+f[1])/2));a.push(["M",z,c>e?c:c+n],["L",q,e]);a=a.concat(g.circle(q-1,e-1,2,2))}return a}}var b=C.noop,r=y.addEvent,I=y.defined,J=y.isNumber,u=y.merge,p=y.objectEach,H=y.wrap;y=C.Renderer;var f=C.TrackerMixin,w=C.VMLRenderer,g=A.prototype.symbols;"";c.seriesType("flags","column",{pointRange:0,
allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30,fillColor:"#ffffff",lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:E.prototype.init,pointAttribs:function(d,b){var c=this.options,f=d&&d.color||this.color,l=c.lineColor,e=d&&d.lineWidth;d=d&&d.fillColor||
c.fillColor;b&&(d=c.states[b].fillColor,l=c.states[b].lineColor,e=c.states[b].lineWidth);return{fill:d||f,stroke:l||f,"stroke-width":e||c.lineWidth||0}},translate:B.translate,getPlotBox:B.getPlotBox,drawPoints:function(){var d=this.points,b=this.chart,c=b.renderer,f=b.inverted,n=this.options,e=n.y,q,a=this.yAxis,z={},h=[];for(q=d.length;q--;){var x=d[q];var t=(f?x.plotY:x.plotX)>this.xAxis.len;var m=x.plotX;var g=x.stackIndex;var k=x.options.shape||n.shape;var r=x.plotY;"undefined"!==typeof r&&(r=
x.plotY+e-("undefined"!==typeof g&&g*n.stackDistance));x.anchorX=g?void 0:x.plotX;var w=g?void 0:x.plotY;var y="flag"!==k;g=x.graphic;"undefined"!==typeof r&&0<=m&&!t?(g||(g=x.graphic=c.label("",null,null,k,null,null,n.useHTML),b.styledMode||g.attr(this.pointAttribs(x)).css(u(n.style,x.style)),g.attr({align:y?"center":"left",width:n.width,height:n.height,"text-align":n.textAlign}).addClass("highcharts-point").add(this.markerGroup),x.graphic.div&&(x.graphic.div.point=x),b.styledMode||g.shadow(n.shadow),
g.isNew=!0),0<m&&(m-=g.strokeWidth()%2),k={y:r,anchorY:w},n.allowOverlapX&&(k.x=m,k.anchorX=x.anchorX),g.attr({text:x.options.title||n.title||"A"})[g.isNew?"attr":"animate"](k),n.allowOverlapX||(z[x.plotX]?z[x.plotX].size=Math.max(z[x.plotX].size,g.width):z[x.plotX]={align:y?.5:0,size:g.width,target:m,anchorX:m}),x.tooltipPos=[m,r+a.pos-b.plotTop]):g&&(x.graphic=g.destroy())}n.allowOverlapX||(p(z,function(a){a.plotX=a.anchorX;h.push(a)}),C.distribute(h,f?a.len:this.xAxis.len,100),d.forEach(function(a){var e=
a.graphic&&z[a.plotX];e&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:e.pos+e.align*e.size,anchorX:a.anchorX}),I(e.pos)?a.graphic.isNew=!1:(a.graphic.attr({x:-9999,anchorX:-9999}),a.graphic.isNew=!0))}));n.useHTML&&H(this.markerGroup,"on",function(a){return v.prototype.on.apply(a.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var b=this.points;f.drawTrackerPoint.apply(this);b.forEach(function(d){var c=d.graphic;c&&r(c.element,"mouseover",function(){0<
d.stackIndex&&!d.raised&&(d._y=c.y,c.attr({y:d._y-8}),d.raised=!0);b.forEach(function(b){b!==d&&b.raised&&b.graphic&&(b.graphic.attr({y:b._y}),b.raised=!1)})})})},animate:function(b){b&&this.setClip()},setClip:function(){E.prototype.setClip.apply(this,arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])},buildKDTree:b,invertGroups:b},{isValid:function(){return J(this.y)||"undefined"===typeof this.y}});g.flag=function(b,c,f,k,n){var e=n&&n.anchorX||
b;n=n&&n.anchorY||c;var d=g.circle(e-1,n-1,2,2);d.push(["M",e,n],["L",b,c+k],["L",b,c],["L",b+f,c],["L",b+f,c+k],["L",b,c+k],["Z"]);return d};k("circle");k("square");y===w&&["circlepin","flag","squarepin"].forEach(function(b){w.prototype.symbols[b]=g[b]});""});H(c,"Extensions/RangeSelector.js",[c["Core/Axis/Axis.js"],c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Options.js"],c["Core/Renderer/SVG/SVGElement.js"],c["Core/Utilities.js"]],function(c,C,E,B,v,A){var y=B.defaultOptions,k=A.addEvent,
b=A.createElement,r=A.css,I=A.defined,J=A.destroyObjectProperties,u=A.discardElement,p=A.extend,H=A.fireEvent,f=A.isNumber,w=A.merge,g=A.objectEach,d=A.pick,l=A.pInt,F=A.splat;p(y,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});y.lang=w(y.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});var K=
function(){function n(e){this.buttons=void 0;this.buttonOptions=n.prototype.defaultButtons;this.options=void 0;this.chart=e;this.init(e)}n.prototype.clickButton=function(e,b){var a=this.chart,q=this.buttonOptions[e],h=a.xAxis[0],g=a.scroller&&a.scroller.getUnionExtremes()||h||{},t=g.dataMin,m=g.dataMax,n=h&&Math.round(Math.min(h.max,d(m,h.max))),l=q.type;g=q._range;var p,r=q.dataGrouping;if(null!==t&&null!==m){a.fixedRange=g;r&&(this.forcedDataGrouping=!0,c.prototype.setDataGrouping.call(h||{chart:this.chart},
r,!1),this.frozenStates=q.preserveDataGrouping);if("month"===l||"year"===l)if(h){l={range:q,max:n,chart:a,dataMin:t,dataMax:m};var w=h.minFromRange.call(l);f(l.newMax)&&(n=l.newMax)}else g=q;else if(g)w=Math.max(n-g,t),n=Math.min(w+g,m);else if("ytd"===l)if(h)"undefined"===typeof m&&(t=Number.MAX_VALUE,m=Number.MIN_VALUE,a.series.forEach(function(a){a=a.xData;t=Math.min(a[0],t);m=Math.max(a[a.length-1],m)}),b=!1),n=this.getYTDExtremes(m,t,a.time.useUTC),w=p=n.min,n=n.max;else{this.deferredYTDClick=
e;return}else"all"===l&&h&&(w=t,n=m);I(w)&&(w+=q._offsetMin);I(n)&&(n+=q._offsetMax);this.setSelected(e);if(h)h.setExtremes(w,n,d(b,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:q});else{var y=F(a.options.xAxis)[0];var u=y.range;y.range=g;var v=y.min;y.min=p;k(a,"load",function(){y.range=u;y.min=v})}}};n.prototype.setSelected=function(e){this.selected=this.options.selected=e};n.prototype.init=function(e){var b=this,a=e.options.rangeSelector,c=a.buttons||b.defaultButtons.slice(),d=a.selected,
f=function(){var a=b.minInput,e=b.maxInput;a&&a.blur&&H(a,"blur");e&&e.blur&&H(e,"blur")};b.chart=e;b.options=a;b.buttons=[];b.buttonOptions=c;this.unMouseDown=k(e.container,"mousedown",f);this.unResize=k(e,"resize",f);c.forEach(b.computeButtonRange);"undefined"!==typeof d&&c[d]&&this.clickButton(d,!1);k(e,"load",function(){e.xAxis&&e.xAxis[0]&&k(e.xAxis[0],"setExtremes",function(a){this.max-this.min!==e.fixedRange&&"rangeSelectorButton"!==a.trigger&&"updatedData"!==a.trigger&&b.forcedDataGrouping&&
!b.frozenStates&&this.setDataGrouping(!1,!1)})})};n.prototype.updateButtonStates=function(){var b=this,c=this.chart,a=c.xAxis[0],d=Math.round(a.max-a.min),h=!a.hasVisibleSeries,g=c.scroller&&c.scroller.getUnionExtremes()||a,n=g.dataMin,m=g.dataMax;c=b.getYTDExtremes(m,n,c.time.useUTC);var l=c.min,k=c.max,p=b.selected,r=f(p),w=b.options.allButtonsEnabled,y=b.buttons;b.buttonOptions.forEach(function(e,c){var f=e._range,q=e.type,g=e.count||1,z=y[c],t=0,x=e._offsetMax-e._offsetMin;e=c===p;var D=f>m-n,
u=f<a.minRange,v=!1,G=!1;f=f===d;("month"===q||"year"===q)&&d+36E5>=864E5*{month:28,year:365}[q]*g-x&&d-36E5<=864E5*{month:31,year:366}[q]*g+x?f=!0:"ytd"===q?(f=k-l+x===d,v=!e):"all"===q&&(f=a.max-a.min>=m-n,G=!e&&r&&f);q=!w&&(D||u||G||h);g=e&&f||f&&!r&&!v||e&&b.frozenStates;q?t=3:g&&(r=!0,t=2);z.state!==t&&(z.setState(t),0===t&&p===c&&b.setSelected(null))})};n.prototype.computeButtonRange=function(b){var e=b.type,a=b.count||1,c={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};
if(c[e])b._range=c[e]*a;else if("month"===e||"year"===e)b._range=864E5*{month:30,year:365}[e]*a;b._offsetMin=d(b.offsetMin,0);b._offsetMax=d(b.offsetMax,0);b._range+=b._offsetMax-b._offsetMin};n.prototype.setInputValue=function(b,c){var a=this.chart.options.rangeSelector,e=this.chart.time,d=this[b+"Input"];I(c)&&(d.previousValue=d.HCTime,d.HCTime=c);d.value=e.dateFormat(a.inputEditDateFormat||"%Y-%m-%d",d.HCTime);this[b+"DateBox"].attr({text:e.dateFormat(a.inputDateFormat||"%b %e, %Y",d.HCTime)})};
n.prototype.showInput=function(b){var e=this.inputGroup,a=this[b+"DateBox"];r(this[b+"Input"],{left:e.translateX+a.x+"px",top:e.translateY+"px",width:a.width-2+"px",height:a.height-2+"px",border:"2px solid silver"})};n.prototype.hideInput=function(b){r(this[b+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(b)};n.prototype.defaultInputDateParser=function(b,c){var a=new Date;return E.isSafari?Date.parse(b.split(" ").join("T")):c?Date.parse(b+"Z"):Date.parse(b)-6E4*a.getTimezoneOffset()};
n.prototype.drawInput=function(e){function c(){var b=u.value,e=d.xAxis[0];var c=d.scroller&&d.scroller.xAxis?d.scroller.xAxis:e;var h=c.dataMin,q=c.dataMax;c=(n.inputDateParser||B)(b,d.time.useUTC);c!==u.previousValue&&(u.previousValue=c,f(c)||(c=b.split("-"),c=Date.UTC(l(c[0]),l(c[1])-1,l(c[2]))),f(c)&&(d.time.useUTC||(c+=6E4*(new Date).getTimezoneOffset()),k?c>a.maxInput.HCTime?c=void 0:c<h&&(c=h):c<a.minInput.HCTime?c=void 0:c>q&&(c=q),"undefined"!==typeof c&&e.setExtremes(k?c:e.min,k?e.max:c,
void 0,void 0,{trigger:"rangeSelectorInput"})))}var a=this,d=a.chart,h=d.renderer.style||{},g=d.renderer,n=d.options.rangeSelector,m=a.div,k="min"===e,u,v,A=this.inputGroup,B=this.defaultInputDateParser;this[e+"Label"]=v=g.label(y.lang[k?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(A);A.offset+=v.width+5;this[e+"DateBox"]=g=g.label("",A.offset).addClass("highcharts-range-input").attr({padding:2,width:n.inputBoxWidth||90,height:n.inputBoxHeight||
17,"text-align":"center"}).on("click",function(){a.showInput(e);a[e+"Input"].focus()});d.styledMode||g.attr({stroke:n.inputBoxBorderColor||"#cccccc","stroke-width":1});g.add(A);A.offset+=g.width+(k?10:0);this[e+"Input"]=u=b("input",{name:e,className:"highcharts-range-selector",type:"text"},{top:d.plotTop+"px"},m);d.styledMode||(v.css(w(h,n.labelStyle)),g.css(w({color:"#333333"},h,n.inputStyle)),r(u,p({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:h.fontSize,
fontFamily:h.fontFamily,top:"-9999em"},n.inputStyle)));u.onfocus=function(){a.showInput(e)};u.onblur=function(){u===E.doc.activeElement&&c();a.hideInput(e);u.blur()};u.onchange=c;u.onkeypress=function(a){13===a.keyCode&&c()}};n.prototype.getPosition=function(){var b=this.chart,c=b.options.rangeSelector;b="top"===c.verticalAlign?b.plotTop-b.axisOffset[0]:0;return{buttonTop:b+c.buttonPosition.y,inputTop:b+c.inputPosition.y-10}};n.prototype.getYTDExtremes=function(b,c,a){var d=this.chart.time,e=new d.Date(b),
f=d.get("FullYear",e);a=a?d.Date.UTC(f,0,1):+new d.Date(f,0,1);c=Math.max(c||0,a);e=e.getTime();return{max:Math.min(b||e,e),min:c}};n.prototype.render=function(c,f){var a=this,e=a.chart,h=e.renderer,q=e.container,g=e.options,m=g.exporting&&!1!==g.exporting.enabled&&g.navigation&&g.navigation.buttonOptions,n=y.lang,l=a.div,k=g.rangeSelector,p=d(g.chart.style&&g.chart.style.zIndex,0)+1;g=k.floating;var r=a.buttons;l=a.inputGroup;var u=k.buttonTheme,w=k.buttonPosition,v=k.inputPosition,A=k.inputEnabled,
B=u&&u.states,C=e.plotLeft,E=a.buttonGroup,F,P=a.options.verticalAlign,Q=e.legend,H=Q&&Q.options,J=w.y,I=v.y,K=e.hasLoaded,L=K?"animate":"attr",O=0,N=0;if(!1!==k.enabled){a.rendered||(a.group=F=h.g("range-selector-group").attr({zIndex:7}).add(),a.buttonGroup=E=h.g("range-selector-buttons").add(F),a.zoomText=h.text(n.rangeSelectorZoom,0,15).add(E),e.styledMode||(a.zoomText.css(k.labelStyle),u["stroke-width"]=d(u["stroke-width"],0)),a.buttonOptions.forEach(function(b,c){r[c]=h.button(b.text,0,0,function(e){var d=
b.events&&b.events.click,f;d&&(f=d.call(b,e));!1!==f&&a.clickButton(c);a.isActive=!0},u,B&&B.hover,B&&B.select,B&&B.disabled).attr({"text-align":"center"}).add(E)}),!1!==A&&(a.div=l=b("div",null,{position:"relative",height:0,zIndex:p}),q.parentNode.insertBefore(l,q),a.inputGroup=l=h.g("input-group").add(F),l.offset=0,a.drawInput("min"),a.drawInput("max")));a.zoomText[L]({x:d(C+w.x,C)});var R=d(C+w.x,C)+a.zoomText.getBBox().width+5;a.buttonOptions.forEach(function(a,b){r[b][L]({x:R});R+=r[b].width+
d(k.buttonSpacing,5)});C=e.plotLeft-e.spacing[3];a.updateButtonStates();m&&this.titleCollision(e)&&"top"===P&&"right"===w.align&&w.y+E.getBBox().height-12<(m.y||0)+m.height&&(O=-40);q=w.x-e.spacing[3];"right"===w.align?q+=O-C:"center"===w.align&&(q-=C/2);E.align({y:w.y,width:E.getBBox().width,align:w.align,x:q},!0,e.spacingBox);a.group.placed=K;a.buttonGroup.placed=K;!1!==A&&(O=m&&this.titleCollision(e)&&"top"===P&&"right"===v.align&&v.y-l.getBBox().height-12<(m.y||0)+m.height+e.spacing[0]?-40:0,
"left"===v.align?q=C:"right"===v.align&&(q=-Math.max(e.axisOffset[1],-O)),l.align({y:v.y,width:l.getBBox().width,align:v.align,x:v.x+q-2},!0,e.spacingBox),m=l.alignAttr.translateX+l.alignOptions.x-O+l.getBBox().x+2,q=l.alignOptions.width,n=E.alignAttr.translateX+E.getBBox().x,C=E.getBBox().width+20,(v.align===w.align||n+C>m&&m+q>n&&J<I+l.getBBox().height)&&l.attr({translateX:l.alignAttr.translateX+(e.axisOffset[1]>=-O?0:-O),translateY:l.alignAttr.translateY+E.getBBox().height+10}),a.setInputValue("min",
c),a.setInputValue("max",f),a.inputGroup.placed=K);a.group.align({verticalAlign:P},!0,e.spacingBox);c=a.group.getBBox().height+20;f=a.group.alignAttr.translateY;"bottom"===P&&(Q=H&&"bottom"===H.verticalAlign&&H.enabled&&!H.floating?Q.legendHeight+d(H.margin,10):0,c=c+Q-20,N=f-c-(g?0:k.y)-(e.titleOffset?e.titleOffset[2]:0)-10);if("top"===P)g&&(N=0),e.titleOffset&&e.titleOffset[0]&&(N=e.titleOffset[0]),N+=e.margin[0]-e.spacing[0]||0;else if("middle"===P)if(I===J)N=0>I?f+void 0:f;else if(I||J)N=0>I||
0>J?N-Math.min(I,J):f-c+NaN;a.group.translate(k.x,k.y+Math.floor(N));!1!==A&&(a.minInput.style.marginTop=a.group.translateY+"px",a.maxInput.style.marginTop=a.group.translateY+"px");a.rendered=!0}};n.prototype.getHeight=function(){var b=this.options,c=this.group,a=b.y,d=b.buttonPosition.y,f=b.inputPosition.y;if(b.height)return b.height;b=c?c.getBBox(!0).height+13+a:0;c=Math.min(f,d);if(0>f&&0>d||0<f&&0<d)b+=Math.abs(c);return b};n.prototype.titleCollision=function(b){return!(b.options.title.text||
b.options.subtitle.text)};n.prototype.update=function(b){var c=this.chart;w(!0,c.options.rangeSelector,b);this.destroy();this.init(c);c.rangeSelector.render()};n.prototype.destroy=function(){var b=this,c=b.minInput,a=b.maxInput;b.unMouseDown();b.unResize();J(b.buttons);c&&(c.onfocus=c.onblur=c.onchange=null);a&&(a.onfocus=a.onblur=a.onchange=null);g(b,function(a,c){a&&"chart"!==c&&(a instanceof v?a.destroy():a instanceof window.HTMLElement&&u(a));a!==n.prototype[c]&&(b[c]=null)},this)};return n}();
K.prototype.defaultButtons=[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}];c.prototype.minFromRange=function(){var b=this.range,c=b.type,g=this.max,a=this.chart.time,l=function(b,d){var e="year"===c?"FullYear":"Month",f=new a.Date(b),h=a.get(e,f);a.set(e,f,h+d);h===a.get(e,f)&&a.set("Date",f,0);return f.getTime()-b};if(f(b)){var h=g-b;var k=b}else h=g+l(g,-b.count),
this.chart&&(this.chart.fixedRange=g-h);var t=d(this.dataMin,Number.MIN_VALUE);f(h)||(h=t);h<=t&&(h=t,"undefined"===typeof k&&(k=l(h,b.count)),this.newMax=Math.min(h+k,this.dataMax));f(g)||(h=void 0);return h};E.RangeSelector||(k(C,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new K(this))}),k(C,"beforeRender",function(){var b=this.axes,c=this.rangeSelector;c&&(f(c.deferredYTDClick)&&(c.clickButton(c.deferredYTDClick),delete c.deferredYTDClick),b.forEach(function(b){b.updateNames();
b.setScale()}),this.getAxisMargins(),c.render(),b=c.options.verticalAlign,c.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)))}),k(C,"update",function(b){var c=b.options.rangeSelector;b=this.rangeSelector;var d=this.extraBottomMargin,a=this.extraTopMargin;c&&c.enabled&&!I(b)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new K(this));this.extraTopMargin=this.extraBottomMargin=!1;b&&(b.render(),c=c&&c.verticalAlign||b.options&&b.options.verticalAlign,
b.options.floating||("bottom"===c?this.extraBottomMargin=!0:"middle"!==c&&(this.extraTopMargin=!0)),this.extraBottomMargin!==d||this.extraTopMargin!==a)&&(this.isDirtyBox=!0)}),k(C,"render",function(){var b=this.rangeSelector;b&&!b.options.floating&&(b.render(),b=b.options.verticalAlign,"bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0))}),k(C,"getMargins",function(){var b=this.rangeSelector;b&&(b=b.getHeight(),this.extraTopMargin&&(this.plotTop+=b),this.extraBottomMargin&&
(this.marginBottom+=b))}),C.prototype.callbacks.push(function(b){function c(){d=b.xAxis[0].getExtremes();g=b.legend;l=null===a||void 0===a?void 0:a.options.verticalAlign;f(d.min)&&a.render(d.min,d.max);a&&g.display&&"top"===l&&l===g.options.verticalAlign&&(h=w(b.spacingBox),h.y="vertical"===g.options.layout?b.plotTop:h.y+a.getHeight(),g.group.placed=!1,g.align(h))}var d,a=b.rangeSelector,g,h,l;if(a){var t=k(b.xAxis[0],"afterSetExtremes",function(b){a.render(b.min,b.max)});var m=k(b,"redraw",c);c()}k(b,
"destroy",function(){a&&(m(),t())})}),E.RangeSelector=K);return E.RangeSelector});H(c,"Core/Chart/StockChart.js",[c["Core/Axis/Axis.js"],c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],c["Core/Series/Point.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Utilities.js"]],function(c,C,E,B,v,A,y){var k=y.addEvent,b=y.arrayMax,r=y.arrayMin,H=y.clamp,J=y.defined,u=y.extend,p=y.find,L=y.format,f=y.getOptions,w=y.isNumber,g=y.isString,d=y.merge,l=y.pick,F=y.splat;y=B.prototype;
var K=y.init,n=y.processData,e=v.prototype.tooltipFormatter;E.StockChart=E.stockChart=function(b,a,c){var e=g(b)||b.nodeName,q=arguments[e?1:0],k=q,m=q.series,n=f(),p,r=l(q.navigator&&q.navigator.enabled,n.navigator.enabled,!0);q.xAxis=F(q.xAxis||{}).map(function(a,b){return d({minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},n.xAxis,n.xAxis&&n.xAxis[b],a,{type:"datetime",categories:null},r?{startOnTick:!1,endOnTick:!1}:null)});q.yAxis=
F(q.yAxis||{}).map(function(a,b){p=l(a.opposite,!0);return d({labels:{y:-2},opposite:p,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},n.yAxis,n.yAxis&&n.yAxis[b],a)});q.series=null;q=d({chart:{panning:{enabled:!0,type:"x"},pinchType:"x"},navigator:{enabled:r},scrollbar:{enabled:l(n.scrollbar.enabled,!0)},rangeSelector:{enabled:l(n.rangeSelector.enabled,!0)},title:{text:null},tooltip:{split:l(n.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},q,{isStock:!0});q.series=k.series=
m;return e?new C(b,q,c):new C(q,a)};k(B,"setOptions",function(b){var a;this.chart.options.isStock&&(this.is("column")||this.is("columnrange")?a={borderWidth:0,shadow:!1}:this.is("scatter")||this.is("sma")||(a={marker:{enabled:!1,radius:2}}),a&&(b.plotOptions[this.type]=d(b.plotOptions[this.type],a)))});k(c,"autoLabelAlign",function(b){var a=this.chart,c=this.options;a=a._labelPanes=a._labelPanes||{};var d=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!a[c]&&
d.enabled&&(15===d.x&&(d.x=0),"undefined"===typeof d.align&&(d.align="right"),a[c]=this,b.align="right",b.preventDefault()))});k(c,"destroy",function(){var b=this.chart,a=this.options&&this.options.top+","+this.options.height;a&&b._labelPanes&&b._labelPanes[a]===this&&delete b._labelPanes[a]});k(c,"getPlotLinePath",function(b){function a(a){var b="xAxis"===a?"yAxis":"xAxis";a=c.options[b];return w(a)?[e[b][a]]:g(a)?[e.get(a)]:d.map(function(a){return a[b]})}var c=this,d=this.isLinked&&!this.series?
this.linkedParent.series:this.series,e=c.chart,f=e.renderer,m=c.left,q=c.top,k,n,r,u,v=[],y=[],A=b.translatedValue,B=b.value,C=b.force;if(e.options.isStock&&!1!==b.acrossPanes&&"xAxis"===c.coll||"yAxis"===c.coll){b.preventDefault();y=a(c.coll);var E=c.isXAxis?e.yAxis:e.xAxis;E.forEach(function(a){if(J(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis";b=J(a.options[b])?e[b][a.options[b]]:e[b][0];c===b&&y.push(a)}});var F=y.length?[]:[c.isXAxis?e.yAxis[0]:e.xAxis[0]];
y.forEach(function(a){-1!==F.indexOf(a)||p(F,function(b){return b.pos===a.pos&&b.len===a.len})||F.push(a)});var I=l(A,c.translate(B,null,null,b.old));w(I)&&(c.horiz?F.forEach(function(a){var b;n=a.pos;u=n+a.len;k=r=Math.round(I+c.transB);"pass"!==C&&(k<m||k>m+c.width)&&(C?k=r=H(k,m,m+c.width):b=!0);b||v.push(["M",k,n],["L",r,u])}):F.forEach(function(a){var b;k=a.pos;r=k+a.len;n=u=Math.round(q+c.height-I);"pass"!==C&&(n<q||n>q+c.height)&&(C?n=u=H(n,q,q+c.height):b=!0);b||v.push(["M",k,n],["L",r,u])}));
b.path=0<v.length?f.crispPolyLine(v,b.lineWidth||1):null}});A.prototype.crispPolyLine=function(b,a){for(var c=0;c<b.length;c+=2){var d=b[c],e=b[c+1];d[1]===e[1]&&(d[1]=e[1]=Math.round(d[1])-a%2/2);d[2]===e[2]&&(d[2]=e[2]=Math.round(d[2])+a%2/2)}return b};k(c,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});k(c,"afterDrawCrosshair",function(b){var a,c;if(J(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var d=this.chart,e=this.logarithmic,
f=this.options.crosshair.label,g=this.horiz,k=this.opposite,q=this.left,n=this.top,p=this.crossLabel,r=f.format,v="",y="inside"===this.options.tickPosition,A=!1!==this.crosshair.snap,B=0,C=b.e||this.cross&&this.cross.e,E=b.point;b=this.min;var F=this.max;e&&(b=e.lin2log(b),F=e.lin2log(F));e=g?"center":k?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";p||(p=this.crossLabel=d.renderer.label(null,null,null,f.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&
" highcharts-color-"+this.series[0].colorIndex)).attr({align:f.align||e,padding:l(f.padding,8),r:l(f.borderRadius,3),zIndex:2}).add(this.labelGroup),d.styledMode||p.attr({fill:f.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:f.borderColor||"","stroke-width":f.borderWidth||0}).css(u({color:"#ffffff",fontWeight:"normal",fontSize:"11px",textAlign:"center"},f.style)));g?(e=A?E.plotX+q:C.chartX,n+=k?0:this.height):(e=k?this.width+q:0,n=A?E.plotY+n:C.chartY);r||f.formatter||(this.dateTime&&
(v="%b %d, %Y"),r="{value"+(v?":"+v:"")+"}");v=A?E[this.isXAxis?"x":"y"]:this.toValue(g?C.chartX:C.chartY);p.attr({text:r?L(r,{value:v},d):f.formatter.call(this,v),x:e,y:n,visibility:v<b||v>F?"hidden":"visible"});f=p.getBBox();if(w(p.y))if(g){if(y&&!k||!y&&k)n=p.y-f.height}else n=p.y-f.height/2;g?(a=q-f.x,c=q+this.width-f.x):(a="left"===this.labelAlign?q:0,c="right"===this.labelAlign?q+this.width:d.chartWidth);p.translateX<a&&(B=a-p.translateX);p.translateX+f.width>=c&&(B=-(p.translateX+f.width-c));
p.attr({x:e+B,y:n,anchorX:g?e:this.opposite?0:d.chartWidth,anchorY:g?this.opposite?d.chartHeight:0:n+f.height/2})}});y.init=function(){K.apply(this,arguments);this.setCompare(this.options.compare)};y.setCompare=function(b){this.modifyValue="value"===b||"percent"===b?function(a,c){var d=this.compareValue;return"undefined"!==typeof a&&"undefined"!==typeof d?(a="value"===b?a-d:a/d*100-(100===this.options.compareBase?0:100),c&&(c.change=a),a):0}:null;this.userOptions.compare=b;this.chart.hasRendered&&
(this.isDirty=!0)};y.processData=function(b){var a,c=-1,d=!0===this.options.compareStart?0:1;n.apply(this,arguments);if(this.xAxis&&this.processedYData){var e=this.processedXData;var f=this.processedYData;var g=f.length;this.pointArrayMap&&(c=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(a=0;a<g-d;a++){var k=f[a]&&-1<c?f[a][c]:f[a];if(w(k)&&e[a+d]>=this.xAxis.min&&0!==k){this.compareValue=k;break}}}};k(B,"afterGetExtremes",function(c){c=c.dataExtremes;if(this.modifyValue&&
c){var a=[this.modifyValue(c.dataMin),this.modifyValue(c.dataMax)];c.dataMin=r(a);c.dataMax=b(a)}});c.prototype.setCompare=function(b,a){this.isXAxis||(this.series.forEach(function(a){a.setCompare(b)}),l(a,!0)&&this.chart.redraw())};v.prototype.tooltipFormatter=function(b){var a=this.series.chart.numberFormatter;b=b.replace("{point.change}",(0<this.change?"+":"")+a(this.change,l(this.series.tooltipOptions.changeDecimals,2)));return e.apply(this,[b])};k(B,"render",function(){var b=this.chart;if(!(b.is3d&&
b.is3d()||b.polar)&&this.xAxis&&!this.xAxis.isRadial){var a=this.yAxis.len;if(this.xAxis.axisLine){var c=b.plotTop+b.plotHeight-this.yAxis.pos-this.yAxis.len,e=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=c&&(a-=Math.max(e-c,0))}this.clipBox||b.hasRendered?b[this.sharedClipKey]&&(b[this.sharedClipKey].animate({width:this.xAxis.len,height:a}),b[this.sharedClipKey+"m"]&&b[this.sharedClipKey+"m"].animate({width:this.xAxis.len})):(this.clipBox=d(b.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=
a)}});k(C,"update",function(b){b=b.options;"scrollbar"in b&&this.navigator&&(d(!0,this.options.scrollbar,b.scrollbar),this.navigator.update({},!1),delete b.scrollbar)})});H(c,"masters/modules/stock.src.js",[],function(){})});
//# sourceMappingURL=stock.js.map