/*
 Highcharts JS v8.2.2 (2020-11-05)

 (c) 2014-2019 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/treemap",["highcharts"],function(q){b(q);b.Highcharts=q;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function q(b,f,k,x){b.hasOwnProperty(f)||(b[f]=x.apply(null,k))}b=b?b._modules:{};q(b,"Mixins/ColorMapSeries.js",[b["Core/Globals.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"]],function(b,f,k){var x=k.defined;
return{colorMapPointMixin:{dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(b){f.prototype.setState.call(this,b);this.graphic&&this.graphic.attr({zIndex:"hover"===b?1:0})}},colorMapSeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:b.noop,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:b.seriesTypes.column.prototype.pointAttribs,
colorAttribs:function(b){var k={};x(b.color)&&(k[this.colorProp||"fill"]=b.color);return k}}}});q(b,"Mixins/DrawPoint.js",[],function(){var b=function(b){return"function"===typeof b},f=function(k){var f,t=this,n=t.graphic,g=k.animatableAttribs,v=k.onComplete,p=k.css,d=k.renderer,m=null===(f=t.series)||void 0===f?void 0:f.options.animation;if(t.shouldDraw())n||(t.graphic=n=d[k.shapeType](k.shapeArgs).add(k.group)),n.css(p).attr(k.attribs).animate(g,k.isNew?!1:m,v);else if(n){var G=function(){t.graphic=
n=n.destroy();b(v)&&v()};Object.keys(g).length?n.animate(g,void 0,function(){G()}):G()}};return{draw:f,drawPoint:function(b){(b.attribs=b.attribs||{})["class"]=this.getClassName();f.call(this,b)},isFn:b}});q(b,"Mixins/TreeSeries.js",[b["Core/Color/Color.js"],b["Core/Utilities.js"]],function(b,f){var k=f.extend,q=f.isArray,t=f.isNumber,n=f.isObject,g=f.merge,v=f.pick;return{getColor:function(p,d){var m=d.index,k=d.mapOptionsToLevel,f=d.parentColor,n=d.parentColorIndex,g=d.series,B=d.colors,E=d.siblings,
w=g.points,A=g.chart.options.chart,z;if(p){w=w[p.i];p=k[p.level]||{};if(k=w&&p.colorByPoint){var t=w.index%(B?B.length:A.colorCount);var q=B&&B[t]}if(!g.chart.styledMode){B=w&&w.options.color;A=p&&p.color;if(z=f)z=(z=p&&p.colorVariation)&&"brightness"===z.key?b.parse(f).brighten(m/E*z.to).get():f;z=v(B,A,q,z,g.color)}var x=v(w&&w.options.colorIndex,p&&p.colorIndex,t,n,d.colorIndex)}return{color:z,colorIndex:x}},getLevelOptions:function(b){var d=null;if(n(b)){d={};var f=t(b.from)?b.from:1;var p=b.levels;
var v={};var x=n(b.defaults)?b.defaults:{};q(p)&&(v=p.reduce(function(b,d){if(n(d)&&t(d.level)){var m=g({},d);var p="boolean"===typeof m.levelIsConstant?m.levelIsConstant:x.levelIsConstant;delete m.levelIsConstant;delete m.level;d=d.level+(p?0:f-1);n(b[d])?k(b[d],m):b[d]=m}return b},{}));p=t(b.to)?b.to:1;for(b=0;b<=p;b++)d[b]=g({},x,n(v[b])?v[b]:{})}return d},setTreeValues:function G(b,m){var d=m.before,f=m.idRoot,n=m.mapIdToNode[f],g=m.points[b.i],t=g&&g.options||{},w=0,q=[];k(b,{levelDynamic:b.level-
(("boolean"===typeof m.levelIsConstant?m.levelIsConstant:1)?0:n.level),name:v(g&&g.name,""),visible:f===b.id||("boolean"===typeof m.visible?m.visible:!1)});"function"===typeof d&&(b=d(b,m));b.children.forEach(function(d,f){var g=k({},m);k(g,{index:f,siblings:b.children.length,visible:b.visible});d=G(d,g);q.push(d);d.visible&&(w+=d.val)});b.visible=0<w||b.visible;d=v(t.value,w);k(b,{children:q,childrenTotal:w,isLeaf:b.visible&&!w,val:d});return b},updateRootId:function(b){if(n(b)){var d=n(b.options)?
b.options:{};d=v(b.rootNode,d.rootId,"");n(b.userOptions)&&(b.userOptions.rootId=d);b.rootNode=d}return d}}});q(b,"Series/TreemapSeries.js",[b["Core/Series/Series.js"],b["Core/Color/Color.js"],b["Mixins/ColorMapSeries.js"],b["Mixins/DrawPoint.js"],b["Core/Globals.js"],b["Mixins/LegendSymbol.js"],b["Series/Line/LineSeries.js"],b["Core/Series/Point.js"],b["Mixins/TreeSeries.js"],b["Core/Utilities.js"]],function(b,f,k,q,t,n,g,v,p,d){var m=b.seriesTypes,x=f.parse,L=k.colorMapSeriesMixin;f=t.noop;var O=
p.getColor,P=p.getLevelOptions,B=p.updateRootId,E=d.addEvent,w=d.correctFloat,A=d.defined,z=d.error,F=d.extend,Q=d.fireEvent,M=d.isArray,N=d.isNumber,R=d.isObject,I=d.isString,D=d.merge,S=d.objectEach,y=d.pick,T=d.stableSort,U=function(a,c,e){e=e||this;S(a,function(b,l){c.call(e,b,l,a)})},H=function(a,c,e){e=e||this;a=c.call(e,a);!1!==a&&H(a,c,e)},J=!1;b.seriesType("treemap","scatter",{allowTraversingTree:!1,animationLimit:250,showInLegend:!1,marker:void 0,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,
formatter:function(){var a=this&&this.point?this.point:{};return I(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,colorKey:"colorValue",
opacity:.15,states:{hover:{borderColor:"#999999",brightness:m.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:f,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,c){a=M(a)?a:[];var e=M(c)?c:[];c=a.reduce(function(a,c,e){c=y(c.parent,"");"undefined"===typeof a[c]&&(a[c]=[]);a[c].push(e);return a},{"":[]});U(c,function(a,c,b){""!==c&&-1===e.indexOf(c)&&
(a.forEach(function(a){b[""].push(a)}),delete b[c])});return c},getTree:function(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,a);this.nodeMap={};return this.buildNode("",-1,0,a)},hasData:function(){return!!this.processedXData.length},init:function(a,c){L&&(this.colorAttribs=L.colorAttribs);var e=E(this,"setOptions",function(a){a=a.userOptions;A(a.allowDrillToNode)&&!A(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);
A(a.drillUpButton)&&!A(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)});g.prototype.init.call(this,a,c);delete this.opacity;this.eventsToUnbind.push(e);this.options.allowTraversingTree&&this.eventsToUnbind.push(E(this,"click",this.onClickDrillToNode))},buildNode:function(a,c,e,b,l){var d=this,h=[],u=d.points[c],K=0,r;(b[a]||[]).forEach(function(c){r=d.buildNode(d.points[c].id,c,e+1,b,a);K=Math.max(r.height+1,K);h.push(r)});c={id:a,i:c,children:h,height:K,level:e,
parent:l,visible:!1};d.nodeMap[c.id]=c;u&&(u.node=c);return c},setTreeValues:function(a){var c=this,e=c.options,b=c.nodeMap[c.rootNode];e="boolean"===typeof e.levelIsConstant?e.levelIsConstant:!0;var l=0,d=[],h=c.points[a.i];a.children.forEach(function(a){a=c.setTreeValues(a);d.push(a);a.ignore||(l+=a.val)});T(d,function(a,c){return(a.sortIndex||0)-(c.sortIndex||0)});var C=y(h&&h.options.value,l);h&&(h.value=C);F(a,{children:d,childrenTotal:l,ignore:!(y(h&&h.visible,!0)&&0<C),isLeaf:a.visible&&!l,
levelDynamic:a.level-(e?0:b.level),name:y(h&&h.name,""),sortIndex:y(h&&h.sortIndex,-C),val:C});return a},calculateChildrenAreas:function(a,c){var b=this,d=b.options,l=b.mapOptionsToLevel[a.level+1],V=y(b[l&&l.layoutAlgorithm]&&l.layoutAlgorithm,d.layoutAlgorithm),h=d.alternateStartingDirection,C=[];a=a.children.filter(function(a){return!a.ignore});l&&l.layoutStartingDirection&&(c.direction="vertical"===l.layoutStartingDirection?0:1);C=b[V](c,a);a.forEach(function(a,e){e=C[e];a.values=D(e,{val:a.childrenTotal,
direction:h?1-c.direction:c.direction});a.pointValues=D(e,{x:e.x/b.axisRatio,y:100-e.y-e.height,width:e.width/b.axisRatio});a.children.length&&b.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this,c=a.xAxis,b=a.yAxis,d=a.chart.styledMode;a.points.forEach(function(e){var l=e.node,h=l.pointValues;l=l.visible;if(h&&l){l=h.height;var u=h.width,f=h.x,r=h.y,k=d?0:(a.pointAttribs(e)["stroke-width"]||0)%2/2;h=Math.round(c.toPixels(f,!0))-k;u=Math.round(c.toPixels(f+u,!0))-k;f=Math.round(b.toPixels(r,
!0))-k;l=Math.round(b.toPixels(r+l,!0))-k;e.shapeArgs={x:Math.min(h,u),y:Math.min(f,l),width:Math.abs(u-h),height:Math.abs(l-f)};e.plotX=e.shapeArgs.x+e.shapeArgs.width/2;e.plotY=e.shapeArgs.y+e.shapeArgs.height/2}else delete e.plotX,delete e.plotY})},setColorRecursive:function(a,c,b,d,l){var e=this,h=e&&e.chart;h=h&&h.options&&h.options.colors;if(a){var u=O(a,{colors:h,index:d,mapOptionsToLevel:e.mapOptionsToLevel,parentColor:c,parentColorIndex:b,series:e,siblings:l});if(c=e.points[a.i])c.color=
u.color,c.colorIndex=u.colorIndex;(a.children||[]).forEach(function(c,b){e.setColorRecursive(c,u.color,u.colorIndex,b,a.children.length)})}},algorithmGroup:function(a,c,b,d){this.height=a;this.width=c;this.plot=d;this.startDirection=this.direction=b;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,c){return Math.max(a/c,c/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===
this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=
0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,c,b,d){var e,u,h,f,k=b.lW,r=b.lH,g=b.plot,m=0,p=b.elArr.length-1;if(c)k=b.nW,r=b.nH;else var n=b.elArr[b.elArr.length-1];b.elArr.forEach(function(a){if(c||m<p)0===b.direction?(e=g.x,u=g.y,h=k,f=a/h):(e=g.x,u=g.y,f=r,h=a/f),d.push({x:e,y:u,width:h,height:w(f)}),0===b.direction?g.y+=f:g.x+=h;m+=1});b.reset();0===b.direction?b.width-=k:b.height-=r;g.y=g.parent.y+(g.parent.height-b.height);g.x=g.parent.x+(g.parent.width-b.width);a&&(b.direction=
1-b.direction);c||b.addElement(n)},algorithmLowAspectRatio:function(a,c,b){var e=[],d=this,f,h={x:c.x,y:c.y,parent:c},g=0,k=b.length-1,r=new this.algorithmGroup(c.height,c.width,c.direction,h);b.forEach(function(b){f=b.val/c.val*c.height*c.width;r.addElement(f);r.lP.nR>r.lP.lR&&d.algorithmCalcPoints(a,!1,r,e,h);g===k&&d.algorithmCalcPoints(a,!0,r,e,h);g+=1});return e},algorithmFill:function(a,c,b){var e=[],d,f=c.direction,h=c.x,g=c.y,k=c.width,r=c.height,m,p,n,q;b.forEach(function(b){d=b.val/c.val*
c.height*c.width;m=h;p=g;0===f?(q=r,n=d/q,k-=n,h+=n):(n=k,q=d/n,r-=q,g+=q);e.push({x:m,y:p,width:n,height:q});a&&(f=1-f)});return e},strip:function(a,b){return this.algorithmLowAspectRatio(!1,a,b)},squarified:function(a,b){return this.algorithmLowAspectRatio(!0,a,b)},sliceAndDice:function(a,b){return this.algorithmFill(!0,a,b)},stripes:function(a,b){return this.algorithmFill(!1,a,b)},translate:function(){var a=this,b=a.options,e=B(a);g.prototype.translate.call(a);var d=a.tree=a.getTree();var l=a.nodeMap[e];
a.renderTraverseUpButton(e);a.mapOptionsToLevel=P({from:l.level+1,levels:b.levels,to:d.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});""===e||l&&l.children.length||(a.setRootNode("",!1),e=a.rootNode,l=a.nodeMap[e]);H(a.nodeMap[a.rootNode],function(b){var c=!1,e=b.parent;b.visible=!0;if(e||""===e)c=a.nodeMap[e];return c});H(a.nodeMap[a.rootNode].children,function(a){var b=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(b=(b||[]).concat(a.children))});
return b});a.setTreeValues(d);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=e={x:0,y:0,width:100,height:100};a.nodeMap[""].values=e=D(e,{width:e.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:d.val});a.calculateChildrenAreas(d,e);a.colorAxis||b.colorByPoint||a.setColorRecursive(a.tree);b.allowTraversingTree&&(b=l.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},
drawDataLabels:function(){var a=this,b=a.mapOptionsToLevel,e,d;a.points.filter(function(a){return a.node.visible}).forEach(function(c){d=b[c.node.level];e={style:{}};c.node.isLeaf||(e.enabled=!1);d&&d.dataLabels&&(e=D(e,d.dataLabels),a._hasPointLabels=!0);c.shapeArgs&&(e.style.width=c.shapeArgs.width,c.dataLabel&&c.dataLabel.css({width:c.shapeArgs.width+"px"}));c.dlOptions=D(e,c.options.dataLabels)});g.prototype.drawDataLabels.call(this)},alignDataLabel:function(a,b,e){var c=e.style;!A(c.textOverflow)&&
b.text&&b.getBBox().width>b.text.textWidth&&b.css({textOverflow:"ellipsis",width:c.width+="px"});m.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,b){var c=R(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},d=a&&c[a.node.level]||{};c=this.options;var l=b&&c.states[b]||{},f=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||d.borderColor||l.borderColor||c.borderColor,"stroke-width":y(a&&a.borderWidth,d.borderWidth,
l.borderWidth,c.borderWidth),dashstyle:a&&a.borderDashStyle||d.borderDashStyle||l.borderDashStyle||c.borderDashStyle,fill:a&&a.color||this.color};-1!==f.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==f.indexOf("highcharts-internal-node-interactive")?(b=y(l.opacity,c.opacity),a.fill=x(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==f.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=x(a.fill).brighten(l.brightness).get());return a},drawPoints:function(){var a=
this,b=a.chart,e=b.renderer,d=b.styledMode,f=a.options,g=d?{}:f.shadow,h=f.borderRadius,k=b.pointCount<f.animationLimit,n=f.allowTraversingTree;a.points.forEach(function(b){var c=b.node.levelDynamic,l={},m={},p={},q="level-group-"+b.node.level,u=!!b.graphic,r=k&&u,t=b.shapeArgs;b.shouldDraw()&&(h&&(m.r=h),D(!0,r?l:m,u?t:{},d?{}:a.pointAttribs(b,b.selected?"select":void 0)),a.colorAttribs&&d&&F(p,a.colorAttribs(b)),a[q]||(a[q]=e.g(q).attr({zIndex:1E3-(c||0)}).add(a.group),a[q].survive=!0));b.draw({animatableAttribs:l,
attribs:m,css:p,group:a[q],renderer:e,shadow:g,shapeArgs:t,shapeType:"rect"});n&&b.graphic&&(b.drillId=f.interactByLeaf?a.drillToByLeaf(b):a.drillToByGroup(b))})},onClickDrillToNode:function(a){var b=(a=a.point)&&a.drillId;I(b)&&(a.setState(""),this.setRootNode(b,!0,{trigger:"click"}))},drillToByGroup:function(a){var b=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=
this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&I(a.parent)&&this.setRootNode(a.parent,!0,{trigger:"traverseUpButton"})},drillToNode:function(a,b){z(32,!1,void 0,{"treemap.drillToNode":"use treemap.setRootNode"});this.setRootNode(a,b)},setRootNode:function(a,b,e){a=F({newRootId:a,previousRootId:this.rootNode,redraw:y(b,!0),series:this},e);Q(this,"setRootNode",a,function(a){var b=a.series;b.idPreviousRoot=a.previousRootId;
b.rootNode=a.newRootId;b.isDirty=!0;a.redraw&&b.chart.redraw()})},renderTraverseUpButton:function(a){var b=this,e=b.options.traverseUpButton,d=y(e.text,b.nodeMap[a].name,"\u25c1 Back");if(""===a||b.is("sunburst")&&1===b.tree.children.length&&a===b.tree.children[0].id)b.drillUpButton&&(b.drillUpButton=b.drillUpButton.destroy());else if(this.drillUpButton)this.drillUpButton.placed=!1,this.drillUpButton.attr({text:d}).align();else{var f=(a=e.theme)&&a.states;this.drillUpButton=this.chart.renderer.button(d,
0,0,function(){b.drillUp()},a,f&&f.hover,f&&f.select).addClass("highcharts-drillup-button").attr({align:e.position.align,zIndex:7}).add().align(e.position,!1,e.relativeTo||"plotBox")}},buildKDTree:f,drawLegendSymbol:n.drawRectangle,getExtremes:function(){var a=g.prototype.getExtremes.call(this,this.colorValueData),b=a.dataMax;this.valueMin=a.dataMin;this.valueMax=b;return g.prototype.getExtremes.call(this)},getExtremesFromAll:!0,setState:function(a){this.options.inactiveOtherPoints=!0;g.prototype.setState.call(this,
a,!1);this.options.inactiveOtherPoints=!1},utils:{recursive:H}},{draw:q.drawPoint,setVisible:m.pie.prototype.pointClass.prototype.setVisible,getClassName:function(){var a=v.prototype.getClassName.call(this),b=this.series,d=b.options;this.node.level<=b.nodeMap[b.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||y(d.interactByLeaf,!d.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a},isValid:function(){return!(!this.id&&
!N(this.value))},setState:function(a){v.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},shouldDraw:function(){return N(this.plotY)&&null!==this.y}});E(g,"afterBindAxes",function(){var a=this.xAxis,b=this.yAxis;if(a&&b)if(this.is("treemap")){var d={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};F(b.options,d);F(a.options,d);J=!0}else J&&(b.setOptions(b.userOptions),
a.setOptions(a.userOptions),J=!1)});""});q(b,"masters/modules/treemap.src.js",[],function(){})});
//# sourceMappingURL=treemap.js.map