/*
 Highcharts Gantt JS v8.2.2 (2020-11-05)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(x){b(x);b.Highcharts=x;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function x(b,u,H,l){b.hasOwnProperty(u)||(b[u]=l.apply(null,H))}b=b?b._modules:{};x(b,"Gantt/Tree.js",[b["Core/Utilities.js"]],function(b){var u=b.extend,y=b.isNumber,l=b.pick,k=function(b,k){var n=b.reduce(function(f,
n){var r=l(n.parent,"");"undefined"===typeof f[r]&&(f[r]=[]);f[r].push(n);return f},{});Object.keys(n).forEach(function(f,b){var r=n[f];""!==f&&-1===k.indexOf(f)&&(r.forEach(function(f){b[""].push(f)}),delete b[f])});return n},p=function(b,k,n,f,C,r){var q=0,t=0,m=r&&r.after,a=r&&r.before;k={data:f,depth:n-1,id:b,level:n,parent:k};var g,h;"function"===typeof a&&a(k,r);a=(C[b]||[]).map(function(d){var c=p(d.id,b,n+1,d,C,r),e=d.start;d=!0===d.milestone?e:d.end;g=!y(g)||e<g?e:g;h=!y(h)||d>h?d:h;q=q+
1+c.descendants;t=Math.max(c.height+1,t);return c});f&&(f.start=l(f.start,g),f.end=l(f.end,h));u(k,{children:a,descendants:q,height:t});"function"===typeof m&&m(k,r);return k};return{getListOfParents:k,getNode:p,getTree:function(b,l){var n=b.map(function(f){return f.id});b=k(b,n);return p("",null,1,null,b,l)}}});x(b,"Core/Axis/TreeGridTick.js",[b["Core/Utilities.js"]],function(b){var u=b.addEvent,y=b.defined,l=b.isObject,k=b.isNumber,p=b.pick,w=b.wrap,E;(function(b){function f(){this.treeGrid||(this.treeGrid=
new m(this))}function n(a,g){a=a.treeGrid;var h=!a.labelIcon,d=g.renderer,c=g.xy,e=g.options,z=e.width,D=e.height,f=c.x-z/2-e.padding;c=c.y-D/2;var b=g.collapsed?90:180,q=g.show&&k(c),v=a.labelIcon;v||(a.labelIcon=v=d.path(d.symbols[e.type](e.x,e.y,z,D)).addClass("highcharts-label-icon").add(g.group));q||v.attr({y:-9999});d.styledMode||v.attr({"stroke-width":1,fill:p(g.color,"#666666")}).css({cursor:"pointer",stroke:e.lineColor,strokeWidth:e.lineWidth});v[h?"attr":"animate"]({translateX:f,translateY:c,
rotation:b})}function r(a,g,h,d,c,e,z,D,f){var b=p(this.options&&this.options.labels,e);e=this.pos;var G=this.axis,v="treegrid"===G.options.type;a=a.apply(this,[g,h,d,c,b,z,D,f]);v&&(g=b&&l(b.symbol,!0)?b.symbol:{},b=b&&k(b.indentation)?b.indentation:0,e=(e=(G=G.treeGrid.mapOfPosToGridNode)&&G[e])&&e.depth||1,a.x+=g.width+2*g.padding+(e-1)*b);return a}function q(a){var g=this,h=g.pos,d=g.axis,c=g.label,e=d.treeGrid.mapOfPosToGridNode,z=d.options,D=p(g.options&&g.options.labels,z&&z.labels),b=D&&l(D.symbol,
!0)?D.symbol:{},f=(e=e&&e[h])&&e.depth;z="treegrid"===z.type;var q=-1<d.tickPositions.indexOf(h);h=d.chart.styledMode;z&&e&&c&&c.element&&c.addClass("highcharts-treegrid-node-level-"+f);a.apply(g,Array.prototype.slice.call(arguments,1));z&&c&&c.element&&e&&e.descendants&&0<e.descendants&&(d=d.treeGrid.isCollapsed(e),n(g,{color:!h&&c.styles&&c.styles.color||"",collapsed:d,group:c.parentGroup,options:b,renderer:c.renderer,show:q,xy:c.xy}),b="highcharts-treegrid-node-"+(d?"expanded":"collapsed"),c.addClass("highcharts-treegrid-node-"+
(d?"collapsed":"expanded")).removeClass(b),h||c.css({cursor:"pointer"}),[c,g.treeGrid.labelIcon].forEach(function(e){e&&!e.attachedTreeGridEvents&&(u(e.element,"mouseover",function(){c.addClass("highcharts-treegrid-node-active");c.renderer.styledMode||c.css({textDecoration:"underline"})}),u(e.element,"mouseout",function(){var e=y(D.style)?D.style:{};c.removeClass("highcharts-treegrid-node-active");c.renderer.styledMode||c.css({textDecoration:e.textDecoration})}),u(e.element,"click",function(){g.treeGrid.toggleCollapse()}),
e.attachedTreeGridEvents=!0)}))}var t=!1;b.compose=function(a){t||(u(a,"init",f),w(a.prototype,"getLabelPosition",r),w(a.prototype,"renderLabel",q),a.prototype.collapse=function(a){this.treeGrid.collapse(a)},a.prototype.expand=function(a){this.treeGrid.expand(a)},a.prototype.toggleCollapse=function(a){this.treeGrid.toggleCollapse(a)},t=!0)};var m=function(){function a(a){this.tick=a}a.prototype.collapse=function(a){var h=this.tick,d=h.axis,c=d.brokenAxis;c&&d.treeGrid.mapOfPosToGridNode&&(h=d.treeGrid.collapse(d.treeGrid.mapOfPosToGridNode[h.pos]),
c.setBreaks(h,p(a,!0)))};a.prototype.expand=function(a){var h=this.tick,d=h.axis,c=d.brokenAxis;c&&d.treeGrid.mapOfPosToGridNode&&(h=d.treeGrid.expand(d.treeGrid.mapOfPosToGridNode[h.pos]),c.setBreaks(h,p(a,!0)))};a.prototype.toggleCollapse=function(a){var h=this.tick,d=h.axis,c=d.brokenAxis;c&&d.treeGrid.mapOfPosToGridNode&&(h=d.treeGrid.toggleCollapse(d.treeGrid.mapOfPosToGridNode[h.pos]),c.setBreaks(h,p(a,!0)))};return a}();b.Additions=m})(E||(E={}));return E});x(b,"Mixins/TreeSeries.js",[b["Core/Color/Color.js"],
b["Core/Utilities.js"]],function(b,u){var y=u.extend,l=u.isArray,k=u.isNumber,p=u.isObject,w=u.merge,E=u.pick;return{getColor:function(n,f){var k=f.index,r=f.mapOptionsToLevel,q=f.parentColor,t=f.parentColorIndex,m=f.series,a=f.colors,g=f.siblings,h=m.points,d=m.chart.options.chart,c;if(n){h=h[n.i];n=r[n.level]||{};if(r=h&&n.colorByPoint){var e=h.index%(a?a.length:d.colorCount);var z=a&&a[e]}if(!m.chart.styledMode){a=h&&h.options.color;d=n&&n.color;if(c=q)c=(c=n&&n.colorVariation)&&"brightness"===
c.key?b.parse(q).brighten(k/g*c.to).get():q;c=E(a,d,z,c,m.color)}var D=E(h&&h.options.colorIndex,n&&n.colorIndex,e,t,f.colorIndex)}return{color:c,colorIndex:D}},getLevelOptions:function(b){var f=null;if(p(b)){f={};var n=k(b.from)?b.from:1;var r=b.levels;var q={};var t=p(b.defaults)?b.defaults:{};l(r)&&(q=r.reduce(function(b,a){if(p(a)&&k(a.level)){var g=w({},a);var h="boolean"===typeof g.levelIsConstant?g.levelIsConstant:t.levelIsConstant;delete g.levelIsConstant;delete g.level;a=a.level+(h?0:n-1);
p(b[a])?y(b[a],g):b[a]=g}return b},{}));r=k(b.to)?b.to:1;for(b=0;b<=r;b++)f[b]=w({},t,p(q[b])?q[b]:{})}return f},setTreeValues:function r(b,k){var f=k.before,t=k.idRoot,m=k.mapIdToNode[t],a=k.points[b.i],g=a&&a.options||{},h=0,d=[];y(b,{levelDynamic:b.level-(("boolean"===typeof k.levelIsConstant?k.levelIsConstant:1)?0:m.level),name:E(a&&a.name,""),visible:t===b.id||("boolean"===typeof k.visible?k.visible:!1)});"function"===typeof f&&(b=f(b,k));b.children.forEach(function(c,e){var a=y({},k);y(a,{index:e,
siblings:b.children.length,visible:b.visible});c=r(c,a);d.push(c);c.visible&&(h+=c.val)});b.visible=0<h||b.visible;f=E(g.value,h);y(b,{children:d,childrenTotal:h,isLeaf:b.visible&&!h,val:f});return b},updateRootId:function(b){if(p(b)){var f=p(b.options)?b.options:{};f=E(b.rootNode,f.rootId,"");p(b.userOptions)&&(b.userOptions.rootId=f);b.rootNode=f}return f}}});x(b,"Core/Axis/GridAxis.js",[b["Core/Axis/Axis.js"],b["Core/Globals.js"],b["Core/Axis/Tick.js"],b["Core/Utilities.js"]],function(b,u,x,l){var k=
l.addEvent,p=l.defined,w=l.erase,y=l.find,n=l.isArray,f=l.isNumber,C=l.merge,r=l.pick,q=l.timeUnits,t=l.wrap,m=u.Chart,a=function(d){var c=d.options;c.labels||(c.labels={});c.labels.align=r(c.labels.align,"center");d.categories||(c.showLastLabel=!1);d.labelRotation=0;c.labels.rotation=0};"";b.prototype.getMaxLabelDimensions=function(d,c){var e={width:0,height:0};c.forEach(function(c){c=d[c];if(l.isObject(c,!0)){var a=l.isObject(c.label,!0)?c.label:{};c=a.getBBox?a.getBBox().height:0;a.textStr&&!f(a.textPxLength)&&
(a.textPxLength=a.getBBox().width);var b=f(a.textPxLength)?Math.round(a.textPxLength):0;a.textStr&&(b=Math.round(a.getBBox().width));e.height=Math.max(c,e.height);e.width=Math.max(b,e.width)}});return e};u.dateFormats.W=function(a){a=new this.Date(a);var c=(this.get("Day",a)+6)%7,e=new this.Date(a.valueOf());this.set("Date",e,this.get("Date",a)-c+3);c=new this.Date(this.get("FullYear",e),0,1);4!==this.get("Day",c)&&(this.set("Month",a,0),this.set("Date",a,1+(11-this.get("Day",c))%7));return(1+Math.floor((e.valueOf()-
c.valueOf())/6048E5)).toString()};u.dateFormats.E=function(a){return this.dateFormat("%a",a,!0).charAt(0)};k(m,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.grid&&a.grid.columns||[]).forEach(function(c){c.setAxisSize();c.setAxisTranslation()})})});k(x,"afterGetLabelPosition",function(a){var c=this.label,e=this.axis,b=e.reversed,d=e.chart,g=e.options.grid||{},q=e.options.labels,t=q.align,v=h.Side[e.side],k=a.tickmarkOffset,m=e.tickPositions,F=this.pos-k;m=f(m[a.index+1])?m[a.index+
1]-k:e.max+k;var B=e.tickSize("tick");k=B?B[0]:0;B=B?B[1]/2:0;if(!0===g.enabled){if("top"===v){g=e.top+e.offset;var A=g-k}else"bottom"===v?(A=d.chartHeight-e.bottom+e.offset,g=A+k):(g=e.top+e.len-e.translate(b?m:F),A=e.top+e.len-e.translate(b?F:m));"right"===v?(v=d.chartWidth-e.right+e.offset,b=v+k):"left"===v?(b=e.left+e.offset,v=b-k):(v=Math.round(e.left+e.translate(b?m:F))-B,b=Math.round(e.left+e.translate(b?F:m))-B);this.slotWidth=b-v;a.pos.x="left"===t?v:"right"===t?b:v+(b-v)/2;a.pos.y=A+(g-
A)/2;d=d.renderer.fontMetrics(q.style.fontSize,c.element);c=c.getBBox().height;q.useHTML?a.pos.y+=d.b+-(c/2):(c=Math.round(c/d.h),a.pos.y+=(d.b-(d.h-d.f))/2+-((c-1)*d.h/2));a.pos.x+=e.horiz&&q.x||0}});var g=function(){function a(c){this.axis=c}a.prototype.isOuterAxis=function(){var c=this.axis,a=c.grid.columnIndex,b=c.linkedParent&&c.linkedParent.grid.columns||c.grid.columns,d=a?c.linkedParent:c,g=-1,h=0;c.chart[c.coll].forEach(function(a,e){a.side!==c.side||a.options.isInternal||(h=e,a===d&&(g=e))});
return h===g&&(f(a)?b.length===a:!0)};a.prototype.renderBorder=function(c){var a=this.axis,b=a.chart.renderer,d=a.options;c=b.path(c).addClass("highcharts-axis-line").add(a.axisBorder);b.styledMode||c.attr({stroke:d.lineColor,"stroke-width":d.lineWidth,zIndex:7});return c};return a}(),h=function(){function d(){}d.compose=function(c){b.keepProps.push("grid");t(c.prototype,"unsquish",d.wrapUnsquish);k(c,"init",d.onInit);k(c,"afterGetOffset",d.onAfterGetOffset);k(c,"afterGetTitlePosition",d.onAfterGetTitlePosition);
k(c,"afterInit",d.onAfterInit);k(c,"afterRender",d.onAfterRender);k(c,"afterSetAxisTranslation",d.onAfterSetAxisTranslation);k(c,"afterSetOptions",d.onAfterSetOptions);k(c,"afterSetOptions",d.onAfterSetOptions2);k(c,"afterSetScale",d.onAfterSetScale);k(c,"afterTickSize",d.onAfterTickSize);k(c,"trimTicks",d.onTrimTicks);k(c,"destroy",d.onDestroy)};d.onAfterGetOffset=function(){var c=this.grid;(c&&c.columns||[]).forEach(function(c){c.getOffset()})};d.onAfterGetTitlePosition=function(c){if(!0===(this.options.grid||
{}).enabled){var a=this.axisTitle,b=this.height,g=this.horiz,h=this.left,f=this.offset,q=this.opposite,k=this.options.title,m=void 0===k?{}:k;k=this.top;var t=this.width,F=this.tickSize(),B=a&&a.getBBox().width,A=m.x||0,K=m.y||0,l=r(m.margin,g?5:10);a=this.chart.renderer.fontMetrics(m.style&&m.style.fontSize,a).f;F=(g?k+b:h)+(g?1:-1)*(q?-1:1)*(F?F[0]/2:0)+(this.side===d.Side.bottom?a:0);c.titlePosition.x=g?h-B/2-l+A:F+(q?t:0)+f+A;c.titlePosition.y=g?F-(q?b:0)+(q?a:-a)/2+f+K:k-l+K}};d.onAfterInit=
function(){var c=this.chart,e=this.options.grid;e=void 0===e?{}:e;var d=this.userOptions;e.enabled&&(a(this),t(this,"labelFormatter",function(a){var c=this.axis,e=this.value,b=c.tickPositions,d=(c.isLinked?c.linkedParent:c).series[0],g=e===b[0];b=e===b[b.length-1];var h=d&&y(d.options.data,function(a){return a[c.isXAxis?"x":"y"]===e});if(h&&d.is("gantt")){var z=C(h);u.seriesTypes.gantt.prototype.setGanttPointAliases(z)}this.isFirst=g;this.isLast=b;this.point=z;return a.call(this)}));if(e.columns)for(var g=
this.grid.columns=[],h=this.grid.columnIndex=0;++h<e.columns.length;){var f=C(d,e.columns[e.columns.length-h-1],{linkedTo:0,type:"category",scrollbar:{enabled:!1}});delete f.grid.columns;f=new b(this.chart,f);f.grid.isColumn=!0;f.grid.columnIndex=h;w(c.axes,f);w(c[this.coll],f);g.push(f)}};d.onAfterRender=function(){var c,a=this.grid,b=this.options;if(!0===(b.grid||{}).enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();
if(this.grid&&this.grid.isOuterAxis()&&this.axisLine&&(b=b.lineWidth)){b=this.getLinePath(b);var g=b[0],h=b[1],f=((this.tickSize("tick")||[1])[0]-1)*(this.side===d.Side.top||this.side===d.Side.left?-1:1);"M"===g[0]&&"L"===h[0]&&(this.horiz?(g[2]+=f,h[2]+=f):(g[1]+=f,h[1]+=f));!this.horiz&&this.chart.marginRight&&(g=[g,["L",this.left,g[2]]],f=["L",this.chart.chartWidth-this.chart.marginRight,this.toPixels(this.max+this.tickmarkOffset)],h=[["M",h[1],this.toPixels(this.max+this.tickmarkOffset)],f],this.grid.upperBorder||
0===this.min%1||(this.grid.upperBorder=this.grid.renderBorder(g)),this.grid.upperBorder&&this.grid.upperBorder.animate({d:g}),this.grid.lowerBorder||0===this.max%1||(this.grid.lowerBorder=this.grid.renderBorder(h)),this.grid.lowerBorder&&this.grid.lowerBorder.animate({d:h}));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:b}):this.grid.axisLineExtra=this.grid.renderBorder(b);this.axisLine[this.showAxis?"show":"hide"](!0)}(a&&a.columns||[]).forEach(function(a){a.render()});!this.horiz&&
this.chart.hasRendered&&(this.scrollbar||(null===(c=this.linkedParent)||void 0===c?0:c.scrollbar))&&(c=this.max,a=this.tickmarkOffset,b=this.tickPositions[this.tickPositions.length-1],h=this.tickPositions[0],this.min-h>a?this.ticks[h].label.hide():this.ticks[h].label.show(),b-c>a?this.ticks[b].label.hide():this.ticks[b].label.show(),b-c<a&&0<b-c&&this.ticks[b].isLast?this.ticks[b].mark.hide():this.ticks[b-1].mark.show())}};d.onAfterSetAxisTranslation=function(){var a,b=this.tickPositions&&this.tickPositions.info,
d=this.options,h=d.grid||{},g=this.userOptions.labels||{};this.horiz?(!0===h.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),b&&d.dateTimeLabelFormats&&d.labels&&!p(g.align)&&(!1===d.dateTimeLabelFormats[b.unitName].range||1<b.count)&&(d.labels.align="left",p(g.x)||(d.labels.x=3))):"treegrid"!==this.options.type&&(null===(a=this.grid)||void 0===a?0:a.columns)&&(this.minPointOffset=this.tickInterval)};d.onAfterSetOptions=function(a){var c=this.options;a=a.userOptions;var b=c&&l.isObject(c.grid,
!0)?c.grid:{};if(!0===b.enabled){var d=C(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",
null]]},a);"xAxis"===this.coll&&(p(a.linkedTo)&&!p(a.tickPixelInterval)&&(d.tickPixelInterval=350),p(a.tickPixelInterval)||!p(a.linkedTo)||p(a.tickPositioner)||p(a.tickInterval)||(d.tickPositioner=function(a,c){var b=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(b){var e,h=d.units;for(e=0;e<h.length;e++)if(h[e][0]===b.unitName){var g=e;break}if(h[g+1]){var f=h[g+1][0];var B=(h[g+1][1]||[1])[0]}else"year"===b.unitName&&(f="year",B=10*b.count);b=q[f];this.tickInterval=
b*B;return this.getTimeTicks({unitRange:b,count:B,unitName:f},a,c,this.options.startOfWeek)}}));C(!0,this.options,d);this.horiz&&(c.minPadding=r(a.minPadding,0),c.maxPadding=r(a.maxPadding,0));f(c.grid.borderWidth)&&(c.tickWidth=c.lineWidth=b.borderWidth)}};d.onAfterSetOptions2=function(a){a=(a=a.userOptions)&&a.grid||{};var c=a.columns;a.enabled&&c&&C(!0,this.options,c[c.length-1])};d.onAfterSetScale=function(){(this.grid.columns||[]).forEach(function(a){a.setScale()})};d.onAfterTickSize=function(a){var c=
b.defaultLeftAxisOptions,d=this.horiz,h=this.maxLabelDimensions,g=this.options.grid;g=void 0===g?{}:g;g.enabled&&h&&(c=2*Math.abs(c.labels.x),d=d?g.cellHeight||c+h.height:c+h.width,n(a.tickSize)?a.tickSize[0]=d:a.tickSize=[d,0])};d.onDestroy=function(a){var c=this.grid;(c.columns||[]).forEach(function(c){c.destroy(a.keepEvents)});c.columns=void 0};d.onInit=function(a){a=a.userOptions||{};var c=a.grid||{};c.enabled&&p(c.borderColor)&&(a.tickColor=a.lineColor=c.borderColor);this.grid||(this.grid=new g(this))};
d.onTrimTicks=function(){var a=this.options,b=this.categories,d=this.tickPositions,h=d[0],g=d[d.length-1],f=this.linkedParent&&this.linkedParent.min||this.min,k=this.linkedParent&&this.linkedParent.max||this.max,q=this.tickInterval;!0!==(a.grid||{}).enabled||b||!this.horiz&&!this.isLinked||(h<f&&h+q>f&&!a.startOnTick&&(d[0]=f),g>k&&g-q<k&&!a.endOnTick&&(d[d.length-1]=k))};d.wrapUnsquish=function(a){var c=this.options.grid;return!0===(void 0===c?{}:c).enabled&&this.categories?this.tickInterval:a.apply(this,
Array.prototype.slice.call(arguments,1))};return d}();(function(a){a=a.Side||(a.Side={});a[a.top=0]="top";a[a.right=1]="right";a[a.bottom=2]="bottom";a[a.left=3]="left"})(h||(h={}));h.compose(b);return h});x(b,"Core/Axis/BrokenAxis.js",[b["Core/Axis/Axis.js"],b["Series/Line/LineSeries.js"],b["Extensions/Stacking.js"],b["Core/Utilities.js"]],function(b,u,x,l){var k=l.addEvent,p=l.find,w=l.fireEvent,y=l.isArray,n=l.isNumber,f=l.pick,C=function(){function k(b){this.hasBreaks=!1;this.axis=b}k.isInBreak=
function(b,f){var k=b.repeat||Infinity,a=b.from,g=b.to-b.from;f=f>=a?(f-a)%k:k-(a-f)%k;return b.inclusive?f<=g:f<g&&0!==f};k.lin2Val=function(b){var f=this.brokenAxis;f=f&&f.breakArray;if(!f)return b;var m;for(m=0;m<f.length;m++){var a=f[m];if(a.from>=b)break;else a.to<b?b+=a.len:k.isInBreak(a,b)&&(b+=a.len)}return b};k.val2Lin=function(b){var f=this.brokenAxis;f=f&&f.breakArray;if(!f)return b;var m=b,a;for(a=0;a<f.length;a++){var g=f[a];if(g.to<=b)m-=g.len;else if(g.from>=b)break;else if(k.isInBreak(g,
b)){m-=b-g.from;break}}return m};k.prototype.findBreakAt=function(b,f){return p(f,function(f){return f.from<b&&b<f.to})};k.prototype.isInAnyBreak=function(b,l){var m=this.axis,a=m.options.breaks,g=a&&a.length,h;if(g){for(;g--;)if(k.isInBreak(a[g],b)){var d=!0;h||(h=f(a[g].showPoints,!m.isXAxis))}var c=d&&l?d&&!h:d}return c};k.prototype.setBreaks=function(l,n){var m=this,a=m.axis,g=y(l)&&!!l.length;a.isDirty=m.hasBreaks!==g;m.hasBreaks=g;a.options.breaks=a.userOptions.breaks=l;a.forceRedraw=!0;a.series.forEach(function(a){a.isDirty=
!0});g||a.val2lin!==k.val2Lin||(delete a.val2lin,delete a.lin2val);g&&(a.userOptions.ordinal=!1,a.lin2val=k.lin2Val,a.val2lin=k.val2Lin,a.setExtremes=function(a,d,c,e,g){if(m.hasBreaks){for(var h,f=this.options.breaks;h=m.findBreakAt(a,f);)a=h.to;for(;h=m.findBreakAt(d,f);)d=h.from;d<a&&(d=a)}b.prototype.setExtremes.call(this,a,d,c,e,g)},a.setAxisTranslation=function(){b.prototype.setAxisTranslation.call(this);m.unitLength=null;if(m.hasBreaks){var g=a.options.breaks||[],d=[],c=[],e=0,l,n=a.userMin||
a.min,q=a.userMax||a.max,r=f(a.pointRangePadding,0),t;g.forEach(function(a){l=a.repeat||Infinity;k.isInBreak(a,n)&&(n+=a.to%l-n%l);k.isInBreak(a,q)&&(q-=q%l-a.from%l)});g.forEach(function(a){p=a.from;for(l=a.repeat||Infinity;p-l>n;)p-=l;for(;p<n;)p+=l;for(t=p;t<q;t+=l)d.push({value:t,move:"in"}),d.push({value:t+(a.to-a.from),move:"out",size:a.breakSize})});d.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var v=0;var p=n;d.forEach(function(a){v+=
"in"===a.move?1:-1;1===v&&"in"===a.move&&(p=a.value);0===v&&(c.push({from:p,to:a.value,len:a.value-p-(a.size||0)}),e+=a.value-p-(a.size||0))});a.breakArray=m.breakArray=c;m.unitLength=q-n-e+r;w(a,"afterBreaks");a.staticScale?a.transA=a.staticScale:m.unitLength&&(a.transA*=(q-a.min+r)/m.unitLength);r&&(a.minPixelPadding=a.transA*a.minPointOffset);a.min=n;a.max=q}});f(n,!0)&&a.chart.redraw()};return k}();l=function(){function b(){}b.compose=function(b,l){b.keepProps.push("brokenAxis");var m=u.prototype;
m.drawBreaks=function(a,b){var g=this,d=g.points,c,e,k,l;if(a&&a.brokenAxis&&a.brokenAxis.hasBreaks){var m=a.brokenAxis;b.forEach(function(b){c=m&&m.breakArray||[];e=a.isXAxis?a.min:f(g.options.threshold,a.min);d.forEach(function(d){l=f(d["stack"+b.toUpperCase()],d[b]);c.forEach(function(b){if(n(e)&&n(l)){k=!1;if(e<b.from&&l>b.to||e>b.from&&l<b.from)k="pointBreak";else if(e<b.from&&l>b.from&&l<b.to||e>b.from&&l>b.to&&l<b.from)k="pointInBreak";k&&w(a,k,{point:d,brk:b})}})})})}};m.gappedPath=function(){var a=
this.currentDataGrouping,b=a&&a.gapSize;a=this.options.gapSize;var f=this.points.slice(),d=f.length-1,c=this.yAxis,e;if(a&&0<d)for("value"!==this.options.gapUnit&&(a*=this.basePointRange),b&&b>a&&b>=this.basePointRange&&(a=b),e=void 0;d--;)e&&!1!==e.visible||(e=f[d+1]),b=f[d],!1!==e.visible&&!1!==b.visible&&(e.x-b.x>a&&(e=(b.x+e.x)/2,f.splice(d+1,0,{isNull:!0,x:e}),c.stacking&&this.options.stacking&&(e=c.stacking.stacks[this.stackKey][e]=new x(c,c.options.stackLabels,!1,e,this.stack),e.total=0)),
e=b);return this.getGraphPath(f)};k(b,"init",function(){this.brokenAxis||(this.brokenAxis=new C(this))});k(b,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});k(b,"afterSetTickPositions",function(){var a=this.brokenAxis;if(a&&a.hasBreaks){var b=this.tickPositions,f=this.tickPositions.info,d=[],c;for(c=0;c<b.length;c++)a.isInAnyBreak(b[c])||d.push(b[c]);this.tickPositions=d;this.tickPositions.info=f}});k(b,"afterSetOptions",function(){this.brokenAxis&&
this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});k(l,"afterGeneratePoints",function(){var a=this.options.connectNulls,b=this.points,f=this.xAxis,d=this.yAxis;if(this.isDirty)for(var c=b.length;c--;){var e=b[c],k=!(null===e.y&&!1===a)&&(f&&f.brokenAxis&&f.brokenAxis.isInAnyBreak(e.x,!0)||d&&d.brokenAxis&&d.brokenAxis.isInAnyBreak(e.y,!0));e.visible=k?!1:!1!==e.options.visible}});k(l,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,f(this.pointArrayMap,["y"]))})};
return b}();l.compose(b,u);return l});x(b,"Core/Axis/TreeGridAxis.js",[b["Core/Globals.js"],b["Core/Axis/Axis.js"],b["Core/Axis/Tick.js"],b["Gantt/Tree.js"],b["Core/Axis/TreeGridTick.js"],b["Mixins/TreeSeries.js"],b["Core/Utilities.js"]],function(b,u,x,l,k,p,w){var y=p.getLevelOptions,n=w.addEvent,f=w.find,C=w.fireEvent,r=w.isArray,q=w.isNumber,t=w.isObject,m=w.isString,a=w.merge,g=w.pick,h=w.wrap,d;(function(c){function d(a,b){var c=a.collapseStart||0;a=a.collapseEnd||0;a>=b&&(c-=.5);return{from:c,
to:a,showPoints:!1}}function p(a,b,c){var d=[],e=[],g={},h={},k=-1,B="boolean"===typeof b?b:!1;a=l.getTree(a,{after:function(a){a=h[a.pos];var b=0,c=0;a.children.forEach(function(a){c+=(a.descendants||0)+1;b=Math.max((a.height||0)+1,b)});a.descendants=c;a.height=b;a.collapsed&&e.push(a)},before:function(a){var b=t(a.data,!0)?a.data:{},c=m(b.name)?b.name:"",e=g[a.parent];e=t(e,!0)?h[e.pos]:null;var l=function(a){return a.name===c},A;B&&t(e,!0)&&(A=f(e.children,l))?(l=A.pos,A.nodes.push(a)):l=k++;h[l]||
(h[l]=A={depth:e?e.depth+1:0,name:c,id:b.id,nodes:[a],children:[],pos:l},-1!==l&&d.push(c),t(e,!0)&&e.children.push(A));m(a.id)&&(g[a.id]=a);A&&!0===b.collapsed&&(A.collapsed=!0);a.pos=l}});h=function(a,b){var c=function(a,d,e){var f=d+(-1===d?0:b-1),g=(f-d)/2,h=d+g;a.nodes.forEach(function(a){var b=a.data;t(b,!0)&&(b.y=d+(b.seriesIndex||0),delete b.seriesIndex);a.pos=h});e[h]=a;a.pos=h;a.tickmarkOffset=g+.5;a.collapseStart=f+.5;a.children.forEach(function(a){c(a,f+1,e);f=(a.collapseEnd||0)-.5});
a.collapseEnd=f+.5;return e};return c(a["-1"],-1,{})}(h,c);return{categories:d,mapOfIdToNode:g,mapOfPosToGridNode:h,collapsedNodes:e,tree:a}}function u(c){c.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(d){var e=d.options||{},f=e.labels,g=e.uniqueNames,h=0;e=e.max;if(!d.treeGrid.mapOfPosToGridNode||d.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty})){var k=d.series.reduce(function(a,c){c.visible&&((c.options.data||[]).forEach(function(d){c.options.keys&&
c.options.keys.length&&(d=c.pointClass.prototype.optionsToObject.call({series:c},d),b.seriesTypes.gantt.prototype.setGanttPointAliases(d));t(d,!0)&&(d.seriesIndex=h,a.push(d))}),!0===g&&h++);return a},[]);if(e&&k.length<e)for(var l=k.length;l<=e;l++)k.push({name:l+"\u200b"});e=p(k,g||!1,!0===g?h:1);d.categories=e.categories;d.treeGrid.mapOfPosToGridNode=e.mapOfPosToGridNode;d.hasNames=!0;d.treeGrid.tree=e.tree;d.series.forEach(function(b){var c=(b.options.data||[]).map(function(c){r(c)&&b.options.keys&&
b.options.keys.length&&k.forEach(function(a){0<=c.indexOf(a.x)&&0<=c.indexOf(a.x2)&&(c=a)});return t(c,!0)?a(c):c});b.visible&&b.setData(c,!1)});d.treeGrid.mapOptionsToLevel=y({defaults:f,from:1,levels:f&&f.levels,to:d.treeGrid.tree&&d.treeGrid.tree.height});"beforeRender"===c.type&&(d.treeGrid.collapsedNodes=e.collapsedNodes)}})}function w(a,b){var c=this.treeGrid.mapOptionsToLevel||{},d=this.ticks,e=d[b],f;if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var g=this.treeGrid.mapOfPosToGridNode[b];
(c=c[g.depth])&&(f={labels:c});e?(e.parameters.category=g.name,e.options=f,e.addLabel()):d[b]=new x(this,b,void 0,void 0,{category:g.name,tickmarkOffset:g.tickmarkOffset,options:f})}else a.apply(this,Array.prototype.slice.call(arguments,1))}function E(a){var b=this.options;b=(b=b&&b.labels)&&q(b.indentation)?b.indentation:0;var c=a.apply(this,Array.prototype.slice.call(arguments,1));if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var d=this.treeGrid.mapOfPosToGridNode[-1].height||
0;c.width+=b*(d-1)}return c}function H(b,c,d){var e=this,f="treegrid"===d.type;e.treeGrid||(e.treeGrid=new J(e));f&&(n(c,"beforeRender",u),n(c,"beforeRedraw",u),n(c,"addSeries",function(a){a.options.data&&(a=p(a.options.data,d.uniqueNames||!1,1),e.treeGrid.collapsedNodes=(e.treeGrid.collapsedNodes||[]).concat(a.collapsedNodes))}),n(e,"foundExtremes",function(){e.treeGrid.collapsedNodes&&e.treeGrid.collapsedNodes.forEach(function(a){var b=e.treeGrid.collapse(a);e.brokenAxis&&(e.brokenAxis.setBreaks(b,
!1),e.treeGrid.collapsedNodes&&(e.treeGrid.collapsedNodes=e.treeGrid.collapsedNodes.filter(function(b){return a.collapseStart!==b.collapseStart||a.collapseEnd!==b.collapseEnd})))})}),n(e,"afterBreaks",function(){var a;"yAxis"===e.coll&&!e.staticScale&&(null===(a=e.chart.options.chart)||void 0===a?0:a.height)&&(e.isDirty=!0)}),d=a({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},
d,{reversed:!0,grid:{columns:void 0}}));b.apply(e,[c,d]);f&&(e.hasNames=!0,e.options.showLastLabel=!0)}function v(a){var b=this.options;"treegrid"===b.type?(this.min=g(this.userMin,b.min,this.dataMin),this.max=g(this.userMax,b.max,this.dataMax),C(this,"foundExtremes"),this.setAxisTranslation(),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?this.treeGrid.getTickPositions():[]):a.apply(this,Array.prototype.slice.call(arguments,1))}var I=!1;c.compose=function(a){I||
(h(a.prototype,"generateTick",w),h(a.prototype,"getMaxLabelDimensions",E),h(a.prototype,"init",H),h(a.prototype,"setTickInterval",v),k.compose(x),I=!0)};var J=function(){function a(a){this.axis=a}a.prototype.setCollapsedStatus=function(a){var b=this.axis,c=b.chart;b.series.forEach(function(b){var d=b.options.data;if(a.id&&d){var e=c.get(a.id);b=d[b.data.indexOf(e)];e&&b&&(e.collapsed=a.collapsed,b.collapsed=a.collapsed)}})};a.prototype.collapse=function(a){var b=this.axis,c=b.options.breaks||[],e=
d(a,b.max);c.push(e);a.collapsed=!0;b.treeGrid.setCollapsedStatus(a);return c};a.prototype.expand=function(a){var b=this.axis,c=b.options.breaks||[],e=d(a,b.max);a.collapsed=!1;b.treeGrid.setCollapsedStatus(a);return c.reduce(function(a,b){b.to===e.to&&b.from===e.from||a.push(b);return a},[])};a.prototype.getTickPositions=function(){var a=this.axis,b=Math.floor(a.min/a.tickInterval)*a.tickInterval,c=Math.ceil(a.max/a.tickInterval)*a.tickInterval;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(d,
e){e=+e;!(e>=b&&e<=c)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(e)||d.push(e);return d},[])};a.prototype.isCollapsed=function(a){var b=this.axis,c=b.options.breaks||[],e=d(a,b.max);return c.some(function(a){return a.from===e.from&&a.to===e.to})};a.prototype.toggleCollapse=function(a){return this.isCollapsed(a)?this.expand(a):this.collapse(a)};return a}();c.Additions=J})(d||(d={}));u.prototype.utils={getNode:l.getNode};d.compose(u);return d});x(b,"masters/modules/treegrid.src.js",[],function(){})});
//# sourceMappingURL=treegrid.js.map