/*
 Highcharts JS v8.2.2 (2020-11-05)

 3D features for Highcharts JS

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/highcharts-3d",["highcharts"],function(J){c(J);c.Highcharts=J;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function J(c,u,v,E){c.hasOwnProperty(u)||(c[u]=E.apply(null,v))}c=c?c._modules:{};J(c,"Extensions/Math3D.js",[c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,u){function v(m,f,b){f=0<b&&b<Number.POSITIVE_INFINITY?
b/(m.z+f.z+b):1;return{x:m.x*f,y:m.y*f}}function I(m,f,b,k){var c=f.options.chart.options3d,l=r(k,b?f.inverted:!1),a={x:f.plotWidth/2,y:f.plotHeight/2,z:c.depth/2,vd:r(c.depth,1)*r(c.viewDistance,0)},g=f.scale3d||1;k=t*c.beta*(l?-1:1);c=t*c.alpha*(l?-1:1);var D=Math.cos(c),d=Math.cos(-k),p=Math.sin(c),h=Math.sin(-k);b||(a.x+=f.plotLeft,a.y+=f.plotTop);return m.map(function(b){var q=(l?b.y:b.x)-a.x;var f=(l?b.x:b.y)-a.y;b=(b.z||0)-a.z;q={x:d*q-h*b,y:-p*h*q+D*f-d*p*b,z:D*h*q+p*f+D*d*b};f=v(q,a,a.vd);
f.x=f.x*g+a.x;f.y=f.y*g+a.y;f.z=q.z*g+a.z;return{x:l?f.y:f.x,y:l?f.x:f.y,z:f.z}})}function h(m,f){var b=f.options.chart.options3d,c=f.plotWidth/2;f=f.plotHeight/2;b=r(b.depth,1)*r(b.viewDistance,0)+b.depth;return Math.sqrt(Math.pow(c-r(m.plotX,m.x),2)+Math.pow(f-r(m.plotY,m.y),2)+Math.pow(b-r(m.plotZ,m.z),2))}function y(m){var f=0,b;for(b=0;b<m.length;b++){var c=(b+1)%m.length;f+=m[b].x*m[c].y-m[c].x*m[b].y}return f/2}function k(c,f,b){return y(I(c,f,b))}var r=u.pick,t=c.deg2rad;c.perspective3D=v;
c.perspective=I;c.pointCameraDistance=h;c.shapeArea=y;c.shapeArea3d=k;return{perspective:I,perspective3D:v,pointCameraDistance:h,shapeArea:y,shapeArea3D:k}});J(c,"Core/Renderer/SVG/SVGRenderer3D.js",[c["Core/Animation/AnimationUtilities.js"],c["Core/Color/Color.js"],c["Core/Globals.js"],c["Extensions/Math3D.js"],c["Core/Renderer/SVG/SVGElement.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Utilities.js"]],function(c,u,v,E,h,y,k){function r(a,d,e,M,g,n,b,x){var z=[],w=n-g;return n>g&&n-g>Math.PI/
2+.0001?(z=z.concat(r(a,d,e,M,g,g+Math.PI/2,b,x)),z=z.concat(r(a,d,e,M,g+Math.PI/2,n,b,x))):n<g&&g-n>Math.PI/2+.0001?(z=z.concat(r(a,d,e,M,g,g-Math.PI/2,b,x)),z=z.concat(r(a,d,e,M,g-Math.PI/2,n,b,x))):[["C",a+e*Math.cos(g)-e*q*w*Math.sin(g)+b,d+M*Math.sin(g)+M*q*w*Math.cos(g)+x,a+e*Math.cos(n)+e*q*w*Math.sin(n)+b,d+M*Math.sin(n)-M*q*w*Math.cos(n)+x,a+e*Math.cos(n)+b,d+M*Math.sin(n)+x]]}var t=c.animObject,m=u.parse,f=E.perspective,b=E.shapeArea,C=k.defined,N=k.extend,l=k.merge,a=k.objectEach,g=k.pick,
D=Math.cos,d=Math.PI,p=Math.sin,H=v.charts,O=v.deg2rad;var q=4*(Math.sqrt(2)-1)/3/(d/2);y.prototype.toLinePath=function(a,d){var e=[];a.forEach(function(a){e.push(["L",a.x,a.y])});a.length&&(e[0][0]="M",d&&e.push(["Z"]));return e};y.prototype.toLineSegments=function(a){var d=[],e=!0;a.forEach(function(a){d.push(e?["M",a.x,a.y]:["L",a.x,a.y]);e=!e});return d};y.prototype.face3d=function(a){var d=this,e=this.createElement("path");e.vertexes=[];e.insidePlotArea=!1;e.enabled=!0;e.attr=function(a){if("object"===
typeof a&&(C(a.enabled)||C(a.vertexes)||C(a.insidePlotArea))){this.enabled=g(a.enabled,this.enabled);this.vertexes=g(a.vertexes,this.vertexes);this.insidePlotArea=g(a.insidePlotArea,this.insidePlotArea);delete a.enabled;delete a.vertexes;delete a.insidePlotArea;var e=f(this.vertexes,H[d.chartIndex],this.insidePlotArea),n=d.toLinePath(e,!0);e=b(e);e=this.enabled&&0<e?"visible":"hidden";a.d=n;a.visibility=e}return h.prototype.attr.apply(this,arguments)};e.animate=function(a){if("object"===typeof a&&
(C(a.enabled)||C(a.vertexes)||C(a.insidePlotArea))){this.enabled=g(a.enabled,this.enabled);this.vertexes=g(a.vertexes,this.vertexes);this.insidePlotArea=g(a.insidePlotArea,this.insidePlotArea);delete a.enabled;delete a.vertexes;delete a.insidePlotArea;var e=f(this.vertexes,H[d.chartIndex],this.insidePlotArea),n=d.toLinePath(e,!0);e=b(e);e=this.enabled&&0<e?"visible":"hidden";a.d=n;this.attr("visibility",e)}return h.prototype.animate.apply(this,arguments)};return e.attr(a)};y.prototype.polyhedron=
function(a){var d=this,e=this.g(),g=e.destroy;this.styledMode||e.attr({"stroke-linejoin":"round"});e.faces=[];e.destroy=function(){for(var a=0;a<e.faces.length;a++)e.faces[a].destroy();return g.call(this)};e.attr=function(a,n,g,x){if("object"===typeof a&&C(a.faces)){for(;e.faces.length>a.faces.length;)e.faces.pop().destroy();for(;e.faces.length<a.faces.length;)e.faces.push(d.face3d().add(e));for(var z=0;z<a.faces.length;z++)d.styledMode&&delete a.faces[z].fill,e.faces[z].attr(a.faces[z],null,g,x);
delete a.faces}return h.prototype.attr.apply(this,arguments)};e.animate=function(a,n,g){if(a&&a.faces){for(;e.faces.length>a.faces.length;)e.faces.pop().destroy();for(;e.faces.length<a.faces.length;)e.faces.push(d.face3d().add(e));for(var x=0;x<a.faces.length;x++)e.faces[x].animate(a.faces[x],n,g);delete a.faces}return h.prototype.animate.apply(this,arguments)};return e.attr(a)};c={initArgs:function(a){var d=this,e=d.renderer,g=e[d.pathType+"Path"](a),b=g.zIndexes;d.parts.forEach(function(a){d[a]=
e.path(g[a]).attr({"class":"highcharts-3d-"+a,zIndex:b[a]||0}).add(d)});d.attr({"stroke-linejoin":"round",zIndex:b.group});d.originalDestroy=d.destroy;d.destroy=d.destroyParts;d.forcedSides=g.forcedSides},singleSetterForParts:function(d,g,e,b,f,n){var p={};b=[null,null,b||"attr",f,n];var x=e&&e.zIndexes;e?(x&&x.group&&this.attr({zIndex:x.group}),a(e,function(a,w){p[w]={};p[w][d]=a;x&&(p[w].zIndex=e.zIndexes[w]||0)}),b[1]=p):(p[d]=g,b[0]=p);return this.processParts.apply(this,b)},processParts:function(a,
d,e,b,p){var n=this;n.parts.forEach(function(f){d&&(a=g(d[f],!1));if(!1!==a)n[f][e](a,b,p)});return n},destroyParts:function(){this.processParts(null,null,"destroy");return this.originalDestroy()}};var L=l(c,{parts:["front","top","side"],pathType:"cuboid",attr:function(a,d,e,g){if("string"===typeof a&&"undefined"!==typeof d){var b=a;a={};a[b]=d}return a.shapeArgs||C(a.x)?this.singleSetterForParts("d",null,this.renderer[this.pathType+"Path"](a.shapeArgs||a)):h.prototype.attr.call(this,a,void 0,e,g)},
animate:function(a,d,e){if(C(a.x)&&C(a.y)){a=this.renderer[this.pathType+"Path"](a);var g=a.forcedSides;this.singleSetterForParts("d",null,a,"animate",d,e);this.attr({zIndex:a.zIndexes.group});g!==this.forcedSides&&(this.forcedSides=g,L.fillSetter.call(this,this.fill))}else h.prototype.animate.call(this,a,d,e);return this},fillSetter:function(a){this.forcedSides=this.forcedSides||[];this.singleSetterForParts("fill",null,{front:a,top:m(a).brighten(0<=this.forcedSides.indexOf("top")?0:.1).get(),side:m(a).brighten(0<=
this.forcedSides.indexOf("side")?0:-.1).get()});this.color=this.fill=a;return this}});y.prototype.elements3d={base:c,cuboid:L};y.prototype.element3d=function(a,d){var e=this.g();N(e,this.elements3d[a]);e.initArgs(d);return e};y.prototype.cuboid=function(a){return this.element3d("cuboid",a)};y.prototype.cuboidPath=function(a){function d(a){return 0===c&&1<a&&6>a?{x:F[a].x,y:F[a].y+10,z:F[a].z}:F[0].x===F[7].x&&4<=a?{x:F[a].x+10,y:F[a].y,z:F[a].z}:0===z&&2>a||5<a?{x:F[a].x,y:F[a].y,z:F[a].z+10}:F[a]}
function e(a){return F[a]}var g=a.x,p=a.y,n=a.z||0,c=a.height,x=a.width,z=a.depth,w=H[this.chartIndex],A=w.options.chart.options3d.alpha,D=0,F=[{x:g,y:p,z:n},{x:g+x,y:p,z:n},{x:g+x,y:p+c,z:n},{x:g,y:p+c,z:n},{x:g,y:p+c,z:n+z},{x:g+x,y:p+c,z:n+z},{x:g+x,y:p,z:n+z},{x:g,y:p,z:n+z}],l=[];F=f(F,w,a.insidePlotArea);var B=function(a,w,g){var n=[[],-1],A=a.map(e),p=w.map(e);a=a.map(d);w=w.map(d);0>b(A)?n=[A,0]:0>b(p)?n=[p,1]:g&&(l.push(g),n=0>b(a)?[A,0]:0>b(w)?[p,1]:[A,0]);return n};var G=B([3,2,1,0],[7,
6,5,4],"front");a=G[0];var q=G[1];G=B([1,6,7,0],[4,5,2,3],"top");x=G[0];var m=G[1];G=B([1,2,5,6],[0,7,4,3],"side");B=G[0];G=G[1];1===G?D+=1E6*(w.plotWidth-g):G||(D+=1E6*g);D+=10*(!m||0<=A&&180>=A||360>A&&357.5<A?w.plotHeight-p:10+p);1===q?D+=100*n:q||(D+=100*(1E3-n));return{front:this.toLinePath(a,!0),top:this.toLinePath(x,!0),side:this.toLinePath(B,!0),zIndexes:{group:Math.round(D)},forcedSides:l,isFront:q,isTop:m}};y.prototype.arc3d=function(a){function d(a){var d=!1,e={},g;a=l(a);for(g in a)-1!==
b.indexOf(g)&&(e[g]=a[g],delete a[g],d=!0);return d?[e,a]:!1}var e=this.g(),p=e.renderer,b="x y r innerR start end depth".split(" ");a=l(a);a.alpha=(a.alpha||0)*O;a.beta=(a.beta||0)*O;e.top=p.path();e.side1=p.path();e.side2=p.path();e.inn=p.path();e.out=p.path();e.onAdd=function(){var a=e.parentGroup,d=e.attr("class");e.top.add(e);["out","inn","side1","side2"].forEach(function(g){e[g].attr({"class":d+" highcharts-3d-side"}).add(a)})};["addClass","removeClass"].forEach(function(a){e[a]=function(){var d=
arguments;["top","out","inn","side1","side2"].forEach(function(g){e[g][a].apply(e[g],d)})}});e.setPaths=function(a){var d=e.renderer.arc3dPath(a),g=100*d.zTop;e.attribs=a;e.top.attr({d:d.top,zIndex:d.zTop});e.inn.attr({d:d.inn,zIndex:d.zInn});e.out.attr({d:d.out,zIndex:d.zOut});e.side1.attr({d:d.side1,zIndex:d.zSide1});e.side2.attr({d:d.side2,zIndex:d.zSide2});e.zIndex=g;e.attr({zIndex:g});a.center&&(e.top.setRadialReference(a.center),delete a.center)};e.setPaths(a);e.fillSetter=function(a){var d=
m(a).brighten(-.1).get();this.fill=a;this.side1.attr({fill:d});this.side2.attr({fill:d});this.inn.attr({fill:d});this.out.attr({fill:d});this.top.attr({fill:a});return this};["opacity","translateX","translateY","visibility"].forEach(function(a){e[a+"Setter"]=function(a,d){e[d]=a;["out","inn","side1","side2","top"].forEach(function(g){e[g].attr(d,a)})}});e.attr=function(a){var g;if("object"===typeof a&&(g=d(a))){var p=g[0];arguments[0]=g[1];N(e.attribs,p);e.setPaths(e.attribs)}return h.prototype.attr.apply(e,
arguments)};e.animate=function(a,p,b){var z=this.attribs,w="data-"+Math.random().toString(26).substring(2,9);delete a.center;delete a.z;delete a.alpha;delete a.beta;var A=t(g(p,this.renderer.globalAnimation));if(A.duration){p=d(a);e[w]=0;a[w]=1;e[w+"Setter"]=v.noop;if(p){var f=p[0];A.step=function(a,d){function e(a){return z[a]+(g(f[a],z[a])-z[a])*d.pos}d.prop===w&&d.elem.setPaths(l(z,{x:e("x"),y:e("y"),r:e("r"),innerR:e("innerR"),start:e("start"),end:e("end"),depth:e("depth")}))}}p=A}return h.prototype.animate.call(this,
a,p,b)};e.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();return h.prototype.destroy.call(this)};e.hide=function(){this.top.hide();this.out.hide();this.inn.hide();this.side1.hide();this.side2.hide()};e.show=function(a){this.top.show(a);this.out.show(a);this.inn.show(a);this.side1.show(a);this.side2.show(a)};return e};y.prototype.arc3dPath=function(a){function g(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var e=a.x,b=a.y,
f=a.start,c=a.end-.00001,l=a.r,x=a.innerR||0,z=a.depth||0,w=a.alpha,A=a.beta,q=Math.cos(f),F=Math.sin(f);a=Math.cos(c);var m=Math.sin(c),B=l*Math.cos(A);l*=Math.cos(w);var G=x*Math.cos(A),k=x*Math.cos(w);x=z*Math.sin(A);var h=z*Math.sin(w);z=[["M",e+B*q,b+l*F]];z=z.concat(r(e,b,B,l,f,c,0,0));z.push(["L",e+G*a,b+k*m]);z=z.concat(r(e,b,G,k,c,f,0,0));z.push(["Z"]);var L=0<A?Math.PI/2:0;A=0<w?0:Math.PI/2;L=f>-L?f:c>-L?-L:f;var K=c<d-A?c:f<d-A?d-A:c,H=2*d-A;w=[["M",e+B*D(L),b+l*p(L)]];w=w.concat(r(e,b,
B,l,L,K,0,0));c>H&&f<H?(w.push(["L",e+B*D(K)+x,b+l*p(K)+h]),w=w.concat(r(e,b,B,l,K,H,x,h)),w.push(["L",e+B*D(H),b+l*p(H)]),w=w.concat(r(e,b,B,l,H,c,0,0)),w.push(["L",e+B*D(c)+x,b+l*p(c)+h]),w=w.concat(r(e,b,B,l,c,H,x,h)),w.push(["L",e+B*D(H),b+l*p(H)]),w=w.concat(r(e,b,B,l,H,K,0,0))):c>d-A&&f<d-A&&(w.push(["L",e+B*Math.cos(K)+x,b+l*Math.sin(K)+h]),w=w.concat(r(e,b,B,l,K,c,x,h)),w.push(["L",e+B*Math.cos(c),b+l*Math.sin(c)]),w=w.concat(r(e,b,B,l,c,K,0,0)));w.push(["L",e+B*Math.cos(K)+x,b+l*Math.sin(K)+
h]);w=w.concat(r(e,b,B,l,K,L,x,h));w.push(["Z"]);A=[["M",e+G*q,b+k*F]];A=A.concat(r(e,b,G,k,f,c,0,0));A.push(["L",e+G*Math.cos(c)+x,b+k*Math.sin(c)+h]);A=A.concat(r(e,b,G,k,c,f,x,h));A.push(["Z"]);q=[["M",e+B*q,b+l*F],["L",e+B*q+x,b+l*F+h],["L",e+G*q+x,b+k*F+h],["L",e+G*q,b+k*F],["Z"]];e=[["M",e+B*a,b+l*m],["L",e+B*a+x,b+l*m+h],["L",e+G*a+x,b+k*m+h],["L",e+G*a,b+k*m],["Z"]];m=Math.atan2(h,-x);b=Math.abs(c+m);a=Math.abs(f+m);f=Math.abs((f+c)/2+m);b=g(b);a=g(a);f=g(f);f*=1E5;c=1E5*a;b*=1E5;return{top:z,
zTop:1E5*Math.PI+1,out:w,zOut:Math.max(f,c,b),inn:A,zInn:Math.max(f,c,b),side1:q,zSide1:.99*b,side2:e,zSide2:.99*c}};return y});J(c,"Core/Axis/Tick3D.js",[c["Core/Utilities.js"]],function(c){var u=c.addEvent,v=c.extend,I=c.wrap;return function(){function c(){}c.compose=function(h){u(h,"afterGetLabelPosition",c.onAfterGetLabelPosition);I(h.prototype,"getMarkPath",c.wrapGetMarkPath)};c.onAfterGetLabelPosition=function(c){var k=this.axis.axis3D;k&&v(c.pos,k.fix3dPosition(c.pos))};c.wrapGetMarkPath=function(c){var k=
this.axis.axis3D,h=c.apply(this,[].slice.call(arguments,1));if(k){var t=h[0],m=h[1];if("M"===t[0]&&"L"===m[0])return k=[k.fix3dPosition({x:t[1],y:t[2],z:0}),k.fix3dPosition({x:m[1],y:m[2],z:0})],this.axis.chart.renderer.toLineSegments(k)}return h};return c}()});J(c,"Core/Axis/Axis3D.js",[c["Core/Globals.js"],c["Extensions/Math3D.js"],c["Core/Axis/Tick.js"],c["Core/Axis/Tick3D.js"],c["Core/Utilities.js"]],function(c,u,v,E,h){var y=u.perspective,k=u.perspective3D,r=u.shapeArea,t=h.addEvent,m=h.merge,
f=h.pick,b=h.wrap,C=c.deg2rad,N=function(){function b(a){this.axis=a}b.prototype.fix3dPosition=function(a,g){var b=this.axis,d=b.chart;if("colorAxis"===b.coll||!d.chart3d||!d.is3d())return a;var c=C*d.options.chart.options3d.alpha,l=C*d.options.chart.options3d.beta,m=f(g&&b.options.title.position3d,b.options.labels.position3d);g=f(g&&b.options.title.skew3d,b.options.labels.skew3d);var q=d.chart3d.frame3d,h=d.plotLeft,k=d.plotWidth+h,t=d.plotTop,e=d.plotHeight+t;d=!1;var u=0,v=0,n={x:0,y:1,z:0};a=
b.axis3D.swapZ({x:a.x,y:a.y,z:0});if(b.isZAxis)if(b.opposite){if(null===q.axes.z.top)return{};v=a.y-t;a.x=q.axes.z.top.x;a.y=q.axes.z.top.y;h=q.axes.z.top.xDir;d=!q.top.frontFacing}else{if(null===q.axes.z.bottom)return{};v=a.y-e;a.x=q.axes.z.bottom.x;a.y=q.axes.z.bottom.y;h=q.axes.z.bottom.xDir;d=!q.bottom.frontFacing}else if(b.horiz)if(b.opposite){if(null===q.axes.x.top)return{};v=a.y-t;a.y=q.axes.x.top.y;a.z=q.axes.x.top.z;h=q.axes.x.top.xDir;d=!q.top.frontFacing}else{if(null===q.axes.x.bottom)return{};
v=a.y-e;a.y=q.axes.x.bottom.y;a.z=q.axes.x.bottom.z;h=q.axes.x.bottom.xDir;d=!q.bottom.frontFacing}else if(b.opposite){if(null===q.axes.y.right)return{};u=a.x-k;a.x=q.axes.y.right.x;a.z=q.axes.y.right.z;h=q.axes.y.right.xDir;h={x:h.z,y:h.y,z:-h.x}}else{if(null===q.axes.y.left)return{};u=a.x-h;a.x=q.axes.y.left.x;a.z=q.axes.y.left.z;h=q.axes.y.left.xDir}"chart"!==m&&("flap"===m?b.horiz?(l=Math.sin(c),c=Math.cos(c),b.opposite&&(l=-l),d&&(l=-l),n={x:h.z*l,y:c,z:-h.x*l}):h={x:Math.cos(l),y:0,z:Math.sin(l)}:
"ortho"===m?b.horiz?(n=Math.cos(c),m=Math.sin(l)*n,c=-Math.sin(c),l=-n*Math.cos(l),n={x:h.y*l-h.z*c,y:h.z*m-h.x*l,z:h.x*c-h.y*m},c=1/Math.sqrt(n.x*n.x+n.y*n.y+n.z*n.z),d&&(c=-c),n={x:c*n.x,y:c*n.y,z:c*n.z}):h={x:Math.cos(l),y:0,z:Math.sin(l)}:b.horiz?n={x:Math.sin(l)*Math.sin(c),y:Math.cos(c),z:-Math.cos(l)*Math.sin(c)}:h={x:Math.cos(l),y:0,z:Math.sin(l)});a.x+=u*h.x+v*n.x;a.y+=u*h.y+v*n.y;a.z+=u*h.z+v*n.z;d=y([a],b.chart)[0];g&&(0>r(y([a,{x:a.x+h.x,y:a.y+h.y,z:a.z+h.z},{x:a.x+n.x,y:a.y+n.y,z:a.z+
n.z}],b.chart))&&(h={x:-h.x,y:-h.y,z:-h.z}),a=y([{x:a.x,y:a.y,z:a.z},{x:a.x+h.x,y:a.y+h.y,z:a.z+h.z},{x:a.x+n.x,y:a.y+n.y,z:a.z+n.z}],b.chart),d.matrix=[a[1].x-a[0].x,a[1].y-a[0].y,a[2].x-a[0].x,a[2].y-a[0].y,d.x,d.y],d.matrix[4]-=d.x*d.matrix[0]+d.y*d.matrix[2],d.matrix[5]-=d.x*d.matrix[1]+d.y*d.matrix[3]);return d};b.prototype.swapZ=function(a,b){var g=this.axis;return g.isZAxis?(b=b?0:g.chart.plotLeft,{x:b+a.z,y:a.y,z:a.x-b}):a};return b}();return function(){function c(){}c.compose=function(a){m(!0,
a.defaultOptions,c.defaultOptions);a.keepProps.push("axis3D");t(a,"init",c.onInit);t(a,"afterSetOptions",c.onAfterSetOptions);t(a,"drawCrosshair",c.onDrawCrosshair);t(a,"destroy",c.onDestroy);a=a.prototype;b(a,"getLinePath",c.wrapGetLinePath);b(a,"getPlotBandPath",c.wrapGetPlotBandPath);b(a,"getPlotLinePath",c.wrapGetPlotLinePath);b(a,"getSlotWidth",c.wrapGetSlotWidth);b(a,"getTitlePosition",c.wrapGetTitlePosition);E.compose(v)};c.onAfterSetOptions=function(){var a=this.chart,b=this.options;a.is3d&&
a.is3d()&&"colorAxis"!==this.coll&&(b.tickWidth=f(b.tickWidth,0),b.gridLineWidth=f(b.gridLineWidth,1))};c.onDestroy=function(){["backFrame","bottomFrame","sideFrame"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this)};c.onDrawCrosshair=function(a){this.chart.is3d()&&"colorAxis"!==this.coll&&a.point&&(a.point.crosshairPos=this.isXAxis?a.point.axisXpos:this.len-a.point.axisYpos)};c.onInit=function(){this.axis3D||(this.axis3D=new N(this))};c.wrapGetLinePath=function(a){return this.chart.is3d()&&
"colorAxis"!==this.coll?[]:a.apply(this,[].slice.call(arguments,1))};c.wrapGetPlotBandPath=function(a){if(!this.chart.is3d()||"colorAxis"===this.coll)return a.apply(this,[].slice.call(arguments,1));var b=arguments,c=b[2],d=[];b=this.getPlotLinePath({value:b[1]});c=this.getPlotLinePath({value:c});if(b&&c)for(var f=0;f<b.length;f+=2){var h=b[f],l=b[f+1],m=c[f],k=c[f+1];"M"===h[0]&&"L"===l[0]&&"M"===m[0]&&"L"===k[0]&&d.push(h,l,k,["L",m[1],m[2]],["Z"])}return d};c.wrapGetPlotLinePath=function(a){var b=
this.axis3D,c=this.chart,d=a.apply(this,[].slice.call(arguments,1));if("colorAxis"===this.coll||!c.chart3d||!c.is3d()||null===d)return d;var f=c.options.chart.options3d,h=this.isZAxis?c.plotWidth:f.depth;f=c.chart3d.frame3d;var l=d[0],m=d[1];d=[];"M"===l[0]&&"L"===m[0]&&(b=[b.swapZ({x:l[1],y:l[2],z:0}),b.swapZ({x:l[1],y:l[2],z:h}),b.swapZ({x:m[1],y:m[2],z:0}),b.swapZ({x:m[1],y:m[2],z:h})],this.horiz?(this.isZAxis?(f.left.visible&&d.push(b[0],b[2]),f.right.visible&&d.push(b[1],b[3])):(f.front.visible&&
d.push(b[0],b[2]),f.back.visible&&d.push(b[1],b[3])),f.top.visible&&d.push(b[0],b[1]),f.bottom.visible&&d.push(b[2],b[3])):(f.front.visible&&d.push(b[0],b[2]),f.back.visible&&d.push(b[1],b[3]),f.left.visible&&d.push(b[0],b[1]),f.right.visible&&d.push(b[2],b[3])),d=y(d,this.chart,!1));return c.renderer.toLineSegments(d)};c.wrapGetSlotWidth=function(a,b){var c=this.chart,d=this.ticks,g=this.gridGroup;if(this.categories&&c.frameShapes&&c.is3d()&&g&&b&&b.label){g=g.element.childNodes[0].getBBox();var h=
c.frameShapes.left.getBBox(),l=c.options.chart.options3d;c={x:c.plotWidth/2,y:c.plotHeight/2,z:l.depth/2,vd:f(l.depth,1)*f(l.viewDistance,0)};var m,r;l=b.pos;var t=d[l-1];d=d[l+1];0!==l&&t&&t.label.xy&&(m=k({x:t.label.xy.x,y:t.label.xy.y,z:null},c,c.vd));d&&d.label.xy&&(r=k({x:d.label.xy.x,y:d.label.xy.y,z:null},c,c.vd));d={x:b.label.xy.x,y:b.label.xy.y,z:null};d=k(d,c,c.vd);return Math.abs(m?d.x-m.x:r?r.x-d.x:g.x-h.x)}return a.apply(this,[].slice.call(arguments,1))};c.wrapGetTitlePosition=function(a){var b=
a.apply(this,[].slice.call(arguments,1));return this.axis3D?this.axis3D.fix3dPosition(b,!0):b};c.defaultOptions={labels:{position3d:"offset",skew3d:!1},title:{position3d:null,skew3d:null}};return c}()});J(c,"Core/Axis/ZAxis.js",[c["Core/Axis/Axis.js"],c["Core/Utilities.js"]],function(c,u){var v=this&&this.__extends||function(){var c=function(f,b){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,c){b.__proto__=c}||function(b,c){for(var f in c)c.hasOwnProperty(f)&&(b[f]=c[f])};return c(f,
b)};return function(f,b){function h(){this.constructor=f}c(f,b);f.prototype=null===b?Object.create(b):(h.prototype=b.prototype,new h)}}(),I=u.addEvent,h=u.merge,y=u.pick,k=u.splat,r=function(){function c(){}c.compose=function(f){I(f,"afterGetAxes",c.onAfterGetAxes);f=f.prototype;f.addZAxis=c.wrapAddZAxis;f.collectionsWithInit.zAxis=[f.addZAxis];f.collectionsWithUpdate.push("zAxis")};c.onAfterGetAxes=function(){var c=this,b=this.options;b=b.zAxis=k(b.zAxis||{});c.is3d()&&(c.zAxis=[],b.forEach(function(b,
f){b.index=f;b.isX=!0;c.addZAxis(b).setScale()}))};c.wrapAddZAxis=function(c){return new t(this,c)};return c}(),t=function(c){function f(b,f){b=c.call(this,b,f)||this;b.isZAxis=!0;return b}v(f,c);f.prototype.getSeriesExtremes=function(){var b=this,c=b.chart;b.hasVisibleSeries=!1;b.dataMin=b.dataMax=b.ignoreMinPadding=b.ignoreMaxPadding=void 0;b.stacking&&b.stacking.buildStacks();b.series.forEach(function(f){!f.visible&&c.options.chart&&c.options.chart.ignoreHiddenSeries||(b.hasVisibleSeries=!0,f=
f.zData,f.length&&(b.dataMin=Math.min(y(b.dataMin,f[0]),Math.min.apply(null,f)),b.dataMax=Math.max(y(b.dataMax,f[0]),Math.max.apply(null,f))))})};f.prototype.setAxisSize=function(){var b=this.chart;c.prototype.setAxisSize.call(this);this.width=this.len=b.options.chart&&b.options.chart.options3d&&b.options.chart.options3d.depth||0;this.right=b.chartWidth-this.width-this.left};f.prototype.setOptions=function(b){b=h({offset:0,lineWidth:0},b);c.prototype.setOptions.call(this,b);this.coll="zAxis"};f.ZChartComposition=
r;return f}(c);return t});J(c,"Core/Chart/Chart3D.js",[c["Core/Axis/Axis.js"],c["Core/Axis/Axis3D.js"],c["Core/Chart/Chart.js"],c["Core/Animation/Fx.js"],c["Core/Globals.js"],c["Extensions/Math3D.js"],c["Core/Options.js"],c["Core/Utilities.js"],c["Core/Axis/ZAxis.js"]],function(c,u,v,E,h,y,k,r,t){var m=y.perspective,f=y.shapeArea3D,b=k.defaultOptions,C=r.addEvent,I=r.isArray,l=r.merge,a=r.pick,g=r.wrap,D;(function(c){function d(a){this.is3d()&&"scatter"===a.options.type&&(a.options.type="scatter3d")}
function k(){if(this.chart3d&&this.is3d()){var a=this.renderer,c=this.options.chart.options3d,b=this.chart3d.get3dFrame(),d=this.plotLeft,e=this.plotLeft+this.plotWidth,f=this.plotTop,g=this.plotTop+this.plotHeight;c=c.depth;var l=d-(b.left.visible?b.left.size:0),m=e+(b.right.visible?b.right.size:0),k=f-(b.top.visible?b.top.size:0),p=g+(b.bottom.visible?b.bottom.size:0),q=0-(b.front.visible?b.front.size:0),n=c+(b.back.visible?b.back.size:0),r=this.hasRendered?"animate":"attr";this.chart3d.frame3d=
b;this.frameShapes||(this.frameShapes={bottom:a.polyhedron().add(),top:a.polyhedron().add(),left:a.polyhedron().add(),right:a.polyhedron().add(),back:a.polyhedron().add(),front:a.polyhedron().add()});this.frameShapes.bottom[r]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",zIndex:b.bottom.frontFacing?-1E3:1E3,faces:[{fill:h.color(b.bottom.color).brighten(.1).get(),vertexes:[{x:l,y:p,z:q},{x:m,y:p,z:q},{x:m,y:p,z:n},{x:l,y:p,z:n}],enabled:b.bottom.visible},{fill:h.color(b.bottom.color).brighten(.1).get(),
vertexes:[{x:d,y:g,z:c},{x:e,y:g,z:c},{x:e,y:g,z:0},{x:d,y:g,z:0}],enabled:b.bottom.visible},{fill:h.color(b.bottom.color).brighten(-.1).get(),vertexes:[{x:l,y:p,z:q},{x:l,y:p,z:n},{x:d,y:g,z:c},{x:d,y:g,z:0}],enabled:b.bottom.visible&&!b.left.visible},{fill:h.color(b.bottom.color).brighten(-.1).get(),vertexes:[{x:m,y:p,z:n},{x:m,y:p,z:q},{x:e,y:g,z:0},{x:e,y:g,z:c}],enabled:b.bottom.visible&&!b.right.visible},{fill:h.color(b.bottom.color).get(),vertexes:[{x:m,y:p,z:q},{x:l,y:p,z:q},{x:d,y:g,z:0},
{x:e,y:g,z:0}],enabled:b.bottom.visible&&!b.front.visible},{fill:h.color(b.bottom.color).get(),vertexes:[{x:l,y:p,z:n},{x:m,y:p,z:n},{x:e,y:g,z:c},{x:d,y:g,z:c}],enabled:b.bottom.visible&&!b.back.visible}]});this.frameShapes.top[r]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:b.top.frontFacing?-1E3:1E3,faces:[{fill:h.color(b.top.color).brighten(.1).get(),vertexes:[{x:l,y:k,z:n},{x:m,y:k,z:n},{x:m,y:k,z:q},{x:l,y:k,z:q}],enabled:b.top.visible},{fill:h.color(b.top.color).brighten(.1).get(),
vertexes:[{x:d,y:f,z:0},{x:e,y:f,z:0},{x:e,y:f,z:c},{x:d,y:f,z:c}],enabled:b.top.visible},{fill:h.color(b.top.color).brighten(-.1).get(),vertexes:[{x:l,y:k,z:n},{x:l,y:k,z:q},{x:d,y:f,z:0},{x:d,y:f,z:c}],enabled:b.top.visible&&!b.left.visible},{fill:h.color(b.top.color).brighten(-.1).get(),vertexes:[{x:m,y:k,z:q},{x:m,y:k,z:n},{x:e,y:f,z:c},{x:e,y:f,z:0}],enabled:b.top.visible&&!b.right.visible},{fill:h.color(b.top.color).get(),vertexes:[{x:l,y:k,z:q},{x:m,y:k,z:q},{x:e,y:f,z:0},{x:d,y:f,z:0}],enabled:b.top.visible&&
!b.front.visible},{fill:h.color(b.top.color).get(),vertexes:[{x:m,y:k,z:n},{x:l,y:k,z:n},{x:d,y:f,z:c},{x:e,y:f,z:c}],enabled:b.top.visible&&!b.back.visible}]});this.frameShapes.left[r]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:b.left.frontFacing?-1E3:1E3,faces:[{fill:h.color(b.left.color).brighten(.1).get(),vertexes:[{x:l,y:p,z:q},{x:d,y:g,z:0},{x:d,y:g,z:c},{x:l,y:p,z:n}],enabled:b.left.visible&&!b.bottom.visible},{fill:h.color(b.left.color).brighten(.1).get(),vertexes:[{x:l,
y:k,z:n},{x:d,y:f,z:c},{x:d,y:f,z:0},{x:l,y:k,z:q}],enabled:b.left.visible&&!b.top.visible},{fill:h.color(b.left.color).brighten(-.1).get(),vertexes:[{x:l,y:p,z:n},{x:l,y:k,z:n},{x:l,y:k,z:q},{x:l,y:p,z:q}],enabled:b.left.visible},{fill:h.color(b.left.color).brighten(-.1).get(),vertexes:[{x:d,y:f,z:c},{x:d,y:g,z:c},{x:d,y:g,z:0},{x:d,y:f,z:0}],enabled:b.left.visible},{fill:h.color(b.left.color).get(),vertexes:[{x:l,y:p,z:q},{x:l,y:k,z:q},{x:d,y:f,z:0},{x:d,y:g,z:0}],enabled:b.left.visible&&!b.front.visible},
{fill:h.color(b.left.color).get(),vertexes:[{x:l,y:k,z:n},{x:l,y:p,z:n},{x:d,y:g,z:c},{x:d,y:f,z:c}],enabled:b.left.visible&&!b.back.visible}]});this.frameShapes.right[r]({"class":"highcharts-3d-frame highcharts-3d-frame-right",zIndex:b.right.frontFacing?-1E3:1E3,faces:[{fill:h.color(b.right.color).brighten(.1).get(),vertexes:[{x:m,y:p,z:n},{x:e,y:g,z:c},{x:e,y:g,z:0},{x:m,y:p,z:q}],enabled:b.right.visible&&!b.bottom.visible},{fill:h.color(b.right.color).brighten(.1).get(),vertexes:[{x:m,y:k,z:q},
{x:e,y:f,z:0},{x:e,y:f,z:c},{x:m,y:k,z:n}],enabled:b.right.visible&&!b.top.visible},{fill:h.color(b.right.color).brighten(-.1).get(),vertexes:[{x:e,y:f,z:0},{x:e,y:g,z:0},{x:e,y:g,z:c},{x:e,y:f,z:c}],enabled:b.right.visible},{fill:h.color(b.right.color).brighten(-.1).get(),vertexes:[{x:m,y:p,z:q},{x:m,y:k,z:q},{x:m,y:k,z:n},{x:m,y:p,z:n}],enabled:b.right.visible},{fill:h.color(b.right.color).get(),vertexes:[{x:m,y:k,z:q},{x:m,y:p,z:q},{x:e,y:g,z:0},{x:e,y:f,z:0}],enabled:b.right.visible&&!b.front.visible},
{fill:h.color(b.right.color).get(),vertexes:[{x:m,y:p,z:n},{x:m,y:k,z:n},{x:e,y:f,z:c},{x:e,y:g,z:c}],enabled:b.right.visible&&!b.back.visible}]});this.frameShapes.back[r]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:b.back.frontFacing?-1E3:1E3,faces:[{fill:h.color(b.back.color).brighten(.1).get(),vertexes:[{x:m,y:p,z:n},{x:l,y:p,z:n},{x:d,y:g,z:c},{x:e,y:g,z:c}],enabled:b.back.visible&&!b.bottom.visible},{fill:h.color(b.back.color).brighten(.1).get(),vertexes:[{x:l,y:k,z:n},{x:m,
y:k,z:n},{x:e,y:f,z:c},{x:d,y:f,z:c}],enabled:b.back.visible&&!b.top.visible},{fill:h.color(b.back.color).brighten(-.1).get(),vertexes:[{x:l,y:p,z:n},{x:l,y:k,z:n},{x:d,y:f,z:c},{x:d,y:g,z:c}],enabled:b.back.visible&&!b.left.visible},{fill:h.color(b.back.color).brighten(-.1).get(),vertexes:[{x:m,y:k,z:n},{x:m,y:p,z:n},{x:e,y:g,z:c},{x:e,y:f,z:c}],enabled:b.back.visible&&!b.right.visible},{fill:h.color(b.back.color).get(),vertexes:[{x:d,y:f,z:c},{x:e,y:f,z:c},{x:e,y:g,z:c},{x:d,y:g,z:c}],enabled:b.back.visible},
{fill:h.color(b.back.color).get(),vertexes:[{x:l,y:p,z:n},{x:m,y:p,z:n},{x:m,y:k,z:n},{x:l,y:k,z:n}],enabled:b.back.visible}]});this.frameShapes.front[r]({"class":"highcharts-3d-frame highcharts-3d-frame-front",zIndex:b.front.frontFacing?-1E3:1E3,faces:[{fill:h.color(b.front.color).brighten(.1).get(),vertexes:[{x:l,y:p,z:q},{x:m,y:p,z:q},{x:e,y:g,z:0},{x:d,y:g,z:0}],enabled:b.front.visible&&!b.bottom.visible},{fill:h.color(b.front.color).brighten(.1).get(),vertexes:[{x:m,y:k,z:q},{x:l,y:k,z:q},{x:d,
y:f,z:0},{x:e,y:f,z:0}],enabled:b.front.visible&&!b.top.visible},{fill:h.color(b.front.color).brighten(-.1).get(),vertexes:[{x:l,y:k,z:q},{x:l,y:p,z:q},{x:d,y:g,z:0},{x:d,y:f,z:0}],enabled:b.front.visible&&!b.left.visible},{fill:h.color(b.front.color).brighten(-.1).get(),vertexes:[{x:m,y:p,z:q},{x:m,y:k,z:q},{x:e,y:f,z:0},{x:e,y:g,z:0}],enabled:b.front.visible&&!b.right.visible},{fill:h.color(b.front.color).get(),vertexes:[{x:e,y:f,z:0},{x:d,y:f,z:0},{x:d,y:g,z:0},{x:e,y:g,z:0}],enabled:b.front.visible},
{fill:h.color(b.front.color).get(),vertexes:[{x:m,y:p,z:q},{x:l,y:p,z:q},{x:l,y:k,z:q},{x:m,y:k,z:q}],enabled:b.front.visible}]})}}function r(){this.styledMode&&(this.renderer.definition({tagName:"style",textContent:".highcharts-3d-top{filter: url(#highcharts-brighter)}\n.highcharts-3d-side{filter: url(#highcharts-darker)}\n"}),[{name:"darker",slope:.6},{name:"brighter",slope:1.4}].forEach(function(a){this.renderer.definition({tagName:"filter",id:"highcharts-"+a.name,children:[{tagName:"feComponentTransfer",
children:[{tagName:"feFuncR",type:"linear",slope:a.slope},{tagName:"feFuncG",type:"linear",slope:a.slope},{tagName:"feFuncB",type:"linear",slope:a.slope}]}]})},this))}function q(){var a=this.options;this.is3d()&&(a.series||[]).forEach(function(b){"scatter"===(b.type||a.chart.type||a.chart.defaultSeriesType)&&(b.type="scatter3d")})}function t(){var a=this.options.chart.options3d;if(this.chart3d&&this.is3d()){a&&(a.alpha=a.alpha%360+(0<=a.alpha?0:360),a.beta=a.beta%360+(0<=a.beta?0:360));var b=this.inverted,
c=this.clipBox,d=this.margin;c[b?"y":"x"]=-(d[3]||0);c[b?"x":"y"]=-(d[0]||0);c[b?"height":"width"]=this.chartWidth+(d[3]||0)+(d[1]||0);c[b?"width":"height"]=this.chartHeight+(d[0]||0)+(d[2]||0);this.scale3d=1;!0===a.fitToPlot&&(this.scale3d=this.chart3d.getScale(a.depth));this.chart3d.frame3d=this.chart3d.get3dFrame()}}function u(){this.is3d()&&(this.isDirtyBox=!0)}function D(){this.chart3d&&this.is3d()&&(this.chart3d.frame3d=this.chart3d.get3dFrame())}function e(){this.chart3d||(this.chart3d=new E(this))}
function v(a){return this.is3d()||a.apply(this,[].slice.call(arguments,1))}function y(a){var b=this.series.length;if(this.is3d())for(;b--;)a=this.series[b],a.translate(),a.render();else a.call(this)}function n(a){a.apply(this,[].slice.call(arguments,1));this.is3d()&&(this.container.className+=" highcharts-3d-chart")}var E=function(){function b(a){this.frame3d=void 0;this.chart=a}b.prototype.get3dFrame=function(){var b=this.chart,c=b.options.chart.options3d,d=c.frame,e=b.plotLeft,g=b.plotLeft+b.plotWidth,
l=b.plotTop,h=b.plotTop+b.plotHeight,k=c.depth,p=function(a){a=f(a,b);return.5<a?1:-.5>a?-1:0},q=p([{x:e,y:h,z:k},{x:g,y:h,z:k},{x:g,y:h,z:0},{x:e,y:h,z:0}]),n=p([{x:e,y:l,z:0},{x:g,y:l,z:0},{x:g,y:l,z:k},{x:e,y:l,z:k}]),r=p([{x:e,y:l,z:0},{x:e,y:l,z:k},{x:e,y:h,z:k},{x:e,y:h,z:0}]),t=p([{x:g,y:l,z:k},{x:g,y:l,z:0},{x:g,y:h,z:0},{x:g,y:h,z:k}]),u=p([{x:e,y:h,z:0},{x:g,y:h,z:0},{x:g,y:l,z:0},{x:e,y:l,z:0}]);p=p([{x:e,y:l,z:k},{x:g,y:l,z:k},{x:g,y:h,z:k},{x:e,y:h,z:k}]);var x=!1,D=!1,v=!1,y=!1;[].concat(b.xAxis,
b.yAxis,b.zAxis).forEach(function(a){a&&(a.horiz?a.opposite?D=!0:x=!0:a.opposite?y=!0:v=!0)});var H=function(b,c,d){for(var e=["size","color","visible"],g={},f=0;f<e.length;f++)for(var l=e[f],h=0;h<b.length;h++)if("object"===typeof b[h]){var k=b[h][l];if("undefined"!==typeof k&&null!==k){g[l]=k;break}}b=d;!0===g.visible||!1===g.visible?b=g.visible:"auto"===g.visible&&(b=0<c);return{size:a(g.size,1),color:a(g.color,"none"),frontFacing:0<c,visible:b}};d={axes:{},bottom:H([d.bottom,d.top,d],q,x),top:H([d.top,
d.bottom,d],n,D),left:H([d.left,d.right,d.side,d],r,v),right:H([d.right,d.left,d.side,d],t,y),back:H([d.back,d.front,d],p,!0),front:H([d.front,d.back,d],u,!1)};"auto"===c.axisLabelPosition?(t=function(a,b){return a.visible!==b.visible||a.visible&&b.visible&&a.frontFacing!==b.frontFacing},c=[],t(d.left,d.front)&&c.push({y:(l+h)/2,x:e,z:0,xDir:{x:1,y:0,z:0}}),t(d.left,d.back)&&c.push({y:(l+h)/2,x:e,z:k,xDir:{x:0,y:0,z:-1}}),t(d.right,d.front)&&c.push({y:(l+h)/2,x:g,z:0,xDir:{x:0,y:0,z:1}}),t(d.right,
d.back)&&c.push({y:(l+h)/2,x:g,z:k,xDir:{x:-1,y:0,z:0}}),q=[],t(d.bottom,d.front)&&q.push({x:(e+g)/2,y:h,z:0,xDir:{x:1,y:0,z:0}}),t(d.bottom,d.back)&&q.push({x:(e+g)/2,y:h,z:k,xDir:{x:-1,y:0,z:0}}),n=[],t(d.top,d.front)&&n.push({x:(e+g)/2,y:l,z:0,xDir:{x:1,y:0,z:0}}),t(d.top,d.back)&&n.push({x:(e+g)/2,y:l,z:k,xDir:{x:-1,y:0,z:0}}),r=[],t(d.bottom,d.left)&&r.push({z:(0+k)/2,y:h,x:e,xDir:{x:0,y:0,z:-1}}),t(d.bottom,d.right)&&r.push({z:(0+k)/2,y:h,x:g,xDir:{x:0,y:0,z:1}}),h=[],t(d.top,d.left)&&h.push({z:(0+
k)/2,y:l,x:e,xDir:{x:0,y:0,z:-1}}),t(d.top,d.right)&&h.push({z:(0+k)/2,y:l,x:g,xDir:{x:0,y:0,z:1}}),e=function(a,c,d){if(0===a.length)return null;if(1===a.length)return a[0];for(var e=0,g=m(a,b,!1),f=1;f<g.length;f++)d*g[f][c]>d*g[e][c]?e=f:d*g[f][c]===d*g[e][c]&&g[f].z<g[e].z&&(e=f);return a[e]},d.axes={y:{left:e(c,"x",-1),right:e(c,"x",1)},x:{top:e(n,"y",-1),bottom:e(q,"y",1)},z:{top:e(h,"y",-1),bottom:e(r,"y",1)}}):d.axes={y:{left:{x:e,z:0,xDir:{x:1,y:0,z:0}},right:{x:g,z:0,xDir:{x:0,y:0,z:1}}},
x:{top:{y:l,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:h,z:0,xDir:{x:1,y:0,z:0}}},z:{top:{x:v?g:e,y:l,xDir:v?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:v?g:e,y:h,xDir:v?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return d};b.prototype.getScale=function(a){var b=this.chart,c=b.plotLeft,d=b.plotWidth+c,e=b.plotTop,g=b.plotHeight+e,f=c+b.plotWidth/2,l=e+b.plotHeight/2,h=Number.MAX_VALUE,k=-Number.MAX_VALUE,p=Number.MAX_VALUE,q=-Number.MAX_VALUE,n=1;var r=[{x:c,y:e,z:0},{x:c,y:e,z:a}];[0,1].forEach(function(a){r.push({x:d,y:r[a].y,
z:r[a].z})});[0,1,2,3].forEach(function(a){r.push({x:r[a].x,y:g,z:r[a].z})});r=m(r,b,!1);r.forEach(function(a){h=Math.min(h,a.x);k=Math.max(k,a.x);p=Math.min(p,a.y);q=Math.max(q,a.y)});c>h&&(n=Math.min(n,1-Math.abs((c+f)/(h+f))%1));d<k&&(n=Math.min(n,(d-f)/(k-f)));e>p&&(n=0>p?Math.min(n,(e+l)/(-p+e+l)):Math.min(n,1-(e+l)/(p+l)%1));g<q&&(n=Math.min(n,Math.abs((g-l)/(q-l))));return n};return b}();c.Composition=E;c.defaultOptions={chart:{options3d:{enabled:!1,alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,
axisLabelPosition:null,frame:{visible:"default",size:1,bottom:{},top:{},left:{},right:{},back:{},front:{}}}}};c.compose=function(a,f){var p=a.prototype;f=f.prototype;p.is3d=function(){return this.options.chart.options3d&&this.options.chart.options3d.enabled};p.propsRequireDirtyBox.push("chart.options3d");p.propsRequireUpdateSeries.push("chart.options3d");f.matrixSetter=function(){if(1>this.pos&&(I(this.start)||I(this.end))){var a=this.start||[1,0,0,1,0,0],b=this.end||[1,0,0,1,0,0];var c=[];for(var d=
0;6>d;d++)c.push(this.pos*b[d]+(1-this.pos)*a[d])}else c=this.end;this.elem.attr(this.prop,c,null,!0)};l(!0,b,c.defaultOptions);C(a,"init",e);C(a,"addSeries",d);C(a,"afterDrawChartBox",k);C(a,"afterGetContainer",r);C(a,"afterInit",q);C(a,"afterSetChartSize",t);C(a,"beforeRedraw",u);C(a,"beforeRender",D);g(h.Chart.prototype,"isInsidePlot",v);g(a,"renderSeries",y);g(a,"setClassName",n)}})(D||(D={}));D.compose(v,E);t.ZChartComposition.compose(v);u.compose(c);"";return D});J(c,"Core/Series/Series3D.js",
[c["Series/Line/LineSeries.js"],c["Extensions/Math3D.js"],c["Core/Utilities.js"]],function(c,u,v){var I=u.perspective;u=v.addEvent;var h=v.pick;u(c,"afterTranslate",function(){this.chart.is3d()&&this.translate3dPoints()});c.prototype.translate3dPoints=function(){var c=this.chart,k=h(this.zAxis,c.options.zAxis[0]),r=[],t;for(t=0;t<this.data.length;t++){var m=this.data[t];if(k&&k.translate){var f=k.logarithmic&&k.val2lin?k.val2lin(m.z):m.z;m.plotZ=k.translate(f);m.isInside=m.isInside?f>=k.min&&f<=k.max:
!1}else m.plotZ=0;m.axisXpos=m.plotX;m.axisYpos=m.plotY;m.axisZpos=m.plotZ;r.push({x:m.plotX,y:m.plotY,z:m.plotZ})}c=I(r,c,!0);for(t=0;t<this.data.length;t++)m=this.data[t],k=c[t],m.plotX=k.x,m.plotY=k.y,m.plotZ=k.z}});J(c,"Series/Column3DSeries.js",[c["Core/Series/Series.js"],c["Series/Column/ColumnSeries.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],c["Extensions/Math3D.js"],c["Extensions/Stacking.js"],c["Core/Utilities.js"]],function(c,u,v,E,h,y,k){function r(b,a){var c=b.series,f={},
d,l=1;c.forEach(function(b){d=I(b.options.stack,a?0:c.length-1-b.index);f[d]?f[d].series.push(b):(f[d]={series:[b],position:l},l++)});f.totalStacks=l+1;return f}function t(b){var a=b.apply(this,[].slice.call(arguments,1));this.chart.is3d&&this.chart.is3d()&&(a.stroke=this.options.edgeColor||a.fill,a["stroke-width"]=I(this.options.edgeWidth,1));return a}function m(b,a,c){var f=this.chart.is3d&&this.chart.is3d();f&&(this.options.inactiveOtherPoints=!0);b.call(this,a,c);f&&(this.options.inactiveOtherPoints=
!1)}function f(b){for(var a=[],c=1;c<arguments.length;c++)a[c-1]=arguments[c];return this.series.chart.is3d()?this.graphic&&"g"!==this.graphic.element.nodeName:b.apply(this,a)}u=u.prototype;var b=v.svg,C=h.perspective;v=k.addEvent;var I=k.pick;k=k.wrap;k(u,"translate",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.translate3dShapes()});k(E.prototype,"justifyDataLabel",function(b){return arguments[2].outside3dPlot?!1:b.apply(this,[].slice.call(arguments,1))});u.translate3dPoints=
function(){};u.translate3dShapes=function(){var b=this,a=b.chart,c=b.options,f=c.depth,d=(c.stacking?c.stack||0:b.index)*(f+(c.groupZPadding||1)),h=b.borderWidth%2?.5:0,k;a.inverted&&!b.yAxis.reversed&&(h*=-1);!1!==c.grouping&&(d=0);d+=c.groupZPadding||1;b.data.forEach(function(c){c.outside3dPlot=null;if(null!==c.y){var g=c.shapeArgs,l=c.tooltipPos,p;[["x","width"],["y","height"]].forEach(function(a){p=g[a[0]]-h;0>p&&(g[a[1]]+=g[a[0]]+h,g[a[0]]=-h,p=0);p+g[a[1]]>b[a[0]+"Axis"].len&&0!==g[a[1]]&&(g[a[1]]=
b[a[0]+"Axis"].len-g[a[0]]);if(0!==g[a[1]]&&(g[a[0]]>=b[a[0]+"Axis"].len||g[a[0]]+g[a[1]]<=h)){for(var d in g)g[d]=0;c.outside3dPlot=!0}});"rect"===c.shapeType&&(c.shapeType="cuboid");g.z=d;g.depth=f;g.insidePlotArea=!0;k={x:g.x+g.width/2,y:g.y,z:d+f/2};a.inverted&&(k.x=g.height,k.y=c.clientX);c.plot3d=C([k],a,!0,!1)[0];l=C([{x:l[0],y:l[1],z:d+f/2}],a,!0,!1)[0];c.tooltipPos=[l.x,l.y]}});b.z=d};k(u,"animate",function(c){if(this.chart.is3d()){var a=arguments[1],f=this.yAxis,h=this,d=this.yAxis.reversed;
b&&(a?h.data.forEach(function(a){null!==a.y&&(a.height=a.shapeArgs.height,a.shapey=a.shapeArgs.y,a.shapeArgs.height=1,d||(a.shapeArgs.y=a.stackY?a.plotY+f.translate(a.stackY):a.plotY+(a.negative?-a.height:a.height)))}):(h.data.forEach(function(a){null!==a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic&&a.graphic.animate(a.shapeArgs,h.options.animation))}),this.drawDataLabels()))}else c.apply(this,[].slice.call(arguments,1))});k(u,"plotGroup",function(b,a,c,f,d,h){"dataLabelsGroup"!==
a&&this.chart.is3d()&&(this[a]&&delete this[a],h&&(this.chart.columnGroup||(this.chart.columnGroup=this.chart.renderer.g("columnGroup").add(h)),this[a]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),this[a].survive=!0,"group"===a||"markerGroup"===a))&&(arguments[3]="visible");return b.apply(this,Array.prototype.slice.call(arguments,1))});k(u,"setVisible",function(b,a){var c=this,f;c.chart.is3d()&&c.data.forEach(function(b){f=(b.visible=b.options.visible=a="undefined"===typeof a?
!I(c.visible,b.visible):a)?"visible":"hidden";c.options.data[c.data.indexOf(b)]=b.options;b.graphic&&b.graphic.attr({visibility:f})});b.apply(this,Array.prototype.slice.call(arguments,1))});u.handle3dGrouping=!0;v(E,"afterInit",function(){if(this.chart.is3d()&&this.handle3dGrouping){var b=this.options,a=b.grouping,c=b.stacking,f=I(this.yAxis.options.reversedStacks,!0),d=0;if("undefined"===typeof a||a){a=r(this.chart,c);d=b.stack||0;for(c=0;c<a[d].series.length&&a[d].series[c]!==this;c++);d=10*(a.totalStacks-
a[d].position)+(f?c:-c);this.xAxis.reversed||(d=10*a.totalStacks-d)}b.depth=b.depth||25;this.z=this.z||0;b.zIndex=d}});k(u,"pointAttribs",t);k(u,"setState",m);k(u.pointClass.prototype,"hasNewShapeType",f);c.seriesTypes.columnRange&&(v=c.seriesTypes.columnrange.prototype,k(v,"pointAttribs",t),k(v,"setState",m),k(v.pointClass.prototype,"hasNewShapeType",f),v.plotGroup=u.plotGroup,v.setVisible=u.setVisible);k(E.prototype,"alignDataLabel",function(b,a,c,f,d){var g=this.chart;f.outside3dPlot=a.outside3dPlot;
if(g.is3d()&&this.is("column")){var h=this.options,k=I(f.inside,!!this.options.stacking),l=g.options.chart.options3d,m=a.pointWidth/2||0;h={x:d.x+m,y:d.y,z:this.z+h.depth/2};g.inverted&&(k&&(d.width=0,h.x+=a.shapeArgs.height/2),90<=l.alpha&&270>=l.alpha&&(h.y+=a.shapeArgs.width));h=C([h],g,!0,!1)[0];d.x=h.x-m;d.y=a.outside3dPlot?-9E9:h.y}b.apply(this,[].slice.call(arguments,1))});k(y.prototype,"getStackBox",function(b,a,f,h,d,k,m,r){var g=b.apply(this,[].slice.call(arguments,1));if(a.is3d()&&f.base){var l=
+f.base.split(",")[0],p=a.series[l];l=a.options.chart.options3d;p&&p instanceof c.seriesTypes.column&&(p={x:g.x+(a.inverted?m:k/2),y:g.y,z:p.options.depth/2},a.inverted&&(g.width=0,90<=l.alpha&&270>=l.alpha&&(p.y+=k)),p=C([p],a,!0,!1)[0],g.x=p.x-k/2,g.y=p.y)}return g})});J(c,"Series/Pie3DSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,u,v){c=c.seriesTypes;var E=u.deg2rad,h=u.svg,y=v.pick;u=v.wrap;u(c.pie.prototype,"translate",function(c){c.apply(this,
[].slice.call(arguments,1));if(this.chart.is3d()){var h=this,k=h.options,m=k.depth||0,f=h.chart.options.chart.options3d,b=f.alpha,u=f.beta,v=k.stacking?(k.stack||0)*m:h._i*m;v+=m/2;!1!==k.grouping&&(v=0);h.data.forEach(function(c){var a=c.shapeArgs;c.shapeType="arc3d";a.z=v;a.depth=.75*m;a.alpha=b;a.beta=u;a.center=h.center;a=(a.end+a.start)/2;c.slicedTranslation={translateX:Math.round(Math.cos(a)*k.slicedOffset*Math.cos(b*E)),translateY:Math.round(Math.sin(a)*k.slicedOffset*Math.cos(b*E))}})}});
u(c.pie.prototype.pointClass.prototype,"haloPath",function(c){var h=arguments;return this.series.chart.is3d()?[]:c.call(this,h[1])});u(c.pie.prototype,"pointAttribs",function(c,h,t){c=c.call(this,h,t);t=this.options;this.chart.is3d()&&!this.chart.styledMode&&(c.stroke=t.edgeColor||h.color||this.color,c["stroke-width"]=y(t.edgeWidth,1));return c});u(c.pie.prototype,"drawDataLabels",function(c){if(this.chart.is3d()){var h=this.chart.options.chart.options3d;this.data.forEach(function(c){var k=c.shapeArgs,
f=k.r,b=(k.start+k.end)/2;c=c.labelPosition;var r=c.connectorPosition,t=-f*(1-Math.cos((k.alpha||h.alpha)*E))*Math.sin(b),l=f*(Math.cos((k.beta||h.beta)*E)-1)*Math.cos(b);[c.natural,r.breakAt,r.touchingSliceAt].forEach(function(a){a.x+=l;a.y+=t})})}c.apply(this,[].slice.call(arguments,1))});u(c.pie.prototype,"addPoint",function(c){c.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.update(this.userOptions,!0)});u(c.pie.prototype,"animate",function(c){if(this.chart.is3d()){var k=arguments[1],
t=this.options.animation,m=this.center,f=this.group,b=this.markerGroup;h&&(!0===t&&(t={}),k?(f.oldtranslateX=y(f.oldtranslateX,f.translateX),f.oldtranslateY=y(f.oldtranslateY,f.translateY),k={translateX:m[0],translateY:m[1],scaleX:.001,scaleY:.001},f.attr(k),b&&(b.attrSetters=f.attrSetters,b.attr(k))):(k={translateX:f.oldtranslateX,translateY:f.oldtranslateY,scaleX:1,scaleY:1},f.animate(k,t),b&&b.animate(k,t)))}else c.apply(this,[].slice.call(arguments,1))})});J(c,"Series/Scatter3DSeries.js",[c["Core/Series/Series.js"],
c["Extensions/Math3D.js"],c["Core/Series/Point.js"]],function(c,u,v){var E=c.seriesTypes,h=u.pointCameraDistance;c.seriesType("scatter3d","scatter",{tooltip:{pointFormat:"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>"}},{pointAttribs:function(c){var k=E.scatter.prototype.pointAttribs.apply(this,arguments);this.chart.is3d()&&c&&(k.zIndex=h(c,this.chart));return k},axisTypes:["xAxis","yAxis","zAxis"],pointArrayMap:["x","y","z"],parallelArrays:["x","y","z"],directTouch:!0},
{applyOptions:function(){v.prototype.applyOptions.apply(this,arguments);"undefined"===typeof this.z&&(this.z=0);return this}});""});J(c,"masters/highcharts-3d.src.js",[],function(){})});
//# sourceMappingURL=highcharts-3d.js.map