/*
 Highcharts JS v8.2.2 (2020-11-05)

 (c) 2009-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(E){c(E);c.Highcharts=E;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function E(c,a,k,b){c.hasOwnProperty(a)||(c[a]=b.apply(null,k))}c=c?c._modules:{};E(c,"Extensions/Pane.js",[c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Pointer.js"],c["Core/Utilities.js"],c["Mixins/CenteredSeries.js"]],
function(c,a,k,b,g){function n(d,a,b){return Math.sqrt(Math.pow(d-b[0],2)+Math.pow(a-b[1],2))<=b[2]/2}var p=b.addEvent,z=b.extend,C=b.merge,D=b.pick,d=b.splat;c.prototype.collectionsWithUpdate.push("pane");b=function(){function a(d,a){this.options=this.chart=this.center=this.background=void 0;this.coll="pane";this.defaultOptions={center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0};this.defaultBackgroundOptions={shape:"circle",borderWidth:1,borderColor:"#cccccc",backgroundColor:{linearGradient:{x1:0,
y1:0,x2:0,y2:1},stops:[[0,"#ffffff"],[1,"#e6e6e6"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"};this.init(d,a)}a.prototype.init=function(d,a){this.chart=a;this.background=[];a.pane.push(this);this.setOptions(d)};a.prototype.setOptions=function(d){this.options=C(this.defaultOptions,this.chart.angular?{background:{}}:void 0,d)};a.prototype.render=function(){var a=this.options,b=this.options.background,g=this.chart.renderer;this.group||(this.group=g.g("pane-group").attr({zIndex:a.zIndex||
0}).add());this.updateCenter();if(b)for(b=d(b),a=Math.max(b.length,this.background.length||0),g=0;g<a;g++)b[g]&&this.axis?this.renderBackground(C(this.defaultBackgroundOptions,b[g]),g):this.background[g]&&(this.background[g]=this.background[g].destroy(),this.background.splice(g,1))};a.prototype.renderBackground=function(d,a){var b="animate",g={"class":"highcharts-pane "+(d.className||"")};this.chart.styledMode||z(g,{fill:d.backgroundColor,stroke:d.borderColor,"stroke-width":d.borderWidth});this.background[a]||
(this.background[a]=this.chart.renderer.path().add(this.group),b="attr");this.background[a][b]({d:this.axis.getPlotBandPath(d.from,d.to,d)}).attr(g)};a.prototype.updateCenter=function(d){this.center=(d||this.axis||{}).center=g.getCenter.call(this)};a.prototype.update=function(d,a){C(!0,this.options,d);C(!0,this.chart.options.pane,d);this.setOptions(this.options);this.render();this.chart.axes.forEach(function(d){d.pane===this&&(d.pane=null,d.update({},a))},this)};return a}();c.prototype.getHoverPane=
function(d){var a=this,b;d&&a.pane.forEach(function(g){var u=d.chartX-a.plotLeft,v=d.chartY-a.plotTop;n(a.inverted?v:u,a.inverted?u:v,g.center)&&(b=g)});return b};p(c,"afterIsInsidePlot",function(d){this.polar&&(d.isInsidePlot=this.pane.some(function(a){return n(d.x,d.y,a.center)}))});p(k,"beforeGetHoverData",function(d){var a=this.chart;a.polar&&(a.hoverPane=a.getHoverPane(d),d.filter=function(b){return b.visible&&!(!d.shared&&b.directTouch)&&D(b.options.enableMouseTracking,!0)&&(!a.hoverPane||b.xAxis.pane===
a.hoverPane)})});p(k,"afterGetHoverData",function(d){var a=this.chart;d.hoverPoint&&d.hoverPoint.plotX&&d.hoverPoint.plotY&&a.hoverPane&&!n(d.hoverPoint.plotX,d.hoverPoint.plotY,a.hoverPane.center)&&(d.hoverPoint=void 0)});a.Pane=b;return a.Pane});E(c,"Core/Axis/HiddenAxis.js",[],function(){return function(){function c(){}c.init=function(a){a.getOffset=function(){};a.redraw=function(){this.isDirty=!1};a.render=function(){this.isDirty=!1};a.createLabelCollector=function(){return function(){}};a.setScale=
function(){};a.setCategories=function(){};a.setTitle=function(){};a.isHidden=!0};return c}()});E(c,"Core/Axis/RadialAxis.js",[c["Core/Axis/Axis.js"],c["Core/Axis/Tick.js"],c["Core/Axis/HiddenAxis.js"],c["Core/Utilities.js"]],function(c,a,k,b){var g=b.addEvent,n=b.correctFloat,p=b.defined,z=b.extend,C=b.fireEvent,D=b.merge,d=b.pick,u=b.relativeLength,w=b.wrap;b=function(){function a(){}a.init=function(a){var b=c.prototype;a.setOptions=function(d){d=this.options=D(a.constructor.defaultOptions,this.defaultPolarOptions,
d);d.plotBands||(d.plotBands=[]);C(this,"afterSetOptions")};a.getOffset=function(){b.getOffset.call(this);this.chart.axisOffset[this.side]=0};a.getLinePath=function(v,h,q){v=this.pane.center;var e=this.chart,f=d(h,v[2]/2-this.offset);"undefined"===typeof q&&(q=this.horiz?0:this.center&&-this.center[3]/2);q&&(f+=q);this.isCircular||"undefined"!==typeof h?(h=this.chart.renderer.symbols.arc(this.left+v[0],this.top+v[1],f,f,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}),h.xBounds=[this.left+
v[0]],h.yBounds=[this.top+v[1]-f]):(h=this.postTranslate(this.angleRad,f),h=[["M",this.center[0]+e.plotLeft,this.center[1]+e.plotTop],["L",h.x,h.y]]);return h};a.setAxisTranslation=function(){b.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):(this.center[2]-this.center[3])/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)};a.beforeSetTickPositions=function(){this.autoConnect=
this.isCircular&&"undefined"===typeof d(this.userMax,this.options.max)&&n(this.endAngleRad-this.startAngleRad)===n(2*Math.PI);!this.isCircular&&this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)};a.setAxisSize=function(){b.setAxisSize.call(this);if(this.isRadial){this.pane.updateCenter(this);var v=this.center=z([],this.pane.center);if(this.isCircular)this.sector=this.endAngleRad-this.startAngleRad;else{var h=this.postTranslate(this.angleRad,
v[3]/2);v[0]=h.x-this.chart.plotLeft;v[1]=h.y-this.chart.plotTop}this.len=this.width=this.height=(v[2]-v[3])*d(this.sector,1)/2}};a.getPosition=function(v,h){v=this.translate(v);return this.postTranslate(this.isCircular?v:this.angleRad,d(this.isCircular?h:0>v?0:v,this.center[2]/2)-this.offset)};a.postTranslate=function(d,h){var q=this.chart,e=this.center;d=this.startAngleRad+d;return{x:q.plotLeft+e[0]+Math.cos(d)*h,y:q.plotTop+e[1]+Math.sin(d)*h}};a.getPlotBandPath=function(v,h,q){var e=function(e){if("string"===
typeof e){var f=parseInt(e,10);l.test(e)&&(f=f*t/100);return f}return e},f=this.center,r=this.startAngleRad,t=f[2]/2,m=Math.min(this.offset,0),l=/%$/;var x=this.isCircular;var a=d(e(q.outerRadius),t),b=e(q.innerRadius);e=d(e(q.thickness),10);if("polygon"===this.options.gridLineInterpolation)m=this.getPlotLinePath({value:v}).concat(this.getPlotLinePath({value:h,reverse:!0}));else{v=Math.max(v,this.min);h=Math.min(h,this.max);v=this.translate(v);h=this.translate(h);x||(a=v||0,b=h||0);if("circle"!==
q.shape&&x)q=r+(v||0),r+=h||0;else{q=-Math.PI/2;r=1.5*Math.PI;var g=!0}a-=m;m=this.chart.renderer.symbols.arc(this.left+f[0],this.top+f[1],a,a,{start:Math.min(q,r),end:Math.max(q,r),innerR:d(b,a-(e-m)),open:g});x&&(x=(r+q)/2,g=this.left+f[0]+f[2]/2*Math.cos(x),m.xBounds=x>-Math.PI/2&&x<Math.PI/2?[g,this.chart.plotWidth]:[0,g],m.yBounds=[this.top+f[1]+f[2]/2*Math.sin(x)],m.yBounds[0]+=x>-Math.PI&&0>x||x>Math.PI?-10:10)}return m};a.getCrosshairPosition=function(d,h,q){var e=d.value,f=this.pane.center;
if(this.isCircular){if(p(e))d.point&&(r=d.point.shapeArgs||{},r.start&&(e=this.chart.inverted?this.translate(d.point.rectPlotY,!0):d.point.x));else{var r=d.chartX||0;var t=d.chartY||0;e=this.translate(Math.atan2(t-q,r-h)-this.startAngleRad,!0)}d=this.getPosition(e);r=d.x;t=d.y}else p(e)||(r=d.chartX,t=d.chartY),p(r)&&p(t)&&(q=f[1]+this.chart.plotTop,e=this.translate(Math.min(Math.sqrt(Math.pow(r-h,2)+Math.pow(t-q,2)),f[2]/2)-f[3]/2,!0));return[e,r||0,t||0]};a.getPlotLinePath=function(d){var h=this,
q=h.pane.center,e=h.chart,f=e.inverted,r=d.value,t=d.reverse,m=h.getPosition(r),l=h.pane.options.background?h.pane.options.background[0]||h.pane.options.background:{},a=l.innerRadius||"0%",v=l.outerRadius||"100%";l=q[0]+e.plotLeft;var b=q[1]+e.plotTop,g=m.x,k=m.y,c=h.height;m=q[3]/2;var n;d.isCrosshair&&(k=this.getCrosshairPosition(d,l,b),r=k[0],g=k[1],k=k[2]);if(h.isCircular)r=Math.sqrt(Math.pow(g-l,2)+Math.pow(k-b,2)),t="string"===typeof a?u(a,1):a/r,e="string"===typeof v?u(v,1):v/r,q&&m&&(r=m/
r,t<r&&(t=r),e<r&&(e=r)),q=[["M",l+t*(g-l),b-t*(b-k)],["L",g-(1-e)*(g-l),k+(1-e)*(b-k)]];else if((r=h.translate(r))&&(0>r||r>c)&&(r=0),"circle"===h.options.gridLineInterpolation)q=h.getLinePath(0,r,m);else if(q=[],e[f?"yAxis":"xAxis"].forEach(function(e){e.pane===h.pane&&(n=e)}),n)for(l=n.tickPositions,n.autoConnect&&(l=l.concat([l[0]])),t&&(l=l.slice().reverse()),r&&(r+=m),g=0;g<l.length;g++)b=n.getPosition(l[g],r),q.push(g?["L",b.x,b.y]:["M",b.x,b.y]);return q};a.getTitlePosition=function(){var d=
this.center,h=this.chart,q=this.options.title;return{x:h.plotLeft+d[0]+(q.x||0),y:h.plotTop+d[1]-{high:.5,middle:.25,low:0}[q.align]*d[2]+(q.y||0)}};a.createLabelCollector=function(){var d=this;return function(){if(d.isRadial&&d.tickPositions&&!0!==d.options.labels.allowOverlap)return d.tickPositions.map(function(h){return d.ticks[h]&&d.ticks[h].label}).filter(function(h){return!!h})}}};a.compose=function(b,c){g(b,"init",function(d){var h=this.chart,q=h.inverted,e=h.angular,f=h.polar,r=this.isXAxis,
t=this.coll,m=e&&r,l,x=h.options;d=d.userOptions.pane||0;d=this.pane=h.pane&&h.pane[d];if("colorAxis"===t)this.isRadial=!1;else{if(e){if(m?k.init(this):a.init(this),l=!r)this.defaultPolarOptions=a.defaultRadialGaugeOptions}else f&&(a.init(this),this.defaultPolarOptions=(l=this.horiz)?a.defaultCircularOptions:D("xAxis"===t?b.defaultOptions:b.defaultYAxisOptions,a.defaultRadialOptions),q&&"yAxis"===t&&(this.defaultPolarOptions.stackLabels=b.defaultYAxisOptions.stackLabels));e||f?(this.isRadial=!0,x.chart.zoomType=
null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&h.labelCollectors.push(this.labelCollector)):this.isRadial=!1;d&&l&&(d.axis=this);this.isCircular=l}});g(b,"afterInit",function(){var a=this.chart,h=this.options,q=this.pane,e=q&&q.options;a.angular&&this.isXAxis||!q||!a.angular&&!a.polar||(this.angleRad=(h.angle||0)*Math.PI/180,this.startAngleRad=(e.startAngle-90)*Math.PI/180,this.endAngleRad=(d(e.endAngle,e.startAngle+360)-90)*Math.PI/180,this.offset=
h.offset||0)});g(b,"autoLabelAlign",function(d){this.isRadial&&(d.align=void 0,d.preventDefault())});g(b,"destroy",function(){if(this.chart&&this.chart.labelCollectors){var d=this.labelCollector?this.chart.labelCollectors.indexOf(this.labelCollector):-1;0<=d&&this.chart.labelCollectors.splice(d,1)}});g(b,"initialAxisTranslation",function(){this.isRadial&&this.beforeSetTickPositions()});g(c,"afterGetPosition",function(d){this.axis.getPosition&&z(d.pos,this.axis.getPosition(this.pos))});g(c,"afterGetLabelPosition",
function(a){var h=this.axis,q=this.label;if(q){var e=q.getBBox(),f=h.options.labels,r=f.y,t=20,m=f.align,l=(h.translate(this.pos)+h.startAngleRad+Math.PI/2)/Math.PI*180%360,x=Math.round(l),b="end",v=0>x?x+360:x,g=v,k=0,c=0,n=null===f.y?.3*-e.height:0;if(h.isRadial){var p=h.getPosition(this.pos,h.center[2]/2+u(d(f.distance,-25),h.center[2]/2,-h.center[2]/2));"auto"===f.rotation?q.attr({rotation:l}):null===r&&(r=h.chart.renderer.fontMetrics(q.styles&&q.styles.fontSize).b-e.height/2);null===m&&(h.isCircular?
(e.width>h.len*h.tickInterval/(h.max-h.min)&&(t=0),m=l>t&&l<180-t?"left":l>180+t&&l<360-t?"right":"center"):m="center",q.attr({align:m}));if("auto"===m&&2===h.tickPositions.length&&h.isCircular){90<v&&180>v?v=180-v:270<v&&360>=v&&(v=540-v);180<g&&360>=g&&(g=360-g);if(h.pane.options.startAngle===x||h.pane.options.startAngle===x+360||h.pane.options.startAngle===x-360)b="start";m=-90<=x&&90>=x||-360<=x&&-270>=x||270<=x&&360>=x?"start"===b?"right":"left":"start"===b?"left":"right";70<g&&110>g&&(m="center");
15>v||180<=v&&195>v?k=.3*e.height:15<=v&&35>=v?k="start"===b?0:.75*e.height:195<=v&&215>=v?k="start"===b?.75*e.height:0:35<v&&90>=v?k="start"===b?.25*-e.height:e.height:215<v&&270>=v&&(k="start"===b?e.height:.25*-e.height);15>g?c="start"===b?.15*-e.height:.15*e.height:165<g&&180>=g&&(c="start"===b?.15*e.height:.15*-e.height);q.attr({align:m});q.translate(c,k+n)}a.pos.x=p.x+f.x;a.pos.y=p.y+r}}});w(c.prototype,"getMarkPath",function(d,h,q,e,f,r,t){var m=this.axis;m.isRadial?(d=m.getPosition(this.pos,
m.center[2]/2+e),h=["M",h,q,"L",d.x,d.y]):h=d.call(this,h,q,e,f,r,t);return h})};a.defaultCircularOptions={gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0};a.defaultRadialGaugeOptions={labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2};
a.defaultRadialOptions={gridLineInterpolation:"circle",gridLineWidth:1,labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}};return a}();b.compose(c,a);return b});E(c,"Series/AreaRangeSeries.js",[c["Core/Series/Series.js"],c["Series/Column/ColumnSeries.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,a,k,b,g,n){var p=a.prototype,z=b.prototype,C=g.prototype,D=n.defined,d=n.extend,u=n.isArray,w=n.isNumber,
A=n.pick,y=c.seriesTypes.area.prototype;c.seriesType("arearange","area",{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:void 0,verticalAlign:void 0,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,toYData:function(d){return[d.low,d.high]},highToXY:function(d){var a=this.chart,h=this.xAxis.postTranslate(d.rectPlotX,
this.yAxis.len-d.plotHigh);d.plotHighX=h.x-a.plotLeft;d.plotHigh=h.y-a.plotTop;d.plotLowX=d.plotX},translate:function(){var d=this,a=d.yAxis,h=!!d.modifyValue;y.translate.apply(d);d.points.forEach(function(q){var e=q.high,f=q.plotY;q.isNull?q.plotY=null:(q.plotLow=f,q.plotHigh=a.translate(h?d.modifyValue(e,q):e,0,1,0,1),h&&(q.yBottom=q.plotHigh))});this.chart.polar&&this.points.forEach(function(h){d.highToXY(h);h.tooltipPos=[(h.plotHighX+h.plotLowX)/2,(h.plotHigh+h.plotLow)/2]})},getGraphPath:function(d){var a=
[],h=[],q,e=y.getGraphPath;var f=this.options;var r=this.chart.polar,t=r&&!1!==f.connectEnds,m=f.connectNulls,l=f.step;d=d||this.points;for(q=d.length;q--;){var x=d[q];var b=r?{plotX:x.rectPlotX,plotY:x.yBottom,doCurve:!1}:{plotX:x.plotX,plotY:x.plotY,doCurve:!1};x.isNull||t||m||d[q+1]&&!d[q+1].isNull||h.push(b);var g={polarPlotY:x.polarPlotY,rectPlotX:x.rectPlotX,yBottom:x.yBottom,plotX:A(x.plotHighX,x.plotX),plotY:x.plotHigh,isNull:x.isNull};h.push(g);a.push(g);x.isNull||t||m||d[q-1]&&!d[q-1].isNull||
h.push(b)}d=e.call(this,d);l&&(!0===l&&(l="left"),f.step={left:"right",center:"center",right:"left"}[l]);a=e.call(this,a);h=e.call(this,h);f.step=l;f=[].concat(d,a);!this.chart.polar&&h[0]&&"M"===h[0][0]&&(h[0]=["L",h[0][1],h[0][2]]);this.graphPath=f;this.areaPath=d.concat(h);f.isArea=!0;f.xMap=d.xMap;this.areaPath.xMap=d.xMap;return f},drawDataLabels:function(){var a=this.points,b=a.length,h,q=[],e=this.options.dataLabels,f,r=this.chart.inverted;if(u(e)){var t=e[0]||{enabled:!1};var m=e[1]||{enabled:!1}}else t=
d({},e),t.x=e.xHigh,t.y=e.yHigh,m=d({},e),m.x=e.xLow,m.y=e.yLow;if(t.enabled||this._hasPointLabels){for(h=b;h--;)if(f=a[h]){var l=t.inside?f.plotHigh<f.plotLow:f.plotHigh>f.plotLow;f.y=f.high;f._plotY=f.plotY;f.plotY=f.plotHigh;q[h]=f.dataLabel;f.dataLabel=f.dataLabelUpper;f.below=l;r?t.align||(t.align=l?"right":"left"):t.verticalAlign||(t.verticalAlign=l?"top":"bottom")}this.options.dataLabels=t;z.drawDataLabels&&z.drawDataLabels.apply(this,arguments);for(h=b;h--;)if(f=a[h])f.dataLabelUpper=f.dataLabel,
f.dataLabel=q[h],delete f.dataLabels,f.y=f.low,f.plotY=f._plotY}if(m.enabled||this._hasPointLabels){for(h=b;h--;)if(f=a[h])l=m.inside?f.plotHigh<f.plotLow:f.plotHigh>f.plotLow,f.below=!l,r?m.align||(m.align=l?"left":"right"):m.verticalAlign||(m.verticalAlign=l?"bottom":"top");this.options.dataLabels=m;z.drawDataLabels&&z.drawDataLabels.apply(this,arguments)}if(t.enabled)for(h=b;h--;)if(f=a[h])f.dataLabels=[f.dataLabelUpper,f.dataLabel].filter(function(e){return!!e});this.options.dataLabels=e},alignDataLabel:function(){p.alignDataLabel.apply(this,
arguments)},drawPoints:function(){var a=this.points.length,b;z.drawPoints.apply(this,arguments);for(b=0;b<a;){var h=this.points[b];h.origProps={plotY:h.plotY,plotX:h.plotX,isInside:h.isInside,negative:h.negative,zone:h.zone,y:h.y};h.lowerGraphic=h.graphic;h.graphic=h.upperGraphic;h.plotY=h.plotHigh;D(h.plotHighX)&&(h.plotX=h.plotHighX);h.y=h.high;h.negative=h.high<(this.options.threshold||0);h.zone=this.zones.length&&h.getZone();this.chart.polar||(h.isInside=h.isTopInside="undefined"!==typeof h.plotY&&
0<=h.plotY&&h.plotY<=this.yAxis.len&&0<=h.plotX&&h.plotX<=this.xAxis.len);b++}z.drawPoints.apply(this,arguments);for(b=0;b<a;)h=this.points[b],h.upperGraphic=h.graphic,h.graphic=h.lowerGraphic,d(h,h.origProps),delete h.origProps,b++},setStackedPoints:k.noop},{setState:function(){var d=this.state,a=this.series,h=a.chart.polar;D(this.plotHigh)||(this.plotHigh=a.yAxis.toPixels(this.high,!0));D(this.plotLow)||(this.plotLow=this.plotY=a.yAxis.toPixels(this.low,!0));a.stateMarkerGraphic&&(a.lowerStateMarkerGraphic=
a.stateMarkerGraphic,a.stateMarkerGraphic=a.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;h&&(this.plotX=this.plotHighX);C.setState.apply(this,arguments);this.state=d;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;h&&(this.plotX=this.plotLowX);a.stateMarkerGraphic&&(a.upperStateMarkerGraphic=a.stateMarkerGraphic,a.stateMarkerGraphic=a.lowerStateMarkerGraphic,a.lowerStateMarkerGraphic=void 0);C.setState.apply(this,arguments)},haloPath:function(){var d=this.series.chart.polar,
a=[];this.plotY=this.plotLow;d&&(this.plotX=this.plotLowX);this.isInside&&(a=C.haloPath.apply(this,arguments));this.plotY=this.plotHigh;d&&(this.plotX=this.plotHighX);this.isTopInside&&(a=a.concat(C.haloPath.apply(this,arguments)));return a},destroyElements:function(){["lowerGraphic","upperGraphic"].forEach(function(d){this[d]&&(this[d]=this[d].destroy())},this);this.graphic=null;return C.destroyElements.apply(this,arguments)},isValid:function(){return w(this.low)&&w(this.high)}});""});E(c,"Series/AreaSplineRangeSeries.js",
[c["Core/Series/Series.js"]],function(c){c.seriesType("areasplinerange","arearange",null,{getPointSpline:c.seriesTypes.spline.prototype.getPointSpline});""});E(c,"Series/ColumnRangeSeries.js",[c["Core/Series/Series.js"],c["Series/Column/ColumnSeries.js"],c["Core/Globals.js"],c["Core/Options.js"],c["Core/Utilities.js"]],function(c,a,k,b,g){var n=a.prototype;a=k.noop;b=b.defaultOptions;var p=g.clamp,z=g.merge,C=g.pick,D=c.seriesTypes.arearange.prototype;c.seriesType("columnrange","arearange",z(b.plotOptions.column,
b.plotOptions.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{setOptions:function(){z(!0,arguments[0],{stacking:void 0});return D.setOptions.apply(this,arguments)},translate:function(){var d=this,a=d.yAxis,b=d.xAxis,g=b.startAngleRad,k,c=d.chart,v=d.xAxis.isRadial,h=Math.max(c.chartWidth,c.chartHeight)+999,q;n.translate.apply(d);d.points.forEach(function(e){var f=e.shapeArgs,r=d.options.minPointLength;e.plotHigh=q=p(a.translate(e.high,0,1,0,1),-h,h);e.plotLow=p(e.plotY,-h,h);var t=
q;var m=C(e.rectPlotY,e.plotY)-q;Math.abs(m)<r?(r-=m,m+=r,t-=r/2):0>m&&(m*=-1,t-=m);v?(k=e.barX+g,e.shapeType="arc",e.shapeArgs=d.polarArc(t+m,t,k,k+e.pointWidth)):(f.height=m,f.y=t,e.tooltipPos=c.inverted?[a.len+a.pos-c.plotLeft-t-m/2,b.len+b.pos-c.plotTop-f.x-f.width/2,m]:[b.left-c.plotLeft+f.x+f.width/2,a.pos-c.plotTop+t+m/2,m])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:a,getSymbol:a,crispCol:function(){return n.crispCol.apply(this,arguments)},drawPoints:function(){return n.drawPoints.apply(this,
arguments)},drawTracker:function(){return n.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return n.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return n.pointAttribs.apply(this,arguments)},adjustForMissingColumns:function(){return n.adjustForMissingColumns.apply(this,arguments)},animate:function(){return n.animate.apply(this,arguments)},polarArc:function(){return n.polarArc.apply(this,arguments)},translate3dPoints:function(){return n.translate3dPoints.apply(this,
arguments)},translate3dShapes:function(){return n.translate3dShapes.apply(this,arguments)}},{setState:n.pointClass.prototype.setState});""});E(c,"Series/ColumnPyramidSeries.js",[c["Core/Series/Series.js"],c["Series/Column/ColumnSeries.js"],c["Core/Utilities.js"]],function(c,a,k){var b=a.prototype,g=k.clamp,n=k.pick;c.seriesType("columnpyramid","column",{},{translate:function(){var a=this,c=a.chart,k=a.options,D=a.dense=2>a.closestPointRange*a.xAxis.transA;D=a.borderWidth=n(k.borderWidth,D?0:1);var d=
a.yAxis,u=k.threshold,w=a.translatedThreshold=d.getThreshold(u),A=n(k.minPointLength,5),y=a.getColumnMetrics(),B=y.width,v=a.barW=Math.max(B,1+2*D),h=a.pointXOffset=y.offset;c.inverted&&(w-=.5);k.pointPadding&&(v=Math.ceil(v));b.translate.apply(a);a.points.forEach(function(q){var e=n(q.yBottom,w),f=999+Math.abs(e),r=g(q.plotY,-f,d.len+f);f=q.plotX+h;var t=v/2,m=Math.min(r,e);e=Math.max(r,e)-m;var l;q.barX=f;q.pointWidth=B;q.tooltipPos=c.inverted?[d.len+d.pos-c.plotLeft-r,a.xAxis.len-f-t,e]:[f+t,r+
d.pos-c.plotTop,e];r=u+(q.total||q.y);"percent"===k.stacking&&(r=u+(0>q.y)?-100:100);r=d.toPixels(r,!0);var b=(l=c.plotHeight-r-(c.plotHeight-w))?t*(m-r)/l:0;var F=l?t*(m+e-r)/l:0;l=f-b+t;b=f+b+t;var H=f+F+t;F=f-F+t;var p=m-A;var G=m+e;0>q.y&&(p=m,G=m+e+A);c.inverted&&(H=c.plotWidth-m,l=r-(c.plotWidth-w),b=t*(r-H)/l,F=t*(r-(H-e))/l,l=f+t+b,b=l-2*b,H=f-F+t,F=f+F+t,p=m,G=m+e-A,0>q.y&&(G=m+e+A));q.shapeType="path";q.shapeArgs={x:l,y:p,width:b-l,height:e,d:[["M",l,p],["L",b,p],["L",H,G],["L",F,G],["Z"]]}})}});
""});E(c,"Series/GaugeSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],c["Core/Utilities.js"]],function(c,a,k,b){var g=b.clamp,n=b.isNumber,p=b.merge,z=b.pick,C=b.pInt;b=a.TrackerMixin;c.seriesType("gauge","line",{dataLabels:{borderColor:"#cccccc",borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},{angular:!0,directTouch:!0,drawGraph:a.noop,fixedBox:!0,forceDL:!0,
noSharedTooltip:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var a=this.yAxis,d=this.options,b=a.center;this.generatePoints();this.points.forEach(function(c){var k=p(d.dial,c.dial),u=C(z(k.radius,"80%"))*b[2]/200,w=C(z(k.baseLength,"70%"))*u/100,v=C(z(k.rearLength,"10%"))*u/100,h=k.baseWidth||3,q=k.topWidth||1,e=d.overshoot,f=a.startAngleRad+a.translate(c.y,null,null,null,!0);if(n(e)||!1===d.wrap)e=n(e)?e/180*Math.PI:0,f=g(f,a.startAngleRad-e,a.endAngleRad+e);f=180*f/Math.PI;
c.shapeType="path";c.shapeArgs={d:k.path||[["M",-v,-h/2],["L",w,-h/2],["L",u,-q/2],["L",u,q/2],["L",w,h/2],["L",-v,h/2],["Z"]],translateX:b[0],translateY:b[1],rotation:f};c.plotX=b[0];c.plotY=b[1]})},drawPoints:function(){var a=this,d=a.chart,b=a.yAxis.center,g=a.pivot,c=a.options,k=c.pivot,n=d.renderer;a.points.forEach(function(b){var h=b.graphic,q=b.shapeArgs,e=q.d,f=p(c.dial,b.dial);h?(h.animate(q),q.d=e):b.graphic=n[b.shapeType](q).attr({rotation:q.rotation,zIndex:1}).addClass("highcharts-dial").add(a.group);
if(!d.styledMode)b.graphic[h?"animate":"attr"]({stroke:f.borderColor||"none","stroke-width":f.borderWidth||0,fill:f.backgroundColor||"#000000"})});g?g.animate({translateX:b[0],translateY:b[1]}):(a.pivot=n.circle(0,0,z(k.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(b[0],b[1]).add(a.group),d.styledMode||a.pivot.attr({"stroke-width":k.borderWidth||0,stroke:k.borderColor||"#cccccc",fill:k.backgroundColor||"#000000"}))},animate:function(a){var d=this;a||d.points.forEach(function(a){var b=
a.graphic;b&&(b.attr({rotation:180*d.yAxis.startAngleRad/Math.PI}),b.animate({rotation:a.shapeArgs.rotation},d.options.animation))})},render:function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);k.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(a,d){k.prototype.setData.call(this,a,!1);this.processData();this.generatePoints();z(d,!0)&&this.chart.redraw()},hasData:function(){return!!this.points.length},
drawTracker:b&&b.drawTrackerPoint},{setState:function(a){this.state=a}});""});E(c,"Series/BoxPlotSeries.js",[c["Core/Series/Series.js"],c["Series/Column/ColumnSeries.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,a,k,b){var g=a.prototype;a=k.noop;var n=b.pick;c.seriesType("boxplot","column",{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},
whiskerLength:"50%",fillColor:"#ffffff",lineWidth:1,medianWidth:2,whiskerWidth:2},{pointArrayMap:["low","q1","median","q3","high"],toYData:function(a){return[a.low,a.q1,a.median,a.q3,a.high]},pointValKey:"high",pointAttribs:function(){return{}},drawDataLabels:a,translate:function(){var a=this.yAxis,b=this.pointArrayMap;g.translate.apply(this);this.points.forEach(function(g){b.forEach(function(b){null!==g[b]&&(g[b+"Plot"]=a.translate(g[b],0,1,0,1))});g.plotHigh=g.highPlot})},drawPoints:function(){var a=
this,b=a.options,g=a.chart,c=g.renderer,d,k,w,A,y,B,v=0,h,q,e,f,r=!1!==a.doQuartiles,t,m=a.options.whiskerLength;a.points.forEach(function(l){var x=l.graphic,F=x?"animate":"attr",H=l.shapeArgs,u={},G={},p={},J={},I=l.color||a.color;"undefined"!==typeof l.plotY&&(h=Math.round(H.width),q=Math.floor(H.x),e=q+h,f=Math.round(h/2),d=Math.floor(r?l.q1Plot:l.lowPlot),k=Math.floor(r?l.q3Plot:l.lowPlot),w=Math.floor(l.highPlot),A=Math.floor(l.lowPlot),x||(l.graphic=x=c.g("point").add(a.group),l.stem=c.path().addClass("highcharts-boxplot-stem").add(x),
m&&(l.whiskers=c.path().addClass("highcharts-boxplot-whisker").add(x)),r&&(l.box=c.path(void 0).addClass("highcharts-boxplot-box").add(x)),l.medianShape=c.path(void 0).addClass("highcharts-boxplot-median").add(x)),g.styledMode||(G.stroke=l.stemColor||b.stemColor||I,G["stroke-width"]=n(l.stemWidth,b.stemWidth,b.lineWidth),G.dashstyle=l.stemDashStyle||b.stemDashStyle||b.dashStyle,l.stem.attr(G),m&&(p.stroke=l.whiskerColor||b.whiskerColor||I,p["stroke-width"]=n(l.whiskerWidth,b.whiskerWidth,b.lineWidth),
p.dashstyle=l.whiskerDashStyle||b.whiskerDashStyle||b.dashStyle,l.whiskers.attr(p)),r&&(u.fill=l.fillColor||b.fillColor||I,u.stroke=b.lineColor||I,u["stroke-width"]=b.lineWidth||0,u.dashstyle=l.boxDashStyle||b.boxDashStyle||b.dashStyle,l.box.attr(u)),J.stroke=l.medianColor||b.medianColor||I,J["stroke-width"]=n(l.medianWidth,b.medianWidth,b.lineWidth),J.dashstyle=l.medianDashStyle||b.medianDashStyle||b.dashStyle,l.medianShape.attr(J)),B=l.stem.strokeWidth()%2/2,v=q+f+B,x=[["M",v,k],["L",v,w],["M",
v,d],["L",v,A]],l.stem[F]({d:x}),r&&(B=l.box.strokeWidth()%2/2,d=Math.floor(d)+B,k=Math.floor(k)+B,q+=B,e+=B,x=[["M",q,k],["L",q,d],["L",e,d],["L",e,k],["L",q,k],["Z"]],l.box[F]({d:x})),m&&(B=l.whiskers.strokeWidth()%2/2,w+=B,A+=B,t=/%$/.test(m)?f*parseFloat(m)/100:m/2,x=[["M",v-t,w],["L",v+t,w],["M",v-t,A],["L",v+t,A]],l.whiskers[F]({d:x})),y=Math.round(l.medianPlot),B=l.medianShape.strokeWidth()%2/2,y+=B,x=[["M",q,y],["L",e,y]],l.medianShape[F]({d:x}))})},setStackedPoints:a});""});E(c,"Series/ErrorBarSeries.js",
[c["Core/Series/Series.js"],c["Core/Globals.js"]],function(c,a){a=a.noop;var k=c.seriesTypes;c.seriesType("errorbar","boxplot",{color:"#000000",grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},whiskerWidth:null},{type:"errorbar",pointArrayMap:["low","high"],toYData:function(a){return[a.low,a.high]},pointValKey:"high",doQuartiles:!1,drawDataLabels:k.arearange?function(){var a=this.pointValKey;
k.arearange.prototype.drawDataLabels.call(this);this.data.forEach(function(b){b.y=b[a]})}:a,getColumnMetrics:function(){return this.linkedParent&&this.linkedParent.columnMetrics||k.column.prototype.getColumnMetrics.call(this)}});""});E(c,"Series/WaterfallSeries.js",[c["Core/Axis/Axis.js"],c["Core/Series/Series.js"],c["Core/Chart/Chart.js"],c["Series/Line/LineSeries.js"],c["Core/Series/Point.js"],c["Extensions/Stacking.js"],c["Core/Utilities.js"]],function(c,a,k,b,g,n,p){var z=a.seriesTypes,C=p.addEvent,
D=p.arrayMax,d=p.arrayMin,u=p.correctFloat,w=p.isNumber,A=p.objectEach,y=p.pick,B;(function(a){function d(){var e=this.waterfall.stacks;e&&(e.changed=!1,delete e.alreadyChanged)}function b(){var e=this.options.stackLabels;e&&e.enabled&&this.waterfall.stacks&&this.waterfall.renderStackTotals()}function e(){for(var e=this.axes,f=this.series,a=f.length;a--;)f[a].options.stacking&&(e.forEach(function(e){e.isXAxis||(e.waterfall.stacks.changed=!0)}),a=0)}function f(){this.waterfall||(this.waterfall=new r(this))}
var r=function(){function e(e){this.axis=e;this.stacks={changed:!1}}e.prototype.renderStackTotals=function(){var e=this.axis,f=e.waterfall.stacks,a=e.stacking&&e.stacking.stackTotalGroup,d=new n(e,e.options.stackLabels,!1,0,void 0);this.dummyStackItem=d;A(f,function(e){A(e,function(e){d.total=e.stackTotal;e.label&&(d.label=e.label);n.prototype.render.call(d,a);e.label=d.label;delete d.label})});d.total=null};return e}();a.Composition=r;a.compose=function(a,r){C(a,"init",f);C(a,"afterBuildStacks",
d);C(a,"afterRender",b);C(r,"beforeRedraw",e)}})(B||(B={}));a.seriesType("waterfall","column",{dataLabels:{inside:!0},lineWidth:1,lineColor:"#333333",dashStyle:"Dot",borderColor:"#333333",states:{hover:{lineWidthPlus:0}}},{pointValKey:"y",showLine:!0,generatePoints:function(){var a;z.column.prototype.generatePoints.apply(this);var d=0;for(a=this.points.length;d<a;d++){var b=this.points[d];var e=this.processedYData[d];if(b.isIntermediateSum||b.isSum)b.y=u(e)}},translate:function(){var a=this.options,
d=this.yAxis,b,e=y(a.minPointLength,5),f=e/2,r=a.threshold,t=a.stacking,m=d.waterfall.stacks[this.stackKey];z.column.prototype.translate.apply(this);var l=b=r;var x=this.points;var g=0;for(a=x.length;g<a;g++){var c=x[g];var k=this.processedYData[g];var n=c.shapeArgs;var u=[0,k];var p=c.y;if(t){if(m){u=m[g];if("overlap"===t){var w=u.stackState[u.stateIndex--];w=0<=p?w:w-p;Object.hasOwnProperty.call(u,"absolutePos")&&delete u.absolutePos;Object.hasOwnProperty.call(u,"absoluteNeg")&&delete u.absoluteNeg}else 0<=
p?(w=u.threshold+u.posTotal,u.posTotal-=p):(w=u.threshold+u.negTotal,u.negTotal-=p,w-=p),!u.posTotal&&Object.hasOwnProperty.call(u,"absolutePos")&&(u.posTotal=u.absolutePos,delete u.absolutePos),!u.negTotal&&Object.hasOwnProperty.call(u,"absoluteNeg")&&(u.negTotal=u.absoluteNeg,delete u.absoluteNeg);c.isSum||(u.connectorThreshold=u.threshold+u.stackTotal);d.reversed?(k=0<=p?w-p:w+p,p=w):(k=w,p=w-p);c.below=k<=y(r,0);n.y=d.translate(k,0,1,0,1);n.height=Math.abs(n.y-d.translate(p,0,1,0,1))}if(p=d.waterfall.dummyStackItem)p.x=
g,p.label=m[g].label,p.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[g],this.stackedYPos[g])}else w=Math.max(l,l+p)+u[0],n.y=d.translate(w,0,1,0,1),c.isSum?(n.y=d.translate(u[1],0,1,0,1),n.height=Math.min(d.translate(u[0],0,1,0,1),d.len)-n.y):c.isIntermediateSum?(0<=p?(k=u[1]+b,p=b):(k=b,p=u[1]+b),d.reversed&&(k^=p,p^=k,k^=p),n.y=d.translate(k,0,1,0,1),n.height=Math.abs(n.y-Math.min(d.translate(p,0,1,0,1),d.len)),b+=u[1]):(n.height=0<k?d.translate(l,0,1,0,1)-n.y:d.translate(l,0,1,0,
1)-d.translate(l-k,0,1,0,1),l+=k,c.below=l<y(r,0)),0>n.height&&(n.y+=n.height,n.height*=-1);c.plotY=n.y=Math.round(n.y)-this.borderWidth%2/2;n.height=Math.max(Math.round(n.height),.001);c.yBottom=n.y+n.height;n.height<=e&&!c.isNull?(n.height=e,n.y-=f,c.plotY=n.y,c.minPointLengthOffset=0>c.y?-f:f):(c.isNull&&(n.width=0),c.minPointLengthOffset=0);n=c.plotY+(c.negative?n.height:0);this.chart.inverted?c.tooltipPos[0]=d.len-n:c.tooltipPos[1]=n}},processData:function(d){var a=this.options,q=this.yData,
e=a.data,f=q.length,r=a.threshold||0,t,m,l,x,g;for(g=m=t=l=x=0;g<f;g++){var c=q[g];var k=e&&e[g]?e[g]:{};"sum"===c||k.isSum?q[g]=u(m):"intermediateSum"===c||k.isIntermediateSum?(q[g]=u(t),t=0):(m+=c,t+=c);l=Math.min(m,l);x=Math.max(m,x)}b.prototype.processData.call(this,d);a.stacking||(this.dataMin=l+r,this.dataMax=x)},toYData:function(d){return d.isSum?"sum":d.isIntermediateSum?"intermediateSum":d.y},updateParallelArrays:function(d,a){b.prototype.updateParallelArrays.call(this,d,a);if("sum"===this.yData[0]||
"intermediateSum"===this.yData[0])this.yData[0]=null},pointAttribs:function(d,a){var b=this.options.upColor;b&&!d.options.color&&(d.color=0<d.y?b:null);d=z.column.prototype.pointAttribs.call(this,d,a);delete d.dashstyle;return d},getGraphPath:function(){return[["M",0,0]]},getCrispPath:function(){var d=this.data,a=this.yAxis,b=d.length,e=Math.round(this.graph.strokeWidth())%2/2,f=Math.round(this.borderWidth)%2/2,r=this.xAxis.reversed,t=this.yAxis.reversed,m=this.options.stacking,l=[],g;for(g=1;g<b;g++){var c=
d[g].shapeArgs;var k=d[g-1];var n=d[g-1].shapeArgs;var u=a.waterfall.stacks[this.stackKey];var p=0<k.y?-n.height:0;u&&n&&c&&(u=u[g-1],m?(u=u.connectorThreshold,p=Math.round(a.translate(u,0,1,0,1)+(t?p:0))-e):p=n.y+k.minPointLengthOffset+f-e,l.push(["M",(n.x||0)+(r?0:n.width||0),p],["L",(c.x||0)+(r?c.width||0:0),p]));!m&&l.length&&n&&(0>k.y&&!t||0<k.y&&t)&&(l[l.length-2][2]+=n.height,l[l.length-1][2]+=n.height)}return l},drawGraph:function(){b.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})},
setStackedPoints:function(){function d(e,f,d,a){if(C)for(d;d<C;d++)A.stackState[d]+=a;else A.stackState[0]=e,C=A.stackState.length;A.stackState.push(A.stackState[C-1]+f)}var a=this.options,b=this.yAxis.waterfall.stacks,e=a.threshold,f=e||0,r=f,t=this.stackKey,m=this.xData,l=m.length,g,c,k;this.yAxis.stacking.usePercentage=!1;var n=c=k=f;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var u=b.changed;(g=b.alreadyChanged)&&0>g.indexOf(t)&&(u=!0);b[t]||(b[t]={});g=b[t];for(var p=0;p<l;p++){var w=
m[p];if(!g[w]||u)g[w]={negTotal:0,posTotal:0,stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:u&&g[w]?g[w].label:void 0};var A=g[w];var y=this.yData[p];0<=y?A.posTotal+=y:A.negTotal+=y;var z=a.data[p];w=A.absolutePos=A.posTotal;var D=A.absoluteNeg=A.negTotal;A.stackTotal=w+D;var C=A.stackState.length;z&&z.isIntermediateSum?(d(k,c,0,k),k=c,c=e,f^=r,r^=f,f^=r):z&&z.isSum?(d(e,n,C),f=e):(d(f,y,0,n),z&&(n+=y,c+=y));A.stateIndex++;A.threshold=f;f+=A.stackTotal}b.changed=!1;b.alreadyChanged||(b.alreadyChanged=
[]);b.alreadyChanged.push(t)}},getExtremes:function(){var a=this.options.stacking;if(a){var b=this.yAxis;b=b.waterfall.stacks;var q=this.stackedYNeg=[];var e=this.stackedYPos=[];"overlap"===a?A(b[this.stackKey],function(f){q.push(d(f.stackState));e.push(D(f.stackState))}):A(b[this.stackKey],function(f){q.push(f.negTotal+f.threshold);e.push(f.posTotal+f.threshold)});return{dataMin:d(q),dataMax:D(e)}}return{dataMin:this.dataMin,dataMax:this.dataMax}}},{getClassName:function(){var d=g.prototype.getClassName.call(this);
this.isSum?d+=" highcharts-sum":this.isIntermediateSum&&(d+=" highcharts-intermediate-sum");return d},isValid:function(){return w(this.y)||this.isSum||!!this.isIntermediateSum}});"";B.compose(c,k);return B});E(c,"Series/PolygonSeries.js",[c["Core/Series/Series.js"],c["Core/Globals.js"],c["Mixins/LegendSymbol.js"],c["Series/Line/LineSeries.js"]],function(c,a,k,b){var g=c.seriesTypes;c.seriesType("polygon","scatter",{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,
pointFormat:""},trackByArea:!0},{type:"polygon",getGraphPath:function(){for(var a=b.prototype.getGraphPath.call(this),g=a.length+1;g--;)(g===a.length||"M"===a[g][0])&&0<g&&a.splice(g,0,["Z"]);return this.areaPath=a},drawGraph:function(){this.options.fillColor=this.color;g.area.prototype.drawGraph.call(this)},drawLegendSymbol:k.drawRectangle,drawTracker:b.prototype.drawTracker,setStackedPoints:a.noop});""});E(c,"Series/Bubble/BubbleLegend.js",[c["Core/Chart/Chart.js"],c["Core/Color/Color.js"],c["Core/Globals.js"],
c["Core/Legend.js"],c["Series/Line/LineSeries.js"],c["Core/Utilities.js"]],function(c,a,k,b,g,n){var p=a.parse,z=k.noop;a=n.addEvent;var C=n.arrayMax,D=n.arrayMin,d=n.isNumber,u=n.merge,w=n.objectEach,A=n.pick,y=n.setOptions,B=n.stableSort,v=n.wrap;"";y({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,
align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});y=function(){function a(a,e){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=z;this.init(a,
e)}a.prototype.init=function(a,e){this.options=a;this.visible=!0;this.chart=e.chart;this.legend=e};a.prototype.addToLegend=function(a){a.splice(this.options.legendIndex,0,this)};a.prototype.drawLegendSymbol=function(a){var e=this.chart,f=this.options,r=A(a.options.itemDistance,20),b=f.ranges;var m=f.connectorDistance;this.fontMetrics=e.renderer.fontMetrics(f.labels.style.fontSize.toString()+"px");b&&b.length&&d(b[0].value)?(B(b,function(e,f){return f.value-e.value}),this.ranges=b,this.setOptions(),
this.render(),e=this.getMaxLabelSize(),b=this.ranges[0].radius,a=2*b,m=m-b+e.width,m=0<m?m:0,this.maxLabel=e,this.movementX="left"===f.labels.align?m:0,this.legendItemWidth=a+m+r,this.legendItemHeight=a+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var a=this.ranges,e=this.options,f=this.chart.series[e.seriesIndex],d=this.legend.baseline,b={"z-index":e.zIndex,"stroke-width":e.borderWidth},m={"z-index":e.zIndex,"stroke-width":e.connectorWidth},l=this.getLabelStyles(),
h=f.options.marker.fillOpacity,g=this.chart.styledMode;a.forEach(function(r,t){g||(b.stroke=A(r.borderColor,e.borderColor,f.color),b.fill=A(r.color,e.color,1!==h?p(f.color).setOpacity(h).get("rgba"):f.color),m.stroke=A(r.connectorColor,e.connectorColor,f.color));a[t].radius=this.getRangeRadius(r.value);a[t]=u(a[t],{center:a[0].radius-a[t].radius+d});g||u(!0,a[t],{bubbleStyle:u(!1,b),connectorStyle:u(!1,m),labelStyle:l})},this)};a.prototype.getLabelStyles=function(){var a=this.options,e={},f="left"===
a.labels.align,d=this.legend.options.rtl;w(a.labels.style,function(f,a){"color"!==a&&"fontSize"!==a&&"z-index"!==a&&(e[a]=f)});return u(!1,e,{"font-size":a.labels.style.fontSize,fill:A(a.labels.style.color,"#000000"),"z-index":a.zIndex,align:d||f?"right":"left"})};a.prototype.getRangeRadius=function(a){var e=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,e.ranges[e.ranges.length-1].value,e.ranges[0].value,e.minSize,e.maxSize,a)};a.prototype.render=function(){var a=
this.chart.renderer,e=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(f){f.value>=e&&this.renderRange(f)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};a.prototype.renderRange=function(a){var e=this.options,f=e.labels,
d=this.chart.renderer,b=this.symbols,m=b.labels,l=a.center,h=Math.abs(a.radius),g=e.connectorDistance||0,c=f.align,q=f.style.fontSize;g=this.legend.options.rtl||"left"===c?-g:g;f=e.connectorWidth;var k=this.ranges[0].radius||0,n=l-h-e.borderWidth/2+f/2;q=q/2-(this.fontMetrics.h-q)/2;var u=d.styledMode;"center"===c&&(g=0,e.connectorDistance=0,a.labelStyle.align="center");c=n+e.labels.y;var p=k+g+e.labels.x;b.bubbleItems.push(d.circle(k,l+((n%1?1:.5)-(f%2?0:.5)),h).attr(u?{}:a.bubbleStyle).addClass((u?
"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(e.className||"")).add(this.legendSymbol));b.connectors.push(d.path(d.crispLine([["M",k,n],["L",k+g,n]],e.connectorWidth)).attr(u?{}:a.connectorStyle).addClass((u?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(e.connectorClassName||"")).add(this.legendSymbol));a=d.text(this.formatLabel(a),p,c+q).attr(u?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+(e.labels.className||
"")).add(this.legendSymbol);m.push(a);a.placed=!0;a.alignAttr={x:p,y:c+q}};a.prototype.getMaxLabelSize=function(){var a,e;this.symbols.labels.forEach(function(f){e=f.getBBox(!0);a=a?e.width>a.width?e:a:e});return a||{}};a.prototype.formatLabel=function(a){var e=this.options,f=e.labels.formatter;e=e.labels.format;var d=this.chart.numberFormatter;return e?n.format(e,a):f?f.call(a):d(a.value,1)};a.prototype.hideOverlappingLabels=function(){var a=this.chart,e=this.symbols;!this.options.labels.allowOverlap&&
e&&(a.hideOverlappingLabels(e.labels),e.labels.forEach(function(a,d){a.newOpacity?a.newOpacity!==a.oldOpacity&&e.connectors[d].show():e.connectors[d].hide()}))};a.prototype.getRanges=function(){var a=this.legend.bubbleLegend,e=a.options.ranges,f,b=Number.MAX_VALUE,t=-Number.MAX_VALUE;a.chart.series.forEach(function(e){e.isBubble&&!e.ignoreSeries&&(f=e.zData.filter(d),f.length&&(b=A(e.options.zMin,Math.min(b,Math.max(D(f),!1===e.options.displayNegative?e.options.zThreshold:-Number.MAX_VALUE))),t=A(e.options.zMax,
Math.max(t,C(f)))))});var m=b===t?[{value:t}]:[{value:b},{value:(b+t)/2},{value:t,autoRanges:!0}];e.length&&e[0].radius&&m.reverse();m.forEach(function(a,f){e&&e[f]&&(m[f]=u(!1,e[f],a))});return m};a.prototype.predictBubbleSizes=function(){var a=this.chart,e=this.fontMetrics,f=a.legend.options,d="horizontal"===f.layout,b=d?a.legend.lastLineHeight:0,m=a.plotSizeX,l=a.plotSizeY,h=a.series[this.options.seriesIndex];a=Math.ceil(h.minPxSize);var g=Math.ceil(h.maxPxSize);h=h.options.maxSize;var c=Math.min(l,
m);if(f.floating||!/%$/.test(h))e=g;else if(h=parseFloat(h),e=(c+b-e.h/2)*h/100/(h/100+1),d&&l-e>=m||!d&&m-e>=l)e=g;return[a,Math.ceil(e)]};a.prototype.updateRanges=function(a,e){var f=this.legend.options.bubbleLegend;f.minSize=a;f.maxSize=e;f.ranges=this.getRanges()};a.prototype.correctSizes=function(){var a=this.legend,e=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(e.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,e.maxPxSize),a.render())};return a}();
a(b,"afterGetAllItems",function(a){var d=this.bubbleLegend,e=this.options,f=e.bubbleLegend,b=this.chart.getVisibleBubbleSeriesIndex();d&&d.ranges&&d.ranges.length&&(f.ranges.length&&(f.autoRanges=!!f.ranges[0].autoRanges),this.destroyItem(d));0<=b&&e.enabled&&f.enabled&&(f.seriesIndex=b,this.bubbleLegend=new k.BubbleLegend(f,this),this.bubbleLegend.addToLegend(a.allItems))});c.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=this.series,d=0;d<a.length;){if(a[d]&&a[d].isBubble&&a[d].visible&&
a[d].zData.length)return d;d++}return-1};b.prototype.getLinesHeights=function(){var a=this.allItems,d=[],e=a.length,f,b=0;for(f=0;f<e;f++)if(a[f].legendItemHeight&&(a[f].itemHeight=a[f].legendItemHeight),a[f]===a[e-1]||a[f+1]&&a[f]._legendItemPos[1]!==a[f+1]._legendItemPos[1]){d.push({height:0});var t=d[d.length-1];for(b;b<=f;b++)a[b].itemHeight>t.height&&(t.height=a[b].itemHeight);t.step=f}return d};b.prototype.retranslateItems=function(a){var d,e,f,b=this.options.rtl,t=0;this.allItems.forEach(function(r,
l){d=r.legendGroup.translateX;e=r._legendItemPos[1];if((f=r.movementX)||b&&r.ranges)f=b?d-r.options.maxSize/2:d+f,r.legendGroup.attr({translateX:f});l>a[t].step&&t++;r.legendGroup.attr({translateY:Math.round(e+a[t].height/2)});r._legendItemPos[1]=e+a[t].height/2})};a(g,"legendItemClick",function(){var a=this.chart,d=this.visible,e=this.chart.legend;e&&e.bubbleLegend&&(this.visible=!d,this.ignoreSeries=d,a=0<=a.getVisibleBubbleSeriesIndex(),e.bubbleLegend.visible!==a&&(e.update({bubbleLegend:{enabled:a}}),
e.bubbleLegend.visible=a),this.visible=d)});v(c.prototype,"drawChartBox",function(a,d,e){var f=this.legend,b=0<=this.getVisibleBubbleSeriesIndex();if(f&&f.options.enabled&&f.bubbleLegend&&f.options.bubbleLegend.autoRanges&&b){var t=f.bubbleLegend.options;b=f.bubbleLegend.predictBubbleSizes();f.bubbleLegend.updateRanges(b[0],b[1]);t.placed||(f.group.placed=!1,f.allItems.forEach(function(e){e.legendGroup.translateY=null}));f.render();this.getMargins();this.axes.forEach(function(e){e.visible&&e.render();
t.placed||(e.setScale(),e.updateNames(),w(e.ticks,function(e){e.isNew=!0;e.isNewLabel=!0}))});t.placed=!0;this.getMargins();a.call(this,d,e);f.bubbleLegend.correctSizes();f.retranslateItems(f.getLinesHeights())}else a.call(this,d,e),f&&f.options.enabled&&f.bubbleLegend&&(f.render(),f.retranslateItems(f.getLinesHeights()))});k.BubbleLegend=y;return k.BubbleLegend});E(c,"Series/Bubble/BubbleSeries.js",[c["Core/Axis/Axis.js"],c["Core/Series/Series.js"],c["Core/Color/Color.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],
c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,a,k,b,g,n,p){var z=a.seriesTypes,C=k.parse;k=b.noop;var D=p.arrayMax,d=p.arrayMin,u=p.clamp,w=p.extend,A=p.isNumber,y=p.pick,B=p.pInt;"";a.seriesType("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},
tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(a,d){var b=this.options.marker.fillOpacity;a=g.prototype.pointAttribs.call(this,a,d);1!==b&&(a.fill=C(a.fill).setOpacity(b).get("rgba"));return a},getRadii:function(a,d,b){var e=this.zData,f=this.yData,
r=b.minPxSize,t=b.maxPxSize,m=[];var l=0;for(b=e.length;l<b;l++){var g=e[l];m.push(this.getRadius(a,d,r,t,g,f[l]))}this.radii=m},getRadius:function(a,d,b,e,f,r){var t=this.options,m="width"!==t.sizeBy,l=t.zThreshold,g=d-a,c=.5;if(null===r||null===f)return null;if(A(f)){t.sizeByAbsoluteValue&&(f=Math.abs(f-l),g=Math.max(d-l,Math.abs(a-l)),a=0);if(f<a)return b/2-1;0<g&&(c=(f-a)/g)}m&&0<=c&&(c=Math.sqrt(c));return Math.ceil(b+c*(e-b))/2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&
this.points.forEach(function(a){var d=a.graphic;d&&d.width&&(this.hasRendered||d.attr({x:a.plotX,y:a.plotY,width:1,height:1}),d.animate(this.markerAttribs(a),this.options.animation))},this)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,d=this.data,b=this.radii;z.scatter.prototype.translate.call(this);for(a=d.length;a--;){var e=d[a];var f=b?b[a]:0;A(f)&&f>=this.minPxSize/2?(e.marker=w(e.marker,{radius:f,width:2*f,height:2*f}),e.dlBox={x:e.plotX-f,y:e.plotY-f,width:2*
f,height:2*f}):e.shapeArgs=e.plotY=e.dlBox=void 0}},alignDataLabel:z.column.prototype.alignDataLabel,buildKDTree:k,applyZones:k},{haloPath:function(a){return n.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});c.prototype.beforePadding=function(){var a=this,b=this.len,g=this.chart,e=0,f=b,r=this.isXAxis,t=r?"xData":"yData",m=this.min,l={},c=Math.min(g.plotWidth,g.plotHeight),k=Number.MAX_VALUE,n=-Number.MAX_VALUE,p=this.max-m,w=b/p,z=[];this.series.forEach(function(e){var f=
e.options;!e.bubblePadding||!e.visible&&g.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,z.push(e),r&&(["minSize","maxSize"].forEach(function(a){var e=f[a],d=/%$/.test(e);e=B(e);l[a]=d?c*e/100:e}),e.minPxSize=l.minSize,e.maxPxSize=Math.max(l.maxSize,l.minSize),e=e.zData.filter(A),e.length&&(k=y(f.zMin,u(d(e),!1===f.displayNegative?f.zThreshold:-Number.MAX_VALUE,k)),n=y(f.zMax,Math.max(n,D(e))))))});z.forEach(function(d){var b=d[t],l=b.length;r&&d.getRadii(k,n,d);if(0<p)for(;l--;)if(A(b[l])&&
a.dataMin<=b[l]&&b[l]<=a.max){var g=d.radii?d.radii[l]:0;e=Math.min((b[l]-m)*w-g,e);f=Math.max((b[l]-m)*w+g,f)}});z.length&&0<p&&!this.logarithmic&&(f-=b,w*=(b+Math.max(0,e)-Math.min(f,b))/b,[["min","userMin",e],["max","userMax",f]].forEach(function(e){"undefined"===typeof y(a.options[e[0]],a[e[1]])&&(a[e[0]]+=e[2]/w)}))};""});E(c,"Series/Networkgraph/DraggableNodes.js",[c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,a,k){var b=k.addEvent;a.dragNodesMixin={onMouseDown:function(a,
b){b=this.chart.pointer.normalize(b);a.fixedPosition={chartX:b.chartX,chartY:b.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,b){if(a.fixedPosition&&a.inDragMode){var g=this.chart;b=g.pointer.normalize(b);var c=a.fixedPosition.chartX-b.chartX,k=a.fixedPosition.chartY-b.chartY;b=g.graphLayoutsLookup;if(5<Math.abs(c)||5<Math.abs(k))c=a.fixedPosition.plotX-c,k=a.fixedPosition.plotY-k,g.isInsidePlot(c,k)&&(a.plotX=c,a.plotY=k,a.hasDragged=!0,this.redrawHalo(a),b.forEach(function(a){a.restartSimulation()}))}},
onMouseUp:function(a,b){a.fixedPosition&&(a.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw()),a.inDragMode=a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};b(c,"load",function(){var a=this,c,k,z;a.container&&(c=b(a.container,"mousedown",function(c){var g=a.hoverPoint;g&&g.series&&g.series.hasDraggableNodes&&g.series.options.draggable&&(g.series.onMouseDown(g,
c),k=b(a.container,"mousemove",function(a){return g&&g.series&&g.series.onMouseMove(g,a)}),z=b(a.container.ownerDocument,"mouseup",function(a){k();z();return g&&g.series&&g.series.onMouseUp(g,a)}))}));b(a,"destroy",function(){c()})})});E(c,"Series/Networkgraph/Integrations.js",[c["Core/Globals.js"]],function(c){c.networkgraphIntegrations={verlet:{attractiveForceFunction:function(a,c){return(c-a)/a},repulsiveForceFunction:function(a,c){return(c-a)/a*(c>a?1:0)},barycenter:function(){var a=this.options.gravitationalConstant,
c=this.barycenter.xFactor,b=this.barycenter.yFactor;c=(c-(this.box.left+this.box.width)/2)*a;b=(b-(this.box.top+this.box.height)/2)*a;this.nodes.forEach(function(a){a.fixedPosition||(a.plotX-=c/a.mass/a.degree,a.plotY-=b/a.mass/a.degree)})},repulsive:function(a,c,b){c=c*this.diffTemperature/a.mass/a.degree;a.fixedPosition||(a.plotX+=b.x*c,a.plotY+=b.y*c)},attractive:function(a,c,b){var g=a.getMass(),k=-b.x*c*this.diffTemperature;c=-b.y*c*this.diffTemperature;a.fromNode.fixedPosition||(a.fromNode.plotX-=
k*g.fromNode/a.fromNode.degree,a.fromNode.plotY-=c*g.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.plotX+=k*g.toNode/a.toNode.degree,a.toNode.plotY+=c*g.toNode/a.toNode.degree)},integrate:function(a,c){var b=-a.options.friction,g=a.options.maxSpeed,k=(c.plotX+c.dispX-c.prevX)*b;b*=c.plotY+c.dispY-c.prevY;var p=Math.abs,z=p(k)/(k||1);p=p(b)/(b||1);k=z*Math.min(g,Math.abs(k));b=p*Math.min(g,Math.abs(b));c.prevX=c.plotX+c.dispX;c.prevY=c.plotY+c.dispY;c.plotX+=k;c.plotY+=b;c.temperature=
a.vectorLength({x:k,y:b})},getK:function(a){return Math.pow(a.box.width*a.box.height/a.nodes.length,.5)}},euler:{attractiveForceFunction:function(a,c){return a*a/c},repulsiveForceFunction:function(a,c){return c*c/a},barycenter:function(){var a=this.options.gravitationalConstant,c=this.barycenter.xFactor,b=this.barycenter.yFactor;this.nodes.forEach(function(g){if(!g.fixedPosition){var k=g.getDegree();k*=1+k/2;g.dispX+=(c-g.plotX)*a*k/g.degree;g.dispY+=(b-g.plotY)*a*k/g.degree}})},repulsive:function(a,
c,b,g){a.dispX+=b.x/g*c/a.degree;a.dispY+=b.y/g*c/a.degree},attractive:function(a,c,b,g){var k=a.getMass(),p=b.x/g*c;c*=b.y/g;a.fromNode.fixedPosition||(a.fromNode.dispX-=p*k.fromNode/a.fromNode.degree,a.fromNode.dispY-=c*k.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.dispX+=p*k.toNode/a.toNode.degree,a.toNode.dispY+=c*k.toNode/a.toNode.degree)},integrate:function(a,c){c.dispX+=c.dispX*a.options.friction;c.dispY+=c.dispY*a.options.friction;var b=c.temperature=a.vectorLength({x:c.dispX,
y:c.dispY});0!==b&&(c.plotX+=c.dispX/b*Math.min(Math.abs(c.dispX),a.temperature),c.plotY+=c.dispY/b*Math.min(Math.abs(c.dispY),a.temperature))},getK:function(a){return Math.pow(a.box.width*a.box.height/a.nodes.length,.3)}}}});E(c,"Series/Networkgraph/QuadTree.js",[c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,a){a=a.extend;var k=c.QuadTreeNode=function(a){this.box=a;this.boxSize=Math.min(a.width,a.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};a(k.prototype,{insert:function(a,
c){this.isInternal?this.nodes[this.getBoxPosition(a)].insert(a,c-1):(this.isEmpty=!1,this.body?c?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,c-1),this.body=!0),this.nodes[this.getBoxPosition(a)].insert(a,c-1)):(c=new k({top:a.plotX,left:a.plotY,width:.1,height:.1}),c.body=a,c.isInternal=!1,this.nodes.push(c)):(this.isInternal=!1,this.body=a))},updateMassAndCenter:function(){var a=0,c=0,k=0;this.isInternal?(this.nodes.forEach(function(b){b.isEmpty||
(a+=b.mass,c+=b.plotX*b.mass,k+=b.plotY*b.mass)}),c/=a,k/=a):this.body&&(a=this.body.mass,c=this.body.plotX,k=this.body.plotY);this.mass=a;this.plotX=c;this.plotY=k},divideBox:function(){var a=this.box.width/2,c=this.box.height/2;this.nodes[0]=new k({left:this.box.left,top:this.box.top,width:a,height:c});this.nodes[1]=new k({left:this.box.left+a,top:this.box.top,width:a,height:c});this.nodes[2]=new k({left:this.box.left+a,top:this.box.top+c,width:a,height:c});this.nodes[3]=new k({left:this.box.left,
top:this.box.top+c,width:a,height:c})},getBoxPosition:function(a){var b=a.plotY<this.box.top+this.box.height/2;return a.plotX<this.box.left+this.box.width/2?b?0:3:b?1:2}});c=c.QuadTree=function(a,c,n,p){this.box={left:a,top:c,width:n,height:p};this.maxDepth=25;this.root=new k(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};a(c.prototype,{insertNodes:function(a){a.forEach(function(a){this.root.insert(a,this.maxDepth)},this)},visitNodeRecursive:function(a,c,k){var b;
a||(a=this.root);a===this.root&&c&&(b=c(a));!1!==b&&(a.nodes.forEach(function(a){if(a.isInternal){c&&(b=c(a));if(!1===b)return;this.visitNodeRecursive(a,c,k)}else a.body&&c&&c(a.body);k&&k(a)},this),a===this.root&&k&&k(a))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(a){a.updateMassAndCenter()})}})});E(c,"Series/Networkgraph/Layouts.js",[c["Core/Chart/Chart.js"],c["Core/Animation/AnimationUtilities.js"],c["Core/Globals.js"],c["Core/Utilities.js"]],function(c,a,k,b){var g=
a.setAnimation;a=b.addEvent;var n=b.clamp,p=b.defined,z=b.extend,C=b.isFunction,D=b.pick;k.layouts={"reingold-fruchterman":function(){}};z(k.layouts["reingold-fruchterman"].prototype,{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=k.networkgraphIntegrations[a.integration];this.enableSimulation=a.enableSimulation;this.attractiveForce=D(a.attractiveForce,this.integration.attractiveForceFunction);
this.repulsiveForce=D(a.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=a.approximation},updateSimulation:function(a){this.enableSimulation=D(a,this.options.enableSimulation)},start:function(){var a=this.series,b=this.options;this.currentStep=0;this.forces=a[0]&&a[0].forces||[];this.chart=a[0]&&a[0].chart;this.initialRendering&&(this.initPositions(),a.forEach(function(a){a.finishedAnimating=!0;a.render()}));this.setK();this.resetSimulation(b);this.enableSimulation&&this.step()},
step:function(){var a=this,b=this.series;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),a.quadTree.calculateMassAndCenter());a.forces.forEach(function(d){a[d+"Forces"](a.temperature)});a.applyLimits(a.temperature);a.temperature=a.coolDown(a.startTemperature,a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;a.systemTemperature=a.getSystemTemperature();a.enableSimulation&&(b.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&
!a.isStable()?(a.simulation&&k.win.cancelAnimationFrame(a.simulation),a.simulation=k.win.requestAnimationFrame(function(){a.step()})):a.simulation=!1)},stop:function(){this.simulation&&k.win.cancelAnimationFrame(this.simulation)},setArea:function(a,b,c,g){this.box={left:a,top:b,width:c,height:g}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(a,b){a.forEach(function(a){-1===b.indexOf(a)&&b.push(a)})},removeElementFromCollection:function(a,
b){a=b.indexOf(a);-1!==a&&b.splice(a,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},restartSimulation:function(){this.simulation?this.resetSimulation():(this.setInitialRendering(!1),this.enableSimulation?this.start():this.setMaxIterations(1),this.chart&&this.chart.redraw(),this.setInitialRendering(!0))},
setMaxIterations:function(a){this.maxIterations=D(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=new k.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=
this.options.initialPositions;C(a)?(a.call(this),this.nodes.forEach(function(a){p(a.prevX)||(a.prevX=a.plotX);p(a.prevY)||(a.prevY=a.plotY);a.dispX=0;a.dispY=0})):"circle"===a?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function a(d){d.linksFrom.forEach(function(e){p[e.toNode.id]||(p[e.toNode.id]=!0,n.push(e.toNode),a(e.toNode))})}var b=this.box,c=this.nodes,g=2*Math.PI/(c.length+1),k=c.filter(function(a){return 0===a.linksTo.length}),n=[],p={},h=this.options.initialPositionRadius;
k.forEach(function(d){n.push(d);a(d)});n.length?c.forEach(function(a){-1===n.indexOf(a)&&n.push(a)}):n=c;n.forEach(function(a,e){a.plotX=a.prevX=D(a.plotX,b.width/2+h*Math.cos(e*g));a.plotY=a.prevY=D(a.plotY,b.height/2+h*Math.sin(e*g));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=a*a/Math.PI;return a-=Math.floor(a)}var b=this.box,c=this.nodes,g=c.length+1;c.forEach(function(d,c){d.plotX=d.prevX=D(d.plotX,b.width*a(c));d.plotY=d.prevY=D(d.plotY,b.height*a(g+c));d.dispX=0;d.dispY=
0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();this.force("barycenter")},getBarycenter:function(){var a=0,b=0,c=0;this.nodes.forEach(function(d){b+=d.plotX*d.mass;c+=d.plotY*d.mass;a+=d.mass});return this.barycenter={x:b,y:c,xFactor:b/a,yFactor:c/a}},barnesHutApproximation:function(a,b){var d=this.getDistXY(a,b),c=this.vectorLength(d);if(a!==b&&0!==c)if(b.isInternal)if(b.boxSize/c<this.options.theta&&
0!==c){var g=this.repulsiveForce(c,this.k);this.force("repulsive",a,g*b.mass,d,c);var k=!1}else k=!0;else g=this.repulsiveForce(c,this.k),this.force("repulsive",a,g*b.mass,d,c);return k},repulsiveForces:function(){var a=this;"barnes-hut"===a.approximation?a.nodes.forEach(function(d){a.quadTree.visitNodeRecursive(null,function(b){return a.barnesHutApproximation(d,b)})}):a.nodes.forEach(function(d){a.nodes.forEach(function(b){if(d!==b&&!d.fixedPosition){var c=a.getDistXY(d,b);var g=a.vectorLength(c);
if(0!==g){var k=a.repulsiveForce(g,a.k);a.force("repulsive",d,k*b.mass,c,g)}}})})},attractiveForces:function(){var a=this,b,c,g;a.links.forEach(function(d){d.fromNode&&d.toNode&&(b=a.getDistXY(d.fromNode,d.toNode),c=a.vectorLength(b),0!==c&&(g=a.attractiveForce(c,a.k),a.force("attractive",d,g,b,c)))})},applyLimits:function(){var a=this;a.nodes.forEach(function(b){b.fixedPosition||(a.integration.integrate(a,b),a.applyLimitBox(b,a.box),b.dispX=0,b.dispY=0)})},applyLimitBox:function(a,b){var d=a.radius;
a.plotX=n(a.plotX,b.left+d,b.width-d);a.plotY=n(a.plotY,b.top+d,b.height-d)},coolDown:function(a,b,c){return a-b*c},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,b){return a+b.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,b){a=this.getDistXY(a,b);return this.vectorLength(a)},getDistXY:function(a,b){var c=a.plotX-
b.plotX;a=a.plotY-b.plotY;return{x:c,y:a,absX:Math.abs(c),absY:Math.abs(a)}}});a(c,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});a(c,"render",function(){function a(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),c=!1,b=!0)}var b=!1;if(this.graphLayoutsLookup){g(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!c;){var c=!0;this.graphLayoutsLookup.forEach(a)}b&&
this.series.forEach(function(a){a&&a.layout&&a.render()})}});a(c,"beforePrint",function(){this.graphLayoutsLookup&&(this.graphLayoutsLookup.forEach(function(a){a.updateSimulation(!1)}),this.redraw())});a(c,"afterPrint",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.updateSimulation()});this.redraw()})});E(c,"Series/PackedBubbleSeries.js",[c["Core/Series/Series.js"],c["Core/Chart/Chart.js"],c["Core/Color/Color.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],
c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,a,k,b,g,n,p){var z=k.parse,C=p.addEvent,D=p.clamp,d=p.defined,u=p.extend;k=p.extendClass;var w=p.fireEvent,A=p.isArray,y=p.isNumber,B=p.merge,v=p.pick,h=b.layouts["reingold-fruchterman"],q=b.dragNodesMixin;"";a.prototype.getSelectedParentNodes=function(){var a=[];this.series.forEach(function(e){e.parentNode&&e.parentNode.selected&&a.push(e.parentNode)});return a};b.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,
f,b,c){return Math.min(a,(b.marker.radius+c.marker.radius)/2)},barycenter:function(){var a=this,f=a.options.gravitationalConstant,b=a.box,c=a.nodes,d,l;c.forEach(function(e){a.options.splitSeries&&!e.isParentNode?(d=e.series.parentNode.plotX,l=e.series.parentNode.plotY):(d=b.width/2,l=b.height/2);e.fixedPosition||(e.plotX-=(e.plotX-d)*f/(e.mass*Math.sqrt(c.length)),e.plotY-=(e.plotY-l)*f/(e.mass*Math.sqrt(c.length)))})},repulsive:function(a,f,b,c){var e=f*this.diffTemperature/a.mass/a.degree;f=b.x*
e;b=b.y*e;a.fixedPosition||(a.plotX+=f,a.plotY+=b);c.fixedPosition||(c.plotX-=f,c.plotY-=b)},integrate:b.networkgraphIntegrations.verlet.integrate,getK:b.noop};b.layouts.packedbubble=k(h,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},setCircularPositions:function(){var a=this,f=a.box,b=a.nodes,c=2*Math.PI/(b.length+1),d,l,g=a.options.initialPositionRadius;b.forEach(function(e,b){a.options.splitSeries&&!e.isParentNode?(d=e.series.parentNode.plotX,
l=e.series.parentNode.plotY):(d=f.width/2,l=f.height/2);e.plotX=e.prevX=v(e.plotX,d+g*Math.cos(e.index||b*c));e.plotY=e.prevY=v(e.plotY,l+g*Math.sin(e.index||b*c));e.dispX=0;e.dispY=0})},repulsiveForces:function(){var a=this,f,b,c,d=a.options.bubblePadding;a.nodes.forEach(function(e){e.degree=e.mass;e.neighbours=0;a.nodes.forEach(function(r){f=0;e===r||e.fixedPosition||!a.options.seriesInteraction&&e.series!==r.series||(c=a.getDistXY(e,r),b=a.vectorLength(c)-(e.marker.radius+r.marker.radius+d),0>
b&&(e.degree+=.01,e.neighbours++,f=a.repulsiveForce(-b/Math.sqrt(e.neighbours),a.k,e,r)),a.force("repulsive",e,f*r.mass,c,r,b))})})},applyLimitBox:function(a){if(this.options.splitSeries&&!a.isParentNode&&this.options.parentNodeLimit){var e=this.getDistXY(a,a.series.parentNode);var b=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(e);0>b&&b>-2*a.marker.radius&&(a.plotX-=.01*e.x,a.plotY-=.01*e.y)}h.prototype.applyLimitBox.apply(this,arguments)}});c.seriesType("packedbubble","bubble",{minSize:"10%",
maxSize:"50%",sizeBy:"area",zoneAxis:"y",crisp:!1,tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,parentNode:{allowPointSelect:!1},dataLabels:{formatter:function(){return this.point.value},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0,style:{transition:"opacity 2000ms"}},layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,
gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}},{hasDraggableNodes:!0,forces:["barycenter","repulsive"],pointArrayMap:["value"],trackerGroups:["group","dataLabelsGroup","parentNodesGroup"],pointValKey:"value",isCartesian:!1,requireSorting:!1,
directTouch:!0,axisTypes:[],noSharedTooltip:!0,searchPoint:b.noop,accumulateAllPoints:function(a){var e=a.chart,b=[],c,d;for(c=0;c<e.series.length;c++)if(a=e.series[c],a.is("packedbubble")&&a.visible||!e.options.chart.ignoreHiddenSeries)for(d=0;d<a.yData.length;d++)b.push([null,null,a.yData[d],a.index,d,{id:d,marker:{radius:0}}]);return b},init:function(){g.prototype.init.apply(this,arguments);this.eventsToUnbind.push(C(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===
this.type&&(a.isDirty=!0)},this)}));return this},render:function(){var a=[];g.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(e){A(e.dataLabels)&&e.dataLabels.forEach(function(e){a.push(e)})}),this.options.useSimulation&&this.chart.hideOverlappingLabels(a))},setVisible:function(){var a=this;g.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),
a.parentNodeLayout.removeElementFromCollection(a.parentNode,a.parentNodeLayout.nodes),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(e){a.layout.removeElementFromCollection(e,a.layout.nodes)}))},drawDataLabels:function(){var a=this.options.dataLabels.textPath,b=this.points;g.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=
[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,g.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)},seriesBox:function(){var a=this.chart,b=Math.max,c=Math.min,t,m=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+a.plotHeight];this.data.forEach(function(a){d(a.plotX)&&d(a.plotY)&&a.marker.radius&&(t=a.marker.radius,m[0]=c(m[0],a.plotX-t),m[1]=b(m[1],a.plotX+t),m[2]=c(m[2],a.plotY-t),m[3]=b(m[3],a.plotY+
t))});return y(m.width/m.height)?m:null},calculateParentRadius:function(){var a=this.seriesBox();this.parentNodeRadius=D(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)},drawGraph:function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart,b=this.layout.options.parentNodeOptions.marker;
b={fill:b.fillColor||z(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||this.color,"stroke-width":b.lineWidth};var c=this.visible?"inherit":"hidden";this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",c,.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();c=B({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},
b);this.parentNode.graphic||(this.graph=this.parentNode.graphic=a.renderer.symbol(b.symbol).add(this.parentNodesGroup));this.parentNode.graphic.attr(c)}},createParentNodes:function(){var a=this,b=a.chart,c=a.parentNodeLayout,d,m=a.parentNode,l=a.pointClass;a.parentNodeMass=0;a.points.forEach(function(e){a.parentNodeMass+=Math.PI*Math.pow(e.marker.radius,2)});a.calculateParentRadius();c.nodes.forEach(function(e){e.seriesIndex===a.index&&(d=!0)});c.setArea(0,0,b.plotWidth,b.plotHeight);d||(m||(m=(new l).init(this,
{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(m.plotX=a.parentNode.plotX,m.plotY=a.parentNode.plotY),a.parentNode=m,c.addElementsToCollection([a],c.series),c.addElementsToCollection([m],c.nodes))},drawTracker:function(){var a=this.parentNode;b.TrackerMixin.drawTrackerPoint.call(this);if(a){var c=A(a.dataLabels)?a.dataLabels:a.dataLabel?[a.dataLabel]:[];a.graphic&&
(a.graphic.element.point=a);c.forEach(function(e){e.div?e.div.point=a:e.element.point=a})}},addSeriesLayout:function(){var a=this.options.layoutAlgorithm,c=this.chart.graphLayoutsStorage,d=this.chart.graphLayoutsLookup,t=B(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});var m=c[a.type+"-series"];m||(c[a.type+"-series"]=m=new b.layouts[a.type],m.init(t),d.splice(m.index,0,m));this.parentNodeLayout=m;this.createParentNodes()},addLayout:function(){var a=this.options.layoutAlgorithm,
c=this.chart.graphLayoutsStorage,r=this.chart.graphLayoutsLookup,t=this.chart.options.chart;c||(this.chart.graphLayoutsStorage=c={},this.chart.graphLayoutsLookup=r=[]);var m=c[a.type];m||(a.enableSimulation=d(t.forExport)?!t.forExport:a.enableSimulation,c[a.type]=m=new b.layouts[a.type],m.init(a),r.splice(m.index,0,m));this.layout=m;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=1});m.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);m.addElementsToCollection([this],m.series);
m.addElementsToCollection(this.points,m.nodes)},deferLayout:function(){var a=this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())},translate:function(){var a=this.chart,b=this.data,c=this.index,t,m=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();d(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());if(m)var l=a.allDataPoints;else l=this.placeBubbles(a.allDataPoints),this.options.draggable=
!1;for(t=0;t<l.length;t++)if(l[t][3]===c){var g=b[l[t][4]];var h=l[t][2];m||(g.plotX=l[t][0]-a.plotLeft+a.diffX,g.plotY=l[t][1]-a.plotTop+a.diffY);g.marker=u(g.marker,{radius:h,width:2*h,height:2*h});g.radius=h}m&&this.deferLayout();w(this,"afterTranslate")},checkOverlap:function(a,b){var e=a[0]-b[0],c=a[1]-b[1];return-.001>Math.sqrt(e*e+c*c)-Math.abs(a[2]+b[2])},positionBubble:function(a,b,c){var e=Math.sqrt,f=Math.asin,d=Math.acos,r=Math.pow,g=Math.abs;e=e(r(a[0]-b[0],2)+r(a[1]-b[1],2));d=d((r(e,
2)+r(c[2]+b[2],2)-r(c[2]+a[2],2))/(2*(c[2]+b[2])*e));f=f(g(a[0]-b[0])/e);a=(0>a[1]-b[1]?0:Math.PI)+d+f*(0>(a[0]-b[0])*(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]},placeBubbles:function(a){var b=this.checkOverlap,c=this.positionBubble,e=[],d=1,l=0,g=0;var h=[];var k;a=a.sort(function(a,b){return b[2]-a[2]});if(a.length){e.push([[0,0,a[0][2],a[0][3],a[0][4]]]);if(1<a.length)for(e.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),k=2;k<a.length;k++)a[k][2]=
a[k][2]||1,h=c(e[d][l],e[d-1][g],a[k]),b(h,e[d][0])?(e.push([]),g=0,e[d+1].push(c(e[d][l],e[d][0],a[k])),d++,l=0):1<d&&e[d-1][g+1]&&b(h,e[d-1][g+1])?(g++,e[d].push(c(e[d][l],e[d-1][g],a[k])),l++):(l++,e[d].push(h));this.chart.stages=e;this.chart.rawPositions=[].concat.apply([],e);this.resizeRadius();h=this.chart.rawPositions}return h},resizeRadius:function(){var a=this.chart,b=a.rawPositions,c=Math.min,d=Math.max,g=a.plotLeft,l=a.plotTop,h=a.plotHeight,k=a.plotWidth,n,q,p;var u=n=Number.POSITIVE_INFINITY;
var v=q=Number.NEGATIVE_INFINITY;for(p=0;p<b.length;p++){var w=b[p][2];u=c(u,b[p][0]-w);v=d(v,b[p][0]+w);n=c(n,b[p][1]-w);q=d(q,b[p][1]+w)}p=[v-u,q-n];c=c.apply([],[(k-g)/p[0],(h-l)/p[1]]);if(1e-10<Math.abs(c-1)){for(p=0;p<b.length;p++)b[p][2]*=c;this.placeBubbles(b)}else a.diffY=h/2+l-n-(q-n)/2,a.diffX=k/2+g-u-(v-u)/2},calculateZExtremes:function(){var a=this.options.zMin,b=this.options.zMax,c=Infinity,g=-Infinity;if(a&&b)return[a,b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){d(a)&&
(a>g&&(g=a),a<c&&(c=a))})});a=v(a,c);b=v(b,g);return[a,b]},getPointRadius:function(){var a=this,b=a.chart,c=a.options,d=c.useSimulation,g=Math.min(b.plotWidth,b.plotHeight),l={},h=[],k=b.allDataPoints,n,p,q,u;["minSize","maxSize"].forEach(function(a){var b=parseInt(c[a],10),e=/%$/.test(c[a]);l[a]=e?g*b/100:b*Math.sqrt(k.length)});b.minRadius=n=l.minSize/Math.sqrt(k.length);b.maxRadius=p=l.maxSize/Math.sqrt(k.length);var v=d?a.calculateZExtremes():[n,p];(k||[]).forEach(function(b,c){q=d?D(b[2],v[0],
v[1]):b[2];u=a.getRadius(v[0],v[1],n,p,q);0===u&&(u=null);k[c][2]=u;h.push(u)});a.radii=h},redrawHalo:q.redrawHalo,onMouseDown:q.onMouseDown,onMouseMove:q.onMouseMove,onMouseUp:function(a){if(a.fixedPosition&&!a.removed){var b,c,e=this.layout,d=this.parentNodeLayout;d&&e.options.dragBetweenSeries&&d.nodes.forEach(function(d){a&&a.marker&&d!==a.series.parentNode&&(b=e.getDistXY(a,d),c=e.vectorLength(b)-d.marker.radius-a.marker.radius,0>c&&(d.series.addPoint(B(a.options,{plotX:a.plotX,plotY:a.plotY}),
!1),e.removeElementFromCollection(a,e.nodes),a.remove()))});q.onMouseUp.apply(this,arguments)}},destroy:function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,a.series)},this);this.parentNode&&(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));g.prototype.destroy.apply(this,arguments)},alignDataLabel:g.prototype.alignDataLabel},
{destroy:function(){this.series.layout&&this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return n.prototype.destroy.apply(this,arguments)},firePointEvent:function(a,b,c){var e=this.series.options;if(this.isParentNode&&e.parentNode){var d=e.allowPointSelect;e.allowPointSelect=e.parentNode.allowPointSelect;n.prototype.firePointEvent.apply(this,arguments);e.allowPointSelect=d}else n.prototype.firePointEvent.apply(this,arguments)},select:function(b,c){var e=this.series.chart;
this.isParentNode?(e.getSelectedPoints=e.getSelectedParentNodes,n.prototype.select.apply(this,arguments),e.getSelectedPoints=a.prototype.getSelectedPoints):n.prototype.select.apply(this,arguments)}});C(a,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints});""});E(c,"Extensions/Polar.js",[c["Core/Animation/AnimationUtilities.js"],c["Core/Series/Series.js"],c["Core/Chart/Chart.js"],c["Core/Globals.js"],c["Series/Line/LineSeries.js"],c["Extensions/Pane.js"],c["Core/Pointer.js"],
c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Utilities.js"]],function(c,a,k,b,g,n,p,z,C){var D=c.animObject;a=a.seriesTypes;var d=C.addEvent,u=C.defined,w=C.find,A=C.isNumber,y=C.pick,B=C.splat,v=C.uniqueKey;c=C.wrap;var h=g.prototype;p=p.prototype;h.searchPointByAngle=function(a){var b=this.chart,c=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-c[0]-b.plotLeft,a.chartY-c[1]-b.plotTop)})};h.getConnectors=function(a,b,c,e){var d=e?1:0;var f=0<=b&&b<=
a.length-1?b:0>b?a.length-1+b:0;b=0>f-1?a.length-(1+d):f-1;d=f+1>a.length-1?d:f+1;var g=a[b];d=a[d];var r=g.plotX;g=g.plotY;var h=d.plotX;var m=d.plotY;d=a[f].plotX;f=a[f].plotY;r=(1.5*d+r)/2.5;g=(1.5*f+g)/2.5;h=(1.5*d+h)/2.5;var k=(1.5*f+m)/2.5;m=Math.sqrt(Math.pow(r-d,2)+Math.pow(g-f,2));var t=Math.sqrt(Math.pow(h-d,2)+Math.pow(k-f,2));r=Math.atan2(g-f,r-d);k=Math.PI/2+(r+Math.atan2(k-f,h-d))/2;Math.abs(r-k)>Math.PI/2&&(k-=Math.PI);r=d+Math.cos(k)*m;g=f+Math.sin(k)*m;h=d+Math.cos(Math.PI+k)*t;k=
f+Math.sin(Math.PI+k)*t;d={rightContX:h,rightContY:k,leftContX:r,leftContY:g,plotX:d,plotY:f};c&&(d.prevPointCont=this.getConnectors(a,b,!1,e));return d};h.toXY=function(a){var b=this.chart,c=this.xAxis;var d=this.yAxis;var e=a.plotX,f=a.plotY,g=a.series,h=b.inverted,k=a.y,n=h?e:d.len-f;h&&g&&!g.isRadialBar&&(a.plotY=f="number"===typeof k?d.translate(k)||0:0);a.rectPlotX=e;a.rectPlotY=f;d.center&&(n+=d.center[3]/2);d=h?d.postTranslate(f,n):c.postTranslate(e,n);a.plotX=a.polarPlotX=d.x-b.plotLeft;
a.plotY=a.polarPlotY=d.y-b.plotTop;this.kdByAngle?(b=(e/Math.PI*180+c.pane.options.startAngle)%360,0>b&&(b+=360),a.clientX=b):a.clientX=a.plotX};a.spline&&(c(a.spline.prototype,"getPointSpline",function(a,b,c,d){this.chart.polar?d?(a=this.getConnectors(b,d,!0,this.connectEnds),a=["C",a.prevPointCont.rightContX,a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",c.plotX,c.plotY]:a=a.call(this,b,c,d);return a}),a.areasplinerange&&(a.areasplinerange.prototype.getPointSpline=a.spline.prototype.getPointSpline));
d(g,"afterTranslate",function(){var a=this.chart;if(a.polar&&this.xAxis){(this.kdByAngle=a.tooltip&&a.tooltip.shared)?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(var c=this.points,e=c.length;e--;)this.toXY(c[e]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&c[e].y<this.yAxis.min&&(c[e].isNull=!0);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!this.eventsToUnbind.push(d(this,"afterRender",function(){if(a.polar){var c=this.yAxis.pane.center;
this.clipCircle?this.clipCircle.animate({x:c[0],y:c[1],r:c[2]/2,innerR:c[3]/2}):this.clipCircle=a.renderer.clipCircle(c[0],c[1],c[2]/2,c[3]/2);this.group.clip(this.clipCircle);this.setClip=b.noop}})))}},{order:2});c(h,"getGraphPath",function(a,b){var c=this,d;if(this.chart.polar){b=b||this.points;for(d=0;d<b.length;d++)if(!b[d].isNull){var e=d;break}if(!1!==this.options.connectEnds&&"undefined"!==typeof e){this.connectEnds=!0;b.splice(b.length,0,b[e]);var f=!0}b.forEach(function(a){"undefined"===
typeof a.polarPlotY&&c.toXY(a)})}d=a.apply(this,[].slice.call(arguments,1));f&&b.pop();return d});var q=function(a,c){var d=this,e=this.chart,f=this.options.animation,g=this.group,h=this.markerGroup,k=this.xAxis.center,r=e.plotLeft,n=e.plotTop,p,q,u,v;if(e.polar)if(d.isRadialBar)c||(d.startAngleRad=y(d.translatedThreshold,d.xAxis.startAngleRad),b.seriesTypes.pie.prototype.animate.call(d,c));else{if(e.renderer.isSVG)if(f=D(f),d.is("column")){if(!c){var w=k[3]/2;d.points.forEach(function(a){p=a.graphic;
u=(q=a.shapeArgs)&&q.r;v=q&&q.innerR;p&&q&&(p.attr({r:w,innerR:w}),p.animate({r:u,innerR:v},d.options.animation))})}}else c?(a={translateX:k[0]+r,translateY:k[1]+n,scaleX:.001,scaleY:.001},g.attr(a),h&&h.attr(a)):(a={translateX:r,translateY:n,scaleX:1,scaleY:1},g.animate(a,f),h&&h.animate(a,f))}else a.call(this,c)};c(h,"animate",q);if(a.column){var e=a.arearange.prototype;a=a.column.prototype;a.polarArc=function(a,b,c,d){var e=this.xAxis.center,f=this.yAxis.len,g=e[3]/2;b=f-b+g;a=f-y(a,f)+g;this.yAxis.reversed&&
(0>b&&(b=g),0>a&&(a=g));return{x:e[0],y:e[1],r:b,innerR:a,start:c,end:d}};c(a,"animate",q);c(a,"translate",function(a){var b=this.options,c=b.stacking,d=this.chart,e=this.xAxis,f=this.yAxis,g=f.reversed,h=f.center,k=e.startAngleRad,n=e.endAngleRad-k;this.preventPostTranslate=!0;a.call(this);if(e.isRadial){a=this.points;e=a.length;var p=f.translate(f.min);var q=f.translate(f.max);b=b.threshold||0;if(d.inverted&&A(b)){var v=f.translate(b);u(v)&&(0>v?v=0:v>n&&(v=n),this.translatedThreshold=v+k)}for(;e--;){b=
a[e];var w=b.barX;var z=b.x;var D=b.y;b.shapeType="arc";if(d.inverted){b.plotY=f.translate(D);if(c&&f.stacking){if(D=f.stacking.stacks[(0>D?"-":"")+this.stackKey],this.visible&&D&&D[z]&&!b.isNull){var y=D[z].points[this.getStackIndicator(void 0,z,this.index).key];var B=f.translate(y[0]);y=f.translate(y[1]);u(B)&&(B=C.clamp(B,0,n))}}else B=v,y=b.plotY;B>y&&(y=[B,B=y][0]);if(!g)if(B<p)B=p;else if(y>q)y=q;else{if(y<p||B>q)B=y=0}else if(y>p)y=p;else if(B<q)B=q;else if(B>p||y<q)B=y=n;f.min>f.max&&(B=y=
g?n:0);B+=k;y+=k;h&&(b.barX=w+=h[3]/2);z=Math.max(w,0);D=Math.max(w+b.pointWidth,0);b.shapeArgs={x:h&&h[0],y:h&&h[1],r:D,innerR:z,start:B,end:y};b.opacity=B===y?0:void 0;b.plotY=(u(this.translatedThreshold)&&(B<this.translatedThreshold?B:y))-k}else B=w+k,b.shapeArgs=this.polarArc(b.yBottom,b.plotY,B,B+b.pointWidth);this.toXY(b);d.inverted?(w=f.postTranslate(b.rectPlotY,w+b.pointWidth/2),b.tooltipPos=[w.x-d.plotLeft,w.y-d.plotTop]):b.tooltipPos=[b.plotX,b.plotY];h&&(b.ttBelow=b.plotY>h[1])}}});a.findAlignments=
function(a,b){null===b.align&&(b.align=20<a&&160>a?"left":200<a&&340>a?"right":"center");null===b.verticalAlign&&(b.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle");return b};e&&(e.findAlignments=a.findAlignments);c(a,"alignDataLabel",function(a,b,c,d,e,g){var f=this.chart,k=y(d.inside,!!this.options.stacking);f.polar?(a=b.rectPlotX/Math.PI*180,f.inverted?(this.forceDL=f.isInsidePlot(b.plotX,Math.round(b.plotY),!1),k&&b.shapeArgs?(e=b.shapeArgs,e=this.yAxis.postTranslate((e.start+e.end)/
2-this.xAxis.startAngleRad,b.barX+b.pointWidth/2),e={x:e.x-f.plotLeft,y:e.y-f.plotTop}):b.tooltipPos&&(e={x:b.tooltipPos[0],y:b.tooltipPos[1]}),d.align=y(d.align,"center"),d.verticalAlign=y(d.verticalAlign,"middle")):this.findAlignments&&(d=this.findAlignments(a,d)),h.alignDataLabel.call(this,b,c,d,e,g),this.isRadialBar&&b.shapeArgs&&b.shapeArgs.start===b.shapeArgs.end&&c.hide(!0)):a.call(this,b,c,d,e,g)})}c(p,"getCoordinates",function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var e=
a.isXAxis,f=a.center;if("colorAxis"!==a.coll){var g=b.chartX-f[0]-c.plotLeft;f=b.chartY-f[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(g,f):Math.sqrt(Math.pow(g,2)+Math.pow(f,2)),!0)})}}):d=a.call(this,b);return d});z.prototype.clipCircle=function(a,b,c,d){var e=v(),f=this.createElement("clipPath").attr({id:e}).add(this.defs);a=d?this.arc(a,b,c,d,0,2*Math.PI).add(f):this.circle(a,b,c).add(f);a.id=e;a.clipPath=f;return a};d(k,"getAxes",function(){this.pane||
(this.pane=[]);B(this.options.pane).forEach(function(a){new n(a,this)},this)});d(k,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});d(g,"afterInit",function(){var a=this.chart;a.inverted&&a.polar&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0))});c(k.prototype,"get",function(a,b){return w(this.pane,function(a){return a.options.id===b})||a.call(this,b)})});E(c,"masters/highcharts-more.src.js",[],function(){})});
//# sourceMappingURL=highcharts-more.js.map