/*
 Highstock JS v8.2.2 (2020-11-05)

 Indicator series type for Highstock

 (c) 2010-2019 Pawel Fus, Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators",["highcharts","highcharts/modules/stock"],function(e){a(e);a.Highcharts=e;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function e(a,g,p,f){a.hasOwnProperty(g)||(a[g]=f.apply(null,p))}a=a?a._modules:{};e(a,"Mixins/IndicatorRequired.js",[a["Core/Utilities.js"]],function(a){var g=a.error;return{isParentLoaded:function(a,
f,e,k,l){if(a)return k?k(a):!0;g(l||this.generateMessage(e,f));return!1},generateMessage:function(a,f){return'Error: "'+a+'" indicator type requires "'+f+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+a}}});e(a,"Stock/Indicators/SMAIndicator.js",[a["Core/Series/Series.js"],a["Series/Line/LineSeries.js"],a["Mixins/IndicatorRequired.js"],a["Core/Utilities.js"]],function(a,g,e,f){var q=a.seriesTypes,k=f.addEvent,l=f.error,p=f.extend,r=f.isArray,t=f.pick,
u=f.splat,m=q.ohlc.prototype,v=e.generateMessage;k(g,"init",function(c){c=c.options;c.useOhlcData&&"highcharts-navigator-series"!==c.id&&p(this,{pointValKey:m.pointValKey,keys:m.keys,pointArrayMap:m.pointArrayMap,toYData:m.toYData})});k(g,"afterSetOptions",function(c){c=c.options;var a=c.dataGrouping;a&&c.useOhlcData&&"highcharts-navigator-series"!==c.id&&(a.approximation="ohlc")});a.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}},
{processData:function(){var c=this.options.compareToMain,a=this.linkedParent;g.prototype.processData.apply(this,arguments);a&&a.compareValue&&c&&(this.compareValue=a.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(c){q[c]?q[c].prototype.requireIndicators():(a.allLoaded=!1,a.needed=
c)});return a},init:function(a,d){function c(){var a=b.points||[],c=(b.xData||[]).length,d=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},f=[],e=!0;if(c&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){if(b.xAxis){var h=b.xAxis.min;var g=b.xAxis.max}c=b.cropData(d.xData,d.yData,h,g);for(h=0;h<c.xData.length;h++)f.push([c.xData[h]].concat(u(c.yData[h])));c=d.xData.indexOf(b.xData[0]);h=d.xData.indexOf(b.xData[b.xData.length-1]);-1===c&&h===d.xData.length-2&&f[0][0]===
a[0].x&&f.shift();b.updateData(f)}else d.xData.length!==c-1&&d.xData.length!==c+1&&(e=!1,b.updateData(d.values));e&&(b.xData=d.xData,b.yData=d.yData,b.options.data=d.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,f=b.requireIndicators();if(!f.allLoaded)return l(v(b.type,f.needed));g.prototype.init.call(b,a,d);a.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return l("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",!1,
a);b.dataEventsToUnbind.push(k(b.bindTo.series?b.linkedParent:b.linkedParent.xAxis,b.bindTo.eventName,c));if("init"===b.calculateOn)c();else var e=k(b.chart,b.calculateOn,function(){c();e()});return b},getName:function(){var a=this.name,d=[];a||((this.nameComponents||[]).forEach(function(a,b){d.push(this.options.params[a]+t(this.nameSuffixes[b],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+d.join(", ")+")":""));return a},getValues:function(a,d){var c=d.period,b=
a.xData;a=a.yData;var f=a.length,e=0,g=0,k=[],l=[],m=[],n=-1;if(!(b.length<c)){for(r(a[0])&&(n=d.index?d.index:0);e<c-1;)g+=0>n?a[e]:a[e][n],e++;for(d=e;d<f;d++){g+=0>n?a[d]:a[d][n];var h=[b[d],g/c];k.push(h);l.push(h[0]);m.push(h[1]);g-=0>n?a[d-e]:a[d-e][n]}return{values:k,xData:l,yData:m}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});g.prototype.destroy.apply(this,arguments)}});""});e(a,"masters/indicators/indicators.src.js",[],function(){})});
//# sourceMappingURL=indicators.js.map