/*
 Highstock JS v8.2.2 (2020-11-05)

 All technical indicators for Highstock

 (c) 2010-2019 Pawel Fus

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators-all",["highcharts","highcharts/modules/stock"],function(w){b(w);b.Highcharts=w;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function w(b,g,h,k){b.hasOwnProperty(g)||(b[g]=k.apply(null,h))}b=b?b._modules:{};w(b,"Mixins/IndicatorRequired.js",[b["Core/Utilities.js"]],function(b){var g=b.error;return{isParentLoaded:function(b,
k,e,c,a){if(b)return c?c(b):!0;g(a||this.generateMessage(e,k));return!1},generateMessage:function(b,k){return'Error: "'+b+'" indicator type requires "'+k+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+b}}});w(b,"Stock/Indicators/SMAIndicator.js",[b["Core/Series/Series.js"],b["Series/Line/LineSeries.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h,k){var e=b.seriesTypes,c=k.addEvent,a=k.error,d=k.extend,f=k.isArray,m=k.pick,
t=k.splat,p=e.ohlc.prototype,u=h.generateMessage;c(g,"init",function(a){a=a.options;a.useOhlcData&&"highcharts-navigator-series"!==a.id&&d(this,{pointValKey:p.pointValKey,keys:p.keys,pointArrayMap:p.pointArrayMap,toYData:p.toYData})});c(g,"afterSetOptions",function(a){a=a.options;var d=a.dataGrouping;d&&a.useOhlcData&&"highcharts-navigator-series"!==a.id&&(d.approximation="ohlc")});b.seriesType("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}},
{processData:function(){var a=this.options.compareToMain,d=this.linkedParent;g.prototype.processData.apply(this,arguments);d&&d.compareValue&&a&&(this.compareValue=d.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(d){e[d]?e[d].prototype.requireIndicators():(a.allLoaded=!1,a.needed=
d)});return a},init:function(d,f){function m(){var a=n.points||[],d=(n.xData||[]).length,c=n.getValues(n.linkedParent,n.options.params)||{values:[],xData:[],yData:[]},f=[],m=!0;if(d&&!n.hasGroupedData&&n.visible&&n.points)if(n.cropped){if(n.xAxis){var e=n.xAxis.min;var p=n.xAxis.max}d=n.cropData(c.xData,c.yData,e,p);for(e=0;e<d.xData.length;e++)f.push([d.xData[e]].concat(t(d.yData[e])));d=c.xData.indexOf(n.xData[0]);e=c.xData.indexOf(n.xData[n.xData.length-1]);-1===d&&e===c.xData.length-2&&f[0][0]===
a[0].x&&f.shift();n.updateData(f)}else c.xData.length!==d-1&&c.xData.length!==d+1&&(m=!1,n.updateData(c.values));m&&(n.xData=c.xData,n.yData=c.yData,n.options.data=c.values);!1===n.bindTo.series&&(delete n.processedXData,n.isDirty=!0,n.redraw());n.isDirtyData=!1}var n=this,e=n.requireIndicators();if(!e.allLoaded)return a(u(n.type,e.needed));g.prototype.init.call(n,d,f);d.linkSeries();n.dataEventsToUnbind=[];if(!n.linkedParent)return a("Series "+n.options.linkedTo+" not found! Check `linkedTo`.",!1,
d);n.dataEventsToUnbind.push(c(n.bindTo.series?n.linkedParent:n.linkedParent.xAxis,n.bindTo.eventName,m));if("init"===n.calculateOn)m();else var p=c(n.chart,n.calculateOn,function(){m();p()});return n},getName:function(){var a=this.name,d=[];a||((this.nameComponents||[]).forEach(function(a,c){d.push(this.options.params[a]+m(this.nameSuffixes[c],""))},this),a=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+d.join(", ")+")":""));return a},getValues:function(a,d){var c=d.period,n=
a.xData;a=a.yData;var m=a.length,e=0,t=0,p=[],k=[],u=[],r=-1;if(!(n.length<c)){for(f(a[0])&&(r=d.index?d.index:0);e<c-1;)t+=0>r?a[e]:a[e][r],e++;for(d=e;d<m;d++){t+=0>r?a[d]:a[d][r];var q=[n[d],t/c];p.push(q);k.push(q[0]);u.push(q[1]);t-=0>r?a[d-e]:a[d-e][r]}return{values:p,xData:k,yData:u}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});g.prototype.destroy.apply(this,arguments)}});""});w(b,"Stock/Indicators/ADIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],
function(b,g){var h=g.error;b.seriesType("ad","sma",{params:{volumeSeriesID:"volume"}},{nameComponents:!1,nameBase:"Accumulation/Distribution",getValues:function(k,e){var c=e.period,a=k.xData,d=k.yData,f=e.volumeSeriesID,m=k.chart.get(f);e=m&&m.yData;var t=d?d.length:0,p=[],u=[],r=[];if(!(a.length<=c&&t&&4!==d[0].length)){if(m){for(;c<t;c++){k=p.length;f=d[c][1];m=d[c][2];var q=d[c][3],l=e[c];f=[a[c],q===f&&q===m||f===m?0:(2*q-m-f)/(f-m)*l];0<k&&(f[1]+=p[k-1][1]);p.push(f);u.push(f[0]);r.push(f[1])}return{values:p,
xData:u,yData:r}}h("Series "+f+" not found! Check `volumeSeriesID`.",!0,k.chart)}}});""});w(b,"Stock/Indicators/AOIndicator.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,g,h){var k=h.correctFloat,e=h.isArray;b.seriesType("ao","sma",{greaterBarColor:"#06B535",lowerBarColor:"#F21313",threshold:0,groupPadding:.2,pointPadding:.2,crisp:!1,states:{hover:{halo:{size:0}}}},{nameBase:"AO",nameComponents:!1,markerAttribs:g.noop,getColumnMetrics:g.seriesTypes.column.prototype.getColumnMetrics,
crispCol:g.seriesTypes.column.prototype.crispCol,translate:g.seriesTypes.column.prototype.translate,drawPoints:g.seriesTypes.column.prototype.drawPoints,drawGraph:function(){var c=this.options,a=this.points,d=c.greaterBarColor;c=c.lowerBarColor;var f=a[0];if(!this.userOptions.color&&f)for(f.color=d,f=1;f<a.length;f++)a[f].color=a[f].y>a[f-1].y?d:a[f].y<a[f-1].y?c:a[f-1].color},getValues:function(c){var a=c.xData||[];c=c.yData||[];var d=c.length,f=[],m=[],t=[],p=0,u=0,r;if(!(34>=a.length)&&e(c[0])&&
4===c[0].length){for(r=0;33>r;r++){var q=(c[r][1]+c[r][2])/2;29<=r&&(p=k(p+q));u=k(u+q)}for(r=33;r<d;r++){q=(c[r][1]+c[r][2])/2;p=k(p+q);u=k(u+q);q=p/5;var l=u/34;q=k(q-l);f.push([a[r],q]);m.push(a[r]);t.push(q);q=r+1-5;l=r+1-34;p=k(p-(c[q][1]+c[q][2])/2);u=k(u-(c[l][1]+c[l][2])/2)}return{values:f,xData:m,yData:t}}}});""});w(b,"Mixins/MultipleLines.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,g){var h=g.defined,k=g.error,e=g.merge,c=b.seriesTypes.sma;return{pointArrayMap:["top","bottom"],
pointValKey:"top",linesApiNames:["bottomLine"],getTranslatedLinesNames:function(a){var d=[];(this.pointArrayMap||[]).forEach(function(c){c!==a&&d.push("plot"+c.charAt(0).toUpperCase()+c.slice(1))});return d},toYData:function(a){var d=[];(this.pointArrayMap||[]).forEach(function(c){d.push(a[c])});return d},translate:function(){var a=this,d=a.pointArrayMap,f=[],m;f=a.getTranslatedLinesNames();c.prototype.translate.apply(a,arguments);a.points.forEach(function(c){d.forEach(function(d,e){m=c[d];null!==
m&&(c[f[e]]=a.yAxis.toPixels(m,!0))})})},drawGraph:function(){var a=this,d=a.linesApiNames,f=a.points,m=f.length,t=a.options,p=a.graph,u={options:{gapSize:t.gapSize}},r=[],q;a.getTranslatedLinesNames(a.pointValKey).forEach(function(a,d){for(r[d]=[];m--;)q=f[m],r[d].push({x:q.x,plotX:q.plotX,plotY:q[a],isNull:!h(q[a])});m=f.length});d.forEach(function(d,n){r[n]?(a.points=r[n],t[d]?a.options=e(t[d].styles,u):k('Error: "There is no '+d+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),
a.graph=a["graph"+d],c.prototype.drawGraph.call(a),a["graph"+d]=a.graph):k('Error: "'+d+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=f;a.options=t;a.graph=p;c.prototype.drawGraph.call(a)}}});w(b,"Stock/Indicators/AroonIndicator.js",[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Core/Utilities.js"]],function(b,g,h){function k(a,d){var c=a[0],m=0,e;for(e=1;e<a.length;e++)if("max"===d&&a[e]>=c||"min"===d&&a[e]<=c)c=
a[e],m=e;return m}var e=h.merge,c=h.pick;b.seriesType("aroon","sma",{params:{period:25},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Aroon Up: {point.y}<br/>Aroon Down: {point.aroonDown}<br/>'},aroonDown:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},e(g,{nameBase:"Aroon",pointArrayMap:["y","aroonDown"],pointValKey:"y",linesApiNames:["aroonDown"],getValues:function(a,d){d=d.period;var f=a.xData,
m=(a=a.yData)?a.length:0,e=[],p=[],u=[],r;for(r=d-1;r<m;r++){var q=a.slice(r-d+1,r+2);var l=k(q.map(function(a){return c(a[2],a)}),"min");q=k(q.map(function(a){return c(a[1],a)}),"max");q=q/d*100;l=l/d*100;f[r+1]&&(e.push([f[r+1],q,l]),p.push(f[r+1]),u.push([q,l]))}return{values:e,xData:p,yData:u}}}));""});w(b,"Stock/Indicators/AroonOscillatorIndicator.js",[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h,k){k=k.merge;
var e=b.seriesTypes.aroon;b.seriesType("aroonoscillator","aroon",{params:{period:25},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b>: {point.y}'}},k(g,{nameBase:"Aroon Oscillator",pointArrayMap:["y"],pointValKey:"y",linesApiNames:[],init:function(){var c=arguments,a=this;h.isParentLoaded(e,"aroon",a.type,function(d){d.prototype.init.apply(a,c)})},getValues:function(c,a){var d=[],f=[],m=[];c=e.prototype.getValues.call(this,c,a);for(a=0;a<c.yData.length;a++){var t=
c.yData[a][0];var p=c.yData[a][1];t-=p;d.push([c.xData[a],t]);f.push(c.xData[a]);m.push(t)}return{values:d,xData:f,yData:m}}}));""});w(b,"Stock/Indicators/ATRIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){function h(e,c){return Math.max(e[1]-e[2],"undefined"===typeof c?0:Math.abs(e[1]-c[3]),"undefined"===typeof c?0:Math.abs(e[2]-c[3]))}var k=g.isArray;b.seriesType("atr","sma",{params:{period:14}},{getValues:function(e,c){c=c.period;var a=e.xData,d=(e=e.yData)?e.length:
0,f=1,m=0,t=0,p=[],u=[],r=[],q;var l=[[a[0],e[0]]];if(!(a.length<=c)&&k(e[0])&&4===e[0].length){for(q=1;q<=d;q++)if(l.push([a[q],e[q]]),c<f){var n=c;var v=a[q-1],b=h(e[q-1],e[q-2]);n=[v,(m*(n-1)+b)/n];m=n[1];p.push(n);u.push(n[0]);r.push(n[1])}else c===f?(m=t/(q-1),p.push([a[q-1],m]),u.push(a[q-1]),r.push(m)):t+=h(e[q-1],e[q-2]),f++;return{values:p,xData:u,yData:r}}}});""});w(b,"Stock/Indicators/BBIndicator.js",[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Core/Utilities.js"]],function(b,
g,h){var k=h.isArray,e=h.merge,c=b.seriesTypes.sma;b.seriesType("bb","sma",{params:{period:20,standardDeviation:2,index:3},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"}},e(g,{pointArrayMap:["top","middle","bottom"],
pointValKey:"middle",nameComponents:["period","standardDeviation"],linesApiNames:["topLine","bottomLine"],init:function(){c.prototype.init.apply(this,arguments);this.options=e({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(a,d){var f=d.period,m=d.standardDeviation,e=a.xData,p=(a=a.yData)?a.length:0,u=[],r=[],q=[],l;if(!(e.length<f)){var n=k(a[0]);for(l=f;l<=p;l++){var v=e.slice(l-f,l);var b=a.slice(l-f,l);var g=c.prototype.getValues.call(this,
{xData:v,yData:b},d);v=g.xData[0];g=g.yData[0];for(var h=0,y=b.length,z=0;z<y;z++){var x=(n?b[z][d.index]:b[z])-g;h+=x*x}x=Math.sqrt(h/(y-1));b=g+m*x;x=g-m*x;u.push([v,b,g,x]);r.push(v);q.push([b,g,x])}return{values:u,xData:r,yData:q}}}}));""});w(b,"Stock/Indicators/CCIIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){function h(e){return e.reduce(function(c,a){return c+a},0)}var k=g.isArray;b.seriesType("cci","sma",{params:{period:14}},{getValues:function(e,c){c=c.period;
var a=e.xData,d=(e=e.yData)?e.length:0,f=[],m=1,t=[],p=[],u=[];if(!(a.length<=c)&&k(e[0])&&4===e[0].length){for(;m<c;){var r=e[m-1];f.push((r[1]+r[2]+r[3])/3);m++}for(m=c;m<=d;m++){r=e[m-1];r=(r[1]+r[2]+r[3])/3;var q=f.push(r);var l=f.slice(q-c);q=h(l)/c;var n,v=l.length,b=0;for(n=0;n<v;n++)b+=Math.abs(q-l[n]);l=b/c;r=(r-q)/(.015*l);t.push([a[m-1],r]);p.push(a[m-1]);u.push(r)}return{values:t,xData:p,yData:u}}}});""});w(b,"Stock/Indicators/CMFIndicator.js",[b["Core/Series/Series.js"]],function(b){b.seriesType("cmf",
"sma",{params:{period:14,volumeSeriesID:"volume"}},{nameBase:"Chaikin Money Flow",isValid:function(){var b=this.chart,h=this.options,k=this.linkedParent;b=this.volumeSeries||(this.volumeSeries=b.get(h.params.volumeSeriesID));var e=k&&k.yData&&4===k.yData[0].length;return!!(k&&b&&k.xData&&k.xData.length>=h.params.period&&b.xData&&b.xData.length>=h.params.period&&e)},getValues:function(b,h){if(this.isValid())return this.getMoneyFlow(b.xData,b.yData,this.volumeSeries.yData,h.period)},getMoneyFlow:function(b,
h,k,e){function c(a,d){var c=a[1],f=a[2];a=a[3];return null!==d&&null!==c&&null!==f&&null!==a&&c!==f?(a-f-(c-a))/(c-f)*d:(q=r,null)}var a=h.length,d=[],f=0,m=0,t=[],p=[],u=[],r,q=-1;if(0<e&&e<=a){for(r=0;r<e;r++)d[r]=c(h[r],k[r]),f+=k[r],m+=d[r];t.push(b[r-1]);p.push(r-q>=e&&0!==f?m/f:null);for(u.push([t[0],p[0]]);r<a;r++){d[r]=c(h[r],k[r]);f-=k[r-e];f+=k[r];m-=d[r-e];m+=d[r];var l=[b[r],r-q>=e?m/f:null];t.push(l[0]);p.push(l[1]);u.push([l[0],l[1]])}}return{values:u,xData:t,yData:p}}});""});w(b,"Stock/Indicators/DPOIndicator.js",
[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){function h(c,a,d,f,m){a=e(a[d][f],a[d]);return m?k(c-a):k(c+a)}var k=g.correctFloat,e=g.pick;b.seriesType("dpo","sma",{params:{period:21}},{nameBase:"DPO",getValues:function(c,a){var d=a.period;a=a.index;var f=d+Math.floor(d/2+1),m=c.xData||[];c=c.yData||[];var t=c.length,p=[],k=[],b=[],q=0,l,n;if(!(m.length<=f)){for(l=0;l<d-1;l++)q=h(q,c,l,a);for(n=0;n<=t-f;n++){var v=n+d-1;l=n+f-1;q=h(q,c,v,a);v=e(c[l][a],c[l]);v-=q/d;q=h(q,c,n,a,
!0);p.push([m[l],v]);k.push(m[l]);b.push(v)}return{values:p,xData:k,yData:b}}}});""});w(b,"Stock/Indicators/EMAIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=g.correctFloat,k=g.isArray;b.seriesType("ema","sma",{params:{index:3,period:9}},{accumulatePeriodPoints:function(e,c,a){for(var d=0,f=0,m;f<e;)m=0>c?a[f]:a[f][c],d+=m,f++;return d},calculateEma:function(e,c,a,d,f,m,t){e=e[a-1];c=0>m?c[a-1]:c[a-1][m];d="undefined"===typeof f?t:h(c*d+f*(1-d));return[e,d]},
getValues:function(e,c){var a=c.period,d=e.xData,f=(e=e.yData)?e.length:0,m=2/(a+1),t=[],p=[],b=[],r=-1;if(!(f<a)){k(e[0])&&(r=c.index?c.index:0);c=this.accumulatePeriodPoints(a,r,e);for(c/=a;a<f+1;a++){var q=this.calculateEma(d,e,a,m,q,r,c);t.push(q);p.push(q[0]);b.push(q[1]);q=q[1]}return{values:t,xData:p,yData:b}}}});""});w(b,"Stock/Indicators/ChaikinIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var k=b.seriesTypes,e=h.correctFloat,
c=h.error,a=k.ema,d=k.ad;b.seriesType("chaikin","ema",{params:{volumeSeriesID:"volume",periods:[3,10]}},{nameBase:"Chaikin Osc",nameComponents:["periods"],init:function(){var d=arguments,c=this;g.isParentLoaded(a,"ema",c.type,function(a){a.prototype.init.apply(c,d)})},getValues:function(f,m){var t=m.periods,p=m.period,b=[],k=[],q=[],l;if(2!==t.length||t[1]<=t[0])c('Error: "Chaikin requires two periods. Notice, first period should be lower than the second one."');else if(m=d.prototype.getValues.call(this,
f,{volumeSeriesID:m.volumeSeriesID,period:p}))if(f=a.prototype.getValues.call(this,m,{period:t[0]}),m=a.prototype.getValues.call(this,m,{period:t[1]}),f&&m){t=t[1]-t[0];for(l=0;l<m.yData.length;l++)p=e(f.yData[l+t]-m.yData[l]),b.push([m.xData[l],p]),k.push(m.xData[l]),q.push(p);return{values:b,xData:k,yData:q}}}});""});w(b,"Stock/Indicators/DEMAIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var k=h.correctFloat,e=h.isArray,c=b.seriesTypes.ema;
b.seriesType("dema","ema",{},{init:function(){var a=arguments,d=this;g.isParentLoaded(c,"ema",d.type,function(c){c.prototype.init.apply(d,a)})},getEMA:function(a,d,f,m,e,p){return c.prototype.calculateEma(p||[],a,"undefined"===typeof e?1:e,this.chart.series[0].EMApercent,d,"undefined"===typeof m?-1:m,f)},getValues:function(a,d){var f=d.period,m=2*f,t=a.xData,p=a.yData,b=p?p.length:0,r=-1,q=[],l=[],n=[],v=0,B=[],g;a.EMApercent=2/(f+1);if(!(b<2*f-1)){e(p[0])&&(r=d.index?d.index:0);a=c.prototype.accumulatePeriodPoints(f,
r,p);d=a/f;a=0;for(g=f;g<b+2;g++){g<b+1&&(v=this.getEMA(p,h,d,r,g)[1],B.push(v));var h=v;if(g<m)a+=v;else{g===m&&(d=a/f);v=B[g-f-1];var y=this.getEMA([v],y,d)[1];var z=[t[g-2],k(2*v-y)];q.push(z);l.push(z[0]);n.push(z[1])}}return{values:q,xData:l,yData:n}}}});""});w(b,"Stock/Indicators/TEMAIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var k=h.correctFloat,e=h.isArray,c=b.seriesTypes.ema;b.seriesType("tema","ema",{},{init:function(){var a=
arguments,d=this;g.isParentLoaded(c,"ema",d.type,function(c){c.prototype.init.apply(d,a)})},getEMA:function(a,d,f,m,e,p){return c.prototype.calculateEma(p||[],a,"undefined"===typeof e?1:e,this.chart.series[0].EMApercent,d,"undefined"===typeof m?-1:m,f)},getTemaPoint:function(a,d,c,m){return[a[m-3],k(3*c.level1-3*c.level2+c.level3)]},getValues:function(a,d){var f=d.period,m=2*f,b=3*f,p=a.xData,k=a.yData,r=k?k.length:0,q=-1,l=[],n=[],v=[],B=[],g=[],h,y,z={};a.EMApercent=2/(f+1);if(!(r<3*f-2)){e(k[0])&&
(q=d.index?d.index:0);a=c.prototype.accumulatePeriodPoints(f,q,k);d=a/f;a=0;for(h=f;h<r+3;h++){h<r+1&&(z.level1=this.getEMA(k,x,d,q,h)[1],B.push(z.level1));var x=z.level1;if(h<m)a+=z.level1;else{h===m&&(d=a/f,a=0);z.level1=B[h-f-1];z.level2=this.getEMA([z.level1],F,d)[1];g.push(z.level2);var F=z.level2;if(h<b)a+=z.level2;else{h===b&&(d=a/f);h===r+1&&(z.level1=B[h-f-1],z.level2=this.getEMA([z.level1],F,d)[1],g.push(z.level2));z.level1=B[h-f-2];z.level2=g[h-2*f-1];z.level3=this.getEMA([z.level2],z.prevLevel3,
d)[1];if(y=this.getTemaPoint(p,b,z,h))l.push(y),n.push(y[0]),v.push(y[1]);z.prevLevel3=z.level3}}}return{values:l,xData:n,yData:v}}}});""});w(b,"Stock/Indicators/TRIXIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var k=h.correctFloat,e=b.seriesTypes.tema;b.seriesType("trix","tema",{},{init:function(){var c=arguments,a=this;g.isParentLoaded(e,"tema",a.type,function(d){d.prototype.init.apply(a,c)})},getTemaPoint:function(c,a,d,f){if(f>
a)var m=[c[f-3],0!==d.prevLevel3?k(d.level3-d.prevLevel3)/d.prevLevel3*100:null];return m}});""});w(b,"Stock/Indicators/APOIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var k=h.error,e=b.seriesTypes.ema;b.seriesType("apo","ema",{params:{periods:[10,20]}},{nameBase:"APO",nameComponents:["periods"],init:function(){var c=arguments,a=this;g.isParentLoaded(e,"ema",a.type,function(d){d.prototype.init.apply(a,c)})},getValues:function(c,
a){var d=a.periods,f=a.index;a=[];var m=[],b=[],p;if(2!==d.length||d[1]<=d[0])k('Error: "APO requires two periods. Notice, first period should be lower than the second one."');else{var u=e.prototype.getValues.call(this,c,{index:f,period:d[0]});c=e.prototype.getValues.call(this,c,{index:f,period:d[1]});if(u&&c){d=d[1]-d[0];for(p=0;p<c.yData.length;p++)f=u.yData[p+d]-c.yData[p],a.push([c.xData[p],f]),m.push(c.xData[p]),b.push(f);return{values:a,xData:m,yData:b}}}}});""});w(b,"Stock/Indicators/IKHIndicator.js",
[b["Core/Series/Series.js"],b["Core/Color/Color.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,g,h,k){function e(a){return a.reduce(function(a,d){return Math.max(a,d[1])},-Infinity)}function c(a){return a.reduce(function(a,d){return Math.min(a,d[2])},Infinity)}function a(a){return{high:e(a),low:c(a)}}function d(a){var d,c,f,n,m;a.series.forEach(function(a){if(a.xData)for(n=a.xData,m=c=a.xIncrement?1:n.length-1;0<m;m--)if(f=n[m]-n[m-1],"undefined"===typeof d||f<d)d=f});return d}function f(a,
d,c,f){if(a&&d&&c&&f){var m=d.plotX-a.plotX;d=d.plotY-a.plotY;var n=f.plotX-c.plotX;f=f.plotY-c.plotY;var e=a.plotX-c.plotX,b=a.plotY-c.plotY;c=(-d*e+m*b)/(-n*d+m*f);n=(n*b-f*e)/(-n*d+m*f);if(0<=c&&1>=c&&0<=n&&1>=n)return{plotX:a.plotX+n*m,plotY:a.plotY+n*d}}return!1}function m(a){var d=a.indicator;d.points=a.points;d.nextPoints=a.nextPoints;d.color=a.color;d.options=r(a.options.senkouSpan.styles,a.gap);d.graph=a.graph;d.fillGraph=!0;l.prototype.drawGraph.call(d)}var t=g.parse,p=k.defined,u=k.isArray,
r=k.merge,q=k.objectEach,l=b.seriesTypes.sma;h.approximations["ichimoku-averages"]=function(){var a=[],d;[].forEach.call(arguments,function(c,f){a.push(h.approximations.average(c));d=!d&&"undefined"===typeof a[f]});return d?void 0:a};b.seriesType("ikh","sma",{params:{period:26,periodTenkan:9,periodSenkouSpanB:52},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>TENKAN SEN: {point.tenkanSen:.3f}<br/>KIJUN SEN: {point.kijunSen:.3f}<br/>CHIKOU SPAN: {point.chikouSpan:.3f}<br/>SENKOU SPAN A: {point.senkouSpanA:.3f}<br/>SENKOU SPAN B: {point.senkouSpanB:.3f}<br/>'},
tenkanLine:{styles:{lineWidth:1,lineColor:void 0}},kijunLine:{styles:{lineWidth:1,lineColor:void 0}},chikouLine:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanA:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanB:{styles:{lineWidth:1,lineColor:void 0}},senkouSpan:{styles:{fill:"rgba(255, 0, 0, 0.5)"}},dataGrouping:{approximation:"ichimoku-averages"}},{pointArrayMap:["tenkanSen","kijunSen","chikouSpan","senkouSpanA","senkouSpanB"],pointValKey:"tenkanSen",nameComponents:["periodSenkouSpanB","period",
"periodTenkan"],init:function(){l.prototype.init.apply(this,arguments);this.options=r({tenkanLine:{styles:{lineColor:this.color}},kijunLine:{styles:{lineColor:this.color}},chikouLine:{styles:{lineColor:this.color}},senkouSpanA:{styles:{lineColor:this.color,fill:t(this.color).setOpacity(.5).get()}},senkouSpanB:{styles:{lineColor:this.color,fill:t(this.color).setOpacity(.5).get()}},senkouSpan:{styles:{fill:t(this.color).setOpacity(.2).get()}}},this.options)},toYData:function(a){return[a.tenkanSen,a.kijunSen,
a.chikouSpan,a.senkouSpanA,a.senkouSpanB]},translate:function(){var a=this;l.prototype.translate.apply(a);a.points.forEach(function(d){a.pointArrayMap.forEach(function(c){p(d[c])&&(d["plot"+c]=a.yAxis.toPixels(d[c],!0),d.plotY=d["plot"+c],d.tooltipPos=[d.plotX,d["plot"+c]],d.isNull=!1)})})},drawGraph:function(){var a=this,d=a.points,c=d.length,e=a.options,b=a.graph,k=a.color,t={options:{gapSize:e.gapSize}},u=a.pointArrayMap.length,h=[[],[],[],[],[],[]],g={tenkanLine:h[0],kijunLine:h[1],chikouLine:h[2],
senkouSpanA:h[3],senkouSpanB:h[4],senkouSpan:h[5]},x=[],A=a.options.senkouSpan,w=A.color||A.styles.fill,M=A.negativeColor,L=[[],[]],I=[[],[]],O=0,J,P,N;for(a.ikhMap=g;c--;){var D=d[c];for(J=0;J<u;J++)A=a.pointArrayMap[J],p(D[A])&&h[J].push({plotX:D.plotX,plotY:D["plot"+A],isNull:!1});M&&c!==d.length-1&&(A=g.senkouSpanB.length-1,D=f(g.senkouSpanA[A-1],g.senkouSpanA[A],g.senkouSpanB[A-1],g.senkouSpanB[A]),J={plotX:D.plotX,plotY:D.plotY,isNull:!1,intersectPoint:!0},D&&(g.senkouSpanA.splice(A,0,J),g.senkouSpanB.splice(A,
0,J),x.push(A)))}q(g,function(d,c){e[c]&&"senkouSpan"!==c&&(a.points=h[O],a.options=r(e[c].styles,t),a.graph=a["graph"+c],a.fillGraph=!1,a.color=k,l.prototype.drawGraph.call(a),a["graph"+c]=a.graph);O++});a.graphCollection&&a.graphCollection.forEach(function(d){a[d].destroy();delete a[d]});a.graphCollection=[];if(M&&g.senkouSpanA[0]&&g.senkouSpanB[0]){x.unshift(0);x.push(g.senkouSpanA.length-1);for(u=0;u<x.length-1;u++){A=x[u];D=x[u+1];c=g.senkouSpanB.slice(A,D+1);A=g.senkouSpanA.slice(A,D+1);if(1<=
Math.floor(c.length/2))if(D=Math.floor(c.length/2),c[D].plotY===A[D].plotY){for(N=J=D=0;N<c.length;N++)D+=c[N].plotY,J+=A[N].plotY;D=D>J?0:1}else D=c[D].plotY>A[D].plotY?0:1;else D=c[0].plotY>A[0].plotY?0:1;L[D]=L[D].concat(c);I[D]=I[D].concat(A)}["graphsenkouSpanColor","graphsenkouSpanNegativeColor"].forEach(function(d,c){L[c].length&&I[c].length&&(P=0===c?w:M,m({indicator:a,points:L[c],nextPoints:I[c],color:P,options:e,gap:t,graph:a[d]}),a[d]=a.graph,a.graphCollection.push(d))})}else m({indicator:a,
points:g.senkouSpanB,nextPoints:g.senkouSpanA,color:w,options:e,gap:t,graph:a.graphsenkouSpan}),a.graphsenkouSpan=a.graph;delete a.nextPoints;delete a.fillGraph;a.points=d;a.options=e;a.graph=b},getGraphPath:function(a){var d=[],c;a=a||this.points;if(this.fillGraph&&this.nextPoints){if((c=l.prototype.getGraphPath.call(this,this.nextPoints))&&c.length){c[0][0]="L";d=l.prototype.getGraphPath.call(this,a);c=c.slice(0,d.length);for(var f=c.length-1;0<=f;f--)d.push(c[f])}}else d=l.prototype.getGraphPath.apply(this,
arguments);return d},getValues:function(c,f){var m=f.period,e=f.periodTenkan;f=f.periodSenkouSpanB;var b=c.xData,p=c.yData,n=p&&p.length||0;c=d(c.xAxis);var t=[],k=[],l;if(!(b.length<=m)&&u(p[0])&&4===p[0].length){var r=b[0]-m*c;for(l=0;l<m;l++)k.push(r+l*c);for(l=0;l<n;l++){if(l>=e){var q=p.slice(l-e,l);q=a(q);q=(q.high+q.low)/2}if(l>=m){var g=p.slice(l-m,l);g=a(g);g=(g.high+g.low)/2;var h=(q+g)/2}if(l>=f){var v=p.slice(l-f,l);v=a(v);v=(v.high+v.low)/2}r=p[l][3];var x=b[l];"undefined"===typeof t[l]&&
(t[l]=[]);"undefined"===typeof t[l+m]&&(t[l+m]=[]);t[l+m][0]=q;t[l+m][1]=g;t[l+m][2]=void 0;t[l][2]=r;l<=m&&(t[l+m][3]=void 0,t[l+m][4]=void 0);"undefined"===typeof t[l+2*m]&&(t[l+2*m]=[]);t[l+2*m][3]=h;t[l+2*m][4]=v;k.push(x)}for(l=1;l<=m;l++)k.push(x+l*c);return{values:t,xData:k,yData:t}}}});""});w(b,"Stock/Indicators/KeltnerChannelsIndicator.js",[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Core/Utilities.js"]],function(b,g,h){var k=b.seriesTypes,e=h.correctFloat,c=h.merge,a=k.sma,
d=k.ema,f=k.atr;b.seriesType("keltnerchannels","sma",{params:{period:20,periodATR:10,multiplierATR:2},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Upper Channel: {point.top}<br/>EMA({series.options.params.period}): {point.middle}<br/>Lower Channel: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"},lineWidth:1},c(g,{pointArrayMap:["top",
"middle","bottom"],pointValKey:"middle",nameBase:"Keltner Channels",nameComponents:["period","periodATR","multiplierATR"],linesApiNames:["topLine","bottomLine"],requiredIndicators:["ema","atr"],init:function(){a.prototype.init.apply(this,arguments);this.options=c({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(a,c){var m=c.period,b=c.periodATR,t=c.multiplierATR,k=a.yData;k=k?k.length:0;var l=[];c=d.prototype.getValues(a,{period:m,
index:c.index});var n=f.prototype.getValues(a,{period:b}),g=[],h=[],x;if(!(k<m)){for(x=m;x<=k;x++){var C=c.values[x-m];var y=n.values[x-b];var z=C[0];a=e(C[1]+t*y[1]);y=e(C[1]-t*y[1]);C=C[1];l.push([z,a,C,y]);g.push(z);h.push([a,C,y])}return{values:l,xData:g,yData:h}}}}));""});w(b,"Stock/Indicators/MACDIndicator.js",[b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,g,h){var k=b.seriesTypes,e=h.correctFloat,c=h.defined,a=h.merge,d=k.sma,f=k.ema;b.seriesType("macd",
"sma",{params:{shortPeriod:12,longPeriod:26,signalPeriod:9,period:26},signalLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},macdLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},threshold:0,groupPadding:.1,pointPadding:.1,crisp:!1,states:{hover:{halo:{size:0}}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Value: {point.MACD}<br/>Signal: {point.signal}<br/>Histogram: {point.y}<br/>'},dataGrouping:{approximation:"averages"},minPointLength:0},
{nameComponents:["longPeriod","shortPeriod","signalPeriod"],requiredIndicators:["ema"],pointArrayMap:["y","signal","MACD"],parallelArrays:["x","y","signal","MACD"],pointValKey:"y",markerAttribs:g.noop,getColumnMetrics:g.seriesTypes.column.prototype.getColumnMetrics,crispCol:g.seriesTypes.column.prototype.crispCol,init:function(){d.prototype.init.apply(this,arguments);this.options&&(this.options=a({signalLine:{styles:{lineColor:this.color}},macdLine:{styles:{color:this.color}}},this.options),this.macdZones=
{zones:this.options.macdLine.zones,startIndex:0},this.signalZones={zones:this.macdZones.zones.concat(this.options.signalLine.zones),startIndex:this.macdZones.zones.length},this.resetZones=!0)},toYData:function(a){return[a.y,a.signal,a.MACD]},translate:function(){var a=this,d=["plotSignal","plotMACD"];g.seriesTypes.column.prototype.translate.apply(a);a.points.forEach(function(c){[c.signal,c.MACD].forEach(function(f,m){null!==f&&(c[d[m]]=a.yAxis.toPixels(f,!0))})})},destroy:function(){this.graph=null;
this.graphmacd=this.graphmacd&&this.graphmacd.destroy();this.graphsignal=this.graphsignal&&this.graphsignal.destroy();d.prototype.destroy.apply(this,arguments)},drawPoints:g.seriesTypes.column.prototype.drawPoints,drawGraph:function(){for(var f=this,e=f.points,b=e.length,k=f.options,r=f.zones,q={options:{gapSize:k.gapSize}},l=[[],[]],n;b--;)n=e[b],c(n.plotMACD)&&l[0].push({plotX:n.plotX,plotY:n.plotMACD,isNull:!c(n.plotMACD)}),c(n.plotSignal)&&l[1].push({plotX:n.plotX,plotY:n.plotSignal,isNull:!c(n.plotMACD)});
["macd","signal"].forEach(function(c,e){f.points=l[e];f.options=a(k[c+"Line"].styles,q);f.graph=f["graph"+c];f.currentLineZone=c+"Zones";f.zones=f[f.currentLineZone].zones;d.prototype.drawGraph.call(f);f["graph"+c]=f.graph});f.points=e;f.options=k;f.zones=r;f.currentLineZone=null},getZonesGraphs:function(a){var c=d.prototype.getZonesGraphs.call(this,a),f=c;this.currentLineZone&&(f=c.splice(this[this.currentLineZone].startIndex+1),f.length?f.splice(0,0,a[0]):f=[a[0]]);return f},applyZones:function(){var a=
this.zones;this.zones=this.signalZones.zones;d.prototype.applyZones.call(this);this.graphmacd&&this.options.macdLine.zones.length&&this.graphmacd.hide();this.zones=a},getValues:function(a,d){var b=0,m=[],k=[],t=[];if(!(a.xData.length<d.longPeriod+d.signalPeriod)){var l=f.prototype.getValues(a,{period:d.shortPeriod});var n=f.prototype.getValues(a,{period:d.longPeriod});l=l.values;n=n.values;for(a=1;a<=l.length;a++)c(n[a-1])&&c(n[a-1][1])&&c(l[a+d.shortPeriod+1])&&c(l[a+d.shortPeriod+1][0])&&m.push([l[a+
d.shortPeriod+1][0],0,null,l[a+d.shortPeriod+1][1]-n[a-1][1]]);for(a=0;a<m.length;a++)k.push(m[a][0]),t.push([0,null,m[a][3]]);d=f.prototype.getValues({xData:k,yData:t},{period:d.signalPeriod,index:2});d=d.values;for(a=0;a<m.length;a++)m[a][0]>=d[0][0]&&(m[a][2]=d[b][1],t[a]=[0,d[b][1],m[a][3]],null===m[a][3]?(m[a][1]=0,t[a][0]=0):(m[a][1]=e(m[a][3]-d[b][1]),t[a][0]=e(m[a][3]-d[b][1])),b++);return{values:m,xData:k,yData:t}}}});""});w(b,"Stock/Indicators/MFIIndicator.js",[b["Core/Series/Series.js"],
b["Core/Utilities.js"]],function(b,g){function h(a){return a.reduce(function(a,c){return a+c})}function k(a){return(a[1]+a[2]+a[3])/3}var e=g.error,c=g.isArray;b.seriesType("mfi","sma",{params:{period:14,volumeSeriesID:"volume",decimals:4}},{nameBase:"Money Flow Index",getValues:function(a,d){var f=d.period,b=a.xData,t=a.yData,p=t?t.length:0,g=d.decimals,r=1,q=a.chart.get(d.volumeSeriesID),l=q&&q.yData,n=[],v=[],B=[],x=[],C=[];if(!q)e("Series "+d.volumeSeriesID+" not found! Check `volumeSeriesID`.",
!0,a.chart);else if(!(b.length<=f)&&c(t[0])&&4===t[0].length&&l){for(a=k(t[r]);r<f+1;)d=a,a=k(t[r]),d=a>=d,q=a*l[r],x.push(d?q:0),C.push(d?0:q),r++;for(f=r-1;f<p;f++)f>r-1&&(x.shift(),C.shift(),d=a,a=k(t[f]),d=a>d,q=a*l[f],x.push(d?q:0),C.push(d?0:q)),d=h(C),q=h(x),d=q/d,d=parseFloat((100-100/(1+d)).toFixed(g)),n.push([b[f],d]),v.push(b[f]),B.push(d);return{values:n,xData:v,yData:B}}}});""});w(b,"Stock/Indicators/MomentumIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,
g){function h(e,c,a,d,f){a=a[d-1][3]-a[d-f-1][3];c=c[d-1];e.shift();return[c,a]}var k=g.isArray;b.seriesType("momentum","sma",{params:{period:14}},{nameBase:"Momentum",getValues:function(e,c){c=c.period;var a=e.xData,d=(e=e.yData)?e.length:0,f=a[0],b=[],t=[],p=[];if(!(a.length<=c)&&k(e[0])){var g=e[0][3];g=[[f,g]];for(f=c+1;f<d;f++){var r=h(g,a,e,f,c,void 0);b.push(r);t.push(r[0]);p.push(r[1])}r=h(g,a,e,f,c,void 0);b.push(r);t.push(r[0]);p.push(r[1]);return{values:b,xData:t,yData:p}}}});""});w(b,
"Stock/Indicators/NATRIndicator.js",[b["Core/Series/Series.js"]],function(b){var g=b.seriesTypes.atr;b.seriesType("natr","sma",{tooltip:{valueSuffix:"%"}},{requiredIndicators:["atr"],getValues:function(b,k){var e=g.prototype.getValues.apply(this,arguments),c=e.values.length,a=k.period-1,d=b.yData,f=0;if(e){for(;f<c;f++)e.yData[f]=e.values[f][1]/d[a][3]*100,e.values[f][1]=e.yData[f],a++;return e}}});""});w(b,"Stock/Indicators/PivotPointsIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],
function(b,g){function h(a,d){var f=a.series.pointArrayMap,e=f.length;for(c.prototype.pointClass.prototype[d].call(a);e--;)d="dataLabel"+f[e],a[d]&&a[d].element&&a[d].destroy(),a[d]=null}var k=g.defined,e=g.isArray,c=b.seriesTypes.sma;b.seriesType("pivotpoints","sma",{params:{period:28,algorithm:"standard"},marker:{enabled:!1},enableMouseTracking:!1,dataLabels:{enabled:!0,format:"{point.pivotLine}"},dataGrouping:{approximation:"averages"}},{nameBase:"Pivot Points",pointArrayMap:"R4 R3 R2 R1 P S1 S2 S3 S4".split(" "),
pointValKey:"P",toYData:function(a){return[a.P]},translate:function(){var a=this;c.prototype.translate.apply(a);a.points.forEach(function(d){a.pointArrayMap.forEach(function(c){k(d[c])&&(d["plot"+c]=a.yAxis.toPixels(d[c],!0))})});a.plotEndPoint=a.xAxis.toPixels(a.endPoint,!0)},getGraphPath:function(a){for(var d=this,f=a.length,e=[[],[],[],[],[],[],[],[],[]],b=[],p=d.plotEndPoint,g=d.pointArrayMap.length,r,q,l;f--;){q=a[f];for(l=0;l<g;l++)r=d.pointArrayMap[l],k(q[r])&&e[l].push({plotX:q.plotX,plotY:q["plot"+
r],isNull:!1},{plotX:p,plotY:q["plot"+r],isNull:!1},{plotX:p,plotY:null,isNull:!0});p=q.plotX}e.forEach(function(a){b=b.concat(c.prototype.getGraphPath.call(d,a))});return b},drawDataLabels:function(){var a=this,d=a.pointArrayMap,f,e,b;if(a.options.dataLabels.enabled){var k=a.points.length;d.concat([!1]).forEach(function(m,p){for(b=k;b--;)e=a.points[b],m?(e.y=e[m],e.pivotLine=m,e.plotY=e["plot"+m],f=e["dataLabel"+m],p&&(e["dataLabel"+d[p-1]]=e.dataLabel),e.dataLabels||(e.dataLabels=[]),e.dataLabels[0]=
e.dataLabel=f=f&&f.element?f:null):e["dataLabel"+d[p-1]]=e.dataLabel;c.prototype.drawDataLabels.apply(a,arguments)})}},getValues:function(a,d){var c=d.period,b=a.xData,k=(a=a.yData)?a.length:0;d=this[d.algorithm+"Placement"];var p=[],g=[],r=[],q;if(!(b.length<c)&&e(a[0])&&4===a[0].length){for(q=c+1;q<=k+c;q+=c){var l=b.slice(q-c-1,q);var n=a.slice(q-c-1,q);var h=l.length;var B=l[h-1];n=this.getPivotAndHLC(n);n=d(n);n=p.push([B].concat(n));g.push(B);r.push(p[n-1].slice(1))}this.endPoint=l[0]+(B-l[0])/
h*c;return{values:p,xData:g,yData:r}}},getPivotAndHLC:function(a){var c=-Infinity,f=Infinity,e=a[a.length-1][3];a.forEach(function(a){c=Math.max(c,a[1]);f=Math.min(f,a[2])});return[(c+f+e)/3,c,f,e]},standardPlacement:function(a){var c=a[1]-a[2];return[null,null,a[0]+c,2*a[0]-a[2],a[0],2*a[0]-a[1],a[0]-c,null,null]},camarillaPlacement:function(a){var c=a[1]-a[2];return[a[3]+1.5*c,a[3]+1.25*c,a[3]+1.1666*c,a[3]+1.0833*c,a[0],a[3]-1.0833*c,a[3]-1.1666*c,a[3]-1.25*c,a[3]-1.5*c]},fibonacciPlacement:function(a){var c=
a[1]-a[2];return[null,a[0]+c,a[0]+.618*c,a[0]+.382*c,a[0],a[0]-.382*c,a[0]-.618*c,a[0]-c,null]}},{destroyElements:function(){h(this,"destroyElements")},destroy:function(){h(this,"destroyElements")}});""});w(b,"Stock/Indicators/PPOIndicator.js",[b["Core/Globals.js"],b["Mixins/IndicatorRequired.js"],b["Core/Utilities.js"]],function(b,g,h){var k=h.correctFloat,e=h.error,c=b.seriesTypes.ema;b.seriesType("ppo","ema",{params:{periods:[12,26]}},{nameBase:"PPO",nameComponents:["periods"],init:function(){var a=
arguments,d=this;g.isParentLoaded(c,"ema",d.type,function(c){c.prototype.init.apply(d,a)})},getValues:function(a,d){var f=d.periods,b=d.index;d=[];var t=[],p=[],g;if(2!==f.length||f[1]<=f[0])e('Error: "PPO requires two periods. Notice, first period should be lower than the second one."');else{var r=c.prototype.getValues.call(this,a,{index:b,period:f[0]});a=c.prototype.getValues.call(this,a,{index:b,period:f[1]});if(r&&a){f=f[1]-f[0];for(g=0;g<a.yData.length;g++)b=k((r.yData[g+f]-a.yData[g])/a.yData[g]*
100),d.push([a.xData[g],b]),t.push(a.xData[g]),p.push(b);return{values:d,xData:t,yData:p}}}}});""});w(b,"Mixins/ReduceArray.js",[],function(){return{minInArray:function(b,g){return b.reduce(function(b,k){return Math.min(b,k[g])},Number.MAX_VALUE)},maxInArray:function(b,g){return b.reduce(function(b,k){return Math.max(b,k[g])},-Number.MAX_VALUE)},getArrayExtremes:function(b,g,h){return b.reduce(function(b,e){return[Math.min(b[0],e[g]),Math.max(b[1],e[h])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});
w(b,"Stock/Indicators/PCIndicator.js",[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Mixins/ReduceArray.js"],b["Core/Utilities.js"]],function(b,g,h,k){k=k.merge;var e=h.getArrayExtremes;b.seriesType("pc","sma",{params:{period:20},lineWidth:1,topLine:{styles:{lineColor:"#90ed7d",lineWidth:1}},bottomLine:{styles:{lineColor:"#f45b5b",lineWidth:1}},dataGrouping:{approximation:"averages"}},k(g,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",nameComponents:["period"],
linesApiNames:["topLine","bottomLine"],getValues:function(c,a){a=a.period;var d=c.xData,f=(c=c.yData)?c.length:0,b=[],k=[],p=[],g;if(!(f<a)){for(g=a;g<=f;g++){var r=d[g-1];var q=c.slice(g-a,g);var l=e(q,2,1);q=l[1];var n=l[0];l=(q+n)/2;b.push([r,q,l,n]);k.push(r);p.push([q,l,n])}return{values:b,xData:k,yData:p}}}}));""});w(b,"Stock/Indicators/PriceEnvelopesIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=g.isArray,k=g.merge,e=b.seriesTypes.sma;b.seriesType("priceenvelopes",
"sma",{marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},params:{period:20,topBand:.1,bottomBand:.1},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}},{nameComponents:["period","topBand","bottomBand"],nameBase:"Price envelopes",pointArrayMap:["top","middle","bottom"],parallelArrays:["x",
"y","top","bottom"],pointValKey:"middle",init:function(){e.prototype.init.apply(this,arguments);this.options=k({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},toYData:function(c){return[c.top,c.middle,c.bottom]},translate:function(){var c=this,a=["plotTop","plotMiddle","plotBottom"];e.prototype.translate.apply(c);c.points.forEach(function(d){[d.top,d.middle,d.bottom].forEach(function(b,e){null!==b&&(d[a[e]]=c.yAxis.toPixels(b,!0))})})},drawGraph:function(){for(var c=
this,a=c.points,d=a.length,b=c.options,m=c.graph,g={options:{gapSize:b.gapSize}},p=[[],[]],h;d--;)h=a[d],p[0].push({plotX:h.plotX,plotY:h.plotTop,isNull:h.isNull}),p[1].push({plotX:h.plotX,plotY:h.plotBottom,isNull:h.isNull});["topLine","bottomLine"].forEach(function(a,d){c.points=p[d];c.options=k(b[a].styles,g);c.graph=c["graph"+a];e.prototype.drawGraph.call(c);c["graph"+a]=c.graph});c.points=a;c.options=b;c.graph=m;e.prototype.drawGraph.call(c)},getValues:function(c,a){var d=a.period,b=a.topBand,
k=a.bottomBand,g=c.xData,p=(c=c.yData)?c.length:0,u=[],r=[],q=[],l;if(!(g.length<d)&&h(c[0])&&4===c[0].length){for(l=d;l<=p;l++){var n=g.slice(l-d,l);var v=c.slice(l-d,l);v=e.prototype.getValues.call(this,{xData:n,yData:v},a);n=v.xData[0];v=v.yData[0];var B=v*(1+b);var x=v*(1-k);u.push([n,B,v,x]);r.push(n);q.push([B,v,x])}return{values:u,xData:r,yData:q}}}});""});w(b,"Stock/Indicators/PSARIndicator.js",[b["Core/Series/Series.js"]],function(b){b.seriesType("psar","sma",{lineWidth:0,marker:{enabled:!0},
states:{hover:{lineWidthPlus:0}},params:{initialAccelerationFactor:.02,maxAccelerationFactor:.2,increment:.02,index:2,decimals:4}},{nameComponents:!1,getValues:function(b,h){var k=b.xData;b=b.yData;var e=b[0][1],c=h.maxAccelerationFactor,a=h.increment,d=h.initialAccelerationFactor,f=b[0][2],m=h.decimals,t=h.index,p=[],g=[],r=[],q=1,l;if(!(t>=b.length)){for(l=0;l<t;l++)e=Math.max(b[l][1],e),f=Math.min(b[l][2],parseFloat(f.toFixed(m)));var n=b[l][1]>f?1:-1;h=h.initialAccelerationFactor;var v=h*(e-f);
p.push([k[t],f]);g.push(k[t]);r.push(parseFloat(f.toFixed(m)));for(l=t+1;l<b.length;l++){t=b[l-1][2];var B=b[l-2][2];var x=b[l-1][1];var C=b[l-2][1];var y=b[l][1];var z=b[l][2];null!==B&&null!==C&&null!==t&&null!==x&&null!==y&&null!==z&&(f=n===q?1===n?f+v<Math.min(B,t)?f+v:Math.min(B,t):f+v>Math.max(C,x)?f+v:Math.max(C,x):e,t=1===n?y>e?y:e:z<e?z:e,y=1===q&&z>f||-1===q&&y>f?1:-1,q=y,v=t,z=a,B=c,x=d,h=q===n?1===q&&v>e?h===B?B:parseFloat((h+z).toFixed(2)):-1===q&&v<e?h===B?B:parseFloat((h+z).toFixed(2)):
h:x,e=t-f,v=h*e,p.push([k[l],parseFloat(f.toFixed(m))]),g.push(k[l]),r.push(parseFloat(f.toFixed(m))),q=n,n=y,e=t)}return{values:p,xData:g,yData:r}}}});""});w(b,"Stock/Indicators/ROCIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=g.isArray;b.seriesType("roc","sma",{params:{index:3,period:9}},{nameBase:"Rate of Change",getValues:function(b,e){var c=e.period,a=b.xData,d=(b=b.yData)?b.length:0,f=[],k=[],t=[],p=-1;if(!(a.length<=c)){h(b[0])&&(p=e.index);for(e=c;e<
d;e++){var g=0>p?(g=b[e-c])?(b[e]-g)/g*100:null:(g=b[e-c][p])?(b[e][p]-g)/g*100:null;g=[a[e],g];f.push(g);k.push(g[0]);t.push(g[1])}return{values:f,xData:k,yData:t}}}});""});w(b,"Stock/Indicators/RSIIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=g.isArray;b.seriesType("rsi","sma",{params:{period:14,decimals:4}},{getValues:function(b,e){var c=e.period,a=b.xData,d=(b=b.yData)?b.length:0;e=e.decimals;var f=1,k=[],g=[],p=[],u=0,r=0,q;if(!(a.length<c)&&h(b[0])&&4===
b[0].length){for(;f<c;){var l=parseFloat((b[f][3]-b[f-1][3]).toFixed(e));0<l?u+=l:r+=Math.abs(l);f++}var n=parseFloat((u/(c-1)).toFixed(e));for(q=parseFloat((r/(c-1)).toFixed(e));f<d;f++)l=parseFloat((b[f][3]-b[f-1][3]).toFixed(e)),0<l?(u=l,r=0):(u=0,r=Math.abs(l)),n=parseFloat(((n*(c-1)+u)/c).toFixed(e)),q=parseFloat(((q*(c-1)+r)/c).toFixed(e)),u=0===q?100:0===n?0:parseFloat((100-100/(1+n/q)).toFixed(e)),k.push([a[f],u]),g.push(a[f]),p.push(u);return{values:k,xData:g,yData:p}}}});""});w(b,"Stock/Indicators/StochasticIndicator.js",
[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Mixins/ReduceArray.js"],b["Core/Utilities.js"]],function(b,g,h,k){var e=k.isArray,c=k.merge,a=b.seriesTypes.sma,d=h.getArrayExtremes;b.seriesType("stochastic","sma",{params:{periods:[14,3]},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>%K: {point.y}<br/>%D: {point.smoothed}<br/>'},smoothedLine:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},
c(g,{nameComponents:["periods"],nameBase:"Stochastic",pointArrayMap:["y","smoothed"],parallelArrays:["x","y","smoothed"],pointValKey:"y",linesApiNames:["smoothedLine"],init:function(){a.prototype.init.apply(this,arguments);this.options=c({smoothedLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(c,b){var f=b.periods[0];b=b.periods[1];var k=c.xData,m=(c=c.yData)?c.length:0,g=[],q=[],l=[],n=null,h;if(!(m<f)&&e(c[0])&&4===c[0].length){for(h=f-1;h<m;h++){var B=c.slice(h-f+1,h+1);
var x=d(B,2,1);var C=x[0];B=c[h][3]-C;C=x[1]-C;B=B/C*100;q.push(k[h]);l.push([B,null]);h>=f-1+(b-1)&&(n=a.prototype.getValues.call(this,{xData:q.slice(-b),yData:l.slice(-b)},{period:b}),n=n.yData[0]);g.push([k[h],B,n]);l[l.length-1][1]=n}return{values:g,xData:q,yData:l}}}}));""});w(b,"Stock/Indicators/SlowStochasticIndicator.js",[b["Core/Series/Series.js"],b["Mixins/IndicatorRequired.js"]],function(b,g){var h=b.seriesTypes;b.seriesType("slowstochastic","stochastic",{params:{periods:[14,3,3]}},{nameBase:"Slow Stochastic",
init:function(){var b=arguments,e=this;g.isParentLoaded(h.stochastic,"stochastic",e.type,function(c){c.prototype.init.apply(e,b)})},getValues:function(b,e){var c=e.periods,a=h.stochastic.prototype.getValues.call(this,b,e);b={values:[],xData:[],yData:[]};e=0;if(a){b.xData=a.xData.slice(c[1]-1);a=a.yData.slice(c[1]-1);var d=h.sma.prototype.getValues.call(this,{xData:b.xData,yData:a},{index:1,period:c[2]});if(d){for(var f=b.xData.length;e<f;e++)b.yData[e]=[a[e][1],d.yData[e-c[2]+1]||null],b.values[e]=
[b.xData[e],a[e][1],d.yData[e-c[2]+1]||null];return b}}}});""});w(b,"Stock/Indicators/SupertrendIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){function h(a,c,d){return{index:c,close:a.yData[c][d],x:a.xData[c]}}var k=b.seriesTypes,e=g.correctFloat,c=g.isArray,a=g.merge,d=g.objectEach,f=k.atr,m=k.sma;b.seriesType("supertrend","sma",{params:{multiplier:3,period:10},risingTrendColor:"#06B535",fallingTrendColor:"#F21313",changeTrendLine:{styles:{lineWidth:1,lineColor:"#333333",
dashStyle:"LongDash"}}},{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"],init:function(){m.prototype.init.apply(this,arguments);var a=this.options;a.cropThreshold=this.linkedParent.options.cropThreshold-(a.params.period-1)},drawGraph:function(){var c=this,b=c.options,e=c.linkedParent,f=e?e.points:[],k=c.points,l=c.graph,n=k.length,g=f.length-n;g=0<g?g:0;for(var B={options:{gapSize:b.gapSize}},x={top:[],bottom:[],intersect:[]},C={top:{styles:{lineWidth:b.lineWidth,
lineColor:b.fallingTrendColor||b.color,dashStyle:b.dashStyle}},bottom:{styles:{lineWidth:b.lineWidth,lineColor:b.risingTrendColor||b.color,dashStyle:b.dashStyle}},intersect:b.changeTrendLine},y,z,E,F,w,H,A,G;n--;)y=k[n],z=k[n-1],E=f[n-1+g],F=f[n-2+g],w=f[n+g],H=f[n+g+1],A=y.options.color,G={x:y.x,plotX:y.plotX,plotY:y.plotY,isNull:!1},!F&&E&&e.yData[E.index-1]&&(F=h(e,E.index-1,3)),!H&&w&&e.yData[w.index+1]&&(H=h(e,w.index+1,3)),!E&&F&&e.yData[F.index+1]?E=h(e,F.index+1,3):!E&&w&&e.yData[w.index-
1]&&(E=h(e,w.index-1,3)),y&&E&&w&&F&&y.x!==E.x&&(y.x===w.x?(F=E,E=w):y.x===F.x?(E=F,F={close:e.yData[E.index-1][3],x:e.xData[E.index-1]}):H&&y.x===H.x&&(E=H,F=w)),z&&F&&E?(w={x:z.x,plotX:z.plotX,plotY:z.plotY,isNull:!1},y.y>=E.close&&z.y>=F.close?(y.color=A||b.fallingTrendColor||b.color,x.top.push(G)):y.y<E.close&&z.y<F.close?(y.color=A||b.risingTrendColor||b.color,x.bottom.push(G)):(x.intersect.push(G),x.intersect.push(w),x.intersect.push(a(w,{isNull:!0})),y.y>=E.close&&z.y<F.close?(y.color=A||b.fallingTrendColor||
b.color,z.color=A||b.risingTrendColor||b.color,x.top.push(G),x.top.push(a(w,{isNull:!0}))):y.y<E.close&&z.y>=F.close&&(y.color=A||b.risingTrendColor||b.color,z.color=A||b.fallingTrendColor||b.color,x.bottom.push(G),x.bottom.push(a(w,{isNull:!0}))))):E&&(y.y>=E.close?(y.color=A||b.fallingTrendColor||b.color,x.top.push(G)):(y.color=A||b.risingTrendColor||b.color,x.bottom.push(G)));d(x,function(b,d){c.points=b;c.options=a(C[d].styles,B);c.graph=c["graph"+d+"Line"];m.prototype.drawGraph.call(c);c["graph"+
d+"Line"]=c.graph});c.points=k;c.options=b;c.graph=l},getValues:function(a,b){var d=b.period;b=b.multiplier;var k=a.xData,g=a.yData,l=[],n=[],m=[],p=0===d?0:d-1,h=[],t=[],y;if(!(k.length<=d||!c(g[0])||4!==g[0].length||0>d)){a=f.prototype.getValues.call(this,a,{period:d}).yData;for(y=0;y<a.length;y++){var z=g[p+y];var x=g[p+y-1]||[];var w=h[y-1];var K=t[y-1];var H=m[y-1];0===y&&(w=K=H=0);d=e((z[1]+z[2])/2+b*a[y]);var A=e((z[1]+z[2])/2-b*a[y]);h[y]=d<w||x[3]>w?d:w;t[y]=A>K||x[3]<K?A:K;if(H===w&&z[3]<
h[y]||H===K&&z[3]<t[y])var G=h[y];else if(H===w&&z[3]>h[y]||H===K&&z[3]>t[y])G=t[y];l.push([k[p+y],G]);n.push(k[p+y]);m.push(G)}return{values:l,xData:n,yData:m}}}});""});w(b,"Stock/Indicators/VBPIndicator.js",[b["Core/Animation/AnimationUtilities.js"],b["Core/Series/Series.js"],b["Core/Globals.js"],b["Core/Series/Point.js"],b["Core/Utilities.js"]],function(b,g,h,k,e){var c=b.animObject;b=h.noop;var a=e.addEvent,d=e.arrayMax,f=e.arrayMin,m=e.correctFloat,t=e.error,p=e.extend,u=e.isArray,r=Math.abs,
q=g.seriesTypes.column.prototype;g.seriesType("vbp","sma",{params:{ranges:12,volumeSeriesID:"volume"},zoneLines:{enabled:!0,styles:{color:"#0A9AC9",dashStyle:"LongDash",lineWidth:1}},volumeDivision:{enabled:!0,styles:{positiveColor:"rgba(144, 237, 125, 0.8)",negativeColor:"rgba(244, 91, 91, 0.8)"}},animationLimit:1E3,enableMouseTracking:!1,pointPadding:0,zIndex:-1,crisp:!0,dataGrouping:{enabled:!1},dataLabels:{allowOverlap:!0,enabled:!0,format:"P: {point.volumePos:.2f} | N: {point.volumeNeg:.2f}",
padding:0,style:{fontSize:"7px"},verticalAlign:"top"}},{nameBase:"Volume by Price",bindTo:{series:!1,eventName:"afterSetExtremes"},calculateOn:"render",markerAttribs:b,drawGraph:b,getColumnMetrics:q.getColumnMetrics,crispCol:q.crispCol,init:function(a){h.seriesTypes.sma.prototype.init.apply(this,arguments);var c=this.options.params;var b=this.linkedParent;c=a.get(c.volumeSeriesID);this.addCustomEvents(b,c);return this},addCustomEvents:function(c,b){function d(){e.chart.redraw();e.setData([]);e.zoneStarts=
[];e.zoneLinesSVG&&(e.zoneLinesSVG.destroy(),delete e.zoneLinesSVG)}var e=this;e.dataEventsToUnbind.push(a(c,"remove",function(){d()}));b&&e.dataEventsToUnbind.push(a(b,"remove",function(){d()}));return e},animate:function(a){var b=this,d=b.chart.inverted,e=b.group,f={};!a&&e&&(a=d?"translateY":"translateX",d=d?b.yAxis.top:b.xAxis.left,e["forceAnimate:"+a]=!0,f[a]=d,e.animate(f,p(c(b.options.animation),{step:function(a,c){b.group.attr({scaleX:Math.max(.001,c.pos)})}})))},drawPoints:function(){this.options.volumeDivision.enabled&&
(this.posNegVolume(!0,!0),q.drawPoints.apply(this,arguments),this.posNegVolume(!1,!1));q.drawPoints.apply(this,arguments)},posNegVolume:function(a,c){var b=c?["positive","negative"]:["negative","positive"],d=this.options.volumeDivision,e=this.points.length,f=[],k=[],l=0,g;a?(this.posWidths=f,this.negWidths=k):(f=this.posWidths,k=this.negWidths);for(;l<e;l++){var m=this.points[l];m[b[0]+"Graphic"]=m.graphic;m.graphic=m[b[1]+"Graphic"];if(a){var n=m.shapeArgs.width;var p=this.priceZones[l];(g=p.wholeVolumeData)?
(f.push(n/g*p.positiveVolumeData),k.push(n/g*p.negativeVolumeData)):(f.push(0),k.push(0))}m.color=c?d.styles.positiveColor:d.styles.negativeColor;m.shapeArgs.width=c?this.posWidths[l]:this.negWidths[l];m.shapeArgs.x=c?m.shapeArgs.x:this.posWidths[l]}},translate:function(){var a=this,c=a.options,b=a.chart,e=a.yAxis,f=e.min,k=a.options.zoneLines,g=a.priceZones,p=0,h,t,u;q.translate.apply(a);var x=a.points;if(x.length){var w=.5>c.pointPadding?c.pointPadding:.1;c=a.volumeDataArray;var G=d(c);var M=b.plotWidth/
2;var L=b.plotTop;var I=r(e.toPixels(f)-e.toPixels(f+a.rangeStep));var O=r(e.toPixels(f)-e.toPixels(f+a.rangeStep));w&&(f=r(I*(1-2*w)),p=r((I-f)/2),I=r(f));x.forEach(function(c,b){t=c.barX=c.plotX=0;u=c.plotY=e.toPixels(g[b].start)-L-(e.reversed?I-O:I)-p;h=m(M*g[b].wholeVolumeData/G);c.pointWidth=h;c.shapeArgs=a.crispCol.apply(a,[t,u,h,I]);c.volumeNeg=g[b].negativeVolumeData;c.volumePos=g[b].positiveVolumeData;c.volumeAll=g[b].wholeVolumeData});k.enabled&&a.drawZones(b,e,a.zoneStarts,k.styles)}},
getValues:function(a,c){var b=a.processedXData,d=a.processedYData,e=this.chart,f=c.ranges,k=[],g=[],m=[],l;if(a.chart)if(l=e.get(c.volumeSeriesID))if((c=u(d[0]))&&4!==d[0].length)t("Type of "+a.name+" series is different than line, OHLC or candlestick.",!0,e);else return(this.priceZones=this.specifyZones(c,b,d,f,l)).forEach(function(a,c){k.push([a.x,a.end]);g.push(k[c][0]);m.push(k[c][1])}),{values:k,xData:g,yData:m};else t("Series "+c.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,e);else t("Base series not found! In case it has been removed, add a new one.",
!0,e)},specifyZones:function(a,c,b,e,k){if(a){var g=b.length;for(var l=b[0][3],n=l,p=1,h;p<g;p++)h=b[p][3],h<l&&(l=h),h>n&&(n=h);g={min:l,max:n}}else g=!1;g=(l=g)?l.min:f(b);h=l?l.max:d(b);l=this.zoneStarts=[];n=[];var q=0;p=1;if(!g||!h)return this.points.length&&(this.setData([]),this.zoneStarts=[],this.zoneLinesSVG.destroy()),[];var r=this.rangeStep=m(h-g)/e;for(l.push(g);q<e-1;q++)l.push(m(l[q]+r));l.push(h);for(e=l.length;p<e;p++)n.push({index:p-1,x:c[0],start:l[p-1],end:l[p]});return this.volumePerZone(a,
n,k,c,b)},volumePerZone:function(a,c,b,d,e){var f=this,g=b.processedXData,k=b.processedYData,l=c.length-1,m=e.length;b=k.length;var p,h,n,q,t;r(m-b)&&(d[0]!==g[0]&&k.unshift(0),d[m-1]!==g[b-1]&&k.push(0));f.volumeDataArray=[];c.forEach(function(c){c.wholeVolumeData=0;c.positiveVolumeData=0;for(t=c.negativeVolumeData=0;t<m;t++)n=h=!1,q=a?e[t][3]:e[t],p=t?a?e[t-1][3]:e[t-1]:q,q<=c.start&&0===c.index&&(h=!0),q>=c.end&&c.index===l&&(n=!0),(q>c.start||h)&&(q<c.end||n)&&(c.wholeVolumeData+=k[t],p>q?c.negativeVolumeData+=
k[t]:c.positiveVolumeData+=k[t]);f.volumeDataArray.push(c.wholeVolumeData)});return c},drawZones:function(a,c,b,d){var e=a.renderer,f=this.zoneLinesSVG,k=[],g=a.plotWidth,m=a.plotTop,l;b.forEach(function(b){l=c.toPixels(b)-m;k=k.concat(a.renderer.crispLine([["M",0,l],["L",g,l]],d.lineWidth))});f?f.animate({d:k}):f=this.zoneLinesSVG=e.path(k).attr({"stroke-width":d.lineWidth,stroke:d.color,dashstyle:d.dashStyle,zIndex:this.group.zIndex+.1}).add(this.group)}},{destroy:function(){this.negativeGraphic&&
(this.negativeGraphic=this.negativeGraphic.destroy());return k.prototype.destroy.apply(this,arguments)}});""});w(b,"Stock/Indicators/VWAPIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=g.error,k=g.isArray;b.seriesType("vwap","sma",{params:{period:30,volumeSeriesID:"volume"}},{getValues:function(b,c){var a=b.chart,d=b.xData;b=b.yData;var e=c.period,g=!0,t;if(t=a.get(c.volumeSeriesID))return k(b[0])||(g=!1),this.calculateVWAPValues(g,d,b,t,e);h("Series "+c.volumeSeriesID+
" not found! Check `volumeSeriesID`.",!0,a)},calculateVWAPValues:function(b,c,a,d,f){var e=d.yData,k=d.xData.length,g=c.length;d=[];var h=[],r=[],q=[],l=[],n;k=g<=k?g:k;for(n=g=0;g<k;g++){var v=b?(a[g][1]+a[g][2]+a[g][3])/3:a[g];v*=e[g];v=n?d[g-1]+v:v;var x=n?h[g-1]+e[g]:e[g];d.push(v);h.push(x);l.push([c[g],v/x]);r.push(l[g][0]);q.push(l[g][1]);n++;n===f&&(n=0)}return{values:l,xData:r,yData:q}}});""});w(b,"Stock/Indicators/WilliamsRIndicator.js",[b["Core/Series/Series.js"],b["Mixins/ReduceArray.js"],
b["Core/Utilities.js"]],function(b,g,h){var k=g.getArrayExtremes,e=h.isArray;b.seriesType("williamsr","sma",{params:{period:14}},{nameBase:"Williams %R",getValues:function(c,a){a=a.period;var b=c.xData,f=(c=c.yData)?c.length:0,g=[],h=[],p=[],u;if(!(b.length<a)&&e(c[0])&&4===c[0].length){for(u=a-1;u<f;u++){var r=c.slice(u-a+1,u+1);var q=k(r,2,1);r=q[0];q=q[1];var l=c[u][3];r=(q-l)/(q-r)*-100;b[u]&&(g.push([b[u],r]),h.push(b[u]),p.push(r))}return{values:g,xData:h,yData:p}}}});""});w(b,"Stock/Indicators/WMAIndicator.js",
[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){function h(c,a){a*=(a+1)/2;return c.reduce(function(a,c,b){return[null,a[1]+c[1]*(b+1)]})[1]/a}function k(c,a,b,e){b=h(c,c.length);a=a[e-1];c.shift();return[a,b]}var e=g.isArray;b.seriesType("wma","sma",{params:{index:3,period:9}},{getValues:function(c,a){var b=a.period,f=c.xData,g=(c=c.yData)?c.length:0,h=1,p=f[0],u=c[0],r=[],q=[],l=[],n=-1;if(!(f.length<b)){e(c[0])&&(n=a.index,u=c[0][n]);for(a=[[p,u]];h!==b;)a.push([f[h],0>n?c[h]:
c[h][n]]),h++;for(b=h;b<g;b++)h=k(a,f,c,b),r.push(h),q.push(h[0]),l.push(h[1]),a.push([f[b],0>n?c[b]:c[b][n]]);h=k(a,f,c,b);r.push(h);q.push(h[0]);l.push(h[1]);return{values:r,xData:q,yData:l}}}});""});w(b,"Stock/Indicators/ZigzagIndicator.js",[b["Core/Series/Series.js"]],function(b){b.seriesType("zigzag","sma",{params:{lowIndex:2,highIndex:1,deviation:1}},{nameComponents:["deviation"],nameSuffixes:["%"],nameBase:"Zig Zag",getValues:function(b,h){var g=h.lowIndex,e=h.highIndex,c=h.deviation/100;h=
1+c;var a=1-c;c=b.xData;var d=b.yData;b=d?d.length:0;var f=[],m=[],t=[],p,u,r=!1,q=!1;if(!(!c||1>=c.length||b&&("undefined"===typeof d[0][g]||"undefined"===typeof d[0][e]))){var l=d[0][g];var n=d[0][e];for(p=1;p<b;p++){if(d[p][g]<=n*a){f.push([c[0],n]);var v=[c[p],d[p][g]];r=u=!0}else d[p][e]>=l*h&&(f.push([c[0],l]),v=[c[p],d[p][e]],u=!1,r=!0);if(r){m.push(f[0][0]);t.push(f[0][1]);var w=p++;p=b}}for(p=w;p<b;p++)u?(d[p][g]<=v[1]&&(v=[c[p],d[p][g]]),d[p][e]>=v[1]*h&&(q=e)):(d[p][e]>=v[1]&&(v=[c[p],
d[p][e]]),d[p][g]<=v[1]*a&&(q=g)),!1!==q&&(f.push(v),m.push(v[0]),t.push(v[1]),v=[c[p],d[p][q]],u=!u,q=!1);g=f.length;0!==g&&f[g-1][0]<c[b-1]&&(f.push(v),m.push(v[0]),t.push(v[1]));return{values:f,xData:m,yData:t}}}});""});w(b,"Stock/Indicators/RegressionIndicators.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=g.isArray;b.seriesType("linearRegression","sma",{params:{xAxisUnit:void 0},tooltip:{valueDecimals:4}},{nameBase:"Linear Regression Indicator",getRegressionLineParameters:function(b,
e){var c=this.options.params.index,a=function(a,c){return h(a)?a[c]:a},d=b.reduce(function(a,c){return c+a},0),f=e.reduce(function(b,d){return a(d,c)+b},0);d/=b.length;f/=e.length;var g=0,k=0,p;for(p=0;p<b.length;p++){var u=b[p]-d;var r=a(e[p],c)-f;g+=u*r;k+=Math.pow(u,2)}b=k?g/k:0;return{slope:b,intercept:f-b*d}},getEndPointY:function(b,e){return b.slope*e+b.intercept},transformXData:function(b,e){var c=b[0];return b.map(function(a){return(a-c)/e})},findClosestDistance:function(b){var e,c;for(c=
1;c<b.length-1;c++){var a=b[c]-b[c-1];0<a&&("undefined"===typeof e||a<e)&&(e=a)}return e},getValues:function(b,e){var c=b.xData;b=b.yData;e=e.period;var a,d={xData:[],yData:[],values:[]},f=this.options.params.xAxisUnit||this.findClosestDistance(c);for(a=e-1;a<=c.length-1;a++){var g=a-e+1;var k=a+1;var h=c[a];var u=c.slice(g,k);g=b.slice(g,k);k=this.transformXData(u,f);u=this.getRegressionLineParameters(k,g);g=this.getEndPointY(u,k[k.length-1]);d.values.push({regressionLineParameters:u,x:h,y:g});d.xData.push(h);
d.yData.push(g)}return d}});b.seriesType("linearRegressionSlope","linearRegression",{},{nameBase:"Linear Regression Slope Indicator",getEndPointY:function(b){return b.slope}});b.seriesType("linearRegressionIntercept","linearRegression",{},{nameBase:"Linear Regression Intercept Indicator",getEndPointY:function(b){return b.intercept}});b.seriesType("linearRegressionAngle","linearRegression",{tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span>{series.name}: <b>{point.y}\u00b0</b><br/>'}},
{nameBase:"Linear Regression Angle Indicator",slopeToAngle:function(b){return 180/Math.PI*Math.atan(b)},getEndPointY:function(b){return this.slopeToAngle(b.slope)}});""});w(b,"Stock/Indicators/ABIndicator.js",[b["Core/Series/Series.js"],b["Mixins/MultipleLines.js"],b["Core/Utilities.js"]],function(b,g,h){var k=h.correctFloat;h=h.merge;var e=b.seriesTypes.sma;b.seriesType("abands","sma",{params:{period:20,factor:.001,index:3},lineWidth:1,topLine:{styles:{lineWidth:1}},bottomLine:{styles:{lineWidth:1}},
dataGrouping:{approximation:"averages"}},h(g,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Acceleration Bands",nameComponents:["period","factor"],linesApiNames:["topLine","bottomLine"],getValues:function(b,a){var c=a.period,f=a.factor;a=a.index;var g=b.xData,h=(b=b.yData)?b.length:0,p=[],u=[],r=[],q=[],l=[],n;if(!(h<c)){for(n=0;n<=h;n++){if(n<h){var v=b[n][2];var w=b[n][1];var x=f;v=k(w-v)/(k(w+v)/2)*1E3*x;p.push(b[n][1]*k(1+2*v));u.push(b[n][2]*k(1-2*v))}if(n>=c){v=g.slice(n-
c,n);var C=b.slice(n-c,n);x=e.prototype.getValues.call(this,{xData:v,yData:p.slice(n-c,n)},{period:c});w=e.prototype.getValues.call(this,{xData:v,yData:u.slice(n-c,n)},{period:c});C=e.prototype.getValues.call(this,{xData:v,yData:C},{period:c,index:a});v=C.xData[0];x=x.yData[0];w=w.yData[0];C=C.yData[0];r.push([v,x,C,w]);q.push(v);l.push([x,C,w])}}return{values:r,xData:q,yData:l}}}}));""});w(b,"Stock/Indicators/TrendLineIndicator.js",[b["Core/Series/Series.js"],b["Core/Utilities.js"]],function(b,g){var h=
g.isArray;b.seriesType("trendline","sma",{params:{index:3}},{nameBase:"Trendline",nameComponents:!1,getValues:function(b,e){var c=b.xData,a=b.yData;b=[];var d=[],f=[],g=0,k=0,p=0,u=0,r=c.length,q=e.index;for(e=0;e<r;e++){var l=c[e];var n=h(a[e])?a[e][q]:a[e];g+=l;k+=n;p+=l*n;u+=l*l}a=(r*p-g*k)/(r*u-g*g);isNaN(a)&&(a=0);g=(k-a*g)/r;for(e=0;e<r;e++)l=c[e],n=a*l+g,b[e]=[l,n],d[e]=l,f[e]=n;return{xData:d,yData:f,values:b}}});""});w(b,"masters/indicators/indicators-all.src.js",[],function(){})});
//# sourceMappingURL=indicators-all.js.map